#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Maguuma/DryTop.au3
; Map: DryTop (id 47), geometry from MAP 0000040801.pmap
; Repaired 1 of 1 blocked segments by inserting 1 waypoints.
; Smoothed 4 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Maguuma_DryTopRoute01[165][4] = [ _
	[4726, -6046, " ", $vqrange], _
	[4189, -6202, " ", $vqrange], _
	[3920, -6279, " ", $vqrange], _
	[3652, -6357, " ", $vqrange], _
	[4176, -6816, " ", $vqrange], _
	[3360, -6912, " ", $vqrange], _
	[2947, -6924, " ", $vqrange], _
	[2792, -6928, " ", $vqrange], _
	[2638, -6933, " ", $vqrange], _
	[2483, -6938, " ", $vqrange], _
	[2328, -6942, " ", $vqrange], _
	[2173, -6946, " ", $vqrange], _
	[1709, -6960, " ", $vqrange], _
	[930, -6958, " ", $vqrange], _
	[150, -6957, " ", $vqrange], _
	[-658, -6514, " ", $vqrange], _
	[-1465, -6071, " ", $vqrange], _
	[-2219, -6126, " ", $vqrange], _
	[-2973, -6180, " ", $vqrange], _
	[-1900.5, -6162, " ", $vqrange], _ ; auto
	[-828, -6144, " ", $vqrange], _ ; auto
	[-1872, -6144, " ", $vqrange], _ ; auto
	[-3139, -6034, " ", $vqrange], _
	[-3416, -5792, " ", $vqrange], _
	[-3858, -5403, " ", $vqrange], _
	[-4743, -4626, " ", $vqrange], _
	[-5144, -3908, " ", $vqrange], _
	[-5546, -3189, " ", $vqrange], _
	[-5831, -2322, " ", $vqrange], _
	[-6116, -1455, " ", $vqrange], _
	[-6529, -617, " ", $vqrange], _
	[-6942, 221, " ", $vqrange], _
	[-6997, 982, " ", $vqrange], _
	[-7052, 1744, " ", $vqrange], _
	[-6961, 2710, " ", $vqrange], _
	[-6870, 3675, " ", $vqrange], _
	[-6762, 4836, " ", $vqrange], _
	[-6590, 5848, " ", $vqrange], _
	[-6418, 6860, " ", $vqrange], _
	[-6246, 7872, " ", $vqrange], _
	[-6456, 6633, " ", $vqrange], _
	[-6666, 5394, " ", $vqrange], _
	[-5757, 6057, " ", $vqrange], _
	[-5004, 6624, " ", $vqrange], _ ; auto
	[-4848, 6720, " ", $vqrange], _
	[-4654, 6735, " ", $vqrange], _
	[-4459, 6750, " ", $vqrange], _
	[-4320, 6826, " ", $vqrange], _
	[-4177, 6904, " ", $vqrange], _ ; auto
	[-4034, 6982, " ", $vqrange], _
	[-3610, 7214, " ", $vqrange], _
	[-2761, 7679, " ", $vqrange], _
	[-2045, 6834, " ", $vqrange], _
	[-1634, 6870, " ", $vqrange], _
	[-1428, 6887, " ", $vqrange], _
	[-1274, 6901, " ", $vqrange], _
	[-1120, 6919, " ", $vqrange], _
	[-966, 6927, " ", $vqrange], _
	[-812, 6940, " ", $vqrange], _
	[-606, 6958, " ", $vqrange], _
	[-401, 6976, " ", $vqrange], _
	[376, 6964, " ", $vqrange], _
	[570, 6962, " ", $vqrange], _
	[722, 6959, " ", $vqrange], _
	[874, 6957, " ", $vqrange], _
	[1153, 6953, " ", $vqrange], _
	[2522, 6652, " ", $vqrange], _
	[1794, 5353, " ", $vqrange], _
	[1308, 5184, " ", $vqrange], _
	[2052, 4992, " ", $vqrange], _
	[2657, 4252, " ", $vqrange], _
	[3262, 3513, " ", $vqrange], _
	[3107, 2892, " ", $vqrange], _
	[4117, 2677, " ", $vqrange], _
	[5128, 2463, " ", $vqrange], _
	[6138, 2248, " ", $vqrange], _
	[6333, 3236, " ", $vqrange], _
	[6430, 3730, " ", $vqrange], _
	[6479, 3977, " ", $vqrange], _
	[6528, 4224, " ", $vqrange], _
	[6384, 4177, " ", $vqrange], _
	[6235, 4128, " ", $vqrange], _
	[6324, 3312, " ", $vqrange], _
	[5431, 2767, " ", $vqrange], _
	[4539, 2222, " ", $vqrange], _
	[3646, 1677, " ", $vqrange], _
	[2710, 1522, " ", $vqrange], _
	[1775, 1367, " ", $vqrange], _
	[1492, 588, " ", $vqrange], _
	[1210, -191, " ", $vqrange], _
	[1248, -1248, " ", $vqrange], _
	[2025, -1632, " ", $vqrange], _
	[2801, -2016, " ", $vqrange], _
	[2669, -2336, " ", $vqrange], _
	[2872, -2592, " ", $vqrange], _
	[3548, -2592, " ", $vqrange], _
	[3701, -2592, " ", $vqrange], _
	[3886, -2592, " ", $vqrange], _
	[4224, -2592, " ", $vqrange], _
	[5369, -2187, " ", $vqrange], _
	[6427, -3114, " ", $vqrange], _
	[6310, -4341, " ", $vqrange], _
	[6192, -5568, " ", $vqrange], _
	[5919, -5577, " ", $vqrange], _
	[5458, -6273, " ", $vqrange], _
	[4409, -6592, " ", $vqrange], _
	[3360, -6912, " ", $vqrange], _
	[2930, -6936, " ", $vqrange], _
	[2775, -6945, " ", $vqrange], _
	[2621, -6954, " ", $vqrange], _
	[2466, -6962, " ", $vqrange], _
	[2311, -6971, " ", $vqrange], _
	[2069, -6985, " ", $vqrange], _
	[1639, -7009, " ", $vqrange], _
	[580, -6864, " ", $vqrange], _
	[-480, -6720, " ", $vqrange], _
	[-1140, -6720, " ", $vqrange], _
	[-1470, -6720, " ", $vqrange], _
	[-1625, -6720, " ", $vqrange], _
	[-1779, -6720, " ", $vqrange], _
	[-1934, -6720, " ", $vqrange], _
	[-2089, -6720, " ", $vqrange], _
	[-2243, -6720, " ", $vqrange], _
	[-2460, -6720, " ", $vqrange], _
	[-3120, -6720, " ", $vqrange], _
	[-2905, -6831, " ", $vqrange], _
	[-1896, -6216, " ", $vqrange], _
	[-2736, -5456, " ", $vqrange], _
	[-3576, -4696, " ", $vqrange], _
	[-4416, -3936, " ", $vqrange], _
	[-4104, -3672, " ", $vqrange], _
	[-5428, -3241, " ", $vqrange], _
	[-5781, -2180, " ", $vqrange], _
	[-6134, -1119, " ", $vqrange], _
	[-6457, -74, " ", $vqrange], _
	[-6781, 971, " ", $vqrange], _
	[-7104, 2016, " ", $vqrange], _
	[-7154, 3174, " ", $vqrange], _
	[-6963, 4514, " ", $vqrange], _
	[-6772, 5855, " ", $vqrange], _
	[-5742, 6064, " ", $vqrange], _
	[-4935, 6584, " ", $vqrange], _
	[-4128, 7104, " ", $vqrange], _
	[-3656, 7117, " ", $vqrange], _
	[-3501, 7121, " ", $vqrange], _
	[-3347, 7125, " ", $vqrange], _
	[-3192, 7129, " ", $vqrange], _
	[-3037, 7133, " ", $vqrange], _
	[-2882, 7138, " ", $vqrange], _
	[-2713, 7142, " ", $vqrange], _
	[-2241, 7155, " ", $vqrange], _
	[-1249, 7094, " ", $vqrange], _
	[-256, 7034, " ", $vqrange], _
	[736, 6973, " ", $vqrange], _
	[891, 6963, " ", $vqrange], _
	[1232, 6942, " ", $vqrange], _
	[1728, 6912, " ", $vqrange], _
	[1724, 6378, " ", $vqrange], _
	[1680, 4992, " ", $vqrange], _
	[2072, 4982, " ", $vqrange], _
	[2231, 4978, " ", $vqrange], _
	[2463, 4972, " ", $vqrange], _
	[3246, 4952, " ", $vqrange], _
	[4030, 4933, " ", $vqrange], _
	[4813, 4913, " ", $vqrange] _
]

