#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Maguuma/MamnoonLagoon.au3
; Map: MamnoonLagoon (id 42), geometry from MAP 0000040809.pmap
; Repaired 5 of 11 blocked segments by inserting 19 waypoints.
; Smoothed 67 additional anchor(s) for wall clearance and hop distance.
; Filled 4 long hop(s) by walking the current mesh component toward a disconnected goal.
; 6 segment(s) could not be routed and were left as-is.
; 5 hop(s) still exceed 1500 units (worst 2573 between index 20 and 21).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Maguuma_MamnoonLagoonRoute01[353][4] = [ _
	[-6363, -5190, " ", $vqrange], _
	[-5726, -4419, " ", $vqrange], _
	[-5088, -3648, " ", $vqrange], _
	[-5201, -2844, " ", $vqrange], _
	[-4872, -1710, " ", $vqrange], _
	[-4544, -576, " ", $vqrange], _
	[-4358.5, -544, " ", $vqrange], _ ; auto
	[-4173, -512, " ", $vqrange], _
	[-3237, 373, " ", $vqrange], _
	[-2301, 1258, " ", $vqrange], _
	[-2604, 2526, " ", $vqrange], _
	[-2908, 3795, " ", $vqrange], _
	[-2598, 3819, " ", $vqrange], _
	[-2096, 3843, " ", $vqrange], _
	[-1943, 3850, " ", $vqrange], _
	[-1768.5, 3858.5, " ", $vqrange], _ ; auto
	[-1594, 3867, " ", $vqrange], _
	[-1434, 2620, " ", $vqrange], _
	[-1274, 1374, " ", $vqrange], _
	[-1619, 133, " ", $vqrange], _
	[-1964, -1108, " ", $vqrange], _
	[-1898, -3680, " ", $vqrange], _
	[-1837, -4311, " ", $vqrange], _ ; auto
	[-1821.75, -4468.75, " ", $vqrange], _ ; auto
	[-1806.9766, -4621.5703, " ", $vqrange], _ ; auto
	[-1792.2031, -4774.3906, " ", $vqrange], _ ; auto
	[-1776, -4942, " ", $vqrange], _ ; auto
	[-2148, -4992, " ", $vqrange], _ ; auto
	[-529, -5780, " ", $vqrange], _
	[716, -6068, " ", $vqrange], _
	[1962, -6355, " ", $vqrange], _
	[693, -6542, " ", $vqrange], _
	[-576, -6729, " ", $vqrange], _
	[-1464, -6803, " ", $vqrange], _
	[-2353, -6877, " ", $vqrange], _
	[-1092, -6682, " ", $vqrange], _
	[168, -6488, " ", $vqrange], _
	[1050, -5599, " ", $vqrange], _
	[1932, -4710, " ", $vqrange], _
	[3120, -5222, " ", $vqrange], _
	[4309, -5734, " ", $vqrange], _
	[5877, -3750, " ", $vqrange], _
	[5810, -2454, " ", $vqrange], _
	[5744, -1158, " ", $vqrange], _
	[5012, -98, " ", $vqrange], _
	[4281, 963, " ", $vqrange], _
	[3927, 2174, " ", $vqrange], _
	[3573, 3385, " ", $vqrange], _
	[3322, 4188, " ", $vqrange], _
	[3072, 4992, " ", $vqrange], _
	[4248, 5088, " ", $vqrange], _
	[4207, 5824, " ", $vqrange], _
	[5326, 6492, " ", $vqrange], _
	[6444, 7160, " ", $vqrange], _
	[7152, 6720, " ", $vqrange], _
	[7150, 5834, " ", $vqrange], _
	[7147, 4948, " ", $vqrange], _
	[7126, 5930, " ", $vqrange], _
	[7104, 6912, " ", $vqrange], _
	[6786, 7237, " ", $vqrange], _
	[5748, 6524, " ", $vqrange], _
	[4711, 5810, " ", $vqrange], _
	[4248, 5088, " ", $vqrange], _
	[3726, 5088, " ", $vqrange], _
	[3530, 5088, " ", $vqrange], _
	[3375, 5088, " ", $vqrange], _
	[3204, 5088, " ", $vqrange], _
	[2160, 5088, " ", $vqrange], _
	[2240, 5264, " ", $vqrange], _
	[1173, 5589, " ", $vqrange], _
	[107, 5915, " ", $vqrange], _
	[-960, 6240, " ", $vqrange], _
	[-24, 6356, " ", $vqrange], _
	[-1308, 6486, " ", $vqrange], _
	[-2592, 6615, " ", $vqrange], _
	[-3822, 6216, " ", $vqrange], _
	[-5051, 5817, " ", $vqrange], _
	[-6084, 5062, " ", $vqrange], _
	[-7118, 4306, " ", $vqrange], _
	[-7284, 3890, " ", $vqrange], _
	[-7367, 3683, " ", $vqrange], _
	[-7450, 3475, " ", $vqrange], _
	[-7442.5, 3632.5, " ", $vqrange], _ ; auto
	[-7435, 3790, " ", $vqrange], _
	[-7420, 4106, " ", $vqrange], _
	[-7390, 4736, " ", $vqrange], _
	[-7329, 5997, " ", $vqrange], _
	[-7296, 5376, " ", $vqrange], _
	[-6857, 5376, " ", $vqrange], _
	[-6706, 5376, " ", $vqrange], _
	[-6555, 5376, " ", $vqrange], _
	[-6301, 5376, " ", $vqrange], _ ; auto
	[-6047, 5376, " ", $vqrange], _ ; auto
	[-5539, 5376, " ", $vqrange], _
	[-4763, 5921, " ", $vqrange], _
	[-4464, 6432, " ", $vqrange], _
	[-3612, 6432, " ", $vqrange], _
	[-3186, 6432, " ", $vqrange], _
	[-3026, 6432, " ", $vqrange], _
	[-2866, 6432, " ", $vqrange], _
	[-2626.5, 6432, " ", $vqrange], _ ; auto
	[-2387, 6432, " ", $vqrange], _ ; auto
	[-1908, 6432, " ", $vqrange], _
	[-1056, 6432, " ", $vqrange], _
	[-2273, 6167, " ", $vqrange], _
	[-2408, 4912, " ", $vqrange], _
	[-2544, 3657, " ", $vqrange], _
	[-2814, 2388, " ", $vqrange], _
	[-3085, 1120, " ", $vqrange], _
	[-3054, 320, " ", $vqrange], _
	[-3024, -480, " ", $vqrange], _
	[-3784, -528, " ", $vqrange], _
	[-3974, -540, " ", $vqrange], _
	[-4128, -550, " ", $vqrange], _
	[-4283, -560, " ", $vqrange], _
	[-4544, -576, " ", $vqrange], _
	[-4954, -1414, " ", $vqrange], _
	[-4544, -576, " ", $vqrange], _
	[-3660, -1, " ", $vqrange], _
	[-2934, 480, " ", $vqrange], _
	[-2208, 960, " ", $vqrange], _
	[-3166, 1007, " ", $vqrange], _
	[-2839, 2207, " ", $vqrange], _
	[-2860, 3024, " ", $vqrange], _
	[-2880, 3840, " ", $vqrange], _
	[-3536, 3855, " ", $vqrange], _
	[-2553, 3228, " ", $vqrange], _
	[-2644, 2334, " ", $vqrange], _
	[-2736, 1440, " ", $vqrange], _
	[-1959, 1408, " ", $vqrange], _
	[-1795, 1414, " ", $vqrange], _
	[-1644, 1420, " ", $vqrange], _
	[-1398, 1430, " ", $vqrange], _ ; auto
	[-1152, 1440, " ", $vqrange], _
	[-978, 1903, " ", $vqrange], _
	[-1349, 3002, " ", $vqrange], _
	[-1787, 4080, " ", $vqrange], _
	[-2225, 5157, " ", $vqrange], _
	[-2384, 6261, " ", $vqrange], _
	[-1353.3333, 6318, " ", $vqrange], _ ; auto
	[-322.6667, 6375, " ", $vqrange], _ ; auto
	[708, 6432, " ", $vqrange], _ ; auto
	[-580.6667, 6491, " ", $vqrange], _ ; auto
	[-1869.3333, 6550, " ", $vqrange], _ ; auto
	[-3158, 6609, " ", $vqrange], _
	[-4462, 6011, " ", $vqrange], _
	[-5765, 5414, " ", $vqrange], _
	[-7069, 4816, " ", $vqrange], _
	[-5985, 5308, " ", $vqrange], _
	[-4902, 5801, " ", $vqrange], _
	[-3818, 6294, " ", $vqrange], _
	[-2734, 6786, " ", $vqrange], _
	[-1646, 6377, " ", $vqrange], _
	[-670, 6208, " ", $vqrange], _
	[307, 6038, " ", $vqrange], _
	[1399, 5664, " ", $vqrange], _
	[1920, 5280, " ", $vqrange], _
	[2889, 5225, " ", $vqrange], _
	[3132, 5150, " ", $vqrange], _
	[3277, 5106, " ", $vqrange], _
	[3422, 5061, " ", $vqrange], _
	[3665, 4986, " ", $vqrange], _
	[4501, 5508, " ", $vqrange], _
	[5288, 6174, " ", $vqrange], _
	[6074, 6841, " ", $vqrange], _
	[6861, 7507, " ", $vqrange], _
	[5704, 6600, " ", $vqrange], _
	[4547, 5694, " ", $vqrange], _
	[3710, 4874, " ", $vqrange], _
	[3441, 4550, " ", $vqrange], _
	[3177, 3734, " ", $vqrange], _
	[2913, 2919, " ", $vqrange], _
	[2990, 2781, " ", $vqrange], _
	[3952, 2688, " ", $vqrange], _ ; auto
	[3082, 2618, " ", $vqrange], _
	[3363, 2118, " ", $vqrange], _
	[3813, 1316, " ", $vqrange], _
	[4027, 978, " ", $vqrange], _
	[4616, -12, " ", $vqrange], _
	[5204, -1001, " ", $vqrange], _
	[5210, -2238, " ", $vqrange], _
	[5217, -3474, " ", $vqrange], _
	[4893, -3806, " ", $vqrange], _
	[4731, -3971, " ", $vqrange], _
	[4570, -4137, " ", $vqrange], _
	[4609, -4155, " ", $vqrange], _
	[3984, -4970, " ", $vqrange], _
	[3670, -4944, " ", $vqrange], _
	[3355, -4918, " ", $vqrange], _
	[2726, -4867, " ", $vqrange], _
	[1726, -5276, " ", $vqrange], _
	[1227, -5481, " ", $vqrange], _
	[1039, -5558, " ", $vqrange], _
	[899, -5616, " ", $vqrange], _
	[727, -5686, " ", $vqrange], _
	[960, -6144, " ", $vqrange], _
	[40, -6404, " ", $vqrange], _
	[-880, -6665, " ", $vqrange], _
	[145, -6528, " ", $vqrange], _
	[-379, -6476, " ", $vqrange], _
	[470, -6406, " ", $vqrange], _
	[1320, -6336, " ", $vqrange], _
	[274, -5930, " ", $vqrange], _
	[-772, -5525, " ", $vqrange], _
	[-1818, -5119, " ", $vqrange], _
	[-1864, -4598, " ", $vqrange], _
	[-1888, -4338, " ", $vqrange], _
	[-1911, -4077, " ", $vqrange], _
	[-1903, -3837, " ", $vqrange], _
	[-1896, -3596, " ", $vqrange], _
	[-1891, -3446, " ", $vqrange], _
	[-1886, -3296, " ", $vqrange], _
	[-1881, -3146, " ", $vqrange], _
	[-1667.4615, -3102, " ", $vqrange], _ ; auto
	[-1876, -2996, " ", $vqrange], _
	[-1658.3231, -2933, " ", $vqrange], _ ; auto
	[-1864, -2636, " ", $vqrange], _
	[-1849, -2155, " ", $vqrange], _
	[-2018, -1153, " ", $vqrange], _
	[-2187, -150, " ", $vqrange], _
	[-2356, 852, " ", $vqrange], _
	[-2473, 1812, " ", $vqrange], _
	[-2590, 2772, " ", $vqrange], _
	[-2461, 3931, " ", $vqrange], _
	[-2128.5, 3905.5, " ", $vqrange], _ ; auto
	[-1962.25, 3892.75, " ", $vqrange], _ ; auto
	[-1796, 3880, " ", $vqrange], _
	[-1478.4, 3456, " ", $vqrange], _ ; auto
	[-1626, 3147, " ", $vqrange], _
	[-1455, 2414, " ", $vqrange], _
	[-1430, 1245, " ", $vqrange], _
	[-1542, 480, " ", $vqrange], _
	[-1653, -286, " ", $vqrange], _
	[-1868, -1350, " ", $vqrange], _
	[-1852, -2516, " ", $vqrange], _
	[-1848, -2808, " ", $vqrange], _
	[-1845, -3026, " ", $vqrange], _
	[-1691, -3051, " ", $vqrange], _ ; auto
	[-1842, -3245, " ", $vqrange], _
	[-1836, -3682, " ", $vqrange], _
	[-1814, -4258, " ", $vqrange], _
	[-1806, -4474, " ", $vqrange], _
	[-1800, -4627, " ", $vqrange], _
	[-1792, -4834, " ", $vqrange], _
	[-733, -5717, " ", $vqrange], _
	[393, -6044, " ", $vqrange], _
	[1306, -6078, " ", $vqrange], _
	[2220, -6112, " ", $vqrange], _
	[4115, -4790, " ", $vqrange], _
	[4715, -3795, " ", $vqrange], _
	[4888, -2692, " ", $vqrange], _
	[5062, -1589, " ", $vqrange], _
	[5379, -2602, " ", $vqrange], _
	[4776, -3317, " ", $vqrange], _
	[4988, -2422, " ", $vqrange], _
	[5201, -1528, " ", $vqrange], _
	[4842, -700, " ", $vqrange], _
	[4482, 129, " ", $vqrange], _
	[4232, 865, " ", $vqrange], _
	[3982, 1601, " ", $vqrange], _
	[3502, 2868, " ", $vqrange], _
	[3023, 4135, " ", $vqrange], _
	[2340, 5044, " ", $vqrange], _
	[1254, 5460, " ", $vqrange], _
	[167, 5877, " ", $vqrange], _
	[-96, 6144, " ", $vqrange], _
	[-1032, 6144, " ", $vqrange], _
	[-1186, 6144, " ", $vqrange], _
	[-1383, 6144, " ", $vqrange], _
	[-1968, 6144, " ", $vqrange], _
	[-2009, 5967, " ", $vqrange], _
	[-2433, 4570, " ", $vqrange], _
	[-2474, 3802, " ", $vqrange], _
	[-2515, 3034, " ", $vqrange], _
	[-2650, 2285, " ", $vqrange], _
	[-2784, 1536, " ", $vqrange], _
	[-2380, 1530, " ", $vqrange], _
	[-2545, 1793, " ", $vqrange], _
	[-2368.6667, 3211.3333, " ", $vqrange], _ ; auto
	[-2192.3333, 4629.6667, " ", $vqrange], _ ; auto
	[-1968, 6144, " ", $vqrange], _ ; auto
	[-1500, 6144, " ", $vqrange], _ ; auto
	[-1324.5, 6144, " ", $vqrange], _ ; auto
	[-1170.9375, 6144, " ", $vqrange], _ ; auto
	[-96, 6144, " ", $vqrange], _ ; auto
	[954.6998, 5568, " ", $vqrange], _ ; auto
	[2005.3996, 4992, " ", $vqrange], _ ; auto
	[3056.0994, 4416, " ", $vqrange], _ ; auto
	[3336.4495, 3256.75, " ", $vqrange], _ ; auto
	[3616.7997, 2097.5, " ", $vqrange], _ ; auto
	[3897.1498, 938.25, " ", $vqrange], _ ; auto
	[4037.3249, 358.625, " ", $vqrange], _ ; auto
	[4076.7492, 195.6055, " ", $vqrange], _ ; auto
	[4177.5, -221, " ", $vqrange], _ ; auto
	[4032, -384, " ", $vqrange], _
	[4075.9688, -220.9766, " ", $vqrange], _ ; auto
	[4132.5, -11.375, " ", $vqrange], _ ; auto
	[4233, 361.25, " ", $vqrange], _ ; auto
	[4434, 1106.5, " ", $vqrange], _ ; auto
	[4635, 1851.75, " ", $vqrange], _ ; auto
	[4836, 2597, " ", $vqrange], _
	[4026, 3074, " ", $vqrange], _
	[3216, 3552, " ", $vqrange], _
	[3024, 3840, " ", $vqrange], _
	[3946, 4944, " ", $vqrange], _
	[4867, 6048, " ", $vqrange], _
	[5880, 6912, " ", $vqrange], _
	[6186, 6912, " ", $vqrange], _
	[6339, 6912, " ", $vqrange], _
	[6492, 6912, " ", $vqrange], _
	[6645, 6912, " ", $vqrange], _
	[6798, 6912, " ", $vqrange], _
	[7104, 6912, " ", $vqrange], _
	[7188, 5904, " ", $vqrange], _
	[7272, 4896, " ", $vqrange], _
	[7440, 4800, " ", $vqrange], _
	[7570, 4470, " ", $vqrange], _
	[7200, 5664, " ", $vqrange], _ ; auto
	[7104, 6912, " ", $vqrange], _ ; auto
	[6624, 7296, " ", $vqrange], _ ; auto
	[7008, 7344, " ", $vqrange], _ ; auto
	[7200, 7368, " ", $vqrange], _ ; auto
	[7392, 7392, " ", $vqrange], _
	[7235.6719, 7392, " ", $vqrange], _ ; auto
	[7047, 7392, " ", $vqrange], _ ; auto
	[6702, 7392, " ", $vqrange], _ ; auto
	[6012, 7392, " ", $vqrange], _ ; auto
	[6180, 7488, " ", $vqrange], _ ; auto
	[6240, 7776, " ", $vqrange], _
	[6240, 7776, " ", $vqrange], _
	[6192, 7632, " ", $vqrange], _ ; auto
	[6144, 7488, " ", $vqrange], _ ; auto
	[7216, 6528, " ", $vqrange], _ ; auto
	[7244, 5712, " ", $vqrange], _ ; auto
	[7272, 4896, " ", $vqrange], _ ; auto
	[7440, 4800, " ", $vqrange], _ ; auto
	[8064, 4704, " ", $vqrange], _ ; auto
	[8808, 4704, " ", $vqrange], _ ; auto
	[8994, 4704, " ", $vqrange], _ ; auto
	[9145.125, 4704, " ", $vqrange], _ ; auto
	[9366, 4704, " ", $vqrange], _ ; auto
	[9552, 4704, " ", $vqrange], _ ; auto
	[10236, 5952, " ", $vqrange], _ ; auto
	[10920, 7200, " ", $vqrange], _ ; auto
	[11604, 8448, " ", $vqrange], _ ; auto
	[11946, 9072, " ", $vqrange], _ ; auto
	[12117, 9384, " ", $vqrange], _ ; auto
	[12191.8125, 9520.5, " ", $vqrange], _ ; auto
	[12288, 9696, " ", $vqrange], _
	[12288, 9696, " ", $vqrange], _
	[12288, 9696, " ", $vqrange], _
	[12288, 9696, " ", $vqrange], _
	[12288, 9696, " ", $vqrange] _
]

