#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Maguuma/ReedBog.au3
; Map: ReedBog (id 45), geometry from MAP 0000040802.pmap
; Repaired 0 of 1 blocked segments by inserting 1 waypoints.
; Smoothed 4 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; 1 segment(s) could not be routed and were left as-is.
; 1 hop(s) still exceed 1500 units (worst 2331 between index 66 and 67).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Maguuma_ReedBogRoute01[94][4] = [ _
	[7164, 7081, " ", $vqrange], _
	[6377, 6265, " ", $vqrange], _
	[5590, 5449, " ", $vqrange], _
	[4803, 4633, " ", $vqrange], _
	[3682, 5073, " ", $vqrange], _
	[2561, 5512, " ", $vqrange], _
	[1440, 5952, " ", $vqrange], _
	[478, 6578, " ", $vqrange], _
	[-485, 7205, " ", $vqrange], _
	[-1590, 6644, " ", $vqrange], _
	[-2694, 6082, " ", $vqrange], _
	[-3720, 6022, " ", $vqrange], _
	[-4747, 5961, " ", $vqrange], _
	[-5773, 5901, " ", $vqrange], _
	[-6600, 4907, " ", $vqrange], _
	[-7432, 4594, " ", $vqrange], _
	[-8264, 4282, " ", $vqrange], _
	[-8670, 3619, " ", $vqrange], _
	[-8622, 2436, " ", $vqrange], _
	[-8574, 1253, " ", $vqrange], _
	[-8526, 70, " ", $vqrange], _
	[-7871, -440, " ", $vqrange], _
	[-7442, 835, " ", $vqrange], _
	[-7013, 2110, " ", $vqrange], _
	[-6680, 3211, " ", $vqrange], _
	[-5338, 3510, " ", $vqrange], _
	[-4529, 4059, " ", $vqrange], _
	[-3720, 4608, " ", $vqrange], _
	[-2332, 4959, " ", $vqrange], _
	[-2532, 4036, " ", $vqrange], _
	[-2731, 3112, " ", $vqrange], _
	[-3366, 2228, " ", $vqrange], _
	[-4000, 1344, " ", $vqrange], _
	[-4977, 1142, " ", $vqrange], _
	[-5954, 939, " ", $vqrange], _
	[-4977, 1142, " ", $vqrange], _
	[-4000, 1344, " ", $vqrange], _
	[-3895, 1920, " ", $vqrange], _
	[-3633, 1920, " ", $vqrange], _
	[-3437, 1920, " ", $vqrange], _
	[-3286, 1920, " ", $vqrange], _
	[-3110, 1920, " ", $vqrange], _
	[-2848, 1920, " ", $vqrange], _
	[-2948, 1881, " ", $vqrange], _
	[-3226, 1180, " ", $vqrange], _
	[-3504, 480, " ", $vqrange], _
	[-4351, 2, " ", $vqrange], _
	[-5198, -476, " ", $vqrange], _
	[-4419, 195, " ", $vqrange], _
	[-3640, 865, " ", $vqrange], _
	[-2861, 1536, " ", $vqrange], _
	[-2675, 2560, " ", $vqrange], _
	[-2490, 3584, " ", $vqrange], _
	[-2304, 4608, " ", $vqrange], _
	[-3012, 4608, " ", $vqrange], _
	[-3167, 4608, " ", $vqrange], _
	[-3366, 4608, " ", $vqrange], _
	[-3720, 4608, " ", $vqrange], _
	[-4641, 3744, " ", $vqrange], _
	[-5562, 2880, " ", $vqrange], _
	[-6483, 2016, " ", $vqrange], _
	[-7404, 1152, " ", $vqrange], _
	[-7586, -191, " ", $vqrange], _
	[-7769, -1534, " ", $vqrange], _
	[-7334, -1604, " ", $vqrange], _
	[-8064, -2256, " ", $vqrange], _
	[-8794, -2909, " ", $vqrange], _
	[-7825, -5029, " ", $vqrange], _
	[-7742, -5864, " ", $vqrange], _
	[-7658, -6698, " ", $vqrange], _
	[-6411, -6730, " ", $vqrange], _
	[-5164, -6763, " ", $vqrange], _
	[-3917, -6796, " ", $vqrange], _
	[-2670, -6828, " ", $vqrange], _
	[-2208, -7296, " ", $vqrange], _
	[-1968, -8448, " ", $vqrange], _
	[-1613, -9109, " ", $vqrange], _
	[-333, -8646, " ", $vqrange], _
	[-190, -7587, " ", $vqrange], _
	[-384, -7529, " ", $vqrange], _ ; auto
	[-48, -6528, " ", $vqrange], _
	[186, -5512, " ", $vqrange], _
	[1456, -4937, " ", $vqrange], _
	[2727, -4362, " ", $vqrange], _
	[4117, -4650, " ", $vqrange], _
	[5507, -4939, " ", $vqrange], _
	[5490, -3719, " ", $vqrange], _
	[5473, -2499, " ", $vqrange], _
	[5456, -1279, " ", $vqrange], _
	[5595, 134, " ", $vqrange], _
	[5735, 1548, " ", $vqrange], _
	[5874, 2961, " ", $vqrange], _
	[6268, 3692, " ", $vqrange], _
	[6662, 4422, " ", $vqrange] _
]

