#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Kryta/CursedLands.au3
; Map: CursedLands (id 56), geometry from MAP 0000034216.pmap
; Repaired 0 of 0 blocked segments by inserting 0 waypoints.
; Smoothed 3 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Kryta_CursedLandsRoute01[124][4] = [ _
	[-19496, 8848, " ", $vqrange], _
	[-19272, 8282, " ", $vqrange], _
	[-19217, 8141, " ", $vqrange], _
	[-18972, 8053, " ", $vqrange], _ ; auto
	[-19161, 8000, " ", $vqrange], _
	[-19049, 7717, " ", $vqrange], _
	[-18780, 7584, " ", $vqrange], _ ; auto
	[-18993, 7576, " ", $vqrange], _
	[-18937, 7434, " ", $vqrange], _
	[-18881, 7293, " ", $vqrange], _
	[-18826, 7152, " ", $vqrange], _
	[-18770, 7010, " ", $vqrange], _
	[-18714, 6869, " ", $vqrange], _
	[-18658, 6727, " ", $vqrange], _
	[-18602, 6586, " ", $vqrange], _
	[-17828, 6880, " ", $vqrange], _
	[-17054, 7175, " ", $vqrange], _
	[-15946, 7445, " ", $vqrange], _
	[-15053, 7023, " ", $vqrange], _
	[-14338, 6730, " ", $vqrange], _
	[-13624, 6437, " ", $vqrange], _
	[-12525, 5679, " ", $vqrange], _
	[-11772, 5302, " ", $vqrange], _
	[-11018, 4926, " ", $vqrange], _
	[-11691, 4504, " ", $vqrange], _
	[-12364, 4081, " ", $vqrange], _
	[-11728, 3131, " ", $vqrange], _
	[-11091, 2182, " ", $vqrange], _
	[-10455, 1232, " ", $vqrange], _
	[-11362, 1530, " ", $vqrange], _
	[-12270, 1827, " ", $vqrange], _
	[-12974, 1216, " ", $vqrange], _
	[-13679, 606, " ", $vqrange], _
	[-12880, 121, " ", $vqrange], _
	[-12082, -364, " ", $vqrange], _
	[-12780, 154, " ", $vqrange], _
	[-13478, 672, " ", $vqrange], _
	[-13366, 951, " ", $vqrange], _
	[-12004, 920, " ", $vqrange], _
	[-10643, 888, " ", $vqrange], _
	[-10722, 12, " ", $vqrange], _
	[-10800, -864, " ", $vqrange], _
	[-11053, -1374, " ", $vqrange], _
	[-10248, -1770, " ", $vqrange], _
	[-9443, -2167, " ", $vqrange], _
	[-10789, -2632, " ", $vqrange], _
	[-11207, -3480, " ", $vqrange], _
	[-11878, -4157, " ", $vqrange], _
	[-12322, -5287, " ", $vqrange], _
	[-13230, -5012, " ", $vqrange], _
	[-14137, -4737, " ", $vqrange], _
	[-15358, -5088, " ", $vqrange], _
	[-14723, -5690, " ", $vqrange], _
	[-14089, -6291, " ", $vqrange], _
	[-14768, -5026, " ", $vqrange], _
	[-15448, -3760, " ", $vqrange], _
	[-14264, -4036, " ", $vqrange], _
	[-13079, -4313, " ", $vqrange], _
	[-11957, -3483, " ", $vqrange], _
	[-10834, -2654, " ", $vqrange], _
	[-9712, -1824, " ", $vqrange], _
	[-9292, -1291, " ", $vqrange], _
	[-8747, -2016, " ", $vqrange], _
	[-8202, -2740, " ", $vqrange], _
	[-9170, -3353, " ", $vqrange], _
	[-9211, -4044, " ", $vqrange], _
	[-7843.2, -3936, " ", $vqrange], _ ; auto
	[-8360, -3925, " ", $vqrange], _
	[-7510, -3806, " ", $vqrange], _
	[-7336, -3675, " ", $vqrange], _
	[-8226, -4068, " ", $vqrange], _
	[-9115, -4460, " ", $vqrange], _
	[-9118, -5042, " ", $vqrange], _
	[-10272, -5496, " ", $vqrange], _
	[-10224, -6732, " ", $vqrange], _
	[-10043, -7969, " ", $vqrange], _
	[-10300, -7240, " ", $vqrange], _
	[-10556, -6510, " ", $vqrange], _
	[-9742, -5896, " ", $vqrange], _
	[-8929, -5283, " ", $vqrange], _
	[-7929, -5724, " ", $vqrange], _
	[-6975, -6386, " ", $vqrange], _
	[-6021, -7049, " ", $vqrange], _
	[-6905, -7346, " ", $vqrange], _
	[-7752, -7976, " ", $vqrange], _
	[-8598, -8605, " ", $vqrange], _
	[-9168, -9120, " ", $vqrange], _
	[-9013, -9298, " ", $vqrange], _
	[-9247, -9211, " ", $vqrange], _
	[-9394, -9157, " ", $vqrange], _
	[-9540, -9102, " ", $vqrange], _
	[-9716, -9037, " ", $vqrange], _
	[-9950, -8950, " ", $vqrange], _
	[-10887, -8602, " ", $vqrange], _
	[-12167, -8764, " ", $vqrange], _
	[-11904, -8928, " ", $vqrange], _
	[-12631, -9765, " ", $vqrange], _
	[-13449, -9430, " ", $vqrange], _
	[-14267, -9095, " ", $vqrange], _
	[-13306, -10036, " ", $vqrange], _
	[-12344, -10978, " ", $vqrange], _
	[-10962, -10738, " ", $vqrange], _
	[-9900, -11619, " ", $vqrange], _
	[-11262, -11599, " ", $vqrange], _
	[-10601, -12350, " ", $vqrange], _
	[-9940, -13102, " ", $vqrange], _
	[-8562, -12746, " ", $vqrange], _
	[-7184, -12391, " ", $vqrange], _
	[-7224, -11590, " ", $vqrange], _
	[-7264, -10788, " ", $vqrange], _
	[-6342, -10392, " ", $vqrange], _
	[-5420, -9996, " ", $vqrange], _
	[-4498, -9600, " ", $vqrange], _
	[-4279, -9403, " ", $vqrange], _
	[-3898, -8352, " ", $vqrange], _
	[-3958, -8141, " ", $vqrange], _
	[-4751, -7031, " ", $vqrange], _
	[-5544, -5920, " ", $vqrange], _
	[-6337, -4810, " ", $vqrange], _
	[-5798, -3884, " ", $vqrange], _
	[-5260, -2957, " ", $vqrange], _
	[-4851, -4076, " ", $vqrange], _
	[-4442, -5194, " ", $vqrange], _
	[-4033, -6313, " ", $vqrange] _
]

