#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Kryta/MajestysRest.au3
; Map: MajestysRest (id 60), geometry from MAP 0000034320.pmap
; Repaired 1 of 1 blocked segments by inserting 1 waypoints.
; Smoothed 11 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Kryta_MajestysRestRoute01[264][4] = [ _
	[21522, -3238, " ", $vqrange], _
	[21801, -2435, " ", $vqrange], _
	[22080, -1632, " ", $vqrange], _
	[21980, -268, " ", $vqrange], _
	[21879, 1097, " ", $vqrange], _
	[21779, 2461, " ", $vqrange], _
	[22194, 3534, " ", $vqrange], _
	[22541, 4683, " ", $vqrange], _
	[21906, 5413, " ", $vqrange], _
	[21272, 6143, " ", $vqrange], _
	[21268, 5376, " ", $vqrange], _
	[21264, 4608, " ", $vqrange], _
	[21113, 4524, " ", $vqrange], _
	[20256, 3604, " ", $vqrange], _
	[19968, 2880, " ", $vqrange], _
	[19048, 2861, " ", $vqrange], _
	[18129, 2842, " ", $vqrange], _
	[19141, 2582, " ", $vqrange], _
	[20152, 2323, " ", $vqrange], _
	[21164, 2063, " ", $vqrange], _
	[20319, 2048, " ", $vqrange], _
	[19652, 1492, " ", $vqrange], _
	[18986, 937, " ", $vqrange], _
	[20192, 1033, " ", $vqrange], _
	[20832, 96, " ", $vqrange], _ ; auto
	[21184, 36, " ", $vqrange], _
	[22176, -960, " ", $vqrange], _
	[21882, -1556, " ", $vqrange], _
	[21444, -1607, " ", $vqrange], _
	[21006, -1658, " ", $vqrange], _
	[20129, -1760, " ", $vqrange], _
	[19316, -1504, " ", $vqrange], _
	[18504, -1248, " ", $vqrange], _
	[18193, -269, " ", $vqrange], _
	[17664, 192, " ", $vqrange], _
	[16865, 420, " ", $vqrange], _
	[16448, -318, " ", $vqrange], _
	[16032, -1056, " ", $vqrange], _
	[16252, -1572, " ", $vqrange], _
	[17470, -1816, " ", $vqrange], _
	[16470, -1718, " ", $vqrange], _
	[15470, -1620, " ", $vqrange], _
	[14470, -1522, " ", $vqrange], _
	[13929, -179, " ", $vqrange], _
	[13789, 167, " ", $vqrange], _
	[13383, 1318, " ", $vqrange], _
	[13157.5, 1297, " ", $vqrange], _ ; auto
	[12932, 1276, " ", $vqrange], _
	[12857, 1127, " ", $vqrange], _
	[13153, 1239, " ", $vqrange], _
	[13301, 1295, " ", $vqrange], _
	[13450, 1350, " ", $vqrange], _
	[13598, 1406, " ", $vqrange], _
	[13746, 1462, " ", $vqrange], _
	[14042, 1574, " ", $vqrange], _
	[13714, 1447, " ", $vqrange], _
	[13570, 1391, " ", $vqrange], _
	[13386, 1320, " ", $vqrange], _
	[13783, 170, " ", $vqrange], _
	[13925, -184, " ", $vqrange], _
	[14467, -1528, " ", $vqrange], _
	[14751, -2659, " ", $vqrange], _
	[15036, -3790, " ", $vqrange], _
	[15320, -4921, " ", $vqrange], _
	[16437, -5617, " ", $vqrange], _
	[17555, -6312, " ", $vqrange], _
	[18672, -7008, " ", $vqrange], _
	[19111, -7402, " ", $vqrange], _
	[18216, -6624, " ", $vqrange], _
	[17054, -6072, " ", $vqrange], _
	[15891, -5521, " ", $vqrange], _
	[14728, -4969, " ", $vqrange], _
	[15322, -4908, " ", $vqrange], _
	[14287, -5855, " ", $vqrange], _
	[13405, -5295, " ", $vqrange], _
	[12522, -4736, " ", $vqrange], _
	[11640, -4176, " ", $vqrange], _
	[12394, -3136, " ", $vqrange], _
	[13149, -2097, " ", $vqrange], _
	[12594, -3472, " ", $vqrange], _
	[12039, -4846, " ", $vqrange], _
	[11484, -6221, " ", $vqrange], _
	[10814, -5574, " ", $vqrange], _
	[10479, -5250, " ", $vqrange], _
	[11836.1997, -5151, " ", $vqrange], _ ; auto
	[10364, -5139, " ", $vqrange], _
	[10228, -5007, " ", $vqrange], _
	[9475, -4279, " ", $vqrange], _
	[8805, -3632, " ", $vqrange], _
	[9472, -2743, " ", $vqrange], _
	[10138, -1855, " ", $vqrange], _
	[10805, -966, " ", $vqrange], _
	[10773, 399, " ", $vqrange], _
	[10741, 1763, " ", $vqrange], _
	[10709, 3128, " ", $vqrange], _
	[11820, 4033, " ", $vqrange], _
	[12931, 4938, " ", $vqrange], _
	[14232, 4224, " ", $vqrange], _
	[15534, 3509, " ", $vqrange], _
	[15807, 2570, " ", $vqrange], _
	[16080, 1632, " ", $vqrange], _
	[16319, 1057, " ", $vqrange], _
	[15930, 2164, " ", $vqrange], _
	[15542, 3272, " ", $vqrange], _
	[15541, 3507, " ", $vqrange], _
	[16453, 4139, " ", $vqrange], _
	[17364, 4771, " ", $vqrange], _
	[18276, 5403, " ", $vqrange], _
	[17365, 4774, " ", $vqrange], _
	[16453, 4146, " ", $vqrange], _
	[15542, 3517, " ", $vqrange], _
	[14238, 4228, " ", $vqrange], _
	[12933, 4938, " ", $vqrange], _
	[13440, 6048, " ", $vqrange], _
	[13397, 6362, " ", $vqrange], _
	[12722, 6973, " ", $vqrange], _
	[12048, 7584, " ", $vqrange], _
	[11537, 7896, " ", $vqrange], _
	[10523, 7779, " ", $vqrange], _
	[9509, 7662, " ", $vqrange], _
	[8690, 7287, " ", $vqrange], _
	[7872, 6912, " ", $vqrange], _
	[7572, 6635, " ", $vqrange], _
	[7600, 5817, " ", $vqrange], _
	[7627, 4999, " ", $vqrange], _
	[7780, 4373, " ", $vqrange], _
	[8736, 4896, " ", $vqrange], _
	[9496, 5933, " ", $vqrange], _
	[9516, 6805, " ", $vqrange], _
	[9535, 7677, " ", $vqrange], _
	[8704, 7294, " ", $vqrange], _
	[7872, 6912, " ", $vqrange], _
	[7589, 6650, " ", $vqrange], _
	[7562, 5871, " ", $vqrange], _
	[7535, 5092, " ", $vqrange], _
	[7797, 4379, " ", $vqrange], _
	[7858, 3438, " ", $vqrange], _
	[7920, 2496, " ", $vqrange], _
	[7992, 2016, " ", $vqrange], _
	[7792, 1728, " ", $vqrange], _
	[7341, 1421, " ", $vqrange], _
	[7219, 371, " ", $vqrange], _
	[7098, -678, " ", $vqrange], _
	[6976, -1728, " ", $vqrange], _
	[7536, -2496, " ", $vqrange], _
	[8172, -3048, " ", $vqrange], _
	[8809, -3599, " ", $vqrange], _
	[8028, -2856, " ", $vqrange], _
	[7248, -2112, " ", $vqrange], _
	[7147, -1104, " ", $vqrange], _
	[7047, -96, " ", $vqrange], _
	[7207, 700, " ", $vqrange], _
	[7368, 1495, " ", $vqrange], _
	[7080, 2592, " ", $vqrange], _ ; auto
	[6868, 2620, " ", $vqrange], _
	[6591.6399, 3360, " ", $vqrange], _ ; auto
	[6368, 3744, " ", $vqrange], _
	[5562, 4320, " ", $vqrange], _
	[4757, 4572, " ", $vqrange], _
	[3843, 4332, " ", $vqrange], _
	[3390, 3606, " ", $vqrange], _
	[2938, 2880, " ", $vqrange], _
	[2336, 1664, " ", $vqrange], _
	[1552, 976, " ", $vqrange], _
	[768, 288, " ", $vqrange], _
	[-402, 18, " ", $vqrange], _
	[-1571, -251, " ", $vqrange], _
	[-2741, -521, " ", $vqrange], _
	[-3674, 28, " ", $vqrange], _
	[-4608, 576, " ", $vqrange], _
	[-5523, 833, " ", $vqrange], _
	[-5904, 1152, " ", $vqrange], _
	[-6132, 1152, " ", $vqrange], _
	[-6285, 1152, " ", $vqrange], _
	[-6438, 1152, " ", $vqrange], _
	[-6627, 1152, " ", $vqrange], _ ; auto
	[-6816, 1152, " ", $vqrange], _
	[-7584, 384, " ", $vqrange], _
	[-7752, -960, " ", $vqrange], _
	[-7920, -2304, " ", $vqrange], _
	[-6618, -2564, " ", $vqrange], _
	[-5316, -2823, " ", $vqrange], _
	[-6618, -2564, " ", $vqrange], _
	[-7920, -2304, " ", $vqrange], _
	[-8030, -1960, " ", $vqrange], _
	[-7584, -2400, " ", $vqrange], _
	[-6889, -2790, " ", $vqrange], _
	[-6194, -3179, " ", $vqrange], _
	[-7364, -3771, " ", $vqrange], _
	[-8533, -4362, " ", $vqrange], _
	[-9703, -4954, " ", $vqrange], _
	[-9086, -5651, " ", $vqrange], _
	[-8470, -6348, " ", $vqrange], _
	[-8808, -6144, " ", $vqrange], _
	[-8987, -6144, " ", $vqrange], _
	[-9138, -6144, " ", $vqrange], _
	[-9289, -6144, " ", $vqrange], _
	[-9440, -6144, " ", $vqrange], _
	[-9591, -6144, " ", $vqrange], _
	[-9742, -6144, " ", $vqrange], _
	[-9991, -6144, " ", $vqrange], _ ; auto
	[-10240, -6144, " ", $vqrange], _
	[-10353, -6155, " ", $vqrange], _
	[-9691, -4930, " ", $vqrange], _
	[-9600, -4416, " ", $vqrange], _
	[-10589, -4416, " ", $vqrange], _
	[-10836, -4416, " ", $vqrange], _
	[-10991, -4416, " ", $vqrange], _
	[-11145, -4416, " ", $vqrange], _
	[-11300, -4416, " ", $vqrange], _
	[-11578, -4416, " ", $vqrange], _
	[-11839, -4534, " ", $vqrange], _
	[-11913, -5155, " ", $vqrange], _
	[-11815, -4471, " ", $vqrange], _
	[-11578, -4416, " ", $vqrange], _
	[-11278, -4401, " ", $vqrange], _
	[-11119, -4392, " ", $vqrange], _
	[-10829, -4378, " ", $vqrange], _
	[-10670, -4369, " ", $vqrange], _
	[-10380, -4354, " ", $vqrange], _
	[-9182, -4293, " ", $vqrange], _
	[-10456, -4250, " ", $vqrange], _
	[-10653, -3901, " ", $vqrange], _
	[-10727, -3770, " ", $vqrange], _
	[-10801, -3639, " ", $vqrange], _
	[-10911.75, -3442.75, " ", $vqrange], _ ; auto
	[-11022.5, -3246.5, " ", $vqrange], _ ; auto
	[-11244, -2854, " ", $vqrange], _
	[-11076, -2017, " ", $vqrange], _
	[-10907, -1180, " ", $vqrange], _
	[-9566, -1164, " ", $vqrange], _
	[-8225, -1147, " ", $vqrange], _
	[-7772, -190, " ", $vqrange], _
	[-7320, 768, " ", $vqrange], _
	[-6721, 1585, " ", $vqrange], _
	[-6864, 2880, " ", $vqrange], _
	[-7579, 3633, " ", $vqrange], _
	[-8295, 4386, " ", $vqrange], _
	[-9188, 5174, " ", $vqrange], _
	[-10221, 4633, " ", $vqrange], _
	[-9977, 4624, " ", $vqrange], _ ; auto
	[-11255, 4093, " ", $vqrange], _
	[-12288, 3552, " ", $vqrange], _
	[-12801, 2776, " ", $vqrange], _
	[-13314, 2000, " ", $vqrange], _
	[-12777, 1240, " ", $vqrange], _
	[-12240, 480, " ", $vqrange], _
	[-11376, -384, " ", $vqrange], _ ; auto
	[-11277, -543, " ", $vqrange], _
	[-11824, 96, " ", $vqrange], _ ; auto
	[-12030, 129, " ", $vqrange], _
	[-12783, 800, " ", $vqrange], _
	[-13536, 1472, " ", $vqrange], _
	[-14928, 1248, " ", $vqrange], _
	[-15498, 672, " ", $vqrange], _
	[-16068, 96, " ", $vqrange], _
	[-17144, -511, " ", $vqrange], _
	[-17808, 0, " ", $vqrange], _
	[-18912, 128, " ", $vqrange], _
	[-20016, 256, " ", $vqrange], _
	[-21120, 384, " ", $vqrange], _
	[-21830, 716, " ", $vqrange], _
	[-22539, 1049, " ", $vqrange], _
	[-23160, 337, " ", $vqrange] _
]

