#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Kryta/ScoundrelsRise.au3
; Map: ScoundrelsRise (id 54), geometry from MAP 0000041193.pmap
; Repaired 0 of 0 blocked segments by inserting 0 waypoints.
; Smoothed 8 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Kryta_ScoundrelsRiseRoute01[140][4] = [ _
	[-2529, -5002, " ", $vqrange], _
	[-1456, -4037, " ", $vqrange], _
	[-470, -2966, " ", $vqrange], _
	[-349, -2875, " ", $vqrange], _
	[-228, -2784, " ", $vqrange], _
	[-107, -2693, " ", $vqrange], _
	[28, -2592, " ", $vqrange], _
	[250, -2567, " ", $vqrange], _
	[472, -2542, " ", $vqrange], _
	[917, -2493, " ", $vqrange], _
	[1806, -2394, " ", $vqrange], _
	[2763, -2033, " ", $vqrange], _
	[3074, -1906, " ", $vqrange], _
	[3229, -1843, " ", $vqrange], _
	[3375, -1783, " ", $vqrange], _
	[3540, -1716, " ", $vqrange], _
	[3695, -1653, " ", $vqrange], _
	[4006, -1526, " ", $vqrange], _
	[4333, -1079, " ", $vqrange], _
	[5013, -591, " ", $vqrange], _
	[4648, -167, " ", $vqrange], _
	[4915, 360, " ", $vqrange], _
	[3978, 494, " ", $vqrange], _
	[3316, 968, " ", $vqrange], _
	[2655, 1441, " ", $vqrange], _
	[1804, 1341, " ", $vqrange], _
	[2395, 1895, " ", $vqrange], _
	[2199, 2371, " ", $vqrange], _
	[2892, 2837, " ", $vqrange], _
	[3772, 3968, " ", $vqrange], _
	[3751, 4621, " ", $vqrange], _
	[2862, 4800, " ", $vqrange], _
	[3991, 4800, " ", $vqrange], _
	[4150, 4800, " ", $vqrange], _
	[4353, 4800, " ", $vqrange], _ ; auto
	[4556, 4800, " ", $vqrange], _
	[5120, 4800, " ", $vqrange], _
	[4813, 4418, " ", $vqrange], _
	[4960, 4653, " ", $vqrange], _
	[5106, 4888, " ", $vqrange], _
	[5268, 4899, " ", $vqrange], _
	[5520, 4916, " ", $vqrange], _
	[5934, 4944, " ", $vqrange], _
	[6761, 4999, " ", $vqrange], _
	[6792, 4748, " ", $vqrange], _
	[6903, 4919, " ", $vqrange], _
	[7015, 5090, " ", $vqrange], _
	[7238, 5431, " ", $vqrange], _
	[7321, 5559, " ", $vqrange], _
	[7405, 5687, " ", $vqrange], _
	[7544, 5900.5, " ", $vqrange], _ ; auto
	[7683, 6114, " ", $vqrange], _
	[6914, 7092, " ", $vqrange], _
	[6540, 7500, " ", $vqrange], _
	[6096, 8256, " ", $vqrange], _
	[5112, 8832, " ", $vqrange], _
	[4939, 8858, " ", $vqrange], _
	[4766, 8885, " ", $vqrange], _
	[4940, 8872, " ", $vqrange], _
	[5113, 8858, " ", $vqrange], _
	[5460, 8832, " ", $vqrange], _
	[4359, 8553, " ", $vqrange], _
	[3501, 7961, " ", $vqrange], _
	[3479, 6468, " ", $vqrange], _
	[2428, 5685, " ", $vqrange], _
	[1610, 5374, " ", $vqrange], _
	[791, 5064, " ", $vqrange], _
	[510, 5597, " ", $vqrange], _
	[122.5, 5773, " ", $vqrange], _ ; auto
	[-37, 6023, " ", $vqrange], _
	[-432, 7200, " ", $vqrange], _
	[-624, 7200, " ", $vqrange], _
	[-774, 7200, " ", $vqrange], _
	[-924, 7200, " ", $vqrange], _
	[-1200, 7200, " ", $vqrange], _
	[-1968, 7200, " ", $vqrange], _
	[-1015, 6605, " ", $vqrange], _
	[-1968, 7200, " ", $vqrange], _
	[-1200, 7200, " ", $vqrange], _
	[-1008, 7200, " ", $vqrange], _
	[-858, 7200, " ", $vqrange], _
	[-708, 7200, " ", $vqrange], _
	[-432, 7200, " ", $vqrange], _
	[-672, 7194, " ", $vqrange], _
	[-252, 7200, " ", $vqrange], _
	[-1268, 7468, " ", $vqrange], _
	[-2283, 7737, " ", $vqrange], _
	[-2925.5, 8082, " ", $vqrange], _ ; auto
	[-3104, 8092, " ", $vqrange], _
	[-3924, 8448, " ", $vqrange], _
	[-4571, 8588, " ", $vqrange], _
	[-4906.5, 8658, " ", $vqrange], _ ; auto
	[-5058.5234, 8689.7188, " ", $vqrange], _ ; auto
	[-5242, 8728, " ", $vqrange], _
	[-5158, 8757, " ", $vqrange], _
	[-5737, 9153, " ", $vqrange], _
	[-4460, 8620, " ", $vqrange], _
	[-3183, 8086, " ", $vqrange], _
	[-2926, 8082, " ", $vqrange], _
	[-1680, 7488, " ", $vqrange], _ ; auto
	[-2392, 7396, " ", $vqrange], _
	[-1859, 6710, " ", $vqrange], _
	[-2535, 6465, " ", $vqrange], _
	[-1730, 6448, " ", $vqrange], _
	[-924, 6432, " ", $vqrange], _
	[-1112, 6412, " ", $vqrange], _
	[-1300, 6391, " ", $vqrange], _
	[-1677, 6350, " ", $vqrange], _
	[-2430, 6269, " ", $vqrange], _
	[-2394, 5688, " ", $vqrange], _
	[-3249, 4711, " ", $vqrange], _
	[-3686, 4096, " ", $vqrange], _
	[-4190, 3109, " ", $vqrange], _
	[-4695, 2122, " ", $vqrange], _
	[-4876, 1269, " ", $vqrange], _
	[-5057, 416, " ", $vqrange], _
	[-5892, 559, " ", $vqrange], _
	[-5102, 1739, " ", $vqrange], _
	[-4312, 2919, " ", $vqrange], _
	[-3522, 4099, " ", $vqrange], _
	[-3036, 4838, " ", $vqrange], _
	[-2551, 5576, " ", $vqrange], _
	[-2298, 5574, " ", $vqrange], _
	[-1876, 5572, " ", $vqrange], _
	[-1722, 5571, " ", $vqrange], _
	[-1569, 5570, " ", $vqrange], _
	[-1384.5, 5569, " ", $vqrange], _ ; auto
	[-1200, 5568, " ", $vqrange], _
	[-668, 4943, " ", $vqrange], _
	[267, 3976, " ", $vqrange], _
	[1202, 3009, " ", $vqrange], _
	[2164, 2928, " ", $vqrange], _
	[3126, 2848, " ", $vqrange], _
	[4087, 2768, " ", $vqrange], _
	[4568, 2727, " ", $vqrange], _
	[4718, 2715, " ", $vqrange], _
	[4869, 2702, " ", $vqrange], _
	[5049, 2687, " ", $vqrange], _
	[5317, 2208, " ", $vqrange], _
	[5940, 1835, " ", $vqrange] _
]

