#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Kryta/TearsoftheFallen.au3
; Map: TearsoftheFallen (id 53), geometry from MAP 0000041192.pmap
; Repaired 0 of 0 blocked segments by inserting 0 waypoints.
; Smoothed 2 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Kryta_TearsoftheFallenRoute01[137][4] = [ _
	[3377, -6583, " ", $vqrange], _
	[2544, -5393, " ", $vqrange], _
	[1648, -6091, " ", $vqrange], _
	[752, -6790, " ", $vqrange], _
	[-144, -7488, " ", $vqrange], _
	[-294, -7505.5, " ", $vqrange], _ ; auto
	[-444, -7523, " ", $vqrange], _
	[-734, -7556, " ", $vqrange], _
	[-1324, -7624, " ", $vqrange], _
	[-1711, -6355, " ", $vqrange], _
	[-2097, -5085, " ", $vqrange], _
	[-2484, -3816, " ", $vqrange], _
	[-1464, -3780, " ", $vqrange], _
	[-954, -3762, " ", $vqrange], _
	[-699, -3753, " ", $vqrange], _
	[-444, -3744, " ", $vqrange], _
	[-1289, -3744, " ", $vqrange], _
	[-2134, -3744, " ", $vqrange], _
	[-2979, -3744, " ", $vqrange], _
	[-3402, -3744, " ", $vqrange], _
	[-3613, -3744, " ", $vqrange], _
	[-3771, -3744, " ", $vqrange], _
	[-3930, -3744, " ", $vqrange], _
	[-4088, -3744, " ", $vqrange], _ ; auto
	[-4246, -3744, " ", $vqrange], _
	[-4669, -3744, " ", $vqrange], _
	[-5514, -3744, " ", $vqrange], _
	[-6359, -3744, " ", $vqrange], _
	[-7204, -3744, " ", $vqrange], _
	[-6380, -3827, " ", $vqrange], _
	[-5555, -3910, " ", $vqrange], _
	[-4305, -3712, " ", $vqrange], _
	[-3056, -3514, " ", $vqrange], _
	[-1806, -3316, " ", $vqrange], _
	[-1502, -2477, " ", $vqrange], _
	[-850, -1742, " ", $vqrange], _
	[-199, -1006, " ", $vqrange], _
	[-675, 195, " ", $vqrange], _
	[-1151, 1396, " ", $vqrange], _
	[-1614, 2518, " ", $vqrange], _
	[-2077, 3639, " ", $vqrange], _
	[-2895, 3035, " ", $vqrange], _
	[-3713, 2430, " ", $vqrange], _
	[-4531, 1826, " ", $vqrange], _
	[-5626, 990, " ", $vqrange], _
	[-6720, 155, " ", $vqrange], _
	[-7815, -681, " ", $vqrange], _
	[-8078, -1632, " ", $vqrange], _
	[-8601, -2605, " ", $vqrange], _
	[-9006, -3149, " ", $vqrange], _
	[-8554, -2459, " ", $vqrange], _
	[-8256, -2016, " ", $vqrange], _
	[-7680, -768, " ", $vqrange], _
	[-7778, -554, " ", $vqrange], _
	[-6974, 698, " ", $vqrange], _
	[-6171, 1949, " ", $vqrange], _
	[-5202, 2717, " ", $vqrange], _
	[-4233, 3485, " ", $vqrange], _
	[-3648, 3456, " ", $vqrange], _
	[-5050, 3434, " ", $vqrange], _
	[-5401, 3428, " ", $vqrange], _
	[-5576, 3425, " ", $vqrange], _
	[-5729, 3423, " ", $vqrange], _
	[-5927, 3419, " ", $vqrange], _
	[-6102, 3417, " ", $vqrange], _
	[-6452, 3411, " ", $vqrange], _
	[-6382, 3236, " ", $vqrange], _
	[-6749, 4357, " ", $vqrange], _
	[-7116, 5477, " ", $vqrange], _
	[-7483, 6598, " ", $vqrange], _
	[-6816, 7872, " ", $vqrange], _
	[-5532, 8348, " ", $vqrange], _
	[-4248, 8825, " ", $vqrange], _
	[-4805, 9037, " ", $vqrange], _
	[-3842, 8646, " ", $vqrange], _
	[-2880, 8256, " ", $vqrange], _
	[-2196, 8242, " ", $vqrange], _
	[-1853, 8235, " ", $vqrange], _
	[-1682, 8232, " ", $vqrange], _
	[-1522, 8228, " ", $vqrange], _
	[-1340, 8224, " ", $vqrange], _
	[-1169, 8221, " ", $vqrange], _
	[-827, 8214, " ", $vqrange], _
	[-142, 8200, " ", $vqrange], _
	[194, 8115, " ", $vqrange], _
	[584, 7258, " ", $vqrange], _
	[973, 6401, " ", $vqrange], _
	[1984, 5877, " ", $vqrange], _
	[2996, 5353, " ", $vqrange], _
	[3024, 4992, " ", $vqrange], _
	[2136, 4992, " ", $vqrange], _
	[1983, 4992, " ", $vqrange], _
	[1831, 4992, " ", $vqrange], _
	[1678, 4992, " ", $vqrange], _
	[1470, 4992, " ", $vqrange], _
	[1248, 4992, " ", $vqrange], _
	[1063, 5022, " ", $vqrange], _
	[878, 5051, " ", $vqrange], _
	[1063, 5022, " ", $vqrange], _
	[1248, 4992, " ", $vqrange], _
	[1470, 4992, " ", $vqrange], _
	[1623, 4992, " ", $vqrange], _
	[1775, 4992, " ", $vqrange], _
	[1928, 4992, " ", $vqrange], _
	[2080, 4992, " ", $vqrange], _
	[3024, 4992, " ", $vqrange], _
	[3886, 6194, " ", $vqrange], _
	[3600, 4896, " ", $vqrange], _
	[4219, 4096, " ", $vqrange], _
	[5296, 3180, " ", $vqrange], _
	[6372, 2264, " ", $vqrange], _
	[6106, 1557, " ", $vqrange], _
	[5841, 850, " ", $vqrange], _
	[5394, -534, " ", $vqrange], _
	[4948, -1917, " ", $vqrange], _
	[4213, -2660, " ", $vqrange], _
	[3477, -3403, " ", $vqrange], _
	[2742, -4146, " ", $vqrange], _
	[2800, -3762, " ", $vqrange], _
	[3975, -3762, " ", $vqrange], _
	[4268, -3762, " ", $vqrange], _
	[4562, -3762, " ", $vqrange], _
	[5150, -3762, " ", $vqrange], _
	[6403, -4134, " ", $vqrange], _
	[7656, -4505, " ", $vqrange], _
	[6340, -4044, " ", $vqrange], _
	[5023, -3583, " ", $vqrange], _
	[3706, -3122, " ", $vqrange], _
	[2390, -2661, " ", $vqrange], _
	[1282, -2364, " ", $vqrange], _
	[173, -2066, " ", $vqrange], _
	[-936, -1768, " ", $vqrange], _
	[-2044, -1471, " ", $vqrange], _
	[-2611, -629, " ", $vqrange], _
	[-3177, 214, " ", $vqrange], _
	[-3744, 1056, " ", $vqrange], _
	[-3145, 1059, " ", $vqrange] _
]

