#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Kryta/WatchtowerCoast.au3
; Map: WatchtowerCoast (id 62), geometry from MAP 0000034222.pmap
; Repaired 1 of 2 blocked segments by inserting 2 waypoints.
; Smoothed 15 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; 1 segment(s) could not be routed and were left as-is.
; 2 hop(s) still exceed 1500 units (worst 2350 between index 4 and 5).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Kryta_WatchtowerCoastRoute01[338][4] = [ _
	[15452, -7007, " ", $vqrange], _
	[14793.5, -6360.5, " ", $vqrange], _ ; auto
	[14135, -5714, " ", $vqrange], _ ; auto
	[14701.1572, -5664, " ", $vqrange], _ ; auto
	[14790, -5702, " ", $vqrange], _
	[13011, -4166, " ", $vqrange], _
	[13618, -3289, " ", $vqrange], _
	[14226, -2413, " ", $vqrange], _
	[14833, -1536, " ", $vqrange], _
	[14376, -576, " ", $vqrange], _
	[13920, 384, " ", $vqrange], _
	[14695, 445, " ", $vqrange], _
	[13409, 747, " ", $vqrange], _
	[13121, 1034, " ", $vqrange], _
	[12431, 1258, " ", $vqrange], _
	[12725, 2549, " ", $vqrange], _
	[13019, 3840, " ", $vqrange], _
	[13312, 5131, " ", $vqrange], _
	[13606, 6422, " ", $vqrange], _
	[13187, 7579, " ", $vqrange], _
	[12768, 8736, " ", $vqrange], _
	[13209, 8833, " ", $vqrange], _
	[12658, 8928, " ", $vqrange], _
	[11844, 8682, " ", $vqrange], _
	[11030, 8437, " ", $vqrange], _
	[11683, 7578, " ", $vqrange], _
	[12336, 6720, " ", $vqrange], _
	[11492, 6653, " ", $vqrange], _
	[12248, 5554, " ", $vqrange], _
	[13004, 4454, " ", $vqrange], _
	[13761, 3355, " ", $vqrange], _
	[13776, 2397, " ", $vqrange], _
	[13792, 1440, " ", $vqrange], _
	[12672, 1377, " ", $vqrange], _
	[11552, 1313, " ", $vqrange], _
	[11261, 1270, " ", $vqrange], _
	[10380, 444, " ", $vqrange], _
	[9500, -381, " ", $vqrange], _
	[8619, -1207, " ", $vqrange], _
	[8222, -1180, " ", $vqrange], _
	[8023, -1166, " ", $vqrange], _
	[7824, -1152, " ", $vqrange], _
	[7834, -864, " ", $vqrange], _
	[7495, -864, " ", $vqrange], _
	[7326, -864, " ", $vqrange], _
	[7157, -864, " ", $vqrange], _
	[6480, -864, " ", $vqrange], _
	[5760, -1632, " ", $vqrange], _
	[4316, -1931, " ", $vqrange], _
	[2872, -2230, " ", $vqrange], _
	[4316, -1931, " ", $vqrange], _
	[5760, -1632, " ", $vqrange], _
	[6048, -352, " ", $vqrange], _
	[6336, 928, " ", $vqrange], _
	[6624, 2208, " ", $vqrange], _
	[7968, 2218, " ", $vqrange], _
	[9312, 2228, " ", $vqrange], _
	[9032, 2971, " ", $vqrange], _
	[8751, 3714, " ", $vqrange], _
	[7529, 3342, " ", $vqrange], _
	[6307, 2971, " ", $vqrange], _
	[5085, 2600, " ", $vqrange], _
	[3863, 2228, " ", $vqrange], _
	[3087, 2773, " ", $vqrange], _
	[2311, 3318, " ", $vqrange], _
	[3113, 4356, " ", $vqrange], _
	[3914, 5394, " ", $vqrange], _
	[4716, 6432, " ", $vqrange], _
	[5599, 6478, " ", $vqrange], _
	[6481, 6524, " ", $vqrange], _
	[7001, 7776, " ", $vqrange], _
	[6373, 7586, " ", $vqrange], _
	[4991, 7288, " ", $vqrange], _
	[3610, 6989, " ", $vqrange], _
	[2228, 6691, " ", $vqrange], _
	[847, 6392, " ", $vqrange], _
	[-535, 6094, " ", $vqrange], _
	[-1916, 5795, " ", $vqrange], _
	[-1855, 4944, " ", $vqrange], _
	[-1794, 4092, " ", $vqrange], _
	[-2096, 4608, " ", $vqrange], _
	[-2596, 4608, " ", $vqrange], _
	[-1994, 4608, " ", $vqrange], _ ; auto
	[-1693, 4608, " ", $vqrange], _ ; auto
	[-1542.5, 4608, " ", $vqrange], _ ; auto
	[-1392, 4608, " ", $vqrange], _
	[-188, 4608, " ", $vqrange], _
	[-784, 4608, " ", $vqrange], _
	[-944, 3792, " ", $vqrange], _
	[-1104, 2976, " ", $vqrange], _
	[-864, 2016, " ", $vqrange], _
	[-1032, 1728, " ", $vqrange], _
	[-1454, 354, " ", $vqrange], _
	[-1839, -1121, " ", $vqrange], _
	[-2084, -2480, " ", $vqrange], _
	[-2328, -3840, " ", $vqrange], _
	[-2015, -3981, " ", $vqrange], _
	[-710, -4382, " ", $vqrange], _
	[595, -4783, " ", $vqrange], _
	[1899, -5184, " ", $vqrange], _
	[2121, -5765, " ", $vqrange], _
	[1948, -5962, " ", $vqrange], _
	[651, -5727, " ", $vqrange], _
	[-646, -5492, " ", $vqrange], _
	[-1943, -5257, " ", $vqrange], _
	[-2268, -5199, " ", $vqrange], _
	[-2430, -5169, " ", $vqrange], _
	[-2592, -5140, " ", $vqrange], _
	[-2754, -5110, " ", $vqrange], _
	[-2916, -5081, " ", $vqrange], _
	[-3078, -5052, " ", $vqrange], _
	[-3241, -5022, " ", $vqrange], _
	[-3931, -4542, " ", $vqrange], _
	[-3549, -3188, " ", $vqrange], _
	[-3166, -1834, " ", $vqrange], _
	[-2784, -480, " ", $vqrange], _
	[-2311, 466, " ", $vqrange], _
	[-2116, 1193, " ", $vqrange], _
	[-1920, 1920, " ", $vqrange], _
	[-1392, 2784, " ", $vqrange], _
	[-864, 3648, " ", $vqrange], _
	[-892, 4705, " ", $vqrange], _
	[-1193, 4681, " ", $vqrange], _
	[-1344, 4669, " ", $vqrange], _
	[-1494, 4656, " ", $vqrange], _
	[-1644, 4644, " ", $vqrange], _
	[-1795, 4632, " ", $vqrange], _
	[-2096, 4608, " ", $vqrange], _
	[-2218, 3840, " ", $vqrange], _
	[-2642, 3840, " ", $vqrange], _
	[-2855, 3840, " ", $vqrange], _
	[-3014, 3840, " ", $vqrange], _
	[-3173, 3840, " ", $vqrange], _
	[-3332.5, 3840, " ", $vqrange], _ ; auto
	[-3492, 3840, " ", $vqrange], _
	[-3917, 3840, " ", $vqrange], _
	[-4766, 3840, " ", $vqrange], _
	[-5616, 3840, " ", $vqrange], _
	[-6623, 4025, " ", $vqrange], _
	[-7630, 4210, " ", $vqrange], _
	[-6383, 3962, " ", $vqrange], _
	[-5136, 3714, " ", $vqrange], _
	[-3890, 3467, " ", $vqrange], _
	[-2643, 3219, " ", $vqrange], _
	[-2805, 2304, " ", $vqrange], _
	[-3583, 1292, " ", $vqrange], _
	[-4360, 280, " ", $vqrange], _
	[-5479, 70, " ", $vqrange], _
	[-6039, -35, " ", $vqrange], _
	[-6318, -88, " ", $vqrange], _
	[-6598, -140, " ", $vqrange], _
	[-6743, -187, " ", $vqrange], _
	[-7019, -277, " ", $vqrange], _
	[-7170, 870, " ", $vqrange], _
	[-7320, 2016, " ", $vqrange], _
	[-7927, 2459, " ", $vqrange], _
	[-7711, 1975, " ", $vqrange], _
	[-7408, 891, " ", $vqrange], _
	[-7256, 350, " ", $vqrange], _
	[-7208, 180, " ", $vqrange], _
	[-7166, 28, " ", $vqrange], _
	[-7104, -192, " ", $vqrange], _
	[-8158, -1174, " ", $vqrange], _
	[-7104, -192, " ", $vqrange], _
	[-6852, -192, " ", $vqrange], _
	[-6694, -192, " ", $vqrange], _
	[-6537, -192, " ", $vqrange], _
	[-6380, -192, " ", $vqrange], _
	[-6222, -192, " ", $vqrange], _
	[-5938.5, -192, " ", $vqrange], _ ; auto
	[-5655, -192, " ", $vqrange], _ ; auto
	[-5088, -192, " ", $vqrange], _
	[-5038, -1112, " ", $vqrange], _
	[-4988, -2032, " ", $vqrange], _
	[-5406, -2946, " ", $vqrange], _
	[-5824, -3859, " ", $vqrange], _
	[-6242, -4773, " ", $vqrange], _
	[-6768, -5280, " ", $vqrange], _
	[-7704, -5568, " ", $vqrange], _
	[-8172, -5712, " ", $vqrange], _ ; auto
	[-8406, -5784, " ", $vqrange], _ ; auto
	[-8640, -5856, " ", $vqrange], _
	[-8640, -6036, " ", $vqrange], _
	[-8640, -6336, " ", $vqrange], _
	[-8801, -6493, " ", $vqrange], _
	[-8948, -6637, " ", $vqrange], _
	[-9462, -7139, " ", $vqrange], _
	[-10284, -7942, " ", $vqrange], _
	[-10734, -8010, " ", $vqrange], _
	[-11474, -8036, " ", $vqrange], _
	[-11844, -8048, " ", $vqrange], _
	[-12029, -8055, " ", $vqrange], _
	[-12214, -8061, " ", $vqrange], _
	[-12375, -8061, " ", $vqrange], _
	[-12536, -8062, " ", $vqrange], _
	[-12688, -8062, " ", $vqrange], _
	[-12839, -8062, " ", $vqrange], _
	[-12990, -8063, " ", $vqrange], _
	[-13141, -8063, " ", $vqrange], _
	[-13504, -8064, " ", $vqrange], _
	[-14546, -8615, " ", $vqrange], _
	[-15589, -9166, " ", $vqrange], _
	[-16105, -9126, " ", $vqrange], _
	[-16550, -9126, " ", $vqrange], _
	[-16772, -9126, " ", $vqrange], _
	[-16925, -9126, " ", $vqrange], _
	[-17077, -9126, " ", $vqrange], _
	[-17438, -9126, " ", $vqrange], _
	[-17883, -9126, " ", $vqrange], _
	[-19023, -9760, " ", $vqrange], _
	[-17883, -9126, " ", $vqrange], _
	[-16769, -9046, " ", $vqrange], _
	[-15655, -8967, " ", $vqrange], _
	[-14580, -8516, " ", $vqrange], _
	[-14378, -8431, " ", $vqrange], _
	[-14235, -8371, " ", $vqrange], _
	[-14042, -8290, " ", $vqrange], _
	[-13504, -8064, " ", $vqrange], _
	[-13303, -8063, " ", $vqrange], _
	[-13152, -8062, " ", $vqrange], _
	[-13001, -8061, " ", $vqrange], _
	[-12850, -8061, " ", $vqrange], _
	[-12699, -8060, " ", $vqrange], _
	[-12548, -8059, " ", $vqrange], _
	[-12397, -8058, " ", $vqrange], _
	[-12246, -8057, " ", $vqrange], _
	[-12096, -8057, " ", $vqrange], _
	[-11894, -8056, " ", $vqrange], _
	[-11090, -8051, " ", $vqrange], _
	[-10687, -8049, " ", $vqrange], _
	[-10486, -8048, " ", $vqrange], _
	[-10285, -8047, " ", $vqrange], _
	[-10965, -7911, " ", $vqrange], _
	[-11410, -8261, " ", $vqrange], _
	[-10375, -8451, " ", $vqrange], _
	[-9339, -8642, " ", $vqrange], _
	[-8304, -8832, " ", $vqrange], _
	[-7450, -9609, " ", $vqrange], _
	[-6596, -10386, " ", $vqrange], _
	[-5742, -11163, " ", $vqrange], _
	[-4888, -11940, " ", $vqrange], _
	[-5454, -10803, " ", $vqrange], _
	[-6020, -9666, " ", $vqrange], _
	[-6586, -8529, " ", $vqrange], _
	[-7134, -7250, " ", $vqrange], _
	[-6903, -8137, " ", $vqrange], _
	[-6672, -9024, " ", $vqrange], _
	[-6296, -9024, " ", $vqrange], _
	[-6143, -9024, " ", $vqrange], _
	[-5920, -9024, " ", $vqrange], _
	[-5616, -8256, " ", $vqrange], _
	[-5434, -7010, " ", $vqrange], _
	[-5252, -5764, " ", $vqrange], _
	[-5494, -7202, " ", $vqrange], _
	[-5736, -8640, " ", $vqrange], _
	[-6507, -9925, " ", $vqrange], _
	[-6000, -10368, " ", $vqrange], _
	[-5232, -10368, " ", $vqrange], _
	[-5082, -10368, " ", $vqrange], _
	[-4848, -10368, " ", $vqrange], _
	[-4464, -10368, " ", $vqrange], _
	[-3804, -10176, " ", $vqrange], _
	[-4548, -9984, " ", $vqrange], _
	[-4144, -8666, " ", $vqrange], _
	[-3739, -7348, " ", $vqrange], _
	[-3335, -6030, " ", $vqrange], _
	[-3039, -6358, " ", $vqrange], _
	[-3039, -7746, " ", $vqrange], _
	[-3039, -9133, " ", $vqrange], _
	[-3920, -10038, " ", $vqrange], _
	[-4800, -10944, " ", $vqrange], _
	[-3986, -10946, " ", $vqrange], _
	[-3171, -10949, " ", $vqrange], _
	[-4149, -10964, " ", $vqrange], _
	[-4638, -10972, " ", $vqrange], _
	[-4790, -10975, " ", $vqrange], _
	[-4958, -10977.5, " ", $vqrange], _ ; auto
	[-5126, -10980, " ", $vqrange], _
	[-6104, -10996, " ", $vqrange], _
	[-6593, -11003, " ", $vqrange], _
	[-6838, -11007, " ", $vqrange], _
	[-7082, -11011, " ", $vqrange], _
	[-6869, -11032, " ", $vqrange], _
	[-6656, -11053, " ", $vqrange], _
	[-6230, -11094, " ", $vqrange], _
	[-5378, -11177, " ", $vqrange], _
	[-4952, -11219, " ", $vqrange], _
	[-4792, -11234, " ", $vqrange], _
	[-4632, -11250, " ", $vqrange], _
	[-3674, -11344, " ", $vqrange], _
	[-2821, -11427, " ", $vqrange], _
	[-2608, -11447, " ", $vqrange], _
	[-2449, -11463, " ", $vqrange], _
	[-2289, -11479, " ", $vqrange], _
	[-2129, -11494.5, " ", $vqrange], _ ; auto
	[-1969, -11510, " ", $vqrange], _
	[-1117, -11593, " ", $vqrange], _
	[-265, -11676, " ", $vqrange], _
	[-1140, -11550, " ", $vqrange], _
	[-2016, -11424, " ", $vqrange], _
	[-662, -11420, " ", $vqrange], _
	[693, -11415, " ", $vqrange], _
	[1370, -11413, " ", $vqrange], _ ; auto
	[1523.3828, -11412.5469, " ", $vqrange], _ ; auto
	[1708.5, -11412, " ", $vqrange], _ ; auto
	[2047, -11411, " ", $vqrange], _
	[2537, -10200, " ", $vqrange], _
	[3027, -8989, " ", $vqrange], _
	[3121, -8755, " ", $vqrange], _
	[3409, -8036, " ", $vqrange], _
	[3698, -7316, " ", $vqrange], _
	[4755, -7514, " ", $vqrange], _
	[5811, -7713, " ", $vqrange], _
	[6868, -7911, " ", $vqrange], _
	[7085, -9146, " ", $vqrange], _
	[7303, -10381, " ", $vqrange], _
	[7441.4521, -11424, " ", $vqrange], _ ; auto
	[7520, -11616, " ", $vqrange], _
	[7760, -11973, " ", $vqrange], _
	[8000, -12288, " ", $vqrange], _
	[8592, -12292, " ", $vqrange], _
	[8814, -12293, " ", $vqrange], _
	[8972, -12294, " ", $vqrange], _
	[9129, -12295, " ", $vqrange], _
	[9481, -12297, " ", $vqrange], _
	[9638, -12298, " ", $vqrange], _
	[9795, -12299, " ", $vqrange], _
	[10073, -12301, " ", $vqrange], _
	[10369, -12303, " ", $vqrange], _
	[10237, -10883, " ", $vqrange], _
	[10105, -9463, " ", $vqrange], _
	[9197, -8984, " ", $vqrange], _
	[8289, -8505, " ", $vqrange], _
	[9012, -7516, " ", $vqrange], _
	[9736, -6528, " ", $vqrange], _
	[10508, -5833, " ", $vqrange], _
	[11281, -5138, " ", $vqrange], _
	[12053, -4443, " ", $vqrange] _
]

