#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_NorthernShiverpeaks/GriffonsMouth.au3
; Map: GriffonsMouth (id 27), geometry from MAP 0000046590.pmap
; Repaired 1 of 1 blocked segments by inserting 1 waypoints.
; Smoothed 17 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_NorthernShiverpeaks_GriffonsMouthRoute01[189][4] = [ _
	[5472, 5376, " ", $vqrange], _
	[5750.5, 5387.75, " ", $vqrange], _ ; auto
	[6029, 5399.5, " ", $vqrange], _ ; auto
	[6586, 5423, " ", $vqrange], _
	[5662, 5727, " ", $vqrange], _
	[4944, 6336, " ", $vqrange], _
	[4800, 6528, " ", $vqrange], _
	[4176, 6912, " ", $vqrange], _
	[4224, 7104, " ", $vqrange], _
	[4128, 7584, " ", $vqrange], _
	[3655, 8160, " ", $vqrange], _
	[3499, 8203, " ", $vqrange], _
	[3343, 8246, " ", $vqrange], _
	[3032, 8331, " ", $vqrange], _
	[2990, 8158, " ", $vqrange], _
	[2770.5, 8039.25, " ", $vqrange], _ ; auto
	[2551, 7920.5, " ", $vqrange], _ ; auto
	[2112, 7683, " ", $vqrange], _
	[1963, 7334, " ", $vqrange], _
	[1440, 6720, " ", $vqrange], _
	[1229, 6689, " ", $vqrange], _ ; auto
	[1018, 6658, " ", $vqrange], _
	[597, 6595, " ", $vqrange], _
	[-48, 6912, " ", $vqrange], _
	[-648, 7968, " ", $vqrange], _
	[-1159, 8115, " ", $vqrange], _
	[-1919, 8042, " ", $vqrange], _
	[-2073, 8027, " ", $vqrange], _
	[-2227, 8012, " ", $vqrange], _
	[-2394, 7996, " ", $vqrange], _
	[-2678, 7968, " ", $vqrange], _
	[-3042, 7400, " ", $vqrange], _
	[-3224, 7115, " ", $vqrange], _
	[-3315, 6973, " ", $vqrange], _
	[-3406, 6831, " ", $vqrange], _
	[-3315, 6973, " ", $vqrange], _
	[-3224, 7115, " ", $vqrange], _
	[-3042, 7400, " ", $vqrange], _
	[-2678, 7968, " ", $vqrange], _
	[-2464, 7986, " ", $vqrange], _
	[-2309, 8000, " ", $vqrange], _
	[-2155, 8013, " ", $vqrange], _
	[-2001, 8026, " ", $vqrange], _
	[-1820, 8042, " ", $vqrange], _
	[-961, 8115, " ", $vqrange], _
	[-480, 7776, " ", $vqrange], _ ; auto
	[-206, 7384, " ", $vqrange], _
	[-367, 6241, " ", $vqrange], _
	[-762, 4946, " ", $vqrange], _
	[-1156, 3651, " ", $vqrange], _
	[-866, 3210, " ", $vqrange], _
	[-651, 3182, " ", $vqrange], _
	[-494, 3161.5, " ", $vqrange], _ ; auto
	[-337, 3141, " ", $vqrange], _
	[192, 3072, " ", $vqrange], _
	[1349, 2834, " ", $vqrange], _
	[220, 3049, " ", $vqrange], _
	[-345, 3156, " ", $vqrange], _
	[-557, 3197, " ", $vqrange], _
	[-762.7812, 3203.0938, " ", $vqrange], _ ; auto
	[-996, 3210, " ", $vqrange], _ ; auto
	[-710, 3225, " ", $vqrange], _
	[-910, 3264, " ", $vqrange], _
	[-1731, 3921, " ", $vqrange], _
	[-2345, 4080, " ", $vqrange], _
	[-2584, 4811, " ", $vqrange], _
	[-3518, 5166, " ", $vqrange], _
	[-4303, 4935, " ", $vqrange], _
	[-5088, 4704, " ", $vqrange], _
	[-5749, 4091, " ", $vqrange], _
	[-6410, 3478, " ", $vqrange], _
	[-6997, 2315, " ", $vqrange], _
	[-7584, 1152, " ", $vqrange], _
	[-7529, 905, " ", $vqrange], _
	[-6932, 308, " ", $vqrange], _
	[-6634, 10, " ", $vqrange], _
	[-6485, -139, " ", $vqrange], _
	[-6336, -288, " ", $vqrange], _
	[-6181, -374, " ", $vqrange], _
	[-6026, -460, " ", $vqrange], _
	[-5717, -632, " ", $vqrange], _
	[-5098, -977, " ", $vqrange], _
	[-3781, -1257, " ", $vqrange], _
	[-3627, -1290, " ", $vqrange], _
	[-3452, -1327, " ", $vqrange], _
	[-3122, -1397, " ", $vqrange], _
	[-2968, -1430, " ", $vqrange], _
	[-2793, -1467, " ", $vqrange], _
	[-2464, -1537, " ", $vqrange], _
	[-1957, -2487, " ", $vqrange], _
	[-1450, -3437, " ", $vqrange], _
	[-1550, -3577, " ", $vqrange], _ ; auto
	[-1650, -3717, " ", $vqrange], _ ; auto
	[-1850, -3997, " ", $vqrange], _
	[-1849, -4314, " ", $vqrange], _
	[-1814.1609, -3875.7, " ", $vqrange], _ ; auto
	[-1655, -3794, " ", $vqrange], _
	[-1600, -3648, " ", $vqrange], _
	[-1545, -3502, " ", $vqrange], _
	[-1460, -3274, " ", $vqrange], _
	[-1993, -2405, " ", $vqrange], _
	[-2557, -1440, " ", $vqrange], _
	[-2270, -1127, " ", $vqrange], _
	[-2307, -2181, " ", $vqrange], _
	[-2112, -2304, " ", $vqrange], _
	[-1450, -3437, " ", $vqrange], _
	[-1630, -3850, " ", $vqrange], _
	[-1814.1609, -3875.7, " ", $vqrange], _ ; auto
	[-1691, -3992, " ", $vqrange], _
	[-1991, -3997, " ", $vqrange], _ ; auto
	[-1753, -4134, " ", $vqrange], _
	[-1857.25, -4372.5, " ", $vqrange], _ ; auto
	[-1961.5, -4611, " ", $vqrange], _ ; auto
	[-2170, -5088, " ", $vqrange], _
	[-1582, -5472, " ", $vqrange], _
	[-1463, -5712, " ", $vqrange], _ ; auto
	[-1344, -5952, " ", $vqrange], _
	[-1458, -6874, " ", $vqrange], _
	[-1218, -6874, " ", $vqrange], _
	[-1068, -6874, " ", $vqrange], _
	[-918, -6874, " ", $vqrange], _
	[-768, -6874, " ", $vqrange], _
	[-498, -6874, " ", $vqrange], _
	[-75, -6125, " ", $vqrange], _
	[348, -5376, " ", $vqrange], _
	[504, -4800, " ", $vqrange], _
	[768, -4704, " ", $vqrange], _
	[937, -4588, " ", $vqrange], _
	[1067, -4514, " ", $vqrange], _
	[1184, -4417, " ", $vqrange], _
	[1312, -4329, " ", $vqrange], _
	[1464, -4224, " ", $vqrange], _
	[1824, -3264, " ", $vqrange], _
	[1824, -2976, " ", $vqrange], _
	[1700, -2208, " ", $vqrange], _
	[1575, -1440, " ", $vqrange], _
	[762, -1374, " ", $vqrange], _
	[1728, -2304, " ", $vqrange], _
	[1692, -3331, " ", $vqrange], _
	[1704, -3648, " ", $vqrange], _
	[1488, -4320, " ", $vqrange], _
	[2110, -4812, " ", $vqrange], _
	[2400, -5664, " ", $vqrange], _
	[3041, -6006, " ", $vqrange], _
	[4176, -5376, " ", $vqrange], _
	[4649, -4634, " ", $vqrange], _
	[5122, -3891, " ", $vqrange], _
	[6002, -3706, " ", $vqrange], _
	[6480, -4320, " ", $vqrange], _
	[6432, -5232, " ", $vqrange], _
	[6384, -6144, " ", $vqrange], _
	[5773, -6704, " ", $vqrange], _
	[5162, -7264, " ", $vqrange], _
	[5797, -6608, " ", $vqrange], _
	[6432, -5952, " ", $vqrange], _
	[6432, -5040, " ", $vqrange], _
	[6432, -4128, " ", $vqrange], _
	[5998, -3834, " ", $vqrange], _
	[5587, -2688, " ", $vqrange], _
	[5830, -2265, " ", $vqrange], _
	[5905, -2132, " ", $vqrange], _
	[5981, -2000, " ", $vqrange], _
	[6151, -1991, " ", $vqrange], _ ; auto
	[6072, -1841, " ", $vqrange], _
	[6054, -672, " ", $vqrange], _
	[6196, -356, " ", $vqrange], _
	[6011, -1728, " ", $vqrange], _
	[6089, -2016, " ", $vqrange], _
	[5884, -2133, " ", $vqrange], _
	[5752, -2208, " ", $vqrange], _
	[5584, -2304, " ", $vqrange], _
	[5547, -3291, " ", $vqrange], _
	[4766, -4430, " ", $vqrange], _
	[3984, -5568, " ", $vqrange], _
	[3009, -6002, " ", $vqrange], _
	[2328, -5568, " ", $vqrange], _
	[2016, -4686, " ", $vqrange], _
	[1535, -4368, " ", $vqrange], _
	[384, -4896, " ", $vqrange], _
	[140, -5712, " ", $vqrange], _
	[-104, -6528, " ", $vqrange], _
	[-570, -6574, " ", $vqrange], _
	[-498, -6874, " ", $vqrange], _
	[-1488, -7104, " ", $vqrange], _
	[-2200, -7104, " ", $vqrange], _
	[-2351, -7105, " ", $vqrange], _
	[-2501, -7105, " ", $vqrange], _
	[-2651, -7105, " ", $vqrange], _
	[-2913, -7105, " ", $vqrange] _
]

