#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_NorthernShiverpeaks/TravelersVale.au3
; Map: TravelersVale (id 99), geometry from MAP 0000046603.pmap
; Repaired 1 of 2 blocked segments by inserting 10 waypoints.
; Smoothed 32 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; 1 segment(s) could not be routed and were left as-is.
; 1 hop(s) still exceed 1500 units (worst 3529 between index 111 and 112).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_NorthernShiverpeaks_TravelersValeRoute01[251][4] = [ _
	[8207, -333, " ", $vqrange], _
	[9504, -694, " ", $vqrange], _
	[10800, -1056, " ", $vqrange], _
	[11108, -1978, " ", $vqrange], _
	[11417, -2899, " ", $vqrange], _
	[10948, -4031, " ", $vqrange], _
	[10479, -5164, " ", $vqrange], _
	[10010, -6296, " ", $vqrange], _
	[10131, -7372, " ", $vqrange], _
	[10253, -8448, " ", $vqrange], _
	[10108, -9423, " ", $vqrange], _
	[9963, -10398, " ", $vqrange], _
	[10077, -11404, " ", $vqrange], _
	[10192, -12411, " ", $vqrange], _
	[10306, -13417, " ", $vqrange], _
	[9612, -13964, " ", $vqrange], _
	[8917, -14510, " ", $vqrange], _
	[8105, -14551, " ", $vqrange], _
	[7953, -14559, " ", $vqrange], _
	[7801, -14566, " ", $vqrange], _
	[7648, -14574, " ", $vqrange], _
	[7496, -14582, " ", $vqrange], _
	[7293, -14592, " ", $vqrange], _
	[6488, -15654, " ", $vqrange], _
	[5683, -16716, " ", $vqrange], _
	[4618, -16470, " ", $vqrange], _
	[3552, -16224, " ", $vqrange], _
	[2951, -14883, " ", $vqrange], _
	[1584, -14546, " ", $vqrange], _
	[216, -14208, " ", $vqrange], _
	[338, -13873, " ", $vqrange], _
	[-264, -14785, " ", $vqrange], _
	[-866, -15697, " ", $vqrange], _
	[-1152, -16128, " ", $vqrange], _
	[-1314, -16140, " ", $vqrange], _
	[-1466, -16151, " ", $vqrange], _
	[-1618, -16162, " ", $vqrange], _
	[-1800, -16176, " ", $vqrange], _
	[-2448, -16224, " ", $vqrange], _
	[-1652, -16225, " ", $vqrange], _
	[-1254, -16226, " ", $vqrange], _
	[-1055, -16226, " ", $vqrange], _
	[-856, -16226, " ", $vqrange], _
	[-1015, -16305, " ", $vqrange], _
	[-1174, -16384, " ", $vqrange], _
	[-1493, -16542, " ", $vqrange], _
	[-2474, -16664, " ", $vqrange], _
	[-2965, -16724, " ", $vqrange], _
	[-3211, -16755, " ", $vqrange], _
	[-3456, -16785, " ", $vqrange], _
	[-3198, -16775, " ", $vqrange], _
	[-2940, -16765, " ", $vqrange], _
	[-2424, -16744, " ", $vqrange], _
	[-1392, -16704, " ", $vqrange], _
	[-1283, -15970, " ", $vqrange], _
	[-1851, -14644, " ", $vqrange], _
	[-2135, -13981, " ", $vqrange], _
	[-2277, -13650, " ", $vqrange], _
	[-2296, -13631, " ", $vqrange], _
	[-2316, -13613, " ", $vqrange], _
	[-2335, -13595, " ", $vqrange], _
	[-2354, -13577, " ", $vqrange], _
	[-2456, -13559, " ", $vqrange], _ ; auto
	[-2465.5, -13499, " ", $vqrange], _ ; auto
	[-2344, -13504, " ", $vqrange], _
	[-2333, -13504, " ", $vqrange], _
	[-2323, -13504, " ", $vqrange], _
	[-2312, -13504, " ", $vqrange], _
	[-2316, -13501, " ", $vqrange], _
	[-2321, -13499, " ", $vqrange], _
	[-2325, -13496, " ", $vqrange], _
	[-2330, -13494, " ", $vqrange], _
	[-2334, -13491, " ", $vqrange], _
	[-2339, -13489, " ", $vqrange], _
	[-2343, -13486, " ", $vqrange], _
	[-2348, -13484, " ", $vqrange], _
	[-2418, -13318, " ", $vqrange], _
	[-3080, -12849, " ", $vqrange], _
	[-3397, -12884, " ", $vqrange], _
	[-3632, -12729, " ", $vqrange], _
	[-4286, -12483, " ", $vqrange], _
	[-4862, -12555, " ", $vqrange], _
	[-5149, -12591, " ", $vqrange], _
	[-5437, -12627, " ", $vqrange], _
	[-5693, -12545, " ", $vqrange], _
	[-5949, -12463, " ", $vqrange], _
	[-6116, -12514, " ", $vqrange], _
	[-6284, -12564, " ", $vqrange], _
	[-6130, -12538, " ", $vqrange], _
	[-5791, -12480, " ", $vqrange], _
	[-6803, -12336, " ", $vqrange], _
	[-7814, -12192, " ", $vqrange], _
	[-8216, -11267, " ", $vqrange], _
	[-7342, -12259, " ", $vqrange], _
	[-6328, -12375, " ", $vqrange], _
	[-5315, -12491, " ", $vqrange], _
	[-4301, -12607, " ", $vqrange], _
	[-3242, -12882, " ", $vqrange], _
	[-2184, -13157, " ", $vqrange], _
	[-1140, -12530, " ", $vqrange], _
	[-97, -11902, " ", $vqrange], _
	[947, -11275, " ", $vqrange], _
	[1754, -10467, " ", $vqrange], _
	[2561, -9659, " ", $vqrange], _
	[2304, -10368, " ", $vqrange], _ ; auto
	[2701, -11001, " ", $vqrange], _
	[3398, -11616, " ", $vqrange], _
	[3322, -12900, " ", $vqrange], _
	[3307, -11448, " ", $vqrange], _
	[3292, -9996, " ", $vqrange], _
	[3278, -8544, " ", $vqrange], _
	[4254, -7633, " ", $vqrange], _
	[7700, -6871, " ", $vqrange], _
	[6772, -7067, " ", $vqrange], _
	[6541, -7116, " ", $vqrange], _
	[6381, -7150, " ", $vqrange], _
	[6222, -7183, " ", $vqrange], _
	[6062, -7217, " ", $vqrange], _
	[5845, -7263, " ", $vqrange], _
	[5671, -7300, " ", $vqrange], _
	[5512, -7333, " ", $vqrange], _
	[5352, -7367, " ", $vqrange], _
	[5149, -7410, " ", $vqrange], _
	[4918, -7459, " ", $vqrange], _
	[3990, -7655, " ", $vqrange], _
	[3147, -7332, " ", $vqrange], _
	[2304, -7008, " ", $vqrange], _
	[2096, -6324, " ", $vqrange], _
	[2718, -4995, " ", $vqrange], _
	[3341, -3666, " ", $vqrange], _
	[4014.599, -2899.9, " ", $vqrange], _ ; auto
	[4300, -2797, " ", $vqrange], _
	[5260, -1928, " ", $vqrange], _
	[6397, -1776, " ", $vqrange], _
	[6681.25, -1737.75, " ", $vqrange], _ ; auto
	[6965.5, -1699.5, " ", $vqrange], _ ; auto
	[7534, -1623, " ", $vqrange], _
	[6707, -1847, " ", $vqrange], _ ; auto
	[6169, -1858, " ", $vqrange], _
	[4804, -2093, " ", $vqrange], _
	[3439, -2328, " ", $vqrange], _
	[3267, -2325, " ", $vqrange], _
	[3117, -2322, " ", $vqrange], _
	[2966, -2320, " ", $vqrange], _
	[2752, -2316, " ", $vqrange], _
	[2064, -2304, " ", $vqrange], _
	[1005, -1759, " ", $vqrange], _
	[495, -1613, " ", $vqrange], _
	[-374, -1352, " ", $vqrange], _
	[-622, -1664, " ", $vqrange], _
	[-1035, -2487, " ", $vqrange], _
	[-1550, -2966, " ", $vqrange], _
	[-1625, -4076, " ", $vqrange], _
	[-1701, -5185, " ", $vqrange], _
	[-1776, -6295, " ", $vqrange], _
	[-1668, -4913, " ", $vqrange], _
	[-1560, -3532, " ", $vqrange], _
	[-1452, -2150, " ", $vqrange], _
	[-1344, -768, " ", $vqrange], _
	[-1550, -737, " ", $vqrange], _
	[-2287, -512, " ", $vqrange], _
	[-3024, -288, " ", $vqrange], _
	[-3429, 853, " ", $vqrange], _
	[-3184, 1337, " ", $vqrange], _
	[-2864, 2248, " ", $vqrange], _
	[-2544, 3160, " ", $vqrange], _
	[-2720, 4514, " ", $vqrange], _
	[-2897, 5869, " ", $vqrange], _
	[-2571, 6561, " ", $vqrange], _
	[-1686, 7404, " ", $vqrange], _
	[-801, 8248, " ", $vqrange], _
	[-1456, 9356, " ", $vqrange], _
	[-2112, 10464, " ", $vqrange], _
	[-3472.8, 10656, " ", $vqrange], _ ; auto
	[-3139, 10752, " ", $vqrange], _
	[-3412, 11003, " ", $vqrange], _
	[-3679, 11100, " ", $vqrange], _
	[-4607, 12008, " ", $vqrange], _
	[-5535, 12916, " ", $vqrange], _
	[-6463, 13824, " ", $vqrange], _
	[-7062, 13313, " ", $vqrange], _
	[-6822, 13261, " ", $vqrange], _
	[-6971, 13299, " ", $vqrange], _
	[-7154.5, 13346, " ", $vqrange], _ ; auto
	[-7338, 13393, " ", $vqrange], _
	[-8547, 12819, " ", $vqrange], _
	[-7348, 13410, " ", $vqrange], _
	[-6150, 14002, " ", $vqrange], _
	[-6867, 14676, " ", $vqrange], _
	[-6912, 15840, " ", $vqrange], _
	[-6371, 16077, " ", $vqrange], _
	[-5286, 16652, " ", $vqrange], _
	[-4202, 17226, " ", $vqrange], _
	[-3117, 17801, " ", $vqrange], _
	[-2184, 17376, " ", $vqrange], _
	[-2224, 16896, " ", $vqrange], _
	[-2035, 16561, " ", $vqrange], _
	[-1720, 16362, " ", $vqrange], _
	[-1563, 16262, " ", $vqrange], _
	[-1406, 16162, " ", $vqrange], _
	[-1699, 16193, " ", $vqrange], _
	[-1991, 16224, " ", $vqrange], _
	[-2080, 16427, " ", $vqrange], _
	[-1490, 16440, " ", $vqrange], _
	[-1195, 16447, " ", $vqrange], _
	[-1039, 16451, " ", $vqrange], _
	[-882, 16454, " ", $vqrange], _
	[-726, 16458, " ", $vqrange], _
	[-518.5, 16463, " ", $vqrange], _ ; auto
	[-311, 16468, " ", $vqrange], _
	[278, 16481, " ", $vqrange], _
	[239, 15300, " ", $vqrange], _
	[536, 14324, " ", $vqrange], _
	[1248, 13440, " ", $vqrange], _ ; auto
	[832, 13347, " ", $vqrange], _
	[690, 14178, " ", $vqrange], _
	[603, 14686, " ", $vqrange], _
	[662, 13823, " ", $vqrange], _
	[720, 12960, " ", $vqrange], _
	[-80, 12864, " ", $vqrange], _
	[-880, 12768, " ", $vqrange], _
	[-733, 12616, " ", $vqrange], _
	[-1633, 12227, " ", $vqrange], _
	[-1848, 11298, " ", $vqrange], _
	[-2064, 10368, " ", $vqrange], _
	[-1646, 9483, " ", $vqrange], _
	[-1227, 8598, " ", $vqrange], _
	[-638, 7563, " ", $vqrange], _
	[-48, 6528, " ", $vqrange], _
	[217, 6522, " ", $vqrange], _
	[375, 6519, " ", $vqrange], _
	[533, 6515, " ", $vqrange], _
	[690, 6512, " ", $vqrange], _
	[852, 6508.5, " ", $vqrange], _ ; auto
	[1014, 6505, " ", $vqrange], _
	[2076, 6481, " ", $vqrange], _
	[1825, 6460, " ", $vqrange], _
	[2370, 5556, " ", $vqrange], _
	[2915, 4653, " ", $vqrange], _
	[2107, 4256, " ", $vqrange], _
	[1299, 3860, " ", $vqrange], _
	[2093, 4532, " ", $vqrange], _
	[2886, 5204, " ", $vqrange], _
	[3284, 5688, " ", $vqrange], _
	[3075, 6866, " ", $vqrange], _
	[4084, 6942, " ", $vqrange], _
	[4337, 6960, " ", $vqrange], _
	[4487, 6972, " ", $vqrange], _
	[4637, 6983, " ", $vqrange], _
	[4842, 6998, " ", $vqrange], _
	[5094, 7017, " ", $vqrange] _
]

