#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_KainengCity/BukdekByway.au3
; Map: BukdekByway (id 240), geometry from MAP 0000321291.pmap
; Repaired 7 of 20 blocked segments by inserting 40 waypoints.
; Smoothed 79 additional anchor(s) for wall clearance and hop distance.
; Filled 15 long hop(s) by walking the current mesh component toward a disconnected goal.
; 13 segment(s) could not be routed and were left as-is.
; 14 hop(s) still exceed 1500 units (worst 10035 between index 230 and 231).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_KainengCity_BukdekBywayRoute01[235][4] = [ _
	[-8896, -10049, " ", $vqrange], _
	[-7851, -9668, " ", $vqrange], _
	[-6805, -9286, " ", $vqrange], _
	[-5760, -8905, " ", $vqrange], _
	[-4819, -9798, " ", $vqrange], _
	[-3877, -10691, " ", $vqrange], _
	[-3037, -10842, " ", $vqrange], _
	[-2196, -10992, " ", $vqrange], _
	[-1280.1362, -11250, " ", $vqrange], _ ; auto
	[-364.2724, -11508, " ", $vqrange], _ ; auto
	[803.8638, -11508, " ", $vqrange], _ ; auto
	[1972, -11508, " ", $vqrange], _
	[1190, -13031, " ", $vqrange], _
	[3762, -12138, " ", $vqrange], _
	[4129, -11441, " ", $vqrange], _
	[4496, -10744, " ", $vqrange], _
	[5084, -10744, " ", $vqrange], _
	[5249, -10744, " ", $vqrange], _
	[5414, -10744, " ", $vqrange], _
	[5671, -10744, " ", $vqrange], _
	[6846, -10744, " ", $vqrange], _
	[7333, -10819, " ", $vqrange], _
	[6381, -10136, " ", $vqrange], _
	[5428, -9454, " ", $vqrange], _
	[5942, -8720, " ", $vqrange], _
	[6457, -7987, " ", $vqrange], _
	[7343, -7689, " ", $vqrange], _
	[8470, -7592, " ", $vqrange], _
	[9597, -7495, " ", $vqrange], _
	[10724, -7398, " ", $vqrange], _
	[11197, -7148, " ", $vqrange], _
	[11646, -6387, " ", $vqrange], _
	[12096, -5626, " ", $vqrange], _
	[12144, -5280, " ", $vqrange], _
	[12041, -4992, " ", $vqrange], _
	[11784, -4964, " ", $vqrange], _
	[11527, -4936, " ", $vqrange], _
	[11013, -4880, " ", $vqrange], _
	[9985, -4768, " ", $vqrange], _
	[8659, -4857, " ", $vqrange], _
	[7333, -4946, " ", $vqrange], _
	[7001.25, -4968.25, " ", $vqrange], _ ; auto
	[6669.5, -4990.5, " ", $vqrange], _ ; auto
	[6006, -5035, " ", $vqrange], _
	[5264, -5436, " ", $vqrange], _
	[4521, -5838, " ", $vqrange], _
	[2201, -8490, " ", $vqrange], _
	[-2861, -7833, " ", $vqrange], _
	[-2704.5, -7382.5, " ", $vqrange], _ ; auto
	[-2626.25, -7157.25, " ", $vqrange], _ ; auto
	[-2548, -6932, " ", $vqrange], _ ; auto
	[-2890.9307, -6912.1, " ", $vqrange], _ ; auto
	[-3046.0737, -4434.7, " ", $vqrange], _ ; auto
	[-2649, -3518, " ", $vqrange], _
	[-978, 1103, " ", $vqrange], _
	[-282, 1243, " ", $vqrange], _
	[-1017, 1274, " ", $vqrange], _
	[-1385, 1290, " ", $vqrange], _
	[-1569, 1297, " ", $vqrange], _
	[-281.389, 1305, " ", $vqrange], _ ; auto
	[-1753, 1305, " ", $vqrange], _
	[-1755, 2586, " ", $vqrange], _
	[-1756, 3866, " ", $vqrange], _
	[-1758, 5146, " ", $vqrange], _
	[-1760, 6427, " ", $vqrange], _
	[-1606, 5147, " ", $vqrange], _
	[-1453, 3866, " ", $vqrange], _
	[-1299, 2586, " ", $vqrange], _
	[-1146, 1306, " ", $vqrange], _
	[-978, 1103, " ", $vqrange], _
	[-948, -92, " ", $vqrange], _
	[-919, -1287, " ", $vqrange], _
	[-889, -2482, " ", $vqrange], _
	[260, -2502, " ", $vqrange], _
	[1408, -2521, " ", $vqrange], _
	[2557, -2540, " ", $vqrange], _
	[3706, -2560, " ", $vqrange], _
	[4795, -2599, " ", $vqrange], _
	[5883, -2639, " ", $vqrange], _
	[6972, -2678, " ", $vqrange], _
	[8155, -2112, " ", $vqrange], _
	[8535, -2094, " ", $vqrange], _
	[8724, -2085, " ", $vqrange], _
	[8890, -2077, " ", $vqrange], _
	[9045, -2070, " ", $vqrange], _
	[9199, -2062, " ", $vqrange], _
	[9436, -2051, " ", $vqrange], _ ; auto
	[9673, -2040, " ", $vqrange], _
	[10470, -2026, " ", $vqrange], _
	[11266, -2013, " ", $vqrange], _
	[11280, -1391, " ", $vqrange], _
	[11284, -1236, " ", $vqrange], _
	[11285, -1197, " ", $vqrange], _
	[11285, -1177, " ", $vqrange], _
	[11286, -1158, " ", $vqrange], _
	[11286, -1138, " ", $vqrange], _
	[11287, -1119, " ", $vqrange], _
	[11287, -1099, " ", $vqrange], _
	[11287, -1080, " ", $vqrange], _
	[11288, -1061, " ", $vqrange], _
	[11288, -1041, " ", $vqrange], _
	[11289, -1022, " ", $vqrange], _
	[11289, -1002, " ", $vqrange], _
	[11290, -983, " ", $vqrange], _
	[11290, -963, " ", $vqrange], _
	[11291, -944, " ", $vqrange], _
	[11291, -924, " ", $vqrange], _
	[11292, -905, " ", $vqrange], _
	[11292, -886, " ", $vqrange], _
	[11292, -866, " ", $vqrange], _
	[11293, -847, " ", $vqrange], _
	[11458.207, -829, " ", $vqrange], _ ; auto
	[11293, -827, " ", $vqrange], _
	[11294, -808, " ", $vqrange], _
	[11295, -769, " ", $vqrange], _
	[11296, -691, " ", $vqrange], _
	[11297, -672, " ", $vqrange], _
	[11297, -652, " ", $vqrange], _
	[11298, -633, " ", $vqrange], _
	[11298, -614, " ", $vqrange], _
	[11299, -594, " ", $vqrange], _
	[11299, -575, " ", $vqrange], _
	[11300, -555, " ", $vqrange], _
	[11300, -536, " ", $vqrange], _
	[11300, -516, " ", $vqrange], _
	[11301, -497, " ", $vqrange], _
	[11301, -477, " ", $vqrange], _
	[11302, -458, " ", $vqrange], _
	[11302, -439, " ", $vqrange], _
	[11303, -419, " ", $vqrange], _
	[11303, -400, " ", $vqrange], _
	[11304, -380, " ", $vqrange], _
	[11304, -361, " ", $vqrange], _
	[11305, -341, " ", $vqrange], _
	[11459.5967, -336, " ", $vqrange], _ ; auto
	[11305, -322, " ", $vqrange], _
	[11305, -302, " ", $vqrange], _
	[11309, -147, " ", $vqrange], _
	[11309, -128, " ", $vqrange], _
	[11310, -108, " ", $vqrange], _
	[11310, -89, " ", $vqrange], _
	[11311, -69, " ", $vqrange], _
	[11311, -50, " ", $vqrange], _
	[11312, -30, " ", $vqrange], _
	[11312, -11, " ", $vqrange], _
	[11313, 8, " ", $vqrange], _
	[11313, 28, " ", $vqrange], _
	[11313, 47, " ", $vqrange], _
	[11314, 67, " ", $vqrange], _
	[11314, 86, " ", $vqrange], _
	[11315, 106, " ", $vqrange], _
	[11315, 125, " ", $vqrange], _
	[11316, 164, " ", $vqrange], _
	[11323, 475, " ", $vqrange], _
	[11327, 630, " ", $vqrange], _
	[11327, 650, " ", $vqrange], _
	[11328, 669, " ", $vqrange], _
	[11328, 689, " ", $vqrange], _
	[11329, 708, " ", $vqrange], _
	[11329, 728, " ", $vqrange], _
	[11330, 747, " ", $vqrange], _
	[11330, 767, " ", $vqrange], _
	[11330, 786, " ", $vqrange], _
	[11331, 805, " ", $vqrange], _
	[11331, 825, " ", $vqrange], _
	[11332, 864, " ", $vqrange], _
	[11334, 942, " ", $vqrange], _
	[11338, 1097, " ", $vqrange], _
	[11303.1943, 1168, " ", $vqrange], _ ; auto
	[11327.5972, 1443.5, " ", $vqrange], _ ; auto
	[11352, 1719, " ", $vqrange], _
	[11366, 2341, " ", $vqrange], _
	[11367, 2372, " ", $vqrange], _
	[11289.2837, 2372, " ", $vqrange], _ ; auto
	[11347, 2404, " ", $vqrange], _
	[11288.7002, 2434, " ", $vqrange], _ ; auto
	[11291.4277, 2436, " ", $vqrange], _ ; auto
	[11368, 2436, " ", $vqrange], _
	[11370, 2496, " ", $vqrange], _
	[11373, 2652, " ", $vqrange], _
	[11377, 2808, " ", $vqrange], _
	[11378, 2827, " ", $vqrange], _
	[11378, 2846, " ", $vqrange], _
	[11378, 2866, " ", $vqrange], _
	[11379, 2885, " ", $vqrange], _
	[11379, 2905, " ", $vqrange], _
	[11380, 2924, " ", $vqrange], _
	[11380, 2944, " ", $vqrange], _
	[11381, 2963, " ", $vqrange], _
	[11389, 3114, " ", $vqrange], _
	[11401, 3325, " ", $vqrange], _
	[11822, 3704, " ", $vqrange], _
	[11597, 3408, " ", $vqrange], _
	[11505, 3288, " ", $vqrange], _
	[11372, 3113, " ", $vqrange], _
	[11371, 2947, " ", $vqrange], _
	[11371, 2781, " ", $vqrange], _
	[11370, 2582, " ", $vqrange], _
	[11346, 2423, " ", $vqrange], _
	[11357, 2236.5, " ", $vqrange], _ ; auto
	[11368, 2050, " ", $vqrange], _
	[11320.3823, 1577, " ", $vqrange], _ ; auto
	[11296.5735, 1340.5, " ", $vqrange], _ ; auto
	[11272.7646, 1104, " ", $vqrange], _ ; auto
	[11365, 987, " ", $vqrange], _
	[11375, -52, " ", $vqrange], _ ; auto
	[11385, -1091, " ", $vqrange], _
	[11249.269, -1114, " ", $vqrange], _ ; auto
	[11324, -1273, " ", $vqrange], _
	[11313, -1319, " ", $vqrange], _
	[11194, -1981, " ", $vqrange], _
	[10434, -2010, " ", $vqrange], _
	[9673, -2040, " ", $vqrange], _
	[9294, -2058, " ", $vqrange], _
	[9139, -2065, " ", $vqrange], _
	[8985, -2073, " ", $vqrange], _
	[8819, -2080, " ", $vqrange], _
	[8535, -2094, " ", $vqrange], _
	[8155, -2112, " ", $vqrange], _
	[6844, -2767, " ", $vqrange], _
	[3308, -367, " ", $vqrange], _
	[5398, 4370, " ", $vqrange], _
	[8013, 5940, " ", $vqrange], _
	[8505, 5968, " ", $vqrange], _
	[7057, 5978, " ", $vqrange], _
	[5609, 5989, " ", $vqrange], _
	[4161, 5999, " ", $vqrange], _
	[4567, 7410, " ", $vqrange], _
	[4974, 8820, " ", $vqrange], _
	[5380, 10231, " ", $vqrange], _
	[4585, 14354, " ", $vqrange], _
	[-5403, 13383, " ", $vqrange], _
	[3597, 16816, " ", $vqrange], _
	[-1308, 16658, " ", $vqrange], _
	[-9369, 11527, " ", $vqrange] _
]

