#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_KainengCity/NahpuiQuarter.au3
; Map: NahpuiQuarter (id 265), geometry from MAP 0000157177.pmap
; Repaired 1 of 3 blocked segments by inserting 8 waypoints.
; Smoothed 15 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; 2 segment(s) could not be routed and were left as-is.
; 2 hop(s) still exceed 1500 units (worst 3563 between index 35 and 36).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_KainengCity_NahpuiQuarterRoute01[135][4] = [ _
	[10479, 12811, " ", $vqrange], _
	[10650, 11919, " ", $vqrange], _
	[10822, 11027, " ", $vqrange], _
	[12054, 10822, " ", $vqrange], _
	[13287, 10618, " ", $vqrange], _
	[14520, 10413, " ", $vqrange], _
	[15752, 10208, " ", $vqrange], _
	[16606, 9275, " ", $vqrange], _
	[17460, 8342, " ", $vqrange], _
	[18314, 7409, " ", $vqrange], _
	[19168, 6476, " ", $vqrange], _
	[19241.1426, 5442, " ", $vqrange], _ ; auto
	[18994, 5394, " ", $vqrange], _
	[18820, 4312, " ", $vqrange], _
	[17675, 3915, " ", $vqrange], _
	[16530, 3518, " ", $vqrange], _
	[17319, 3106, " ", $vqrange], _
	[18107, 2694, " ", $vqrange], _
	[16929, 2676, " ", $vqrange], _
	[16634, 2672, " ", $vqrange], _
	[16413, 2668, " ", $vqrange], _
	[16256, 2666, " ", $vqrange], _
	[16045, 2662, " ", $vqrange], _
	[15750, 2658, " ", $vqrange], _
	[14292, 2903, " ", $vqrange], _
	[14424, 2980, " ", $vqrange], _
	[14292, 4038, " ", $vqrange], _
	[14161, 5095, " ", $vqrange], _
	[12705, 5053, " ", $vqrange], _
	[12444, 3612, " ", $vqrange], _
	[12182, 2170, " ", $vqrange], _
	[11191, 2208, " ", $vqrange], _
	[11298, 3416, " ", $vqrange], _
	[11404, 4625, " ", $vqrange], _
	[11511, 5833, " ", $vqrange], _
	[11383, 6704, " ", $vqrange], _
	[7828, 6949, " ", $vqrange], _
	[6098, 7481, " ", $vqrange], _
	[6715, 6910, " ", $vqrange], _
	[7332, 6339, " ", $vqrange], _
	[7255, 5866, " ", $vqrange], _
	[7206, 4701, " ", $vqrange], _
	[7158, 3536, " ", $vqrange], _
	[7676, 3013, " ", $vqrange], _
	[8394, 2630, " ", $vqrange], _
	[9112, 2248, " ", $vqrange], _
	[9120, 1898, " ", $vqrange], _
	[9033, 546, " ", $vqrange], _
	[8946, -805, " ", $vqrange], _
	[8731, -953, " ", $vqrange], _
	[8270, -1590, " ", $vqrange], _
	[7810, -2226, " ", $vqrange], _
	[7041, -2578, " ", $vqrange], _
	[6766, -3769, " ", $vqrange], _
	[5559, -3803, " ", $vqrange], _
	[5389, -3558, " ", $vqrange], _
	[5299, -3429, " ", $vqrange], _
	[5210, -3299, " ", $vqrange], _
	[5080, -3112, " ", $vqrange], _
	[4920, -2882, " ", $vqrange], _
	[4281, -1961, " ", $vqrange], _
	[3920, -1152, " ", $vqrange], _
	[4808, -165, " ", $vqrange], _
	[4144, -768, " ", $vqrange], _
	[3812, -1961, " ", $vqrange], _
	[4232, -1973, " ", $vqrange], _
	[4848, -2872, " ", $vqrange], _
	[5464, -3772, " ", $vqrange], _
	[6230, -3750, " ", $vqrange], _
	[6995, -3727, " ", $vqrange], _
	[7107, -2365, " ", $vqrange], _
	[7827, -1950, " ", $vqrange], _
	[8547, -1535, " ", $vqrange], _
	[9168, -350, " ", $vqrange], _
	[9789, 835, " ", $vqrange], _
	[10203, 850, " ", $vqrange], _
	[11308, 1626, " ", $vqrange], _
	[12413, 2402, " ", $vqrange], _
	[12564, 3610, " ", $vqrange], _
	[12715, 4819, " ", $vqrange], _
	[13003, 5214, " ", $vqrange], _
	[14315, 4919, " ", $vqrange], _
	[14304, 3911, " ", $vqrange], _
	[14292, 2903, " ", $vqrange], _
	[14666, 1831, " ", $vqrange], _
	[15039, 758, " ", $vqrange], _
	[15413, -314, " ", $vqrange], _
	[15544, -1093, " ", $vqrange], _
	[15842, -2488, " ", $vqrange], _
	[14780.479, -3137.775, " ", $vqrange], _ ; auto
	[13718.958, -3787.55, " ", $vqrange], _ ; auto
	[14929.479, -3834.775, " ", $vqrange], _ ; auto
	[16140, -3882, " ", $vqrange], _
	[16298, -2733, " ", $vqrange], _
	[16455, -1584, " ", $vqrange], _
	[16784, -563, " ", $vqrange], _
	[17113, 457, " ", $vqrange], _
	[18106, 903, " ", $vqrange], _
	[19098, 1350, " ", $vqrange], _
	[20091, 1796, " ", $vqrange], _
	[20117, 1012, " ", $vqrange], _
	[20143, 227, " ", $vqrange], _
	[18755, 18, " ", $vqrange], _
	[17367, -192, " ", $vqrange], _
	[16584, -577, " ", $vqrange], _
	[16447, -1759, " ", $vqrange], _
	[16092, -2175, " ", $vqrange], _ ; auto
	[16393, -2688, " ", $vqrange], _ ; auto
	[16310, -2941, " ", $vqrange], _
	[16174, -4123, " ", $vqrange], _
	[16037, -5305, " ", $vqrange], _
	[16294, -5446, " ", $vqrange], _
	[17340, -5630, " ", $vqrange], _
	[18386, -5813, " ", $vqrange], _
	[19106, -6525, " ", $vqrange], _
	[19825, -7236, " ", $vqrange], _
	[20545, -7948, " ", $vqrange], _
	[20464, -8531, " ", $vqrange], _
	[20225, -9452, " ", $vqrange], _
	[19986, -10373, " ", $vqrange], _
	[18762, -11101, " ", $vqrange], _
	[17503, -11230, " ", $vqrange], _
	[16244, -11359, " ", $vqrange], _
	[14985, -11488, " ", $vqrange], _
	[13670, -10999, " ", $vqrange], _
	[12355, -10510, " ", $vqrange], _
	[12752, -10501, " ", $vqrange], _
	[12973, -9180, " ", $vqrange], _
	[13195, -7860, " ", $vqrange], _
	[13416, -6539, " ", $vqrange], _
	[13567, -5163, " ", $vqrange], _
	[13719, -3788, " ", $vqrange], _
	[12413, -3364, " ", $vqrange], _
	[13126, -2764, " ", $vqrange], _
	[13840, -2163, " ", $vqrange] _
]

