#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_KainengCity/PongmeiValley.au3
; Map: PongmeiValley (id 211), geometry from MAP 0000155151.pmap
; Repaired 0 of 4 blocked segments by inserting 6 waypoints.
; Smoothed 41 additional anchor(s) for wall clearance and hop distance.
; Filled 2 long hop(s) by walking the current mesh component toward a disconnected goal.
; 4 segment(s) could not be routed and were left as-is.
; 5 hop(s) still exceed 1500 units (worst 5237 between index 109 and 110).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_KainengCity_PongmeiValleyRoute01[251][4] = [ _
	[-13428, 8312, " ", $vqrange], _
	[-16034, 8455, " ", $vqrange], _ ; auto
	[-14668, 8492, " ", $vqrange], _
	[-15909, 8672, " ", $vqrange], _
	[-15570, 9936, " ", $vqrange], _
	[-16540, 9209, " ", $vqrange], _
	[-17509, 8482, " ", $vqrange], _
	[-16881, 7677, " ", $vqrange], _
	[-16253, 6872, " ", $vqrange], _
	[-15625, 6067, " ", $vqrange], _
	[-16694, 5017, " ", $vqrange], _
	[-17764, 3967, " ", $vqrange], _
	[-18833, 2917, " ", $vqrange], _
	[-17670, 3126, " ", $vqrange], _
	[-16506, 3334, " ", $vqrange], _
	[-15342, 3542, " ", $vqrange], _
	[-14179, 3751, " ", $vqrange], _
	[-14747, 3798, " ", $vqrange], _
	[-15570, 2586, " ", $vqrange], _
	[-16394, 1374, " ", $vqrange], _
	[-17218, 163, " ", $vqrange], _
	[-18041, -1049, " ", $vqrange], _
	[-17669, -2191, " ", $vqrange], _
	[-17297, -3333, " ", $vqrange], _
	[-16925, -4475, " ", $vqrange], _
	[-17324, -5778, " ", $vqrange], _
	[-17722, -7081, " ", $vqrange], _
	[-16609, -7688, " ", $vqrange], _
	[-15496, -8294, " ", $vqrange], _
	[-15804, -7367, " ", $vqrange], _
	[-16112, -6440, " ", $vqrange], _
	[-15174, -6369, " ", $vqrange], _
	[-16112, -6440, " ", $vqrange], _
	[-15293, -6444, " ", $vqrange], _
	[-14474, -6448, " ", $vqrange], _
	[-14321, -6449, " ", $vqrange], _
	[-14167, -6450, " ", $vqrange], _
	[-14014, -6451, " ", $vqrange], _
	[-13860, -6452, " ", $vqrange], _
	[-13707, -6452, " ", $vqrange], _
	[-13553, -6453, " ", $vqrange], _
	[-13399.5, -6454, " ", $vqrange], _ ; auto
	[-13246, -6455, " ", $vqrange], _
	[-12837, -6457, " ", $vqrange], _
	[-13164, -7720, " ", $vqrange], _
	[-12520, -7073, " ", $vqrange], _
	[-11877, -6426, " ", $vqrange], _
	[-12610, -5613, " ", $vqrange], _
	[-13344, -4800, " ", $vqrange], _
	[-13288, -4409, " ", $vqrange], _
	[-12526, -3391, " ", $vqrange], _
	[-11763, -2373, " ", $vqrange], _
	[-13053, -1710, " ", $vqrange], _
	[-14344, -1048, " ", $vqrange], _
	[-15634, -385, " ", $vqrange], _
	[-16924, 278, " ", $vqrange], _
	[-16078, 1339, " ", $vqrange], _
	[-15231, 2400, " ", $vqrange], _
	[-14385, 3461, " ", $vqrange], _
	[-13538, 4522, " ", $vqrange], _
	[-12692, 5583, " ", $vqrange], _
	[-12215, 4405, " ", $vqrange], _
	[-11738, 3226, " ", $vqrange], _
	[-11262, 2048, " ", $vqrange], _
	[-10785, 870, " ", $vqrange], _
	[-10308, -309, " ", $vqrange], _
	[-9831, -1487, " ", $vqrange], _
	[-8623, -1398, " ", $vqrange], _
	[-7415, -1308, " ", $vqrange], _
	[-6206, -1219, " ", $vqrange], _
	[-4998, -1129, " ", $vqrange], _
	[-3790, -1040, " ", $vqrange], _
	[-2865, -832, " ", $vqrange], _
	[-1940, -623, " ", $vqrange], _
	[-859, -593, " ", $vqrange], _
	[222, -563, " ", $vqrange], _
	[279, 117, " ", $vqrange], _
	[480, 192, " ", $vqrange], _ ; auto
	[292, 276, " ", $vqrange], _
	[305, 436, " ", $vqrange], _
	[1514.5, 458, " ", $vqrange], _ ; auto
	[2724, 480, " ", $vqrange], _ ; auto
	[1521.5, 537.5, " ", $vqrange], _ ; auto
	[319, 595, " ", $vqrange], _
	[332, 754, " ", $vqrange], _
	[345, 914, " ", $vqrange], _
	[364, 1137, " ", $vqrange], _
	[392, 1477, " ", $vqrange], _
	[449, 2157, " ", $vqrange], _
	[-608, 1866, " ", $vqrange], _
	[541, 1356, " ", $vqrange], _
	[1680, 384, " ", $vqrange], _
	[2948, -4, " ", $vqrange], _
	[4216, -392, " ", $vqrange], _
	[5484, -780, " ", $vqrange], _
	[6753, -1168, " ", $vqrange], _
	[8021, -1556, " ", $vqrange], _
	[9289, -1944, " ", $vqrange], _
	[10170, -954, " ", $vqrange], _
	[11050, 35, " ", $vqrange], _
	[11618, -1180, " ", $vqrange], _
	[12185, -2396, " ", $vqrange], _
	[13028, -3232, " ", $vqrange], _
	[13870, -4068, " ", $vqrange], _
	[14713, -4904, " ", $vqrange], _
	[15556, -5740, " ", $vqrange], _
	[14775, -5692, " ", $vqrange], _
	[13611, -7825, " ", $vqrange], _
	[16681, -8381, " ", $vqrange], _
	[13534, -7833, " ", $vqrange], _
	[16511, -3525, " ", $vqrange], _
	[17512, -2808, " ", $vqrange], _
	[18513, -2091, " ", $vqrange], _
	[17832, -962, " ", $vqrange], _
	[17152, 166, " ", $vqrange], _
	[18100, 996, " ", $vqrange], _
	[19049, 1827, " ", $vqrange], _
	[19997, 2657, " ", $vqrange], _
	[20948, 2266, " ", $vqrange], _
	[21899, 1875, " ", $vqrange], _
	[21908, 2960, " ", $vqrange], _
	[21916, 4046, " ", $vqrange], _
	[22056, 4876, " ", $vqrange], _
	[22195, 5706, " ", $vqrange], _
	[21552, 5109, " ", $vqrange], _
	[20909, 4512, " ", $vqrange], _
	[19680, 4320, " ", $vqrange], _
	[19092, 4312, " ", $vqrange], _
	[18567, 3114, " ", $vqrange], _
	[18042, 1916, " ", $vqrange], _
	[17517, 718, " ", $vqrange], _
	[16992, -480, " ", $vqrange], _
	[16256, -1079, " ", $vqrange], _
	[14837, -655, " ", $vqrange], _
	[13419, -232, " ", $vqrange], _
	[12000, 192, " ", $vqrange], _
	[12912, 200, " ", $vqrange], _
	[13825, 208, " ", $vqrange], _
	[14141, 1344, " ", $vqrange], _
	[14457, 2480, " ", $vqrange], _
	[13544, 3105, " ", $vqrange], _
	[13417, 4276, " ", $vqrange], _
	[13290, 5446, " ", $vqrange], _
	[13164, 6617, " ", $vqrange], _
	[13037, 7788, " ", $vqrange], _
	[13648, 6517, " ", $vqrange], _
	[14259, 5245, " ", $vqrange], _
	[14870, 3974, " ", $vqrange], _
	[13948, 4687, " ", $vqrange], _
	[13026, 5400, " ", $vqrange], _
	[12105, 6113, " ", $vqrange], _
	[11183, 6826, " ", $vqrange], _
	[12312, 7589, " ", $vqrange], _
	[13440, 8352, " ", $vqrange], _
	[12298, 9054, " ", $vqrange], _
	[11157, 9756, " ", $vqrange], _
	[10256, 9784, " ", $vqrange], _
	[10101, 9789, " ", $vqrange], _
	[9805, 9798, " ", $vqrange], _
	[9580, 9805, " ", $vqrange], _
	[9425, 9809, " ", $vqrange], _
	[9182, 9816.5, " ", $vqrange], _ ; auto
	[8939, 9824, " ", $vqrange], _ ; auto
	[8453, 9839, " ", $vqrange], _
	[7552, 9867, " ", $vqrange], _
	[7535, 10982, " ", $vqrange], _
	[7518, 12098, " ", $vqrange], _
	[7501, 13213, " ", $vqrange], _
	[7794, 13707, " ", $vqrange], _
	[8129, 13732, " ", $vqrange], _
	[7887, 13868, " ", $vqrange], _
	[8122, 13868, " ", $vqrange], _
	[8272, 13868, " ", $vqrange], _
	[8423, 13868, " ", $vqrange], _
	[8592, 13868, " ", $vqrange], _
	[8827, 13868, " ", $vqrange], _
	[9475, 13779, " ", $vqrange], _
	[8568, 13824, " ", $vqrange], _
	[9407, 13937, " ", $vqrange], _
	[9644, 13937, " ", $vqrange], _
	[9870.5, 13937, " ", $vqrange], _ ; auto
	[10097, 13937, " ", $vqrange], _
	[10787, 13937, " ", $vqrange], _
	[11132, 13937, " ", $vqrange], _
	[11283, 13937, " ", $vqrange], _
	[11477, 13937, " ", $vqrange], _
	[12167, 13937, " ", $vqrange], _
	[12437, 13885, " ", $vqrange], _
	[13119, 13748, " ", $vqrange], _
	[14390, 14292, " ", $vqrange], _
	[15660, 14835, " ", $vqrange], _
	[14561, 14380, " ", $vqrange], _
	[13490, 13900, " ", $vqrange], _
	[12419, 13420, " ", $vqrange], _
	[11282, 13296, " ", $vqrange], _
	[10144, 13173, " ", $vqrange], _
	[9006, 13050, " ", $vqrange], _
	[7869, 12926, " ", $vqrange], _
	[7862, 11881, " ", $vqrange], _
	[7855, 10837, " ", $vqrange], _
	[7848, 9792, " ", $vqrange], _
	[6761, 9315, " ", $vqrange], _
	[5904, 10296, " ", $vqrange], _
	[5047, 11276, " ", $vqrange], _
	[4635, 10117, " ", $vqrange], _
	[4222, 8958, " ", $vqrange], _
	[3810, 7799, " ", $vqrange], _
	[3398, 6640, " ", $vqrange], _
	[2012, 6579, " ", $vqrange], _
	[626, 6518, " ", $vqrange], _
	[452.75, 6510.5, " ", $vqrange], _ ; auto
	[301.1562, 6503.9375, " ", $vqrange], _ ; auto
	[-67, 6488, " ", $vqrange], _ ; auto
	[-760, 6458, " ", $vqrange], _
	[-2146, 6397, " ", $vqrange], _
	[-3532, 6336, " ", $vqrange], _
	[-2301, 6109, " ", $vqrange], _
	[-1070, 5882, " ", $vqrange], _
	[161, 5656, " ", $vqrange], _
	[1392, 5429, " ", $vqrange], _
	[1960, 5660, " ", $vqrange], _ ; auto
	[2244, 5775.5, " ", $vqrange], _ ; auto
	[2386, 5833.25, " ", $vqrange], _ ; auto
	[2528, 5891, " ", $vqrange], _
	[3632.923, 6014.3333, " ", $vqrange], _ ; auto
	[4737.8459, 6137.6667, " ", $vqrange], _ ; auto
	[5842.7689, 6261, " ", $vqrange], _ ; auto
	[4753.3845, 6307.5, " ", $vqrange], _ ; auto
	[3664, 6354, " ", $vqrange], _
	[4800, 6816, " ", $vqrange], _
	[3533, 6879, " ", $vqrange], _
	[2267, 6942, " ", $vqrange], _
	[1000, 7005, " ", $vqrange], _
	[475, 5788, " ", $vqrange], _
	[-74, 6402, " ", $vqrange], _
	[-624, 7015, " ", $vqrange], _
	[-666, 7840, " ", $vqrange], _
	[-709, 8664, " ", $vqrange], _
	[-1600, 8638, " ", $vqrange], _
	[-2490, 8611, " ", $vqrange], _
	[-2394, 7618, " ", $vqrange], _
	[-2299, 6625, " ", $vqrange], _
	[-3766, 6314, " ", $vqrange], _
	[-4500, 6159, " ", $vqrange], _ ; auto
	[-5234, 6004, " ", $vqrange], _
	[-6341, 6258, " ", $vqrange], _
	[-7448, 6511, " ", $vqrange], _
	[-8004, 5519, " ", $vqrange], _
	[-8561, 4527, " ", $vqrange], _
	[-7450, 3522, " ", $vqrange], _
	[-6339, 2517, " ", $vqrange] _
]

