#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_KainengCity/RaisuPalace.au3
; Map: RaisuPalace (id 233), geometry from MAP 0000157212.pmap
; Repaired 9 of 38 blocked segments by inserting 52 waypoints.
; Smoothed 122 additional anchor(s) for wall clearance and hop distance.
; Filled 32 long hop(s) by walking the current mesh component toward a disconnected goal.
; 29 segment(s) could not be routed and were left as-is.
; 32 hop(s) still exceed 1500 units (worst 6164 between index 170 and 171).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_KainengCity_RaisuPalaceRoute01[312][4] = [ _
	[24090, 1284, " ", $vqrange], _
	[24090, 1581, " ", $vqrange], _
	[24292.7539, 1637, " ", $vqrange], _ ; auto
	[24090, 1746, " ", $vqrange], _
	[24090, 1911, " ", $vqrange], _
	[24090, 2075, " ", $vqrange], _
	[24090, 2240, " ", $vqrange], _
	[24090, 2528.5, " ", $vqrange], _ ; auto
	[24090, 2817, " ", $vqrange], _ ; auto
	[24090, 3394, " ", $vqrange], _
	[24090, 4450, " ", $vqrange], _
	[24090, 5505, " ", $vqrange], _
	[19992, 7624, " ", $vqrange], _
	[16662, 8435, " ", $vqrange], _
	[12694, 8359, " ", $vqrange], _
	[12786, 9241, " ", $vqrange], _
	[12877, 10123, " ", $vqrange], _
	[11912, 10126, " ", $vqrange], _
	[11761, 10126, " ", $vqrange], _
	[11611, 10127, " ", $vqrange], _
	[11460, 10127, " ", $vqrange], _
	[11309, 10128, " ", $vqrange], _
	[11158, 10128, " ", $vqrange], _
	[10947, 10129, " ", $vqrange], _
	[11128, 11072, " ", $vqrange], _
	[11754, 11750, " ", $vqrange], _
	[12379, 12427, " ", $vqrange], _
	[13297.2856, 13057, " ", $vqrange], _ ; auto
	[13675, 13132, " ", $vqrange], _
	[12906.8569, 12874, " ", $vqrange], _ ; auto
	[12952, 12718, " ", $vqrange], _
	[12228, 12304, " ", $vqrange], _
	[11678, 11688, " ", $vqrange], _
	[11128, 11072, " ", $vqrange], _
	[11175, 10204, " ", $vqrange], _
	[11837, 9199, " ", $vqrange], _
	[10698, 8296, " ", $vqrange], _
	[9559, 7392, " ", $vqrange], _
	[8420, 6489, " ", $vqrange], _
	[7817, 5916, " ", $vqrange], _
	[7516, 5629, " ", $vqrange], _
	[7402, 5521, " ", $vqrange], _
	[7214, 5342, " ", $vqrange], _
	[4900, 6273, " ", $vqrange], _
	[2191, 5494, " ", $vqrange], _
	[1354, 6217, " ", $vqrange], _
	[-357, 4631, " ", $vqrange], _
	[-3681, 5381, " ", $vqrange], _
	[-4722, 5632, " ", $vqrange], _
	[-5243, 5758, " ", $vqrange], _
	[-5390, 5794, " ", $vqrange], _
	[-5536, 5829, " ", $vqrange], _
	[-5764, 5884, " ", $vqrange], _
	[-6011, 6038, " ", $vqrange], _ ; auto
	[-6125, 6190, " ", $vqrange], _ ; auto
	[-6014.8228, 7308, " ", $vqrange], _ ; auto
	[-6073.4358, 7402, " ", $vqrange], _ ; auto
	[-7173.6035, 7433, " ", $vqrange], _ ; auto
	[-8906.8237, 7433, " ", $vqrange], _ ; auto
	[-9261, 6950, " ", $vqrange], _
	[-8870.6494, 6937, " ", $vqrange], _ ; auto
	[-9161.8247, 6931.5, " ", $vqrange], _ ; auto
	[-9453, 6926, " ", $vqrange], _
	[-9627, 6904, " ", $vqrange], _
	[-9846, 6876, " ", $vqrange], _
	[-10431, 6802, " ", $vqrange], _
	[-10723, 6764, " ", $vqrange], _
	[-10906, 6741, " ", $vqrange], _
	[-11061, 6721, " ", $vqrange], _
	[-11217, 6702, " ", $vqrange], _
	[-11409, 6677.5, " ", $vqrange], _ ; auto
	[-11601, 6653, " ", $vqrange], _
	[-11989, 5693, " ", $vqrange], _
	[-13409, 5856, " ", $vqrange], _
	[-13690, 6048, " ", $vqrange], _
	[-14141, 6240, " ", $vqrange], _
	[-14282, 6300, " ", $vqrange], _
	[-14423, 6360, " ", $vqrange], _
	[-14592, 6432, " ", $vqrange], _
	[-14762, 6432, " ", $vqrange], _
	[-14917, 6432, " ", $vqrange], _
	[-15073, 6432, " ", $vqrange], _
	[-15228, 6432, " ", $vqrange], _
	[-15497, 6432, " ", $vqrange], _
	[-15653, 6432, " ", $vqrange], _
	[-15808, 6432, " ", $vqrange], _
	[-15964, 6432, " ", $vqrange], _
	[-16120, 6432, " ", $vqrange], _
	[-16275, 6432, " ", $vqrange], _
	[-16431, 6432, " ", $vqrange], _
	[-16586, 6432, " ", $vqrange], _
	[-16742, 6432, " ", $vqrange], _
	[-16912, 6432, " ", $vqrange], _
	[-17081, 6432, " ", $vqrange], _
	[-17308, 6432, " ", $vqrange], _
	[-18213, 6432, " ", $vqrange], _
	[-17663, 6376, " ", $vqrange], _
	[-18417, 5660, " ", $vqrange], _
	[-19170, 4944, " ", $vqrange], _
	[-18815, 3837, " ", $vqrange], _
	[-18195, 3517, " ", $vqrange], _
	[-18348, 3168, " ", $vqrange], _
	[-17491, 3168, " ", $vqrange], _
	[-17062, 3168, " ", $vqrange], _
	[-16848, 3168, " ", $vqrange], _
	[-16687, 3168, " ", $vqrange], _
	[-16527, 3168, " ", $vqrange], _
	[-16366, 3168, " ", $vqrange], _
	[-16205, 3168, " ", $vqrange], _
	[-16045, 3168, " ", $vqrange], _
	[-15884, 3168, " ", $vqrange], _
	[-15723, 3168, " ", $vqrange], _
	[-15562, 3168, " ", $vqrange], _
	[-15348, 3168, " ", $vqrange], _
	[-14920, 3168, " ", $vqrange], _
	[-14079, 3298, " ", $vqrange], _
	[-13410, 3683, " ", $vqrange], _
	[-12327, 3926, " ", $vqrange], _
	[-11828, 3648, " ", $vqrange], _
	[-11767, 3290, " ", $vqrange], _
	[-11721, 3092, " ", $vqrange], _
	[-11458, 2937, " ", $vqrange], _
	[-11054, 2904, " ", $vqrange], _
	[-10903, 2892, " ", $vqrange], _
	[-10751, 2880, " ", $vqrange], _
	[-10523.75, 2861.5, " ", $vqrange], _ ; auto
	[-10296.5, 2843, " ", $vqrange], _ ; auto
	[-9842, 2806, " ", $vqrange], _
	[-8441, 2882, " ", $vqrange], _
	[-7040, 2959, " ", $vqrange], _
	[-6718, 2328, " ", $vqrange], _
	[-6544, 2307, " ", $vqrange], _
	[-6346, 2284, " ", $vqrange], _
	[-5974, 2239, " ", $vqrange], _
	[-4969, 2208, " ", $vqrange], _
	[-3964, 2176, " ", $vqrange], _
	[-5189, 2173, " ", $vqrange], _
	[-6415, 2170, " ", $vqrange], _
	[-7640, 2167, " ", $vqrange], _
	[-6552, 2167, " ", $vqrange], _
	[-5464, 2166, " ", $vqrange], _
	[-4376, 2166, " ", $vqrange], _
	[-3967, 2166, " ", $vqrange], _
	[-3763, 2166, " ", $vqrange], _
	[-3610, 2166, " ", $vqrange], _
	[-3457, 2166, " ", $vqrange], _
	[-3304, 2166, " ", $vqrange], _
	[-3151, 2166, " ", $vqrange], _
	[-2947, 2166, " ", $vqrange], _
	[-2743, 2166, " ", $vqrange], _
	[-1927, 2166, " ", $vqrange], _
	[-1111, 2166, " ", $vqrange], _
	[-295, 2165, " ", $vqrange], _
	[113, 2165, " ", $vqrange], _
	[266, 2165, " ", $vqrange], _
	[419, 2165, " ", $vqrange], _
	[572, 2165, " ", $vqrange], _
	[725, 2165, " ", $vqrange], _
	[929, 2165, " ", $vqrange], _
	[1337, 2165, " ", $vqrange], _
	[2153, 2165, " ", $vqrange], _
	[3241, 2164, " ", $vqrange], _
	[4329, 2164, " ", $vqrange], _
	[5418, 2164, " ", $vqrange], _
	[4117, 2146, " ", $vqrange], _
	[2817, 2129, " ", $vqrange], _
	[1517, 2111, " ", $vqrange], _
	[216, 2094, " ", $vqrange], _
	[-1084, 2076, " ", $vqrange], _
	[-298, 2050, " ", $vqrange], _
	[489, 2023, " ", $vqrange], _
	[-4110, -2081, " ", $vqrange], _
	[-3998, -3390, " ", $vqrange], _
	[-3887, -4698, " ", $vqrange], _
	[-3957, -5568, " ", $vqrange], _
	[-4027, -6437, " ", $vqrange], _
	[-7539, -5778, " ", $vqrange], _
	[-9164, -4781, " ", $vqrange], _
	[-10522, -7763, " ", $vqrange], _
	[-10456.5, -7524, " ", $vqrange], _ ; auto
	[-10748.6875, -7509.375, " ", $vqrange], _ ; auto
	[-11040.875, -7494.75, " ", $vqrange], _ ; auto
	[-11260.0156, -7483.7812, " ", $vqrange], _ ; auto
	[-11479.1562, -7472.8125, " ", $vqrange], _ ; auto
	[-11771.3438, -7458.1875, " ", $vqrange], _ ; auto
	[-11926.5684, -7450.418, " ", $vqrange], _ ; auto
	[-12081.793, -7442.6484, " ", $vqrange], _ ; auto
	[-12237.0176, -7434.8789, " ", $vqrange], _ ; auto
	[-12392.2422, -7427.1094, " ", $vqrange], _ ; auto
	[-12547.4668, -7419.3398, " ", $vqrange], _ ; auto
	[-12794, -7407, " ", $vqrange], _ ; auto
	[-12811, -7396, " ", $vqrange], _ ; auto
	[-12811, -7035, " ", $vqrange], _
	[-12858, -5560, " ", $vqrange], _
	[-12844, -4169, " ", $vqrange], _
	[-12831, -2778, " ", $vqrange], _
	[-10563, -2283, " ", $vqrange], _
	[-8583, -4833, " ", $vqrange], _
	[-4663, -4661, " ", $vqrange], _
	[-1484, -6175, " ", $vqrange], _
	[-354, -4608, " ", $vqrange], _
	[464, -5196, " ", $vqrange], _
	[410, -6336, " ", $vqrange], _
	[2900, -4619, " ", $vqrange], _
	[4688, -5890, " ", $vqrange], _
	[4769, -4628, " ", $vqrange], _
	[4735, -3748, " ", $vqrange], _
	[4701, -2867, " ", $vqrange], _
	[4438, -2706, " ", $vqrange], _
	[6448, -3311, " ", $vqrange], _
	[8337, -3234, " ", $vqrange], _
	[8436, -4677, " ", $vqrange], _
	[8536, -6121, " ", $vqrange], _
	[8635, -7564, " ", $vqrange], _
	[10382, -8101, " ", $vqrange], _
	[8589, -4496, " ", $vqrange], _
	[11908, -3622, " ", $vqrange], _
	[12057.5, -3679.5, " ", $vqrange], _ ; auto
	[12207, -3737, " ", $vqrange], _ ; auto
	[12901, -4072.5, " ", $vqrange], _ ; auto
	[13595, -4408, " ", $vqrange], _
	[14996, -2335, " ", $vqrange], _
	[18060, -2947, " ", $vqrange], _
	[18147, -3728, " ", $vqrange], _
	[18234, -4508, " ", $vqrange], _
	[15166, -1857, " ", $vqrange], _
	[16144, 50, " ", $vqrange], _
	[16288, 172, " ", $vqrange], _ ; auto
	[17723.5, 196, " ", $vqrange], _ ; auto
	[17778, 318, " ", $vqrange], _
	[19100, 380, " ", $vqrange], _
	[19761, 412, " ", $vqrange], _
	[19916, 419, " ", $vqrange], _
	[20070, 426, " ", $vqrange], _
	[20225, 434, " ", $vqrange], _
	[20422, 443, " ", $vqrange], _
	[20422, 450, " ", $vqrange], _
	[20624, 450, " ", $vqrange], _
	[20775, 450, " ", $vqrange], _
	[20926, 451, " ", $vqrange], _
	[21077, 451, " ", $vqrange], _
	[21244, 451, " ", $vqrange], _
	[21563, 306, " ", $vqrange], _
	[24176, 3104, " ", $vqrange], _
	[24087.5, 3286, " ", $vqrange], _ ; auto
	[23999, 3468, " ", $vqrange], _ ; auto
	[24147.5, 5256, " ", $vqrange], _ ; auto
	[21505.6445, 5608, " ", $vqrange], _ ; auto
	[20497, 5666, " ", $vqrange], _
	[19052, 5540, " ", $vqrange], _
	[18691, 5508, " ", $vqrange], _
	[18533, 5494, " ", $vqrange], _
	[18374, 5480, " ", $vqrange], _
	[18149, 5460, " ", $vqrange], _
	[17968, 5445, " ", $vqrange], _
	[17607, 5413, " ", $vqrange], _
	[17317, 5280, " ", $vqrange], _
	[17177, 5225, " ", $vqrange], _
	[16975.7129, 5223, " ", $vqrange], _ ; auto
	[17028, 5146, " ", $vqrange], _
	[17048, 4923, " ", $vqrange], _
	[16948, 4784, " ", $vqrange], _
	[17504, 4605, " ", $vqrange], _ ; auto
	[17753, 4572, " ", $vqrange], _
	[16602, 4468, " ", $vqrange], _
	[15471, 4520, " ", $vqrange], _
	[15321, 4527, " ", $vqrange], _
	[15113.5, 4536.5, " ", $vqrange], _ ; auto
	[14906, 4546, " ", $vqrange], _
	[14340, 4572, " ", $vqrange], _
	[14555, 5534, " ", $vqrange], _
	[14080, 4146, " ", $vqrange], _
	[13618, 4150, " ", $vqrange], _
	[13445, 4151, " ", $vqrange], _
	[13294, 4152, " ", $vqrange], _
	[13143, 4153, " ", $vqrange], _
	[12991, 4147, " ", $vqrange], _
	[13151.4817, 4146.9258, " ", $vqrange], _ ; auto
	[13303.5171, 4146.8555, " ", $vqrange], _ ; auto
	[13463.9988, 4146.7812, " ", $vqrange], _ ; auto
	[14072.1401, 4146.5, " ", $vqrange], _ ; auto
	[15153.2803, 4146, " ", $vqrange], _ ; auto
	[14300.395, 4146, " ", $vqrange], _ ; auto
	[13447.5098, 4146, " ", $vqrange], _ ; auto
	[13287.5938, 4146, " ", $vqrange], _ ; auto
	[13127.6778, 4146, " ", $vqrange], _ ; auto
	[12967.7618, 4146, " ", $vqrange], _ ; auto
	[12807.8458, 4146, " ", $vqrange], _ ; auto
	[12647.9298, 4146, " ", $vqrange], _ ; auto
	[12488.0139, 4146, " ", $vqrange], _ ; auto
	[12168.1819, 4146, " ", $vqrange], _ ; auto
	[11741.7393, 4146, " ", $vqrange], _ ; auto
	[12029.1747, 4148.3555, " ", $vqrange], _ ; auto
	[12290.8696, 4150.5, " ", $vqrange], _ ; auto
	[12441.0225, 4151.7305, " ", $vqrange], _ ; auto
	[12591.1753, 4152.9609, " ", $vqrange], _ ; auto
	[12840, 4155, " ", $vqrange], _
	[12689, 4157, " ", $vqrange], _
	[12537, 4158, " ", $vqrange], _
	[12386, 4159, " ", $vqrange], _
	[12235, 4160, " ", $vqrange], _
	[12173, 4450, " ", $vqrange], _ ; auto
	[12111, 4740, " ", $vqrange], _
	[11784, 4740, " ", $vqrange], _
	[11456, 4740, " ", $vqrange], _
	[10801, 4740, " ", $vqrange], _
	[11279, 3915, " ", $vqrange], _
	[9539, 1886, " ", $vqrange], _
	[10556.4751, 1043, " ", $vqrange], _ ; auto
	[10543.2375, 211.5, " ", $vqrange], _ ; auto
	[10530, -620, " ", $vqrange], _ ; auto
	[10530, -1051, " ", $vqrange] _
]

