#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_KainengCity/ShadowsPassage.au3
; Map: ShadowsPassage (id 232), geometry from MAP 0000157176.pmap
; Repaired 1 of 2 blocked segments by inserting 2 waypoints.
; Smoothed 3 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; 1 segment(s) could not be routed and were left as-is.
; 1 hop(s) still exceed 1500 units (worst 2596 between index 0 and 1).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.

Global $aFactions_KainengCity_ShadowsPassageRoute01[37][2] = [ _
	[3396, 16639], _
	[2094, 18885], _
	[1078, 18887], _
	[61, 18889], _
	[-339.8942, 17962], _ ; auto
	[-155, 17788], _
	[-372, 16688], _
	[-527, 15212], _
	[-682, 13737], _
	[-1180, 13762], _
	[-1429, 13774], _
	[-1584, 13782], _
	[-2673, 13837], _
	[-3820, 14234], _
	[-3699, 14519], _
	[-3977, 15310], _
	[-4255, 16101], _
	[-3977, 15310], _
	[-3699, 14519], _
	[-3039, 13867], _
	[-2673, 13837], _
	[-1677, 13787], _
	[-1522, 13779], _
	[-1351, 13770.5], _ ; auto
	[-1180, 13762], _
	[-682, 13737], _
	[-526, 14992], _
	[-370, 16246], _
	[-214, 17501], _
	[-57, 18756], _
	[61, 18889], _
	[1078, 18887], _
	[2094, 18885], _
	[2909.5363, 17944], _ ; auto
	[3725.0725, 17003], _ ; auto
	[3396, 16758], _ ; auto
	[3396, 16639] _
]

