#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: vendor/vanquish-bot/Maps/Factions_KainengCity/ShadowsPassage.au3
; Map: ShadowsPassage (id 232), geometry from MAP 0000157176.pmap
; Repaired 2 of 4 blocked segments by inserting 4 waypoints.
; Smoothed 17 additional anchor(s) for wall clearance and hop distance.
; 2 segment(s) could not be routed and were left as-is.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.

Global $aFactions_KainengCity_ShadowsPassageRoute01[32][2] = [ _
	[3396, 16639], _
	[2094, 18885], _
	[1077.5, 18887], _ ; auto
	[61, 18889], _
	[-155.4872, 17788.5], _ ; auto
	[-371.9744, 16688], _ ; auto
	[-526.9872, 15212.5], _ ; auto
	[-682, 13737], _
	[-1179.7436, 13762], _ ; auto
	[-1428.6154, 13774.5], _ ; auto
	[-1584.1603, 13782.3125], _ ; auto
	[-2672.9745, 13837], _ ; auto
	[-3819.5623, 14234], _ ; auto
	[-3699, 14519], _
	[-3977, 15310], _ ; auto
	[-4255, 16101], _
	[-3977, 15310], _ ; auto
	[-3699, 14519], _
	[-3039.3333, 13867], _ ; auto
	[-2672.9745, 13837], _ ; auto
	[-1677.4872, 13787], _ ; auto
	[-1521.9424, 13779.1875], _ ; auto
	[-1179.7436, 13762], _ ; auto
	[-682, 13737], _
	[-525.8694, 14991.75], _ ; auto
	[-369.7388, 16246.5], _ ; auto
	[-213.6082, 17501.25], _ ; auto
	[-57.4776, 18756], _ ; auto
	[61, 18889], _
	[1077.5, 18887], _ ; auto
	[2094, 18885], _
	[3396, 16639] _
]

