#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_KainengCity/ShadowsPassage.au3
; Map: ShadowsPassage (id 232), geometry from MAP 0000157176.pmap
; Repaired 1 of 2 blocked segments by inserting 2 waypoints.
; Smoothed 3 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; 1 segment(s) could not be routed and were left as-is.
; 1 hop(s) still exceed 1500 units (worst 2596 between index 0 and 1).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_KainengCity_ShadowsPassageRoute01[37][4] = [ _
	[3396, 16639, " ", $vqrange], _
	[2094, 18885, " ", $vqrange], _
	[1078, 18887, " ", $vqrange], _
	[61, 18889, " ", $vqrange], _
	[-339.8942, 17962, " ", $vqrange], _ ; auto
	[-155, 17788, " ", $vqrange], _
	[-372, 16688, " ", $vqrange], _
	[-527, 15212, " ", $vqrange], _
	[-682, 13737, " ", $vqrange], _
	[-1180, 13762, " ", $vqrange], _
	[-1429, 13774, " ", $vqrange], _
	[-1584, 13782, " ", $vqrange], _
	[-2673, 13837, " ", $vqrange], _
	[-3820, 14234, " ", $vqrange], _
	[-3699, 14519, " ", $vqrange], _
	[-3977, 15310, " ", $vqrange], _
	[-4255, 16101, " ", $vqrange], _
	[-3977, 15310, " ", $vqrange], _
	[-3699, 14519, " ", $vqrange], _
	[-3039, 13867, " ", $vqrange], _
	[-2673, 13837, " ", $vqrange], _
	[-1677, 13787, " ", $vqrange], _
	[-1522, 13779, " ", $vqrange], _
	[-1351, 13770.5, " ", $vqrange], _ ; auto
	[-1180, 13762, " ", $vqrange], _
	[-682, 13737, " ", $vqrange], _
	[-526, 14992, " ", $vqrange], _
	[-370, 16246, " ", $vqrange], _
	[-214, 17501, " ", $vqrange], _
	[-57, 18756, " ", $vqrange], _
	[61, 18889, " ", $vqrange], _
	[1078, 18887, " ", $vqrange], _
	[2094, 18885, " ", $vqrange], _
	[2909.5363, 17944, " ", $vqrange], _ ; auto
	[3725.0725, 17003, " ", $vqrange], _ ; auto
	[3396, 16758, " ", $vqrange], _ ; auto
	[3396, 16639, " ", $vqrange] _
]

