#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_KainengCity/ShenzunTunnels.au3
; Map: ShenzunTunnels (id 197), geometry from MAP 0000157169.pmap
; Repaired 7 of 22 blocked segments by inserting 31 waypoints.
; Smoothed 72 additional anchor(s) for wall clearance and hop distance.
; Filled 16 long hop(s) by walking the current mesh component toward a disconnected goal.
; 15 segment(s) could not be routed and were left as-is.
; 16 hop(s) still exceed 1500 units (worst 7074 between index 475 and 476).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_KainengCity_ShenzunTunnelsRoute01[504][4] = [ _
	[6219, -18196, " ", $vqrange], _
	[6608, -13566, " ", $vqrange], _
	[6955.75, -12519, " ", $vqrange], _ ; auto
	[7130, -12509, " ", $vqrange], _
	[8030, -11589, " ", $vqrange], _
	[7952, -10786, " ", $vqrange], _
	[7873, -9984, " ", $vqrange], _
	[7502, -9586, " ", $vqrange], _
	[7434, -6495, " ", $vqrange], _
	[8370, -7010, " ", $vqrange], _
	[9472, -7156, " ", $vqrange], _
	[10575, -7301, " ", $vqrange], _
	[11079, -8428, " ", $vqrange], _
	[11583, -9555, " ", $vqrange], _
	[12583, -10825, " ", $vqrange], _
	[12487, -10833, " ", $vqrange], _ ; auto
	[12773, -10824, " ", $vqrange], _ ; auto
	[12773, -10821, " ", $vqrange], _
	[12940, -10817, " ", $vqrange], _
	[13094, -10814, " ", $vqrange], _
	[13249, -10811, " ", $vqrange], _
	[13403, -10807, " ", $vqrange], _
	[13558, -10804, " ", $vqrange], _
	[13713, -10801, " ", $vqrange], _
	[13867, -10797, " ", $vqrange], _
	[14105, -10792, " ", $vqrange], _
	[14743.9048, -9835, " ", $vqrange], _ ; auto
	[14631, -9762, " ", $vqrange], _
	[14204, -10788, " ", $vqrange], _
	[13777, -11813, " ", $vqrange], _
	[13350, -12839, " ", $vqrange], _
	[14261, -12907, " ", $vqrange], _
	[14768, -14098, " ", $vqrange], _
	[15143.25, -15025, " ", $vqrange], _ ; auto
	[15274, -15290, " ", $vqrange], _
	[15135, -16133, " ", $vqrange], _
	[14564, -16160, " ", $vqrange], _
	[14350, -16160, " ", $vqrange], _
	[14199, -16160, " ", $vqrange], _
	[14049, -16160, " ", $vqrange], _
	[13898, -16160, " ", $vqrange], _
	[13747, -16160, " ", $vqrange], _
	[13597, -16160, " ", $vqrange], _
	[13446, -16160, " ", $vqrange], _
	[13296, -16160, " ", $vqrange], _
	[13042, -16160, " ", $vqrange], _
	[12534, -16160, " ", $vqrange], _
	[12825.5, -15005, " ", $vqrange], _ ; auto
	[12767, -14821, " ", $vqrange], _
	[12852, -13506, " ", $vqrange], _
	[12936, -12192, " ", $vqrange], _
	[13020, -10877, " ", $vqrange], _
	[12755, -10871, " ", $vqrange], _
	[12489, -10865, " ", $vqrange], _
	[10714, -7424, " ", $vqrange], _
	[9923, -7219, " ", $vqrange], _
	[9133, -7014, " ", $vqrange], _
	[8978, -7013, " ", $vqrange], _
	[8826, -7012, " ", $vqrange], _
	[8598, -7011, " ", $vqrange], _ ; auto
	[8370, -7010, " ", $vqrange], _
	[7810, -6446, " ", $vqrange], _
	[7965, -5250, " ", $vqrange], _
	[8496.675, -4140, " ", $vqrange], _ ; auto
	[8120, -4055, " ", $vqrange], _
	[8275, -2859, " ", $vqrange], _
	[8430, -1664, " ", $vqrange], _
	[8585, -468, " ", $vqrange], _
	[8464, 370, " ", $vqrange], _
	[8468, 1190, " ", $vqrange], _
	[8472, 2009, " ", $vqrange], _
	[7617, 2753, " ", $vqrange], _
	[7909, 2768, " ", $vqrange], _
	[8202, 2784, " ", $vqrange], _
	[8279, 2880, " ", $vqrange], _
	[8439, 2880, " ", $vqrange], _
	[8591, 2880, " ", $vqrange], _
	[8743, 2880, " ", $vqrange], _
	[8895, 2880, " ", $vqrange], _
	[9047, 2880, " ", $vqrange], _
	[9199, 2880, " ", $vqrange], _
	[9351, 2880, " ", $vqrange], _
	[9503, 2880, " ", $vqrange], _
	[9655, 2880, " ", $vqrange], _
	[9807, 2880, " ", $vqrange], _
	[9959, 2880, " ", $vqrange], _
	[10135, 2880, " ", $vqrange], _
	[10327, 2880, " ", $vqrange], _
	[11019, 1691, " ", $vqrange], _
	[12202, 2381, " ", $vqrange], _
	[12432, 3264, " ", $vqrange], _
	[12581, 3298, " ", $vqrange], _
	[12730, 3333, " ", $vqrange], _
	[12687, 4521, " ", $vqrange], _
	[12645, 5710, " ", $vqrange], _
	[12602, 6898, " ", $vqrange], _
	[11663, 6954, " ", $vqrange], _
	[10724, 7010, " ", $vqrange], _
	[11551, 8980, " ", $vqrange], _
	[10272, 8992, " ", $vqrange], _
	[8993, 9005, " ", $vqrange], _
	[7714, 9017, " ", $vqrange], _
	[7686, 10429, " ", $vqrange], _
	[7658, 11842, " ", $vqrange], _
	[7631, 13254, " ", $vqrange], _
	[7603, 14666, " ", $vqrange], _
	[6708, 14436, " ", $vqrange], _
	[6038, 14430, " ", $vqrange], _
	[5703, 14427, " ", $vqrange], _
	[5535, 14426, " ", $vqrange], _
	[5378, 14425, " ", $vqrange], _
	[5221, 14423, " ", $vqrange], _
	[5065, 14422, " ", $vqrange], _
	[4908, 14421, " ", $vqrange], _
	[4751, 14419, " ", $vqrange], _
	[4594, 14418, " ", $vqrange], _
	[4437, 14417, " ", $vqrange], _
	[4280, 14415, " ", $vqrange], _
	[4028, 14413, " ", $vqrange], _
	[3789, 14409, " ", $vqrange], _
	[3550, 14406, " ", $vqrange], _
	[3071, 14398, " ", $vqrange], _
	[2114, 14383, " ", $vqrange], _
	[3071.25, 14398, " ", $vqrange], _ ; auto
	[3549.875, 14405.5, " ", $vqrange], _ ; auto
	[3789.1875, 14409.25, " ", $vqrange], _ ; auto
	[4028.5, 14413, " ", $vqrange], _ ; auto
	[3741.6971, 14413, " ", $vqrange], _ ; auto
	[3454.8942, 14413, " ", $vqrange], _ ; auto
	[2881.2885, 14413, " ", $vqrange], _ ; auto
	[1734.0769, 14413, " ", $vqrange], _ ; auto
	[586.8654, 14413, " ", $vqrange], _ ; auto
	[300.0625, 14413, " ", $vqrange], _ ; auto
	[84.9604, 14413, " ", $vqrange], _ ; auto
	[-130.1418, 14413, " ", $vqrange], _ ; auto
	[-560.3461, 14413, " ", $vqrange], _ ; auto
	[-1542, 13702, " ", $vqrange], _ ; auto
	[-1542, 13628, " ", $vqrange], _
	[-1470, 12531, " ", $vqrange], _
	[-1399, 11433, " ", $vqrange], _
	[-1327, 10336, " ", $vqrange], _
	[-1286, 9958, " ", $vqrange], _
	[-1134, 9727, " ", $vqrange], _ ; auto
	[-982, 9496, " ", $vqrange], _ ; auto
	[438.5559, 9485, " ", $vqrange], _ ; auto
	[956.5874, 9469, " ", $vqrange], _ ; auto
	[2403, 8363, " ", $vqrange], _
	[1617, 9447, " ", $vqrange], _
	[1256, 9447, " ", $vqrange], _
	[1076, 9447, " ", $vqrange], _
	[918, 9447, " ", $vqrange], _
	[766, 9447, " ", $vqrange], _
	[534, 9447, " ", $vqrange], _
	[382, 9447, " ", $vqrange], _
	[174, 9447, " ", $vqrange], _
	[-731, 8826, " ", $vqrange], _
	[-1106, 8815, " ", $vqrange], _
	[-1129, 8815, " ", $vqrange], _
	[-1141, 8814, " ", $vqrange], _
	[-1153, 8814, " ", $vqrange], _
	[-1164, 8814, " ", $vqrange], _
	[-1176, 8813, " ", $vqrange], _
	[-1188, 8813, " ", $vqrange], _
	[-1200, 8813, " ", $vqrange], _
	[-1211, 8812, " ", $vqrange], _
	[-1223, 8812, " ", $vqrange], _
	[-1235, 8812, " ", $vqrange], _
	[-1247, 8811, " ", $vqrange], _
	[-1258, 8811, " ", $vqrange], _
	[-1270, 8811, " ", $vqrange], _
	[-1282, 8810, " ", $vqrange], _
	[-1293, 8810, " ", $vqrange], _
	[-1305, 8810, " ", $vqrange], _
	[-1317, 8809, " ", $vqrange], _
	[-1329, 8809, " ", $vqrange], _
	[-1340, 8809, " ", $vqrange], _
	[-1352, 8808, " ", $vqrange], _
	[-1364, 8808, " ", $vqrange], _
	[-1376, 8808, " ", $vqrange], _
	[-1387, 8807, " ", $vqrange], _
	[-1399, 8807, " ", $vqrange], _
	[-1411, 8807, " ", $vqrange], _
	[-1422, 8806, " ", $vqrange], _
	[-1434, 8806, " ", $vqrange], _
	[-1446, 8806, " ", $vqrange], _
	[-1458, 8805, " ", $vqrange], _
	[-1481, 8804, " ", $vqrange], _
	[-1528, 8803, " ", $vqrange], _
	[-1540, 8803, " ", $vqrange], _
	[-1551, 8802, " ", $vqrange], _
	[-1563, 8802, " ", $vqrange], _
	[-1575, 8802, " ", $vqrange], _
	[-1601, 8801, " ", $vqrange], _
	[-1611, 8801, " ", $vqrange], _
	[-1622, 8800, " ", $vqrange], _
	[-1669, 8799, " ", $vqrange], _
	[-1689, 8810, " ", $vqrange], _
	[-1647.0818, 8821, " ", $vqrange], _ ; auto
	[-1740.2143, 8821, " ", $vqrange], _ ; auto
	[-1710, 8816, " ", $vqrange], _
	[-1727, 8821, " ", $vqrange], _
	[-1742, 8815, " ", $vqrange], _
	[-1757, 8809, " ", $vqrange], _
	[-1771, 8803, " ", $vqrange], _
	[-1786, 8797, " ", $vqrange], _
	[-1795, 8797, " ", $vqrange], _
	[-1804, 8796, " ", $vqrange], _
	[-1821, 8795, " ", $vqrange], _
	[-1856, 8794, " ", $vqrange], _
	[-2044, 8788, " ", $vqrange], _
	[-2138, 8786, " ", $vqrange], _
	[-2185, 8784, " ", $vqrange], _
	[-2196, 8784, " ", $vqrange], _
	[-2208, 8784, " ", $vqrange], _
	[-2220, 8783, " ", $vqrange], _
	[-2231, 8783, " ", $vqrange], _
	[-2236, 8786, " ", $vqrange], _
	[-2242, 8790, " ", $vqrange], _
	[-2247, 8794, " ", $vqrange], _
	[-2252, 8797, " ", $vqrange], _
	[-2270, 8793, " ", $vqrange], _
	[-2288, 8789, " ", $vqrange], _
	[-2307, 8784, " ", $vqrange], _
	[-2325, 8780, " ", $vqrange], _
	[-2337, 8780, " ", $vqrange], _
	[-2349, 8780, " ", $vqrange], _
	[-2360, 8779, " ", $vqrange], _
	[-2372, 8779, " ", $vqrange], _
	[-2384, 8779, " ", $vqrange], _
	[-2396, 8778, " ", $vqrange], _
	[-2419, 8778, " ", $vqrange], _
	[-2513, 8775, " ", $vqrange], _
	[-2560, 8774, " ", $vqrange], _
	[-2571, 8773, " ", $vqrange], _
	[-2583, 8773, " ", $vqrange], _
	[-2595, 8773, " ", $vqrange], _
	[-2607, 8772, " ", $vqrange], _
	[-2618, 8772, " ", $vqrange], _
	[-2630, 8772, " ", $vqrange], _
	[-2642, 8771, " ", $vqrange], _
	[-2654, 8771, " ", $vqrange], _
	[-2665, 8771, " ", $vqrange], _
	[-2677, 8770, " ", $vqrange], _
	[-2689, 8770, " ", $vqrange], _
	[-2700, 8770, " ", $vqrange], _
	[-2712, 8769, " ", $vqrange], _
	[-2724, 8769, " ", $vqrange], _
	[-2736, 8769, " ", $vqrange], _
	[-2747, 8768, " ", $vqrange], _
	[-2759, 8768, " ", $vqrange], _
	[-2771, 8768, " ", $vqrange], _
	[-2783, 8767, " ", $vqrange], _
	[-2794, 8767, " ", $vqrange], _
	[-2806, 8767, " ", $vqrange], _
	[-2818, 8766, " ", $vqrange], _
	[-2829, 8766, " ", $vqrange], _
	[-2841, 8766, " ", $vqrange], _
	[-2853, 8765, " ", $vqrange], _
	[-2865, 8765, " ", $vqrange], _
	[-2876, 8765, " ", $vqrange], _
	[-2888, 8764, " ", $vqrange], _
	[-2900, 8764, " ", $vqrange], _
	[-2911, 8764, " ", $vqrange], _
	[-2923, 8763, " ", $vqrange], _
	[-2935, 8763, " ", $vqrange], _
	[-2947, 8763, " ", $vqrange], _
	[-2958, 8762, " ", $vqrange], _
	[-2970, 8762, " ", $vqrange], _
	[-2982, 8762, " ", $vqrange], _
	[-2994, 8761, " ", $vqrange], _
	[-3005, 8761, " ", $vqrange], _
	[-3017, 8760, " ", $vqrange], _
	[-3029, 8760, " ", $vqrange], _
	[-3040, 8760, " ", $vqrange], _
	[-3052, 8759, " ", $vqrange], _
	[-3064, 8759, " ", $vqrange], _
	[-3076, 8759, " ", $vqrange], _
	[-3087, 8758, " ", $vqrange], _
	[-3099, 8758, " ", $vqrange], _
	[-3111, 8758, " ", $vqrange], _
	[-3123, 8757, " ", $vqrange], _
	[-3169, 8756, " ", $vqrange], _
	[-3357, 8751, " ", $vqrange], _
	[-3732, 8740, " ", $vqrange], _
	[-4528, 8636, " ", $vqrange], _
	[-4729, 8420, " ", $vqrange], _
	[-4719, 8225, " ", $vqrange], _
	[-4711, 8066, " ", $vqrange], _
	[-4703, 7907, " ", $vqrange], _
	[-4690, 7639, " ", $vqrange], _
	[-4651, 6858, " ", $vqrange], _
	[-4612, 6076, " ", $vqrange], _
	[-4573, 5295, " ", $vqrange], _
	[-924, 2913, " ", $vqrange], _
	[-2393, 2902, " ", $vqrange], _
	[-3863, 2891, " ", $vqrange], _
	[-5332, 2879, " ", $vqrange], _
	[-6802, 2868, " ", $vqrange], _
	[-8271, 2857, " ", $vqrange], _
	[-8286, 2033, " ", $vqrange], _
	[-8293, 1621, " ", $vqrange], _
	[-8297, 1415, " ", $vqrange], _
	[-8300, 1260, " ", $vqrange], _
	[-8302, 1106, " ", $vqrange], _
	[-8305, 952, " ", $vqrange], _
	[-8308, 797, " ", $vqrange], _
	[-8311, 642, " ", $vqrange], _
	[-8313, 488, " ", $vqrange], _
	[-8317.25, 256.25, " ", $vqrange], _ ; auto
	[-8321.5, 24.5, " ", $vqrange], _ ; auto
	[-8330, -439, " ", $vqrange], _
	[-7956, -566, " ", $vqrange], _
	[-8321, -569, " ", $vqrange], _
	[-8504, -570, " ", $vqrange], _
	[-8658, -571, " ", $vqrange], _
	[-8813, -572, " ", $vqrange], _
	[-8967, -574, " ", $vqrange], _
	[-9121, -575, " ", $vqrange], _
	[-9418, -577, " ", $vqrange], _
	[-9659, -656, " ", $vqrange], _
	[-9900, -735, " ", $vqrange], _
	[-10382, -894, " ", $vqrange], _
	[-11347, -1210, " ", $vqrange], _
	[-11923, -386, " ", $vqrange], _
	[-12498, 437, " ", $vqrange], _
	[-13074, 1261, " ", $vqrange], _
	[-11197, -2587, " ", $vqrange], _
	[-11191, -3901, " ", $vqrange], _
	[-11185, -5216, " ", $vqrange], _
	[-11179, -6530, " ", $vqrange], _
	[-11173, -7844, " ", $vqrange], _
	[-8483, -10857, " ", $vqrange], _
	[-7854, -11985, " ", $vqrange], _
	[-6518, -12319, " ", $vqrange], _
	[-5183, -12653, " ", $vqrange], _
	[-4338, -13116, " ", $vqrange], _
	[-4420, -14364, " ", $vqrange], _
	[-4503, -15611, " ", $vqrange], _
	[-4591, -15823, " ", $vqrange], _ ; auto
	[-4369.8113, -15838, " ", $vqrange], _ ; auto
	[-7881, -16828, " ", $vqrange], _ ; auto
	[-5764, -16878, " ", $vqrange], _
	[-6605, -17970, " ", $vqrange], _
	[-7444, -18208, " ", $vqrange], _
	[-8282, -18446, " ", $vqrange], _
	[-8430, -18818, " ", $vqrange], _
	[-7757, -18143, " ", $vqrange], _
	[-7162, -18143, " ", $vqrange], _
	[-6864, -18143, " ", $vqrange], _
	[-6706, -18143, " ", $vqrange], _
	[-6548, -18143, " ", $vqrange], _
	[-6270, -18143, " ", $vqrange], _
	[-5972, -18143, " ", $vqrange], _
	[-5675, -18143, " ", $vqrange], _
	[-5377, -18143, " ", $vqrange], _
	[-4414, -18682, " ", $vqrange], _
	[-5604, -13644, " ", $vqrange], _
	[-5544, -13704, " ", $vqrange], _
	[-5332, -13704, " ", $vqrange], _
	[-5279, -13703, " ", $vqrange], _
	[-5252, -13703, " ", $vqrange], _
	[-5226, -13703, " ", $vqrange], _
	[-5199, -13703, " ", $vqrange], _
	[-5173, -13703, " ", $vqrange], _
	[-5146, -13703, " ", $vqrange], _
	[-5120, -13703, " ", $vqrange], _
	[-5102, -13703, " ", $vqrange], _
	[-5084, -13703, " ", $vqrange], _
	[-5067, -13703, " ", $vqrange], _
	[-5049, -13703, " ", $vqrange], _
	[-5053, -13703, " ", $vqrange], _
	[-5056, -13703, " ", $vqrange], _
	[-5059, -13703, " ", $vqrange], _
	[-4907, -13703, " ", $vqrange], _
	[-4881, -13703, " ", $vqrange], _
	[-4854, -13702, " ", $vqrange], _
	[-4801, -13702, " ", $vqrange], _
	[-4695, -13702, " ", $vqrange], _
	[-3845, -13700, " ", $vqrange], _
	[-2995.5, -13698, " ", $vqrange], _ ; auto
	[-2146, -13696, " ", $vqrange], _
	[-1296.5, -13694.5, " ", $vqrange], _ ; auto
	[-447, -13693, " ", $vqrange], _
	[-234, -13692, " ", $vqrange], _
	[-208, -13692, " ", $vqrange], _
	[-181, -13692, " ", $vqrange], _
	[-155, -13692, " ", $vqrange], _
	[-128, -13692, " ", $vqrange], _
	[-102, -13692, " ", $vqrange], _
	[-75, -13692, " ", $vqrange], _
	[-49, -13692, " ", $vqrange], _
	[-22, -13692, " ", $vqrange], _
	[403, -13691, " ", $vqrange], _
	[1252, -13689, " ", $vqrange], _
	[520, -13684, " ", $vqrange], _
	[154, -13681, " ", $vqrange], _
	[-29, -13680, " ", $vqrange], _
	[-189, -13679, " ", $vqrange], _
	[-1677, -13668, " ", $vqrange], _
	[-212, -13678, " ", $vqrange], _
	[-52, -13680, " ", $vqrange], _
	[154, -13681, " ", $vqrange], _
	[520, -13684, " ", $vqrange], _
	[1252, -13689, " ", $vqrange], _
	[2557, -13925, " ", $vqrange], _
	[2538, -12875, " ", $vqrange], _
	[2519, -11825, " ", $vqrange], _
	[1981, -12522, " ", $vqrange], _
	[2384.5256, -13049, " ", $vqrange], _ ; auto
	[1442, -13219, " ", $vqrange], _
	[1223, -13282, " ", $vqrange], _
	[2271, -13282, " ", $vqrange], _
	[3319, -13282, " ", $vqrange], _
	[3582, -13282, " ", $vqrange], _
	[3745, -13282, " ", $vqrange], _
	[3909, -13282, " ", $vqrange], _
	[4106, -13282, " ", $vqrange], _
	[4368, -13282, " ", $vqrange], _
	[5416, -13282, " ", $vqrange], _
	[6390, -13105, " ", $vqrange], _
	[7299, -12264, " ", $vqrange], _
	[8208, -11424, " ", $vqrange], _
	[7896, -10518, " ", $vqrange], _
	[7818, -10291.75, " ", $vqrange], _ ; auto
	[7759.5, -10122.0625, " ", $vqrange], _ ; auto
	[7584, -9613, " ", $vqrange], _
	[6216, -5519, " ", $vqrange], _
	[5361, -4491, " ", $vqrange], _
	[5171, -4487, " ", $vqrange], _
	[5020, -4483, " ", $vqrange], _
	[4870, -4480, " ", $vqrange], _
	[4719, -4476, " ", $vqrange], _
	[4568, -4473, " ", $vqrange], _
	[4418, -4469, " ", $vqrange], _
	[4267, -4466, " ", $vqrange], _
	[4116, -4462, " ", $vqrange], _
	[3942, -4462, " ", $vqrange], _
	[3783, -4462, " ", $vqrange], _
	[3623, -4462, " ", $vqrange], _
	[3463, -4462, " ", $vqrange], _
	[3304, -4462, " ", $vqrange], _
	[3144, -4462, " ", $vqrange], _
	[2985, -4462, " ", $vqrange], _
	[2825, -4462, " ", $vqrange], _
	[2666, -4462, " ", $vqrange], _
	[2492, -4462, " ", $vqrange], _
	[2259, -4462, " ", $vqrange], _
	[1331, -4462, " ", $vqrange], _
	[403, -4462, " ", $vqrange], _
	[1239, -5375, " ", $vqrange], _
	[2075, -6287, " ", $vqrange], _
	[2911, -7200, " ", $vqrange], _
	[3677, -7372, " ", $vqrange], _
	[2744, -6846, " ", $vqrange], _
	[1810, -6321, " ", $vqrange], _
	[1024, -5363, " ", $vqrange], _
	[237, -4405, " ", $vqrange], _
	[-1106, -4907, " ", $vqrange], _
	[-2448, -5409, " ", $vqrange], _
	[-2572, -6355, " ", $vqrange], _
	[-2697, -7301, " ", $vqrange], _
	[-3529, -7378, " ", $vqrange], _
	[-4361, -7456, " ", $vqrange], _
	[-4650, -7332.5, " ", $vqrange], _ ; auto
	[-4794.5, -7270.75, " ", $vqrange], _ ; auto
	[-4939, -7209, " ", $vqrange], _ ; auto
	[-5470.2163, -7209, " ", $vqrange], _ ; auto
	[-5139, -7135, " ", $vqrange], _ ; auto
	[-5387, -6125, " ", $vqrange], _
	[-5516, -5104, " ", $vqrange], _
	[-5595, -4889, " ", $vqrange], _
	[-6543, -4725, " ", $vqrange], _
	[-7492, -4561, " ", $vqrange], _
	[-8228, -3523, " ", $vqrange], _
	[-8218, 2407, " ", $vqrange], _
	[-5939, 3539, " ", $vqrange], _
	[1097, 2809, " ", $vqrange], _
	[1396.9196, 2936, " ", $vqrange], _ ; auto
	[1957, 3594, " ", $vqrange], _
	[2817, 4378, " ", $vqrange], _
	[3677, 5163, " ", $vqrange], _
	[4054, 4194, " ", $vqrange], _
	[4432, 3225, " ", $vqrange], _
	[4754, 3207.75, " ", $vqrange], _ ; auto
	[5076, 3190.5, " ", $vqrange], _ ; auto
	[5720, 3156, " ", $vqrange], _
	[7008, 3088, " ", $vqrange], _
	[6110, 3034, " ", $vqrange], _
	[5363, 3181, " ", $vqrange], _
	[4409.8694, 3240, " ", $vqrange], _ ; auto
	[4615, 3328, " ", $vqrange], _
	[3635, 4251, " ", $vqrange], _
	[3121, 4251, " ", $vqrange], _
	[2968, 4251, " ", $vqrange], _
	[2787, 4251, " ", $vqrange], _ ; auto
	[2606, 4251, " ", $vqrange], _
	[1542, 3357, " ", $vqrange], _
	[1446, 2114, " ", $vqrange], _
	[1351, 870, " ", $vqrange], _
	[1255, -373, " ", $vqrange], _
	[1037, -394, " ", $vqrange], _
	[868, -410, " ", $vqrange], _
	[223, -472, " ", $vqrange], _
	[-809, -571, " ", $vqrange] _
]

