#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_KainengCity/SunjiangDistrict.au3
; Map: SunjiangDistrict (id 256), geometry from MAP 0000157179.pmap
; Repaired 7 of 15 blocked segments by inserting 35 waypoints.
; Smoothed 69 additional anchor(s) for wall clearance and hop distance.
; Filled 14 long hop(s) by walking the current mesh component toward a disconnected goal.
; 8 segment(s) could not be routed and were left as-is.
; 8 hop(s) still exceed 1500 units (worst 4452 between index 119 and 120).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_KainengCity_SunjiangDistrictRoute01[253][4] = [ _
	[6836, 13075, " ", $vqrange], _
	[6877, 11788, " ", $vqrange], _
	[7551, 10917, " ", $vqrange], _
	[8600, 10425, " ", $vqrange], _
	[8950, 10399, " ", $vqrange], _
	[9103, 10388, " ", $vqrange], _
	[9256, 10376, " ", $vqrange], _
	[9475, 10360, " ", $vqrange], _
	[9649, 10347, " ", $vqrange], _
	[9824, 10334, " ", $vqrange], _
	[9977, 10323, " ", $vqrange], _
	[9663.7231, 10301, " ", $vqrange], _ ; auto
	[9881.7777, 10301, " ", $vqrange], _ ; auto
	[10038.5044, 10301, " ", $vqrange], _ ; auto
	[10208.8596, 10301, " ", $vqrange], _ ; auto
	[10535.9414, 10301, " ", $vqrange], _ ; auto
	[11408.1597, 10301, " ", $vqrange], _ ; auto
	[10771.5798, 10306.5, " ", $vqrange], _ ; auto
	[10453.2899, 10309.25, " ", $vqrange], _ ; auto
	[10294.145, 10310.625, " ", $vqrange], _ ; auto
	[10135, 10312, " ", $vqrange], _
	[10360, 10298, " ", $vqrange], _
	[10721, 10276, " ", $vqrange], _
	[11442, 10230, " ", $vqrange], _
	[12153, 9600, " ", $vqrange], _
	[12318, 8459, " ", $vqrange], _
	[12847, 8114, " ", $vqrange], _
	[11859, 7680, " ", $vqrange], _
	[11775, 6266, " ", $vqrange], _
	[11841, 7021, " ", $vqrange], _
	[11908, 7776, " ", $vqrange], _
	[12290, 7776, " ", $vqrange], _
	[12481, 7776, " ", $vqrange], _
	[12672, 7776, " ", $vqrange], _
	[12720, 7296, " ", $vqrange], _
	[12891, 7296, " ", $vqrange], _
	[13044, 7296, " ", $vqrange], _
	[13234, 7296, " ", $vqrange], _
	[13405, 7296, " ", $vqrange], _
	[13554, 8208, " ", $vqrange], _
	[13854, 8373, " ", $vqrange], _
	[15037, 8292, " ", $vqrange], _
	[15333, 8271, " ", $vqrange], _
	[15490, 8260, " ", $vqrange], _
	[15647, 8249, " ", $vqrange], _
	[15924, 8230, " ", $vqrange], _
	[16220, 8210, " ", $vqrange], _
	[16517, 8019, " ", $vqrange], _
	[16421, 6722, " ", $vqrange], _
	[16030, 6230, " ", $vqrange], _
	[16462, 5624, " ", $vqrange], _
	[16179, 4754, " ", $vqrange], _
	[15897, 3884, " ", $vqrange], _
	[15843, 3046, " ", $vqrange], _
	[15789, 2208, " ", $vqrange], _
	[16004, 2196, " ", $vqrange], _
	[16218, 2185, " ", $vqrange], _
	[15802, 2154, " ", $vqrange], _
	[16019, 841, " ", $vqrange], _
	[16236, -472, " ", $vqrange], _
	[16030, -1236, " ", $vqrange], _
	[16357, -2174, " ", $vqrange], _
	[16685, -3111, " ", $vqrange], _
	[16704.75, -3271.875, " ", $vqrange], _ ; auto
	[16724.5, -3432.75, " ", $vqrange], _ ; auto
	[16764, -3754.5, " ", $vqrange], _ ; auto
	[16843, -4398, " ", $vqrange], _
	[17056, -5572, " ", $vqrange], _
	[16943, -6685, " ", $vqrange], _
	[16829, -7798, " ", $vqrange], _
	[16657, -8448, " ", $vqrange], _
	[15901, -8853, " ", $vqrange], _
	[15622, -9800, " ", $vqrange], _
	[15552, -10037, " ", $vqrange], _
	[15499, -10214, " ", $vqrange], _
	[15831, -10258, " ", $vqrange], _ ; auto
	[15447, -10392, " ", $vqrange], _
	[15394.5, -10569.5, " ", $vqrange], _ ; auto
	[15342, -10747, " ", $vqrange], _
	[15274, -10889, " ", $vqrange], _
	[15204.5, -11033.5, " ", $vqrange], _ ; auto
	[15135, -11178, " ", $vqrange], _
	[14929, -11610, " ", $vqrange], _
	[15941, -12673, " ", $vqrange], _
	[16107, -12889, " ", $vqrange], _
	[15213, -11903, " ", $vqrange], _
	[14319, -10917, " ", $vqrange], _
	[13277, -10755, " ", $vqrange], _
	[12455, -10560, " ", $vqrange], _
	[11633, -10366, " ", $vqrange], _
	[11005, -10500, " ", $vqrange], _
	[10691, -10567, " ", $vqrange], _
	[10534, -10600, " ", $vqrange], _
	[10386, -10632, " ", $vqrange], _
	[10226.5, -10666, " ", $vqrange], _ ; auto
	[10067, -10700, " ", $vqrange], _ ; auto
	[9748, -10768, " ", $vqrange], _
	[9591, -10802, " ", $vqrange], _
	[9444, -10833, " ", $vqrange], _
	[9297, -10864, " ", $vqrange], _
	[9120, -10902, " ", $vqrange], _
	[8252, -11911, " ", $vqrange], _
	[8844, -10839, " ", $vqrange], _ ; auto
	[8844, -9644, " ", $vqrange], _ ; auto
	[8844, -8449, " ", $vqrange], _
	[8127, -8342, " ", $vqrange], _
	[9186, -7645, " ", $vqrange], _
	[10245, -6949, " ", $vqrange], _
	[11304, -6252, " ", $vqrange], _
	[11968.25, -5246, " ", $vqrange], _ ; auto
	[12632.5, -4240, " ", $vqrange], _ ; auto
	[12495, -3881, " ", $vqrange], _ ; auto
	[12279, -2572, " ", $vqrange], _
	[12147, -1244, " ", $vqrange], _
	[12015, 85, " ", $vqrange], _
	[11907, 1440, " ", $vqrange], _
	[11799, 2795, " ", $vqrange], _
	[11918, 1468, " ", $vqrange], _
	[12037, 141, " ", $vqrange], _
	[12156, -1186, " ", $vqrange], _
	[12002, -5635, " ", $vqrange], _
	[10717, -6165, " ", $vqrange], _
	[9433, -6694, " ", $vqrange], _
	[8148, -7224, " ", $vqrange], _
	[7018, -7226, " ", $vqrange], _
	[5752, -7741, " ", $vqrange], _
	[4486, -8256, " ", $vqrange], _
	[4677, -8318, " ", $vqrange], _
	[4117, -12337, " ", $vqrange], _
	[2764, -12354, " ", $vqrange], _
	[2087, -12363, " ", $vqrange], _
	[1748, -12368, " ", $vqrange], _
	[1579, -12370, " ", $vqrange], _
	[1410, -12372, " ", $vqrange], _
	[1286, -12281, " ", $vqrange], _ ; auto
	[1162, -12190, " ", $vqrange], _
	[1038, -12099, " ", $vqrange], _
	[914, -12008, " ", $vqrange], _
	[790, -11917, " ", $vqrange], _
	[666, -11827, " ", $vqrange], _
	[542, -11736, " ", $vqrange], _
	[418, -11645, " ", $vqrange], _
	[-219, -10854, " ", $vqrange], _
	[-1231, -10634, " ", $vqrange], _
	[-1577, -10110, " ", $vqrange], _ ; auto
	[-1577, -8710, " ", $vqrange], _
	[-1573, -7382, " ", $vqrange], _
	[-1093, -7379, " ", $vqrange], _
	[-942, -7378, " ", $vqrange], _
	[-792, -7377, " ", $vqrange], _
	[-612, -7376, " ", $vqrange], _
	[-5, -6187, " ", $vqrange], _
	[20, -5190, " ", $vqrange], _
	[-108, -4262, " ", $vqrange], _
	[-133, -4088, " ", $vqrange], _
	[228, -4032, " ", $vqrange], _ ; auto
	[-154, -3936, " ", $vqrange], _
	[324, -3936, " ", $vqrange], _ ; auto
	[-237, -3334, " ", $vqrange], _
	[2245, -1057, " ", $vqrange], _
	[1064, -800, " ", $vqrange], _
	[1007, -417, " ", $vqrange], _
	[2584, 232, " ", $vqrange], _
	[4035, 2381, " ", $vqrange], _
	[4706, 1962, " ", $vqrange], _
	[5003, 1083, " ", $vqrange], _
	[5144, 720, " ", $vqrange], _
	[5214, 539, " ", $vqrange], _
	[5285, 358, " ", $vqrange], _
	[5037, 192, " ", $vqrange], _
	[5665, 119, " ", $vqrange], _
	[6281, 271, " ", $vqrange], _
	[6437, 271, " ", $vqrange], _
	[6589, 271, " ", $vqrange], _
	[6741, 271, " ", $vqrange], _
	[6907, 271, " ", $vqrange], _
	[7533, 271, " ", $vqrange], _
	[6986, 165, " ", $vqrange], _
	[6983.5, 323, " ", $vqrange], _ ; auto
	[5975, 353.5, " ", $vqrange], _ ; auto
	[5470.75, 368.75, " ", $vqrange], _ ; auto
	[5313.1719, 373.5156, " ", $vqrange], _ ; auto
	[4966.5, 384, " ", $vqrange], _ ; auto
	[4742.7787, 1288.5, " ", $vqrange], _ ; auto
	[4519.0574, 2193, " ", $vqrange], _ ; auto
	[4264.9877, 2218.25, " ", $vqrange], _ ; auto
	[4114.1338, 2233.2422, " ", $vqrange], _ ; auto
	[3963.28, 2248.2344, " ", $vqrange], _ ; auto
	[3756.8484, 2268.75, " ", $vqrange], _ ; auto
	[3502.7787, 2294, " ", $vqrange], _ ; auto
	[2486.5, 2395, " ", $vqrange], _ ; auto
	[2407.0345, 2194, " ", $vqrange], _ ; auto
	[2657.7759, 2193.3859, " ", $vqrange], _ ; auto
	[2814.4892, 2193.002, " ", $vqrange], _ ; auto
	[2967.2848, 2192.6278, " ", $vqrange], _ ; auto
	[3120.0803, 2192.2536, " ", $vqrange], _ ; auto
	[3410, 2191.5435, " ", $vqrange], _ ; auto
	[3410, 2285, " ", $vqrange], _
	[3242, 2280, " ", $vqrange], _
	[3090, 2275, " ", $vqrange], _
	[2938, 2270, " ", $vqrange], _
	[2738, 2263, " ", $vqrange], _
	[2066, 2241, " ", $vqrange], _
	[1043, 2219, " ", $vqrange], _
	[922.25, 2117.75, " ", $vqrange], _ ; auto
	[801.5, 2016.5, " ", $vqrange], _ ; auto
	[560, 1814, " ", $vqrange], _
	[78, 1410, " ", $vqrange], _
	[2740, 2341, " ", $vqrange], _
	[2570.2574, 2481, " ", $vqrange], _ ; auto
	[2976.3207, 2481.5, " ", $vqrange], _ ; auto
	[3128.5944, 2481.6875, " ", $vqrange], _ ; auto
	[3280.8682, 2481.875, " ", $vqrange], _ ; auto
	[3433.1419, 2482.0625, " ", $vqrange], _ ; auto
	[3585.4156, 2482.25, " ", $vqrange], _ ; auto
	[3788.4472, 2482.5, " ", $vqrange], _ ; auto
	[4194.5105, 2483, " ", $vqrange], _ ; auto
	[3891, 2954, " ", $vqrange], _ ; auto
	[3891, 4081, " ", $vqrange], _
	[4143, 4435, " ", $vqrange], _
	[3752, 4435, " ", $vqrange], _
	[3557, 4435, " ", $vqrange], _
	[3404, 4435, " ", $vqrange], _
	[3166, 4434, " ", $vqrange], _
	[3014, 4434, " ", $vqrange], _
	[2861, 4434, " ", $vqrange], _
	[2580, 4434, " ", $vqrange], _
	[2428, 4448, " ", $vqrange], _
	[2277, 4461, " ", $vqrange], _
	[2126, 4474, " ", $vqrange], _
	[1968, 4488, " ", $vqrange], _
	[2008, 5760, " ", $vqrange], _
	[1673, 5932, " ", $vqrange], _
	[2478, 6987, " ", $vqrange], _
	[3283, 8042, " ", $vqrange], _
	[2092, 7313, " ", $vqrange], _
	[902, 6584, " ", $vqrange], _
	[612.5, 6599.75, " ", $vqrange], _ ; auto
	[323, 6615.5, " ", $vqrange], _ ; auto
	[-256, 6647, " ", $vqrange], _
	[-1414, 6711, " ", $vqrange], _
	[-2572, 6774, " ", $vqrange], _
	[-3625.02, 6328, " ", $vqrange], _ ; auto
	[-3643, 6133, " ", $vqrange], _ ; auto
	[-3643, 5366, " ", $vqrange], _
	[-3797, 5257, " ", $vqrange], _
	[-4670, 5078, " ", $vqrange], _
	[-5780, 4685, " ", $vqrange], _
	[-3630, 2845, " ", $vqrange], _
	[-3623, 2574, " ", $vqrange], _
	[-3619, 2411, " ", $vqrange], _
	[-4536, 792, " ", $vqrange], _
	[-4413, -173, " ", $vqrange] _
]

