#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_KainengCity/TahnnakiTemple.au3
; Map: TahnnakiTemple (id 269), geometry from MAP 0000157178.pmap
; Repaired 4 of 23 blocked segments by inserting 38 waypoints.
; Smoothed 87 additional anchor(s) for wall clearance and hop distance.
; Filled 21 long hop(s) by walking the current mesh component toward a disconnected goal.
; 19 segment(s) could not be routed and were left as-is.
; 18 hop(s) still exceed 1500 units (worst 5718 between index 135 and 136).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_KainengCity_TahnnakiTempleRoute01[223][4] = [ _
	[2885, -12388, " ", $vqrange], _
	[1936, -11867, " ", $vqrange], _
	[651.5385, -11481, " ", $vqrange], _ ; auto
	[987, -11345, " ", $vqrange], _
	[37, -10824, " ", $vqrange], _
	[71, -10568, " ", $vqrange], _
	[213, -9480, " ", $vqrange], _
	[355, -8392, " ", $vqrange], _
	[1048, -7874, " ", $vqrange], _
	[227, -7361, " ", $vqrange], _
	[-311, -6872, " ", $vqrange], _
	[691, -5919, " ", $vqrange], _
	[524, -5394, " ", $vqrange], _
	[1392, -4382, " ", $vqrange], _
	[2259, -3369, " ", $vqrange], _
	[1287, -2533, " ", $vqrange], _
	[2074, -1484, " ", $vqrange], _
	[1454, -578, " ", $vqrange], _
	[2011, -6, " ", $vqrange], _
	[2567, 567, " ", $vqrange], _
	[3051, 733, " ", $vqrange], _
	[3171, 2109, " ", $vqrange], _
	[3623, 2331, " ", $vqrange], _
	[3623, 3332, " ", $vqrange], _
	[4624, 3511, " ", $vqrange], _
	[5626, 3690, " ", $vqrange], _
	[5615, 3851, " ", $vqrange], _
	[5605, 4001, " ", $vqrange], _
	[5390.9458, 4097, " ", $vqrange], _ ; auto
	[5593, 4172, " ", $vqrange], _
	[5582, 4333, " ", $vqrange], _
	[5538, 4976, " ", $vqrange], _
	[5449, 6262, " ", $vqrange], _
	[6527, 6347, " ", $vqrange], _
	[7605, 6432, " ", $vqrange], _
	[7728, 7919, " ", $vqrange], _
	[7745, 8716, " ", $vqrange], _
	[7762, 9512, " ", $vqrange], _
	[7770, 9910, " ", $vqrange], _
	[7774, 10072, " ", $vqrange], _
	[7777, 10234, " ", $vqrange], _
	[7781, 10396, " ", $vqrange], _
	[7784, 10557, " ", $vqrange], _
	[7788, 10719, " ", $vqrange], _
	[7792, 10906, " ", $vqrange], _
	[7796, 11105, " ", $vqrange], _
	[6907, 11708, " ", $vqrange], _
	[6018, 12310, " ", $vqrange], _
	[5189, 13210, " ", $vqrange], _
	[4360, 14110, " ", $vqrange], _
	[3531, 15010, " ", $vqrange], _
	[2702, 15910, " ", $vqrange], _
	[2509, 15721, " ", $vqrange], _
	[1272, 15557, " ", $vqrange], _
	[36, 15393, " ", $vqrange], _
	[816, 15323, " ", $vqrange], _
	[1597, 15253, " ", $vqrange], _
	[2467, 15527, " ", $vqrange], _
	[3337, 15801, " ", $vqrange], _
	[3263, 17048, " ", $vqrange], _
	[2776, 17784, " ", $vqrange], _
	[2288, 18519, " ", $vqrange], _
	[896, 18516, " ", $vqrange], _
	[-497, 18514, " ", $vqrange], _
	[-1401.2165, 18816, " ", $vqrange], _ ; auto
	[-1698.9124, 18816, " ", $vqrange], _ ; auto
	[-1852.4118, 18816, " ", $vqrange], _ ; auto
	[-2005.9112, 18816, " ", $vqrange], _ ; auto
	[-2159.4107, 18816, " ", $vqrange], _ ; auto
	[-2312.9101, 18816, " ", $vqrange], _ ; auto
	[-2592, 18816, " ", $vqrange], _ ; auto
	[-2798, 18799, " ", $vqrange], _ ; auto
	[-3207, 18475, " ", $vqrange], _ ; auto
	[-3374.25, 18475, " ", $vqrange], _ ; auto
	[-3531.0469, 18475, " ", $vqrange], _ ; auto
	[-3687.8438, 18475, " ", $vqrange], _ ; auto
	[-3844.6406, 18475, " ", $vqrange], _ ; auto
	[-4001.4375, 18475, " ", $vqrange], _ ; auto
	[-4158.2344, 18475, " ", $vqrange], _ ; auto
	[-4377.75, 18475, " ", $vqrange], _ ; auto
	[-4534.5469, 18475, " ", $vqrange], _ ; auto
	[-4691.3438, 18475, " ", $vqrange], _ ; auto
	[-4848.1406, 18475, " ", $vqrange], _ ; auto
	[-5046.75, 18475, " ", $vqrange], _ ; auto
	[-5214, 18475, " ", $vqrange], _ ; auto
	[-5883, 18475, " ", $vqrange], _
	[-3351, 19307, " ", $vqrange], _
	[-4000, 20523, " ", $vqrange], _
	[-6150, 15909, " ", $vqrange], _
	[-6068, 15746, " ", $vqrange], _
	[-5778, 15696, " ", $vqrange], _
	[-5523, 15651, " ", $vqrange], _
	[-4979, 15556, " ", $vqrange], _
	[-4706, 15509, " ", $vqrange], _
	[-4553, 15482, " ", $vqrange], _
	[-4400, 15456, " ", $vqrange], _
	[-4230, 15426, " ", $vqrange], _
	[-3889, 15367, " ", $vqrange], _
	[-3063, 14492, " ", $vqrange], _
	[-3010, 14238, " ", $vqrange], _
	[-2056, 9994, " ", $vqrange], _
	[-1184, 6957, " ", $vqrange], _
	[-795, 2365, " ", $vqrange], _
	[-1685, 492, " ", $vqrange], _
	[-3603, 1783, " ", $vqrange], _
	[-1183, 2540, " ", $vqrange], _
	[-1213, 3657, " ", $vqrange], _
	[-1242, 4774, " ", $vqrange], _
	[-1257, 5332, " ", $vqrange], _
	[-1265, 5612, " ", $vqrange], _
	[-1269, 5769, " ", $vqrange], _
	[-1276, 6031, " ", $vqrange], _
	[-1280, 6188, " ", $vqrange], _
	[-1284, 6345, " ", $vqrange], _
	[-1289, 6502, " ", $vqrange], _
	[-1293, 6659, " ", $vqrange], _
	[-1012, 6674, " ", $vqrange], _ ; auto
	[-1302, 7008, " ", $vqrange], _
	[-4043, 11366, " ", $vqrange], _
	[-3834, 12548, " ", $vqrange], _
	[-3625, 13730, " ", $vqrange], _
	[-3120, 14516, " ", $vqrange], _
	[-3193, 14776, " ", $vqrange], _
	[-4210, 15485, " ", $vqrange], _
	[-4845, 15731, " ", $vqrange], _
	[-5151, 15734.5, " ", $vqrange], _ ; auto
	[-5304, 15736.25, " ", $vqrange], _ ; auto
	[-5457, 15738, " ", $vqrange], _
	[-5609, 15740, " ", $vqrange], _
	[-5762, 15742, " ", $vqrange], _
	[-5915, 15744, " ", $vqrange], _
	[-6068, 15746, " ", $vqrange], _
	[-5954, 16052, " ", $vqrange], _
	[-4060, 20011, " ", $vqrange], _
	[-3351, 19307, " ", $vqrange], _
	[-5730, 18567, " ", $vqrange], _
	[-45, 17958, " ", $vqrange], _
	[-148, 16625, " ", $vqrange], _
	[-250, 15292, " ", $vqrange], _
	[-352, 13958, " ", $vqrange], _
	[-455, 12625, " ", $vqrange], _
	[995, 11490, " ", $vqrange], _
	[1808, 11426, " ", $vqrange], _
	[2622, 11362, " ", $vqrange], _
	[2563, 10063, " ", $vqrange], _
	[529, 6662, " ", $vqrange], _
	[1898, 6606, " ", $vqrange], _
	[3268, 6549, " ", $vqrange], _
	[4637, 6493, " ", $vqrange], _
	[3639, 6399, " ", $vqrange], _
	[3140, 6352, " ", $vqrange], _
	[3015, 6340, " ", $vqrange], _
	[4249.5, 6344, " ", $vqrange], _ ; auto
	[5484, 6348, " ", $vqrange], _ ; auto
	[6718.5, 6352, " ", $vqrange], _ ; auto
	[7953, 6356, " ", $vqrange], _ ; auto
	[6615.9531, 6423, " ", $vqrange], _ ; auto
	[5278.9062, 6490, " ", $vqrange], _ ; auto
	[4139.4531, 6490, " ", $vqrange], _ ; auto
	[3569.7266, 6490, " ", $vqrange], _ ; auto
	[3284.8633, 6490, " ", $vqrange], _ ; auto
	[3000, 6490, " ", $vqrange], _
	[3284.8633, 6490, " ", $vqrange], _ ; auto
	[3569.7266, 6490, " ", $vqrange], _ ; auto
	[4139.4531, 6490, " ", $vqrange], _ ; auto
	[5278.9062, 6490, " ", $vqrange], _ ; auto
	[6615.9531, 6423, " ", $vqrange], _ ; auto
	[7953, 6356, " ", $vqrange], _ ; auto
	[6710.75, 6351.25, " ", $vqrange], _ ; auto
	[5468.5, 6346.5, " ", $vqrange], _ ; auto
	[4226.25, 6341.75, " ", $vqrange], _ ; auto
	[3605.125, 6339.375, " ", $vqrange], _ ; auto
	[3294.5625, 6338.1875, " ", $vqrange], _ ; auto
	[3139.2812, 6337.5938, " ", $vqrange], _ ; auto
	[2984, 6337, " ", $vqrange], _
	[2968, 6335, " ", $vqrange], _
	[2953, 6334, " ", $vqrange], _
	[2937, 6332, " ", $vqrange], _
	[2922, 6331, " ", $vqrange], _
	[2906, 6330, " ", $vqrange], _
	[2890, 6328, " ", $vqrange], _
	[2875, 6327, " ", $vqrange], _
	[2859, 6325, " ", $vqrange], _
	[2844, 6324, " ", $vqrange], _
	[2828, 6322, " ", $vqrange], _
	[2766, 6316, " ", $vqrange], _
	[2641, 6304, " ", $vqrange], _
	[1643, 6210, " ", $vqrange], _ ; auto
	[645, 6116, " ", $vqrange], _
	[417.5, 6225, " ", $vqrange], _ ; auto
	[190, 6334, " ", $vqrange], _ ; auto
	[118.5, 6257, " ", $vqrange], _ ; auto
	[-796, 6068, " ", $vqrange], _ ; auto
	[-2728.5, 6068, " ", $vqrange], _ ; auto
	[-4318.4624, 6345, " ", $vqrange], _ ; auto
	[-4204, 6542, " ", $vqrange], _
	[-6157, 9375, " ", $vqrange], _
	[-7161, 9432, " ", $vqrange], _
	[-8165, 9488, " ", $vqrange], _
	[-7991, 9500, " ", $vqrange], _
	[-7840, 9510, " ", $vqrange], _
	[-7689, 9520, " ", $vqrange], _
	[-7394, 9540, " ", $vqrange], _
	[-7328, 10265, " ", $vqrange], _
	[-8142, 10241, " ", $vqrange], _
	[-8955, 10217, " ", $vqrange], _
	[-8643, 9051, " ", $vqrange], _
	[-8331, 7886, " ", $vqrange], _
	[-8019, 6720, " ", $vqrange], _
	[-7034, 6410, " ", $vqrange], _
	[-7125, 5286, " ", $vqrange], _
	[-7148, 5005, " ", $vqrange], _
	[-7161, 4847, " ", $vqrange], _
	[-7174, 4689, " ", $vqrange], _
	[-7187, 4531, " ", $vqrange], _
	[-7199, 4373, " ", $vqrange], _
	[-7212, 4215, " ", $vqrange], _
	[-7225, 4057, " ", $vqrange], _
	[-7239, 3881, " ", $vqrange], _
	[-7262, 3600, " ", $vqrange], _
	[-7308, 3038, " ", $vqrange], _
	[-7399, 1914, " ", $vqrange], _
	[-10296, -2138, " ", $vqrange] _
]

