#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_KainengCity/XaquangSkyway.au3
; Map: XaquangSkyway (id 31), geometry from MAP 0000157168.pmap
; Repaired 9 of 30 blocked segments by inserting 40 waypoints.
; Smoothed 97 additional anchor(s) for wall clearance and hop distance.
; Filled 24 long hop(s) by walking the current mesh component toward a disconnected goal.
; 21 segment(s) could not be routed and were left as-is.
; 21 hop(s) still exceed 1500 units (worst 4475 between index 12 and 13).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_KainengCity_XaquangSkywayRoute01[378][4] = [ _
	[2270, -9983, " ", $vqrange], _
	[1630, -9495, " ", $vqrange], _
	[1497, -8877, " ", $vqrange], _ ; auto
	[1336, -8855.5, " ", $vqrange], _ ; auto
	[1175, -8834, " ", $vqrange], _
	[798.5, -8666.5, " ", $vqrange], _ ; auto
	[422, -8499, " ", $vqrange], _
	[-2306, -8072, " ", $vqrange], _
	[-2189, -7077, " ", $vqrange], _
	[-2071, -6081, " ", $vqrange], _
	[-1954, -5086, " ", $vqrange], _
	[-4062, -5228, " ", $vqrange], _
	[-5925, -6310, " ", $vqrange], _
	[-9577, -3723, " ", $vqrange], _
	[-9691, -3594, " ", $vqrange], _
	[-9810, -3458, " ", $vqrange], _
	[-9864, -3181, " ", $vqrange], _
	[-10441, -2832, " ", $vqrange], _
	[-11143, -3350, " ", $vqrange], _
	[-11341, -3455.5, " ", $vqrange], _ ; auto
	[-11539, -3561, " ", $vqrange], _ ; auto
	[-11935, -3772, " ", $vqrange], _
	[-11864, -4215, " ", $vqrange], _
	[-12143, -3226, " ", $vqrange], _
	[-12422, -2236, " ", $vqrange], _
	[-12467, -915, " ", $vqrange], _
	[-12259, -479, " ", $vqrange], _
	[-12250, 514, " ", $vqrange], _
	[-12249, 669, " ", $vqrange], _
	[-12248, 824, " ", $vqrange], _
	[-12246, 979, " ", $vqrange], _
	[-12245, 1134, " ", $vqrange], _
	[-12243, 1289, " ", $vqrange], _
	[-12242, 1444, " ", $vqrange], _
	[-12241, 1600, " ", $vqrange], _
	[-12239, 1755, " ", $vqrange], _
	[-12238, 1910, " ", $vqrange], _
	[-12237, 2065, " ", $vqrange], _
	[-12235, 2220, " ", $vqrange], _
	[-12234, 2375, " ", $vqrange], _
	[-12224, 3492, " ", $vqrange], _
	[-13417, 3580, " ", $vqrange], _
	[-14610, 3667, " ", $vqrange], _
	[-14587, 4718, " ", $vqrange], _
	[-14564, 5769, " ", $vqrange], _
	[-14142, 5798, " ", $vqrange], _
	[-13931, 5812, " ", $vqrange], _
	[-13720, 5826, " ", $vqrange], _
	[-13483, 5847, " ", $vqrange], _
	[-13246, 5868, " ", $vqrange], _
	[-13419, 5839, " ", $vqrange], _
	[-13571, 5814, " ", $vqrange], _
	[-13723, 5789, " ", $vqrange], _
	[-13875, 5769, " ", $vqrange], _
	[-14064.5, 5736, " ", $vqrange], _ ; auto
	[-14254, 5703, " ", $vqrange], _ ; auto
	[-14633, 5637, " ", $vqrange], _
	[-14586, 4694, " ", $vqrange], _
	[-14539, 3751, " ", $vqrange], _
	[-13344, 3484, " ", $vqrange], _
	[-12148, 3217, " ", $vqrange], _
	[-12079, 2660, " ", $vqrange], _
	[-12065, 2094, " ", $vqrange], _
	[-12058, 1812, " ", $vqrange], _
	[-12054, 1662, " ", $vqrange], _
	[-12050, 1511, " ", $vqrange], _
	[-12046, 1361, " ", $vqrange], _
	[-12042, 1211, " ", $vqrange], _
	[-12039, 1061, " ", $vqrange], _
	[-12035, 910, " ", $vqrange], _
	[-12031, 760, " ", $vqrange], _
	[-12221, 694, " ", $vqrange], _ ; auto
	[-12027, 610, " ", $vqrange], _
	[-12022, 398, " ", $vqrange], _
	[-10815, -183, " ", $vqrange], _
	[-10630, -1546, " ", $vqrange], _
	[-10315, -2930, " ", $vqrange], _
	[-9863.9727, -3181, " ", $vqrange], _ ; auto
	[-9796.9226, -3387.2031, " ", $vqrange], _ ; auto
	[-9750.1141, -3531.1562, " ", $vqrange], _ ; auto
	[-9702.0405, -3679, " ", $vqrange], _ ; auto
	[-9502.0574, -3676.4609, " ", $vqrange], _ ; auto
	[-9308.2275, -3674, " ", $vqrange], _ ; auto
	[-9146.0853, -3674.6445, " ", $vqrange], _ ; auto
	[-8994.7525, -3675.2461, " ", $vqrange], _ ; auto
	[-8843.4198, -3675.8477, " ", $vqrange], _ ; auto
	[-8692.087, -3676.4492, " ", $vqrange], _ ; auto
	[-8540.7543, -3677.0508, " ", $vqrange], _ ; auto
	[-8389.4215, -3677.6523, " ", $vqrange], _ ; auto
	[-8238.0888, -3678.2539, " ", $vqrange], _ ; auto
	[-8086.756, -3678.8555, " ", $vqrange], _ ; auto
	[-7935.4233, -3679.457, " ", $vqrange], _ ; auto
	[-7784.0905, -3680.0586, " ", $vqrange], _ ; auto
	[-7632.7577, -3680.6602, " ", $vqrange], _ ; auto
	[-7481.425, -3681.2617, " ", $vqrange], _ ; auto
	[-7330.0922, -3681.8633, " ", $vqrange], _ ; auto
	[-7178.7595, -3682.4648, " ", $vqrange], _ ; auto
	[-7027.4267, -3683.0664, " ", $vqrange], _ ; auto
	[-6876.094, -3683.668, " ", $vqrange], _ ; auto
	[-6724.7612, -3684.2695, " ", $vqrange], _ ; auto
	[-6541, -3685, " ", $vqrange], _
	[-5721, -643, " ", $vqrange], _
	[-5147, 3386, " ", $vqrange], _
	[-4502, 3875, " ", $vqrange], _
	[-3856, 4364, " ", $vqrange], _
	[-5925, 5794, " ", $vqrange], _
	[-5249, 8027, " ", $vqrange], _
	[-5234, 8299, " ", $vqrange], _
	[-5308.9114, 8660, " ", $vqrange], _ ; auto
	[-5611.8818, 9084, " ", $vqrange], _ ; auto
	[-5407, 9088, " ", $vqrange], _
	[-5171, 9113, " ", $vqrange], _
	[-5020, 9129, " ", $vqrange], _
	[-4720, 9161, " ", $vqrange], _
	[-4033, 9234, " ", $vqrange], _
	[-1216, 10613, " ", $vqrange], _
	[-1191.25, 10770.5, " ", $vqrange], _ ; auto
	[-1167.6602, 10920.6172, " ", $vqrange], _ ; auto
	[-1144.0703, 11070.7344, " ", $vqrange], _ ; auto
	[-1117, 11243, " ", $vqrange], _ ; auto
	[-1216.6154, 11279, " ", $vqrange], _ ; auto
	[-443.6693, 11282, " ", $vqrange], _ ; auto
	[-939, 11479, " ", $vqrange], _
	[63, 10485, " ", $vqrange], _
	[1261, 10416, " ", $vqrange], _
	[1560, 10398, " ", $vqrange], _
	[1710, 10389, " ", $vqrange], _
	[1860, 10381, " ", $vqrange], _
	[2010, 10372, " ", $vqrange], _
	[2160, 10363, " ", $vqrange], _
	[2309, 10355, " ", $vqrange], _
	[2459, 10346, " ", $vqrange], _
	[3714, 8253, " ", $vqrange], _
	[3692, 6829, " ", $vqrange], _
	[3748, 10412, " ", $vqrange], _
	[4994, 11443, " ", $vqrange], _
	[4662, 11485, " ", $vqrange], _
	[4330, 11526, " ", $vqrange], _
	[3998.5, 11568, " ", $vqrange], _ ; auto
	[3832.75, 11589, " ", $vqrange], _ ; auto
	[3667, 11610, " ", $vqrange], _
	[3650, 11774, " ", $vqrange], _
	[3479.9524, 11775, " ", $vqrange], _ ; auto
	[3626, 12014, " ", $vqrange], _
	[3585, 12418, " ", $vqrange], _
	[3503, 13226, " ", $vqrange], _
	[3649, 14006, " ", $vqrange], _
	[3685.5, 14201.25, " ", $vqrange], _ ; auto
	[3722, 14396.5, " ", $vqrange], _ ; auto
	[3795, 14787, " ", $vqrange], _
	[3709, 14040, " ", $vqrange], _ ; auto
	[3703.0898, 13879.8945, " ", $vqrange], _ ; auto
	[3697.5273, 13729.207, " ", $vqrange], _ ; auto
	[3691.9648, 13578.5195, " ", $vqrange], _ ; auto
	[3686.4023, 13427.832, " ", $vqrange], _ ; auto
	[3680.8398, 13277.1445, " ", $vqrange], _ ; auto
	[3675.2773, 13126.457, " ", $vqrange], _ ; auto
	[3669.7148, 12975.7695, " ", $vqrange], _ ; auto
	[3664.1523, 12825.082, " ", $vqrange], _ ; auto
	[3658.5898, 12674.3945, " ", $vqrange], _ ; auto
	[3653.0273, 12523.707, " ", $vqrange], _ ; auto
	[3647.4648, 12373.0195, " ", $vqrange], _ ; auto
	[3620, 11629, " ", $vqrange], _
	[3856, 11593, " ", $vqrange], _
	[4093, 11558, " ", $vqrange], _
	[4565, 11487, " ", $vqrange], _
	[5510, 11344, " ", $vqrange], _
	[6456, 11202, " ", $vqrange], _
	[7401, 11060, " ", $vqrange], _
	[8264, 10916, " ", $vqrange], _
	[9128, 10773, " ", $vqrange], _
	[9835, 9469, " ", $vqrange], _
	[10727, 8965, " ", $vqrange], _
	[12050, 9534, " ", $vqrange], _
	[12594.4131, 10104, " ", $vqrange], _ ; auto
	[12789.3098, 10104, " ", $vqrange], _ ; auto
	[12984.2065, 10104, " ", $vqrange], _ ; auto
	[13179.1033, 10104, " ", $vqrange], _ ; auto
	[13374, 10104, " ", $vqrange], _
	[13215.5, 10016, " ", $vqrange], _ ; auto
	[13081.7656, 9941.75, " ", $vqrange], _ ; auto
	[12938.125, 9862, " ", $vqrange], _ ; auto
	[12740, 9752, " ", $vqrange], _ ; auto
	[12601.3125, 9675, " ", $vqrange], _ ; auto
	[12423, 9576, " ", $vqrange], _ ; auto
	[12106, 9400, " ", $vqrange], _
	[10837, 8696, " ", $vqrange], _
	[11202, 8231, " ", $vqrange], _
	[10579, 5302, " ", $vqrange], _
	[11377, 5262, " ", $vqrange], _
	[11539, 5254, " ", $vqrange], _
	[11776, 5242, " ", $vqrange], _
	[12175, 5222, " ", $vqrange], _
	[12973, 5181, " ", $vqrange], _
	[13771, 5141, " ", $vqrange], _
	[14647, 4389, " ", $vqrange], _
	[15522, 3638, " ", $vqrange], _
	[16398, 2886, " ", $vqrange], _
	[13388, 5007, " ", $vqrange], _
	[12051, 5016, " ", $vqrange], _
	[11382, 5021, " ", $vqrange], _
	[11215, 5022, " ", $vqrange], _
	[11059, 5024, " ", $vqrange], _
	[10902, 5025, " ", $vqrange], _
	[10714, 5026, " ", $vqrange], _
	[9151, 4038, " ", $vqrange], _
	[7851, 3674, " ", $vqrange], _
	[8628, 3611, " ", $vqrange], _
	[8965, 3578, " ", $vqrange], _
	[9302, 3544, " ", $vqrange], _
	[9358, 2554, " ", $vqrange], _
	[9414, 1563, " ", $vqrange], _
	[9462, 230, " ", $vqrange], _
	[9510, -1104, " ", $vqrange], _
	[9367.5, -1336, " ", $vqrange], _ ; auto
	[9225, -1568, " ", $vqrange], _ ; auto
	[9403.1108, -1580.9, " ", $vqrange], _ ; auto
	[9294.1401, -3521, " ", $vqrange], _ ; auto
	[8562.583, -3978, " ", $vqrange], _ ; auto
	[6724, -4068, " ", $vqrange], _
	[7027, -4072, " ", $vqrange], _
	[7178, -4074, " ", $vqrange], _
	[7330, -4076, " ", $vqrange], _
	[7481, -4078, " ", $vqrange], _
	[7633, -4080, " ", $vqrange], _
	[7784, -4082, " ", $vqrange], _
	[7936, -4084, " ", $vqrange], _
	[8087, -4086, " ", $vqrange], _
	[8239, -4088, " ", $vqrange], _
	[8390, -4090, " ", $vqrange], _
	[8542, -4092, " ", $vqrange], _
	[9148, -4100, " ", $vqrange], _
	[8290, -5096, " ", $vqrange], _
	[8302, -5901, " ", $vqrange], _
	[8313, -6706, " ", $vqrange], _
	[8294, -8077, " ", $vqrange], _
	[8274, -9449, " ", $vqrange], _
	[8255, -10820, " ", $vqrange], _
	[7132, -11320, " ", $vqrange], _
	[6008, -11819, " ", $vqrange], _
	[4896, -11309, " ", $vqrange], _
	[4056.3024, -10980, " ", $vqrange], _ ; auto
	[3783, -10799, " ", $vqrange], _
	[2671, -10289, " ", $vqrange], _
	[2849, -9578, " ", $vqrange], _
	[2656, -8364, " ", $vqrange], _
	[2464, -7149, " ", $vqrange], _
	[1064, -5517, " ", $vqrange], _
	[448, -4484, " ", $vqrange], _
	[636, -4464, " ", $vqrange], _
	[731, -4453, " ", $vqrange], _
	[778, -4448, " ", $vqrange], _
	[790, -4447, " ", $vqrange], _
	[801, -4446, " ", $vqrange], _
	[813, -4444, " ", $vqrange], _
	[825, -4443, " ", $vqrange], _
	[837, -4440, " ", $vqrange], _
	[848, -4438, " ", $vqrange], _
	[860, -4435, " ", $vqrange], _
	[872, -4432, " ", $vqrange], _
	[884, -4432, " ", $vqrange], _
	[896, -4432, " ", $vqrange], _
	[907, -4433, " ", $vqrange], _
	[919, -4433, " ", $vqrange], _
	[931, -4432, " ", $vqrange], _
	[943, -4430, " ", $vqrange], _
	[954, -4429, " ", $vqrange], _
	[966, -4428, " ", $vqrange], _
	[978, -4427, " ", $vqrange], _
	[990, -4425, " ", $vqrange], _
	[1002, -4424, " ", $vqrange], _
	[1013, -4423, " ", $vqrange], _
	[1025, -4421, " ", $vqrange], _
	[1037, -4420, " ", $vqrange], _
	[1049, -4419, " ", $vqrange], _
	[1060, -4418, " ", $vqrange], _
	[1072, -4416, " ", $vqrange], _
	[1084, -4415, " ", $vqrange], _
	[1096, -4414, " ", $vqrange], _
	[1108, -4412, " ", $vqrange], _
	[1119, -4411, " ", $vqrange], _
	[1131, -4410, " ", $vqrange], _
	[1143, -4409, " ", $vqrange], _
	[1155, -4407, " ", $vqrange], _
	[1166, -4406, " ", $vqrange], _
	[1178, -4405, " ", $vqrange], _
	[1190, -4404, " ", $vqrange], _
	[1202, -4402, " ", $vqrange], _
	[1214, -4401, " ", $vqrange], _
	[1225, -4400, " ", $vqrange], _
	[1237, -4398, " ", $vqrange], _
	[1249, -4397, " ", $vqrange], _
	[1261, -4396, " ", $vqrange], _
	[1272, -4395, " ", $vqrange], _
	[1284, -4393, " ", $vqrange], _
	[1296, -4392, " ", $vqrange], _
	[1308, -4391, " ", $vqrange], _
	[1320, -4389, " ", $vqrange], _
	[1331, -4388, " ", $vqrange], _
	[1343, -4387, " ", $vqrange], _
	[1355, -4386, " ", $vqrange], _
	[1367, -4384, " ", $vqrange], _
	[1378, -4383, " ", $vqrange], _
	[1390, -4382, " ", $vqrange], _
	[1402, -4381, " ", $vqrange], _
	[1414, -4379, " ", $vqrange], _
	[1426, -4378, " ", $vqrange], _
	[1437, -4377, " ", $vqrange], _
	[1449, -4375, " ", $vqrange], _
	[1461, -4374, " ", $vqrange], _
	[1473, -4373, " ", $vqrange], _
	[1484, -4372, " ", $vqrange], _
	[1579, -4361, " ", $vqrange], _
	[1956, -4320, " ", $vqrange], _
	[2709.5, -4238.5, " ", $vqrange], _ ; auto
	[3463, -4157, " ", $vqrange], _
	[5526, -3630, " ", $vqrange], _
	[5348, -2487, " ", $vqrange], _ ; auto
	[5170, -1344, " ", $vqrange], _ ; auto
	[5170, -141.3333, " ", $vqrange], _ ; auto
	[5170, 1061.3333, " ", $vqrange], _ ; auto
	[5170, 2264, " ", $vqrange], _
	[4875, 3424, " ", $vqrange], _
	[4671, 3424, " ", $vqrange], _
	[4518, 3424, " ", $vqrange], _
	[4365, 3424, " ", $vqrange], _
	[4212, 3424, " ", $vqrange], _
	[4059, 3424, " ", $vqrange], _
	[4020, 3393, " ", $vqrange], _
	[689, 3591, " ", $vqrange], _
	[2634, 3958, " ", $vqrange], _
	[3197.6163, 4320, " ", $vqrange], _ ; auto
	[3328, 4689, " ", $vqrange], _ ; auto
	[3812, 5332, " ", $vqrange], _
	[3707, 6331, " ", $vqrange], _
	[3823, 6295, " ", $vqrange], _
	[3881, 6278, " ", $vqrange], _
	[3889, 6275, " ", $vqrange], _
	[3896, 6273, " ", $vqrange], _
	[3903, 6271, " ", $vqrange], _
	[3910, 6269, " ", $vqrange], _
	[3918, 6266, " ", $vqrange], _
	[3925, 6264, " ", $vqrange], _
	[3932, 6262, " ", $vqrange], _
	[3940, 6260, " ", $vqrange], _
	[3947, 6258, " ", $vqrange], _
	[3954, 6255, " ", $vqrange], _
	[3961, 6253, " ", $vqrange], _
	[3969, 6251, " ", $vqrange], _
	[3976, 6249, " ", $vqrange], _
	[3983, 6246, " ", $vqrange], _
	[3990, 6244, " ", $vqrange], _
	[3998, 6242, " ", $vqrange], _
	[4005, 6240, " ", $vqrange], _
	[4012, 6237, " ", $vqrange], _
	[4019, 6235, " ", $vqrange], _
	[4027, 6233, " ", $vqrange], _
	[4034, 6231, " ", $vqrange], _
	[4041, 6229, " ", $vqrange], _
	[4048, 6226, " ", $vqrange], _
	[4056, 6224, " ", $vqrange], _
	[4063, 6222, " ", $vqrange], _
	[4070, 6220, " ", $vqrange], _
	[4078, 6217, " ", $vqrange], _
	[4085, 6215, " ", $vqrange], _
	[4092, 6213, " ", $vqrange], _
	[4099, 6211, " ", $vqrange], _
	[4114, 6206, " ", $vqrange], _
	[4128, 6202, " ", $vqrange], _
	[4136, 6200, " ", $vqrange], _
	[4143, 6197, " ", $vqrange], _
	[4150, 6195, " ", $vqrange], _
	[4157, 6193, " ", $vqrange], _
	[4165, 6191, " ", $vqrange], _
	[4172, 6188, " ", $vqrange], _
	[5305.8076, 6186, " ", $vqrange], _ ; auto
	[4637, 6046, " ", $vqrange], _
	[5567, 5761, " ", $vqrange] _
]

