#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Ascalon/AscalonFoothills.au3
; Map: AscalonFoothills (id 103), geometry from MAP 0000051062.pmap
; Repaired 3 of 7 blocked segments by inserting 15 waypoints.
; Smoothed 31 additional anchor(s) for wall clearance and hop distance.
; Filled 5 long hop(s) by walking the current mesh component toward a disconnected goal.
; 4 segment(s) could not be routed and were left as-is.
; 4 hop(s) still exceed 1500 units (worst 7241 between index 90 and 91).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Ascalon_AscalonFoothillsRoute01[97][4] = [ _
	[-5785, 1558, " ", $vqrange], _
	[-4751, 1707, " ", $vqrange], _
	[-3718, 1857, " ", $vqrange], _
	[-2684, 2006, " ", $vqrange], _
	[-3709, 1817, " ", $vqrange], _
	[-4735, 1629, " ", $vqrange], _
	[-5760, 1440, " ", $vqrange], _
	[-6422, 816, " ", $vqrange], _
	[-7085, 192, " ", $vqrange], _
	[-6314, -710, " ", $vqrange], _
	[-5544, -1613, " ", $vqrange], _
	[-6060, -2774, " ", $vqrange], _
	[-6576, -3936, " ", $vqrange], _
	[-6047, -4800, " ", $vqrange], _
	[-5518, -5664, " ", $vqrange], _
	[-5257, -5672, " ", $vqrange], _
	[-5061, -5678, " ", $vqrange], _
	[-4906, -5683, " ", $vqrange], _
	[-4751, -5688, " ", $vqrange], _
	[-4473, -5696, " ", $vqrange], _
	[-3428, -5729, " ", $vqrange], _
	[-2134, -5360, " ", $vqrange], _
	[-840, -4992, " ", $vqrange], _
	[-234, -4133, " ", $vqrange], _
	[373, -3274, " ", $vqrange], _
	[184, -3456, " ", $vqrange], _
	[-596, -3456, " ", $vqrange], _
	[-748, -3456, " ", $vqrange], _
	[-901, -3456, " ", $vqrange], _
	[-1084, -3456, " ", $vqrange], _
	[-1376, -3456, " ", $vqrange], _
	[-2266, -2777, " ", $vqrange], _
	[-3156, -2098, " ", $vqrange], _
	[-2576, -897, " ", $vqrange], _
	[-1996, 304, " ", $vqrange], _
	[-1639, 751, " ", $vqrange], _
	[-543, 384, " ", $vqrange], _
	[-412.3202, -96, " ", $vqrange], _ ; auto
	[39, -176, " ", $vqrange], _
	[621, -735, " ", $vqrange], _
	[1164, 182, " ", $vqrange], _
	[1707, 1099, " ", $vqrange], _
	[2250, 2016, " ", $vqrange], _
	[2040, 2078, " ", $vqrange], _
	[1170, 2792, " ", $vqrange], _
	[300, 3505, " ", $vqrange], _
	[270, 4291, " ", $vqrange], _
	[240, 5077, " ", $vqrange], _
	[817, 5796, " ", $vqrange], _
	[971, 5834, " ", $vqrange], _
	[1117, 5872, " ", $vqrange], _
	[1263, 5913, " ", $vqrange], _
	[1416, 5954, " ", $vqrange], _
	[1776, 6048, " ", $vqrange], _
	[2176, 6816, " ", $vqrange], _
	[2326.5, 6816, " ", $vqrange], _ ; auto
	[2477, 6816, " ", $vqrange], _
	[2629, 6816, " ", $vqrange], _
	[2782, 6816, " ", $vqrange], _
	[2934, 6816, " ", $vqrange], _
	[3147, 6816, " ", $vqrange], _ ; auto
	[3360, 6816, " ", $vqrange], _
	[3970, 6405, " ", $vqrange], _ ; auto
	[4122.5, 6302.25, " ", $vqrange], _ ; auto
	[4275, 6199.5, " ", $vqrange], _ ; auto
	[4580, 5994, " ", $vqrange], _
	[5800, 5171, " ", $vqrange], _
	[4885, 5096, " ", $vqrange], _
	[6292, 4822, " ", $vqrange], _ ; auto
	[6176.5363, 3721, " ", $vqrange], _ ; auto
	[6061.0726, 2620, " ", $vqrange], _ ; auto
	[5945.6089, 1519, " ", $vqrange], _ ; auto
	[5939, 1126, " ", $vqrange], _
	[3321, -3531, " ", $vqrange], _
	[4405, -4214, " ", $vqrange], _
	[5336.0881, -4542, " ", $vqrange], _ ; auto
	[5490, -4896, " ", $vqrange], _
	[5646.5, -4988.5, " ", $vqrange], _ ; auto
	[5803, -5081, " ", $vqrange], _ ; auto
	[5960.543, -5081.8477, " ", $vqrange], _ ; auto
	[6113.0039, -5082.668, " ", $vqrange], _ ; auto
	[6265.4648, -5083.4883, " ", $vqrange], _ ; auto
	[6453.5, -5084.5, " ", $vqrange], _ ; auto
	[7104, -5088, " ", $vqrange], _ ; auto
	[7321, -5205, " ", $vqrange], _
	[7358, -6068, " ", $vqrange], _
	[7394, -6932, " ", $vqrange], _
	[7350, -6018, " ", $vqrange], _
	[7307, -5105, " ", $vqrange], _
	[6184, 1000, " ", $vqrange], _
	[8736, -4608, " ", $vqrange], _
	[10274, -11684, " ", $vqrange], _
	[10471, -11986, " ", $vqrange], _ ; auto
	[10569.5, -12137, " ", $vqrange], _ ; auto
	[10668, -12288, " ", $vqrange], _
	[10819.5625, -12288, " ", $vqrange], _ ; auto
	[11056, -12288, " ", $vqrange] _
]

