#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: vendor/vanquish-bot/Maps/Proph_Ascalon/AscalonFoothills.au3
; Map: AscalonFoothills (id 103), geometry from MAP 0000051062.pmap
; Repaired 10 of 17 blocked segments by inserting 18 waypoints.
; Smoothed 38 additional anchor(s) for wall clearance and hop distance.
; 7 segment(s) could not be routed and were left as-is.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.

Global $aProph_Ascalon_AscalonFoothillsRoute01[76][2] = [ _
	[-5785, 1558], _
	[-4751.3333, 1707.3333], _ ; auto
	[-3717.6667, 1856.6667], _ ; auto
	[-2684, 2006], _
	[-3709.3333, 1817.3333], _ ; auto
	[-4734.6667, 1628.6667], _ ; auto
	[-5760, 1440], _ ; auto
	[-6422.4, 816], _ ; auto
	[-7084.8, 192], _ ; auto
	[-6314.4, -710.5], _ ; auto
	[-5544, -1613], _
	[-6060, -2774.5], _ ; auto
	[-6576, -3936], _ ; auto
	[-6047.0233, -4800], _ ; auto
	[-5518.0466, -5664], _ ; auto
	[-5256.7908, -5672.125], _ ; auto
	[-5060.8489, -5678.2188], _ ; auto
	[-4905.7283, -5683.043], _ ; auto
	[-4750.6076, -5687.8672], _ ; auto
	[-4473.0233, -5696.5], _ ; auto
	[-3428, -5729], _
	[-2134, -5360.5], _ ; auto
	[-840, -4992], _ ; auto
	[-233.5, -4133], _ ; auto
	[373, -3274], _
	[183.9626, -3456], _ ; auto
	[-596.0187, -3456], _ ; auto
	[-748.3588, -3456], _ ; auto
	[-900.6989, -3456], _ ; auto
	[-1083.507, -3456], _ ; auto
	[-1376, -3456], _ ; auto
	[-2266, -2777], _ ; auto
	[-3156, -2098], _
	[-2576.1024, -897], _ ; auto
	[-1996.2048, 304], _ ; auto
	[-1639, 751], _
	[-542.5877, 384], _ ; auto
	[39.2062, -175.5], _ ; auto
	[621, -735], _
	[1163.861, 182], _ ; auto
	[1706.7221, 1099], _ ; auto
	[2249.5831, 2016], _ ; auto
	[2040, 2078], _
	[1170, 2791.5], _ ; auto
	[300, 3505], _ ; auto
	[270, 4291], _ ; auto
	[240, 5077], _
	[816.9821, 5796], _ ; auto
	[970.5749, 5834.4375], _ ; auto
	[1116.6752, 5872.5], _ ; auto
	[1262.7756, 5912.7188], _ ; auto
	[1416.3683, 5953.5], _ ; auto
	[1776, 6048], _ ; auto
	[2176, 6816], _ ; auto
	[2476.625, 6816], _ ; auto
	[2629.25, 6816], _ ; auto
	[2781.875, 6816], _ ; auto
	[2934.5, 6816], _ ; auto
	[3360, 6816], _ ; auto
	[4579.75, 5993.5], _ ; auto
	[5799.5, 5171], _ ; auto
	[4885, 5096], _
	[5939, 1126], _
	[3321, -3531], _
	[4405.4553, -4213.5], _ ; auto
	[5489.9106, -4896], _ ; auto
	[7321.25, -5205], _ ; auto
	[7357.625, -6068.5], _ ; auto
	[7394, -6932], _
	[7350.5, -6018.5], _ ; auto
	[7307, -5105], _
	[8304, -458], _
	[10540, -4383], _
	[10274, -11684], _
	[10668, -17113], _
	[11056, -17139] _
]

