#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Ascalon/FlameTempleCorridor.au3
; Map: FlameTempleCorridor (id 106), geometry from MAP 0000051064.pmap
; Repaired 0 of 0 blocked segments by inserting 0 waypoints.
; Smoothed 4 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Ascalon_FlameTempleCorridorRoute01[181][4] = [ _
	[-18448, -11278, " ", $vqrange], _
	[-19016, -10295, " ", $vqrange], _
	[-19584, -9312, " ", $vqrange], _
	[-19523, -8452, " ", $vqrange], _
	[-18645, -7392, " ", $vqrange], _
	[-17708, -6816, " ", $vqrange], _
	[-16771, -6240, " ", $vqrange], _
	[-17298, -5976, " ", $vqrange], _
	[-16978, -5240, " ", $vqrange], _
	[-16657, -4503, " ", $vqrange], _
	[-16531, -3652, " ", $vqrange], _
	[-16808, -3391, " ", $vqrange], _
	[-16936, -3287, " ", $vqrange], _
	[-17057, -3188, " ", $vqrange], _
	[-17179, -3090, " ", $vqrange], _
	[-17300, -2991, " ", $vqrange], _
	[-17422, -2893, " ", $vqrange], _
	[-17543, -2794, " ", $vqrange], _
	[-17664, -2695, " ", $vqrange], _
	[-17887, -2515, " ", $vqrange], _
	[-18102, -2340, " ", $vqrange], _
	[-18534, -1989, " ", $vqrange], _
	[-19133, -2480, " ", $vqrange], _
	[-18534, -1989, " ", $vqrange], _
	[-18102, -2340, " ", $vqrange], _
	[-17887, -2515, " ", $vqrange], _
	[-17765, -2613, " ", $vqrange], _
	[-17644, -2712, " ", $vqrange], _
	[-17523, -2810, " ", $vqrange], _
	[-17401, -2909, " ", $vqrange], _
	[-17280, -3008, " ", $vqrange], _
	[-17159, -3106, " ", $vqrange], _
	[-17037, -3205, " ", $vqrange], _
	[-16808, -3391, " ", $vqrange], _
	[-16995, -3456, " ", $vqrange], _
	[-16531, -3652, " ", $vqrange], _
	[-16315, -4578, " ", $vqrange], _
	[-16241, -5522, " ", $vqrange], _
	[-16167, -6465, " ", $vqrange], _
	[-15701, -6991, " ", $vqrange], _
	[-15468, -7254, " ", $vqrange], _
	[-15366, -7369, " ", $vqrange], _
	[-15235, -7517, " ", $vqrange], _
	[-15128, -7624, " ", $vqrange], _
	[-14976, -7776, " ", $vqrange], _
	[-14800, -7872, " ", $vqrange], _
	[-14899, -8035, " ", $vqrange], _
	[-14789, -8148, " ", $vqrange], _
	[-14683, -8257, " ", $vqrange], _
	[-14160, -8544, " ", $vqrange], _ ; auto
	[-14378, -8571, " ", $vqrange], _
	[-13857, -9107, " ", $vqrange], _
	[-12983, -8753, " ", $vqrange], _
	[-12384, -7776, " ", $vqrange], _
	[-12336, -6528, " ", $vqrange], _
	[-11863, -6401, " ", $vqrange], _
	[-12148, -5648, " ", $vqrange], _
	[-12432, -4896, " ", $vqrange], _
	[-11669, -4432, " ", $vqrange], _
	[-12804, -4416, " ", $vqrange], _
	[-11608, -4402, " ", $vqrange], _
	[-11421, -4399, " ", $vqrange], _
	[-11262, -4397, " ", $vqrange], _
	[-11103, -4395, " ", $vqrange], _
	[-10944, -4393, " ", $vqrange], _
	[-10785, -4392, " ", $vqrange], _
	[-10626, -4390, " ", $vqrange], _
	[-10411, -4387, " ", $vqrange], _
	[-10540, -3865, " ", $vqrange], _
	[-9374, -3564, " ", $vqrange], _
	[-8208, -3264, " ", $vqrange], _
	[-8208, -2784, " ", $vqrange], _
	[-9120, -2592, " ", $vqrange], _
	[-9653, -2568, " ", $vqrange], _
	[-9919, -2556, " ", $vqrange], _
	[-10069, -2549, " ", $vqrange], _
	[-10219, -2542, " ", $vqrange], _
	[-10369, -2536, " ", $vqrange], _
	[-10519, -2529, " ", $vqrange], _
	[-10718, -2520, " ", $vqrange], _
	[-11251, -2496, " ", $vqrange], _
	[-11228, -2247, " ", $vqrange], _
	[-11978, -2496, " ", $vqrange], _
	[-10895, -2520, " ", $vqrange], _
	[-10624, -2526, " ", $vqrange], _
	[-10472, -2529, " ", $vqrange], _
	[-10319, -2533, " ", $vqrange], _
	[-10167, -2536, " ", $vqrange], _
	[-10014, -2540, " ", $vqrange], _
	[-9862, -2543, " ", $vqrange], _
	[-9710, -2546, " ", $vqrange], _
	[-9557, -2550, " ", $vqrange], _
	[-9405, -2553, " ", $vqrange], _
	[-9235.75, -2556.75, " ", $vqrange], _ ; auto
	[-9066.5, -2560.5, " ", $vqrange], _ ; auto
	[-8728, -2568, " ", $vqrange], _
	[-7644, -2592, " ", $vqrange], _
	[-8600, -3114, " ", $vqrange], _
	[-8256, -3360, " ", $vqrange], _
	[-9168, -3936, " ", $vqrange], _
	[-10080, -4512, " ", $vqrange], _
	[-10128, -4992, " ", $vqrange], _
	[-9940, -4992, " ", $vqrange], _
	[-9787, -4992, " ", $vqrange], _
	[-9634, -4992, " ", $vqrange], _
	[-9482, -4992, " ", $vqrange], _
	[-9329, -4992, " ", $vqrange], _
	[-9176, -4992, " ", $vqrange], _
	[-9024, -4992, " ", $vqrange], _
	[-8871, -4992, " ", $vqrange], _
	[-8624, -4992, " ", $vqrange], _
	[-8045, -4392, " ", $vqrange], _
	[-7226, -3639, " ", $vqrange], _
	[-6407, -2886, " ", $vqrange], _
	[-7416, -3826, " ", $vqrange], _
	[-8426, -4766, " ", $vqrange], _
	[-8624, -4992, " ", $vqrange], _
	[-8812, -4992, " ", $vqrange], _
	[-8965, -4992, " ", $vqrange], _
	[-9118, -4992, " ", $vqrange], _
	[-9270, -4992, " ", $vqrange], _
	[-9423, -4992, " ", $vqrange], _
	[-9576, -4992, " ", $vqrange], _
	[-9728, -4992, " ", $vqrange], _
	[-9881, -4992, " ", $vqrange], _
	[-10128, -4992, " ", $vqrange], _
	[-9766, -3730, " ", $vqrange], _
	[-8987, -3497, " ", $vqrange], _
	[-8208, -3264, " ", $vqrange], _
	[-7944, -2448, " ", $vqrange], _
	[-7680, -1632, " ", $vqrange], _
	[-7147, -1130, " ", $vqrange], _
	[-6228, -1218, " ", $vqrange], _
	[-5308, -1306, " ", $vqrange], _
	[-5038, -1393, " ", $vqrange], _
	[-4804, -1469, " ", $vqrange], _
	[-4666, -2616, " ", $vqrange], _
	[-4528, -3762, " ", $vqrange], _
	[-5523, -4462, " ", $vqrange], _
	[-6517, -5161, " ", $vqrange], _
	[-5880, -5280, " ", $vqrange], _
	[-6297, -5441, " ", $vqrange], _
	[-6310, -6287, " ", $vqrange], _
	[-6322, -7133, " ", $vqrange], _
	[-7358, -7061, " ", $vqrange], _
	[-8074, -6424, " ", $vqrange], _
	[-8453, -6524, " ", $vqrange], _
	[-8607, -6565, " ", $vqrange], _
	[-8832, -6624, " ", $vqrange], _
	[-8928, -7104, " ", $vqrange], _
	[-10037, -7547, " ", $vqrange], _
	[-10128, -8352, " ", $vqrange], _
	[-9512, -8948, " ", $vqrange], _
	[-8895, -9545, " ", $vqrange], _
	[-8484, -9942, " ", $vqrange], _
	[-8375, -10048, " ", $vqrange], _
	[-8224.5, -10194, " ", $vqrange], _ ; auto
	[-8074, -10340, " ", $vqrange], _
	[-7931, -9197, " ", $vqrange], _
	[-7038, -9158, " ", $vqrange], _
	[-6145, -9120, " ", $vqrange], _
	[-5814, -10069, " ", $vqrange], _
	[-5484, -11018, " ", $vqrange], _
	[-5153, -11967, " ", $vqrange], _
	[-5696, -12656, " ", $vqrange], _
	[-6240, -13344, " ", $vqrange], _
	[-5987, -14539, " ", $vqrange], _
	[-6995, -14933, " ", $vqrange], _
	[-8003, -15327, " ", $vqrange], _
	[-9011, -15721, " ", $vqrange], _
	[-9760, -15203, " ", $vqrange], _
	[-10509, -14685, " ", $vqrange], _
	[-10140, -13344, " ", $vqrange], _
	[-9611, -12759, " ", $vqrange], _
	[-9303, -12518, " ", $vqrange], _
	[-9187, -11808, " ", $vqrange], _
	[-9490, -11040, " ", $vqrange], _
	[-9792, -10272, " ", $vqrange], _
	[-9912, -9792, " ", $vqrange], _
	[-10359, -9564, " ", $vqrange], _
	[-11546, -9365, " ", $vqrange] _
]

