#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_Ascalon/TheBreach.au3
; Map: TheBreach (id 102), geometry from MAP 0000051061.pmap
; Repaired 1 of 2 blocked segments by inserting 2 waypoints.
; Smoothed 28 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; 1 segment(s) could not be routed and were left as-is.
; 1 hop(s) still exceed 1500 units (worst 1983 between index 349 and 350).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_Ascalon_TheBreachRoute01[369][4] = [ _
	[20930, 5611, " ", $vqrange], _
	[21124, 5664, " ", $vqrange], _
	[20598, 6281, " ", $vqrange], _
	[20371, 6288, " ", $vqrange], _
	[20215, 6292, " ", $vqrange], _
	[20058, 6297, " ", $vqrange], _
	[19874, 6302.5, " ", $vqrange], _ ; auto
	[19690, 6308, " ", $vqrange], _
	[18781, 6334, " ", $vqrange], _
	[17873, 6361, " ", $vqrange], _
	[17703, 6366, " ", $vqrange], _
	[17419, 6375, " ", $vqrange], _
	[16965, 6388, " ", $vqrange], _
	[16498, 5090, " ", $vqrange], _
	[16032, 3792, " ", $vqrange], _
	[16835, 3760, " ", $vqrange], _
	[17637, 3728, " ", $vqrange], _
	[18440, 3695, " ", $vqrange], _
	[18842, 3679, " ", $vqrange], _
	[19042, 3671, " ", $vqrange], _
	[19243, 3663, " ", $vqrange], _
	[19291, 3574, " ", $vqrange], _
	[19511.25, 3566, " ", $vqrange], _ ; auto
	[19731.5, 3558, " ", $vqrange], _ ; auto
	[20172, 3542, " ", $vqrange], _
	[21053, 3511, " ", $vqrange], _
	[20829, 2772, " ", $vqrange], _
	[20605, 2033, " ", $vqrange], _
	[19817, 1464, " ", $vqrange], _
	[19029, 894, " ", $vqrange], _
	[18406, 724, " ", $vqrange], _
	[18932, 447, " ", $vqrange], _
	[18958, -328, " ", $vqrange], _
	[18984, -1102, " ", $vqrange], _
	[19100, -1217, " ", $vqrange], _
	[19339, -1122, " ", $vqrange], _
	[19100, -1217, " ", $vqrange], _ ; auto
	[19290, -1141, " ", $vqrange], _ ; auto
	[19480, -1065, " ", $vqrange], _
	[19623.5, -1007.75, " ", $vqrange], _ ; auto
	[19767, -950.5, " ", $vqrange], _ ; auto
	[20054, -836, " ", $vqrange], _
	[21009, -454, " ", $vqrange], _
	[20153, -1059, " ", $vqrange], _
	[19297, -1664, " ", $vqrange], _
	[19393, -2741, " ", $vqrange], _
	[19488, -3819, " ", $vqrange], _
	[19584, -4896, " ", $vqrange], _
	[20424, -5760, " ", $vqrange], _
	[20376, -5923, " ", $vqrange], _
	[20966, -7158, " ", $vqrange], _
	[21555, -8393, " ", $vqrange], _
	[22038, -9691, " ", $vqrange], _
	[21612, -8605, " ", $vqrange], _
	[21186, -7518, " ", $vqrange], _
	[20760, -6432, " ", $vqrange], _
	[20181, -6031, " ", $vqrange], _
	[19882, -5992, " ", $vqrange], _
	[19733, -5972, " ", $vqrange], _
	[19584, -5952, " ", $vqrange], _
	[19431, -5933, " ", $vqrange], _
	[19200, -5904, " ", $vqrange], _
	[18816, -5856, " ", $vqrange], _
	[18404, -5474, " ", $vqrange], _
	[18300, -5604, " ", $vqrange], _
	[18756, -5760, " ", $vqrange], _
	[18906, -5904, " ", $vqrange], _ ; auto
	[19056, -6048, " ", $vqrange], _
	[18528, -6432, " ", $vqrange], _
	[18241, -6912, " ", $vqrange], _
	[17904, -7584, " ", $vqrange], _
	[17587, -7776, " ", $vqrange], _
	[17293, -7776, " ", $vqrange], _
	[17140, -7776, " ", $vqrange], _
	[16971, -7776, " ", $vqrange], _ ; auto
	[16802, -7776, " ", $vqrange], _ ; auto
	[16464, -7776, " ", $vqrange], _
	[15780, -7404, " ", $vqrange], _
	[16171, -6430, " ", $vqrange], _
	[16008, -6048, " ", $vqrange], _
	[15984, -5184, " ", $vqrange], _
	[15863, -4300, " ", $vqrange], _
	[16710, -3394, " ", $vqrange], _
	[17557, -2487, " ", $vqrange], _
	[16456, -3323, " ", $vqrange], _
	[15354, -4158, " ", $vqrange], _
	[14253, -4994, " ", $vqrange], _
	[13151, -5829, " ", $vqrange], _
	[12050, -6665, " ", $vqrange], _
	[11240, -6378, " ", $vqrange], _
	[10429, -6092, " ", $vqrange], _
	[10284, -4726, " ", $vqrange], _
	[10140, -3360, " ", $vqrange], _
	[9558, -2437, " ", $vqrange], _
	[10344, -2112, " ", $vqrange], _
	[10692, -1920, " ", $vqrange], _
	[11304, -1536, " ", $vqrange], _
	[11695, -1393, " ", $vqrange], _
	[11916, -1503, " ", $vqrange], _
	[12055, -1572, " ", $vqrange], _
	[12230, -1659, " ", $vqrange], _
	[13012, -2047, " ", $vqrange], _
	[13792, -1344, " ", $vqrange], _
	[15048, -1200, " ", $vqrange], _
	[15205, -1182, " ", $vqrange], _
	[15362, -1164, " ", $vqrange], _
	[15519, -1146, " ", $vqrange], _
	[15676, -1128, " ", $vqrange], _
	[15833, -1110, " ", $vqrange], _
	[15990, -1092, " ", $vqrange], _
	[16304, -1056, " ", $vqrange], _
	[17062, -574, " ", $vqrange], _
	[17820, -92, " ", $vqrange], _
	[17940, 1056, " ", $vqrange], _
	[17349, 2040, " ", $vqrange], _
	[16647.5, 1969.5, " ", $vqrange], _ ; auto
	[16296.75, 1934.25, " ", $vqrange], _ ; auto
	[16121.375, 1916.625, " ", $vqrange], _ ; auto
	[15946, 1899, " ", $vqrange], _
	[14542, 1758, " ", $vqrange], _
	[14273, 3060, " ", $vqrange], _
	[14004, 4362, " ", $vqrange], _
	[13735, 5664, " ", $vqrange], _
	[13996, 5968, " ", $vqrange], _
	[14506, 6955, " ", $vqrange], _
	[15016, 7942, " ", $vqrange], _
	[15712, 7637, " ", $vqrange], _
	[16704, 8544, " ", $vqrange], _
	[16788, 9096, " ", $vqrange], _
	[15607, 9804, " ", $vqrange], _
	[14553, 8753, " ", $vqrange], _
	[13498, 7703, " ", $vqrange], _
	[12444, 6652, " ", $vqrange], _
	[12070, 7454, " ", $vqrange], _
	[11696, 8256, " ", $vqrange], _
	[11472, 8382, " ", $vqrange], _
	[11832, 8064, " ", $vqrange], _
	[12019, 6902, " ", $vqrange], _
	[11998, 5717, " ", $vqrange], _
	[11977, 4531, " ", $vqrange], _
	[11956, 3346, " ", $vqrange], _
	[10539, 3394, " ", $vqrange], _
	[9830, 3417, " ", $vqrange], _
	[9653, 3423, " ", $vqrange], _
	[9476, 3429, " ", $vqrange], _
	[9122, 3441, " ", $vqrange], _
	[8569, 4312, " ", $vqrange], _
	[8016, 5184, " ", $vqrange], _
	[7517, 5269, " ", $vqrange], _
	[7749, 4934, " ", $vqrange], _
	[7331, 4711, " ", $vqrange], _
	[6632.5, 4711, " ", $vqrange], _ ; auto
	[6479.7031, 4711, " ", $vqrange], _ ; auto
	[6283.25, 4711, " ", $vqrange], _ ; auto
	[5934, 4711, " ", $vqrange], _
	[4537, 4710, " ", $vqrange], _
	[3139, 4710, " ", $vqrange], _
	[1742, 4710, " ", $vqrange], _
	[1051, 4371, " ", $vqrange], _
	[360, 4032, " ", $vqrange], _
	[-569, 3824, " ", $vqrange], _
	[-1158, 4718, " ", $vqrange], _
	[-1746, 5613, " ", $vqrange], _
	[-690, 6161, " ", $vqrange], _
	[367, 6709, " ", $vqrange], _
	[1424, 7257, " ", $vqrange], _
	[2480, 7805, " ", $vqrange], _
	[3202, 8450, " ", $vqrange], _
	[3924, 9094, " ", $vqrange], _
	[3938, 9623, " ", $vqrange], _
	[4122, 9436, " ", $vqrange], _
	[4289, 9436, " ", $vqrange], _
	[4445, 9436, " ", $vqrange], _
	[4601, 9436, " ", $vqrange], _
	[4757, 9436, " ", $vqrange], _
	[4931.5, 9436, " ", $vqrange], _ ; auto
	[5106, 9436, " ", $vqrange], _ ; auto
	[5455, 9436, " ", $vqrange], _
	[6787, 9436, " ", $vqrange], _
	[7495, 9690, " ", $vqrange], _
	[8203, 9945, " ", $vqrange], _
	[7069, 9523, " ", $vqrange], _
	[5935, 9100, " ", $vqrange], _
	[4800, 8678, " ", $vqrange], _
	[3666, 8255, " ", $vqrange], _
	[2532, 7833, " ", $vqrange], _
	[2082, 8476, " ", $vqrange], _
	[1632, 9120, " ", $vqrange], _
	[792, 9840, " ", $vqrange], _
	[582, 10020, " ", $vqrange], _ ; auto
	[372, 10200, " ", $vqrange], _ ; auto
	[-48, 10560, " ", $vqrange], _
	[-240, 10752, " ", $vqrange], _
	[-1296, 10944, " ", $vqrange], _
	[-1144, 10997, " ", $vqrange], _
	[-2122, 10652, " ", $vqrange], _
	[-3100, 10306, " ", $vqrange], _
	[-3245, 9862, " ", $vqrange], _
	[-3937, 9496, " ", $vqrange], _
	[-4986, 9748, " ", $vqrange], _
	[-6036, 9999, " ", $vqrange], _
	[-6301, 8638, " ", $vqrange], _
	[-6567, 7277, " ", $vqrange], _
	[-6832, 5916, " ", $vqrange], _
	[-6527, 7016, " ", $vqrange], _
	[-6222, 8116, " ", $vqrange], _
	[-5916, 9216, " ", $vqrange], _
	[-7058, 9304, " ", $vqrange], _
	[-8200, 9393, " ", $vqrange], _
	[-8784, 9696, " ", $vqrange], _
	[-9078, 9696, " ", $vqrange], _
	[-9298, 9696, " ", $vqrange], _
	[-9455, 9696, " ", $vqrange], _
	[-9666, 9696, " ", $vqrange], _
	[-9960, 9696, " ", $vqrange], _
	[-11136, 9696, " ", $vqrange], _
	[-12489, 9174, " ", $vqrange], _
	[-13055, 8417, " ", $vqrange], _
	[-13140, 7598, " ", $vqrange], _
	[-13224, 6779, " ", $vqrange], _
	[-13296, 6144, " ", $vqrange], _ ; auto
	[-13668, 6078, " ", $vqrange], _
	[-14112, 5376, " ", $vqrange], _
	[-14404, 5028, " ", $vqrange], _
	[-15360, 4224, " ", $vqrange], _
	[-15600, 4224, " ", $vqrange], _
	[-15750, 4224, " ", $vqrange], _
	[-15900, 4224, " ", $vqrange], _
	[-16050, 4224, " ", $vqrange], _
	[-16200, 4224, " ", $vqrange], _
	[-16470, 4224, " ", $vqrange], _ ; auto
	[-16740, 4224, " ", $vqrange], _ ; auto
	[-17280, 4224, " ", $vqrange], _
	[-17412, 4265, " ", $vqrange], _
	[-17280, 4224, " ", $vqrange], _
	[-16320, 4224, " ", $vqrange], _
	[-16170, 4224, " ", $vqrange], _
	[-16020, 4224, " ", $vqrange], _
	[-15870, 4224, " ", $vqrange], _
	[-15720, 4224, " ", $vqrange], _
	[-15360, 4224, " ", $vqrange], _
	[-14248, 4862, " ", $vqrange], _
	[-12950, 4831, " ", $vqrange], _
	[-12798, 4827, " ", $vqrange], _
	[-12646, 4824, " ", $vqrange], _
	[-12494, 4820, " ", $vqrange], _
	[-12342, 4816, " ", $vqrange], _
	[-12189, 4813, " ", $vqrange], _
	[-11976, 4808, " ", $vqrange], _
	[-11652, 4800, " ", $vqrange], _
	[-11442, 3984, " ", $vqrange], _
	[-11232, 3168, " ", $vqrange], _
	[-11520, 2496, " ", $vqrange], _
	[-11130, 2208, " ", $vqrange], _
	[-9820, 2368, " ", $vqrange], _
	[-8510, 2528, " ", $vqrange], _
	[-7200, 2688, " ", $vqrange], _
	[-6693, 3566, " ", $vqrange], _
	[-7192, 2374, " ", $vqrange], _
	[-7690, 1183, " ", $vqrange], _
	[-8189, -8, " ", $vqrange], _
	[-8688, -1200, " ", $vqrange], _
	[-9310, -1710, " ", $vqrange], _
	[-8204, -2515, " ", $vqrange], _
	[-7865, -3929, " ", $vqrange], _
	[-7525, -5342, " ", $vqrange], _
	[-7186, -6756, " ", $vqrange], _
	[-7680, -5882, " ", $vqrange], _
	[-8175, -5009, " ", $vqrange], _
	[-8669, -4135, " ", $vqrange], _
	[-9979, -3716, " ", $vqrange], _
	[-11289, -3298, " ", $vqrange], _
	[-12057, -3762, " ", $vqrange], _
	[-12825, -4227, " ", $vqrange], _
	[-13402, -4896, " ", $vqrange], _
	[-13607.5, -4896, " ", $vqrange], _ ; auto
	[-13813, -4896, " ", $vqrange], _
	[-14019, -4896, " ", $vqrange], _
	[-14225, -4896, " ", $vqrange], _
	[-15048, -4896, " ", $vqrange], _
	[-14576, -3860, " ", $vqrange], _
	[-14104, -2823, " ", $vqrange], _
	[-13632, -1787, " ", $vqrange], _
	[-14104, -2823, " ", $vqrange], _
	[-14576, -3860, " ", $vqrange], _
	[-15048, -4896, " ", $vqrange], _
	[-14225, -4896, " ", $vqrange], _
	[-14019, -4896, " ", $vqrange], _
	[-13813, -4896, " ", $vqrange], _
	[-13402, -4896, " ", $vqrange], _
	[-12762, -4156, " ", $vqrange], _
	[-11815, -4788, " ", $vqrange], _
	[-10867, -5421, " ", $vqrange], _
	[-9920, -6053, " ", $vqrange], _
	[-9742, -7148, " ", $vqrange], _
	[-9565, -8243, " ", $vqrange], _
	[-8100, -8202, " ", $vqrange], _
	[-7917, -8196, " ", $vqrange], _
	[-7757, -8192, " ", $vqrange], _
	[-7597, -8187, " ", $vqrange], _
	[-7368, -8181, " ", $vqrange], _
	[-6636, -8160, " ", $vqrange], _
	[-6846, -8057, " ", $vqrange], _
	[-6288, -7392, " ", $vqrange], _
	[-5540, -7188, " ", $vqrange], _
	[-4791, -6985, " ", $vqrange], _
	[-4032, -6432, " ", $vqrange], _
	[-3816, -6432, " ", $vqrange], _
	[-3654, -6432, " ", $vqrange], _
	[-3502, -6432, " ", $vqrange], _
	[-3330, -6432, " ", $vqrange], _
	[-3168, -6432, " ", $vqrange], _
	[-3130, -7248, " ", $vqrange], _
	[-3091, -8064, " ", $vqrange], _
	[-3600, -8540, " ", $vqrange], _
	[-3069.4, -7937, " ", $vqrange], _ ; auto
	[-3057, -7761, " ", $vqrange], _
	[-3071, -6424, " ", $vqrange], _
	[-3086, -5088, " ", $vqrange], _
	[-2411, -4031, " ", $vqrange], _
	[-1842, -3115, " ", $vqrange], _
	[-579, -3115, " ", $vqrange], _
	[-263, -3115, " ", $vqrange], _
	[-106, -3115, " ", $vqrange], _
	[52, -3115, " ", $vqrange], _
	[683, -3115, " ", $vqrange], _
	[948, -3193, " ", $vqrange], _
	[1793, -2784, " ", $vqrange], _
	[2002, -2784, " ", $vqrange], _
	[2158, -2784, " ", $vqrange], _
	[2315, -2784, " ", $vqrange], _
	[2472, -2784, " ", $vqrange], _ ; auto
	[2629, -2784, " ", $vqrange], _
	[3464, -2784, " ", $vqrange], _
	[4300, -2784, " ", $vqrange], _
	[5136, -2784, " ", $vqrange], _
	[5332, -2861, " ", $vqrange], _
	[5136, -2784, " ", $vqrange], _
	[4300, -2784, " ", $vqrange], _
	[3464, -2784, " ", $vqrange], _
	[2629, -2784, " ", $vqrange], _
	[2420, -2784, " ", $vqrange], _
	[2263, -2784, " ", $vqrange], _
	[2106, -2784, " ", $vqrange], _
	[1793, -2784, " ", $vqrange], _
	[1524, -3510, " ", $vqrange], _
	[1303, -3599, " ", $vqrange], _
	[250, -4467, " ", $vqrange], _
	[441, -4559, " ", $vqrange], _
	[1931, -4717, " ", $vqrange], _
	[2266, -6672, " ", $vqrange], _
	[3424, -6548, " ", $vqrange], _
	[4583, -6424, " ", $vqrange], _
	[5742, -6301, " ", $vqrange], _
	[6900, -6177, " ", $vqrange], _
	[6882, -5304, " ", $vqrange], _
	[6863, -4430, " ", $vqrange], _
	[6855, -3977, " ", $vqrange], _
	[6853, -3807, " ", $vqrange], _
	[6850, -3637, " ", $vqrange], _
	[6844, -3297, " ", $vqrange], _
	[6841, -3141, " ", $vqrange], _
	[6836.5, -2879, " ", $vqrange], _ ; auto
	[6832, -2617, " ", $vqrange], _
	[6712.9951, -2502, " ", $vqrange], _ ; auto
	[6829, -2390, " ", $vqrange], _
	[6825, -2164, " ", $vqrange], _
	[6817, -1710, " ", $vqrange], _
	[6802, -804, " ", $vqrange] _
]

