#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_SouthernShiverpeaks/DreadnoughtsDrift.au3
; Map: DreadnoughtsDrift (id 97), geometry from MAP 0000046601.pmap
; Repaired 0 of 0 blocked segments by inserting 0 waypoints.
; Smoothed 9 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_SouthernShiverpeaks_DreadnoughtsDriftRoute01[110][4] = [ _
	[-1656, -12096, " ", $vqrange], _
	[-1920, -11424, " ", $vqrange], _
	[-3168, -11168, " ", $vqrange], _ ; auto
	[-4416, -10912, " ", $vqrange], _ ; auto
	[-5664, -10656, " ", $vqrange], _
	[-6261.3333, -9472, " ", $vqrange], _ ; auto
	[-6858.6667, -8288, " ", $vqrange], _ ; auto
	[-7456, -7104, " ", $vqrange], _
	[-6287.5, -6255.5, " ", $vqrange], _ ; auto
	[-5119, -5407, " ", $vqrange], _
	[-4427, -4775, " ", $vqrange], _
	[-4272, -4224, " ", $vqrange], _
	[-4644, -2976, " ", $vqrange], _
	[-4446, -2638, " ", $vqrange], _
	[-4560, -3648, " ", $vqrange], _
	[-4272, -4416, " ", $vqrange], _
	[-4704, -5184, " ", $vqrange], _
	[-4555, -5927, " ", $vqrange], _
	[-4605, -6336, " ", $vqrange], _
	[-3777, -7008, " ", $vqrange], _
	[-2949, -7679, " ", $vqrange], _
	[-2050, -6796, " ", $vqrange], _
	[-1673, -5462, " ", $vqrange], _
	[-1296, -4128, " ", $vqrange], _
	[-1584, -3072, " ", $vqrange], _
	[-1872, -2016, " ", $vqrange], _
	[-1590, -1956, " ", $vqrange], _
	[-1308, -1897, " ", $vqrange], _
	[-1521, -1888, " ", $vqrange], _
	[-1734, -1879, " ", $vqrange], _
	[-2160, -1860, " ", $vqrange], _
	[-3012, -1824, " ", $vqrange], _
	[-1973, -1250, " ", $vqrange], _
	[-933, -677, " ", $vqrange], _
	[106, -103, " ", $vqrange], _
	[514, 176, " ", $vqrange], _
	[1520, 283, " ", $vqrange], _
	[2527, 391, " ", $vqrange], _
	[3533, 498, " ", $vqrange], _
	[4526, 262, " ", $vqrange], _
	[5976, 96, " ", $vqrange], _ ; auto
	[5520, 26, " ", $vqrange], _
	[6513, -210, " ", $vqrange], _
	[5734, -1100, " ", $vqrange], _
	[4955, -1990, " ", $vqrange], _
	[4176, -2880, " ", $vqrange], _
	[4356, -3346, " ", $vqrange], _
	[4207, -4303, " ", $vqrange], _
	[3953, -5196, " ", $vqrange], _
	[3699, -6090, " ", $vqrange], _
	[4471, -5998, " ", $vqrange], _
	[5819, -5908, " ", $vqrange], _
	[7167, -5819, " ", $vqrange], _
	[6804, -4842, " ", $vqrange], _
	[6441, -3866, " ", $vqrange], _
	[6078, -2889, " ", $vqrange], _
	[6384, -2016, " ", $vqrange], _
	[6326, -1135, " ", $vqrange], _
	[6525, -355, " ", $vqrange], _
	[5801, 678, " ", $vqrange], _
	[5077, 1710, " ", $vqrange], _
	[5045, 2476, " ", $vqrange], _
	[4953, 3191, " ", $vqrange], _
	[5471, 4407, " ", $vqrange], _
	[6067, 5643, " ", $vqrange], _
	[5381, 4438, " ", $vqrange], _
	[4695, 3234, " ", $vqrange], _
	[4009, 2030, " ", $vqrange], _
	[3323, 825, " ", $vqrange], _
	[2010, 647, " ", $vqrange], _
	[696, 468, " ", $vqrange], _
	[-617, 290, " ", $vqrange], _
	[-1930, 112, " ", $vqrange], _
	[-1997, 919, " ", $vqrange], _
	[-1584, 1660, " ", $vqrange], _
	[-1170, 2400, " ", $vqrange], _
	[-783, 3165, " ", $vqrange], _
	[-738, 3773, " ", $vqrange], _
	[-717, 4814, " ", $vqrange], _
	[-696, 5856, " ", $vqrange], _
	[-1572, 6672, " ", $vqrange], _
	[-2448, 7488, " ", $vqrange], _
	[-1796, 7507, " ", $vqrange], _
	[-2812, 7250, " ", $vqrange], _
	[-3827, 6992, " ", $vqrange], _
	[-4843, 6735, " ", $vqrange], _
	[-5729, 6270, " ", $vqrange], _
	[-6614, 5805, " ", $vqrange], _
	[-6739, 4918, " ", $vqrange], _
	[-7635.3135, 4899, " ", $vqrange], _ ; auto
	[-6864, 4032, " ", $vqrange], _
	[-6772, 3979, " ", $vqrange], _
	[-6440, 3276, " ", $vqrange], _
	[-6108, 2572, " ", $vqrange], _
	[-5394, 1659, " ", $vqrange], _
	[-4355, 1206, " ", $vqrange], _
	[-3584, 1138, " ", $vqrange], _
	[-2539, 1385, " ", $vqrange], _
	[-2277.75, 1446.75, " ", $vqrange], _ ; auto
	[-2016.5, 1508.5, " ", $vqrange], _ ; auto
	[-1494, 1632, " ", $vqrange], _
	[-1491, 2807, " ", $vqrange], _
	[-1006, 3799, " ", $vqrange], _
	[-496, 4800, " ", $vqrange], _
	[-828, 4909, " ", $vqrange], _
	[-1219, 5993, " ", $vqrange], _
	[-2209, 7086, " ", $vqrange], _
	[-3361, 7077, " ", $vqrange], _
	[-4223, 6917, " ", $vqrange], _
	[-5167, 7362, " ", $vqrange] _
]

