#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: vendor/vanquish-bot/Maps/Proph_SouthernShiverpeaks/IceDome.au3
; Map: IceDome (id 87), geometry from MAP 0000046591.pmap
; Repaired 6 of 6 blocked segments by inserting 8 waypoints.
; Smoothed 33 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.

Global $aProph_SouthernShiverpeaks_IceDomeRoute01[60][2] = [ _
	[-4580, -5658], _
	[-5419.6667, -5068.3333], _ ; auto
	[-6259.3333, -4478.6667], _ ; auto
	[-7099, -3889], _
	[-7654, -3082], _ ; auto
	[-8209, -2275], _
	[-7558, -1512.5], _ ; auto
	[-6907, -750], _
	[-6995.5, 167.5], _ ; auto
	[-7084, 1085], _
	[-6816, 1248], _ ; auto
	[-6408, 1248], _ ; auto
	[-6204, 1248], _ ; auto
	[-6051, 1248], _ ; auto
	[-5898, 1248], _ ; auto
	[-5592, 1248], _ ; auto
	[-5388, 1248], _ ; auto
	[-5235, 1248], _ ; auto
	[-5082, 1248], _ ; auto
	[-4776, 1248], _ ; auto
	[-4572, 1248], _ ; auto
	[-4368, 1248], _ ; auto
	[-3552, 1248], _ ; auto
	[-3831, 1230], _
	[-4608, 2400], _ ; auto
	[-4262, 3600], _
	[-3674, 4349.5], _ ; auto
	[-3086, 5099], _
	[-2983, 6101.5], _ ; auto
	[-2880, 7104], _ ; auto
	[-2743, 7372], _
	[-1539.5, 7286], _ ; auto
	[-336, 7200], _ ; auto
	[230.5, 6696.5], _ ; auto
	[797, 6193], _
	[806.5, 5304.5], _ ; auto
	[816, 4416], _ ; auto
	[689, 3516], _ ; auto
	[562, 2616], _
	[1241, 1788], _ ; auto
	[1920, 960], _ ; auto
	[1484.5, 182.5], _ ; auto
	[1049, -595], _
	[2022.3333, -205.6667], _ ; auto
	[2995.6667, 183.6667], _ ; auto
	[3969, 573], _
	[4390, 1866.2667], _ ; auto
	[4811, 3159.5333], _ ; auto
	[5232, 4452.8], _ ; auto
	[5308.8, 5280], _ ; auto
	[5717, 5604], _
	[6436.75, 5064.5], _ ; auto
	[7156.5, 4525], _ ; auto
	[7635, 3729], _
	[7586, 2418.5], _ ; auto
	[7537, 1108], _
	[7073, -101], _
	[5970, -1117], _
	[6908.5, -2159], _ ; auto
	[7847, -3201] _
]

