#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_SouthernShiverpeaks/MineralSprings.au3
; Map: MineralSprings (id 96), geometry from MAP 0000046600.pmap
; Repaired 2 of 2 blocked segments by inserting 2 waypoints.
; Smoothed 8 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_SouthernShiverpeaks_MineralSpringsRoute01[254][4] = [ _
	[-20810, -9703, " ", $vqrange], _
	[-20491, -8464, " ", $vqrange], _
	[-20898, -7356, " ", $vqrange], _
	[-21304, -6247, " ", $vqrange], _
	[-22057, -5304, " ", $vqrange], _
	[-22809, -4360, " ", $vqrange], _
	[-23562, -3417, " ", $vqrange], _
	[-24282, -2193, " ", $vqrange], _
	[-25001, -969, " ", $vqrange], _
	[-24323, 58, " ", $vqrange], _
	[-23646, 1085, " ", $vqrange], _
	[-22884, 2132, " ", $vqrange], _
	[-21960, 2653, " ", $vqrange], _
	[-21037, 3174, " ", $vqrange], _
	[-20113, 3695, " ", $vqrange], _
	[-20348, 4979, " ", $vqrange], _
	[-20584, 6264, " ", $vqrange], _
	[-20819, 7548, " ", $vqrange], _
	[-20355, 8469, " ", $vqrange], _
	[-19891, 9390, " ", $vqrange], _
	[-18912, 9888, " ", $vqrange], _
	[-18019, 9974, " ", $vqrange], _
	[-16714, 9691, " ", $vqrange], _
	[-15408, 9408, " ", $vqrange], _
	[-14592, 8832, " ", $vqrange], _
	[-13776, 8256, " ", $vqrange], _
	[-13637, 7228, " ", $vqrange], _
	[-13392, 7392, " ", $vqrange], _
	[-12448, 7440, " ", $vqrange], _
	[-11976, 7464, " ", $vqrange], _
	[-11814, 7472, " ", $vqrange], _
	[-11504, 7488, " ", $vqrange], _
	[-10396, 8099, " ", $vqrange], _
	[-9288, 8710, " ", $vqrange], _
	[-8437, 8882, " ", $vqrange], _
	[-7586, 9053, " ", $vqrange], _
	[-6846, 9335, " ", $vqrange], _
	[-6105, 9617, " ", $vqrange], _
	[-5808, 8448, " ", $vqrange], _
	[-6418, 8273, " ", $vqrange], _
	[-6011, 7358, " ", $vqrange], _
	[-5604, 6442, " ", $vqrange], _
	[-5435, 6559, " ", $vqrange], _
	[-4617, 6566, " ", $vqrange], _
	[-3798, 6573, " ", $vqrange], _
	[-3334, 6319, " ", $vqrange], _
	[-3101, 6192, " ", $vqrange], _
	[-2869, 6065, " ", $vqrange], _
	[-2712, 6067, " ", $vqrange], _
	[-2498, 6070, " ", $vqrange], _
	[-2126, 6076, " ", $vqrange], _
	[-1384, 6087, " ", $vqrange], _
	[-179, 6448, " ", $vqrange], _
	[1025, 6810, " ", $vqrange], _
	[1664, 7725, " ", $vqrange], _
	[2201, 8670, " ", $vqrange], _
	[1738, 7472, " ", $vqrange], _
	[1276, 6274, " ", $vqrange], _
	[1519.7583, 5554.7583, " ", $vqrange], _ ; auto
	[1763.5166, 4835.5166, " ", $vqrange], _ ; auto
	[2674, 3722, " ", $vqrange], _
	[4071, 3985, " ", $vqrange], _
	[5467, 4249, " ", $vqrange], _
	[6864, 4512, " ", $vqrange], _
	[6881, 4780, " ", $vqrange], _
	[8004, 5375, " ", $vqrange], _
	[9127, 5970, " ", $vqrange], _
	[10250, 6564, " ", $vqrange], _
	[11374, 7159, " ", $vqrange], _
	[12497, 7754, " ", $vqrange], _
	[13620, 8349, " ", $vqrange], _
	[14444, 9216, " ", $vqrange], _
	[15268, 10083, " ", $vqrange], _
	[16455, 9841, " ", $vqrange], _
	[17642, 9599, " ", $vqrange], _
	[18828, 9358, " ", $vqrange], _
	[20015, 9116, " ", $vqrange], _
	[21202, 8874, " ", $vqrange], _
	[21776, 8724, " ", $vqrange], _
	[22062, 8650, " ", $vqrange], _
	[22277, 8594, " ", $vqrange], _
	[22430, 8554, " ", $vqrange], _
	[22582, 8514, " ", $vqrange], _
	[22734, 8475, " ", $vqrange], _
	[22887, 8435, " ", $vqrange], _
	[23039, 8395, " ", $vqrange], _
	[23209, 8351, " ", $vqrange], _
	[23496, 8276, " ", $vqrange], _
	[23534, 8352, " ", $vqrange], _
	[23930, 8352, " ", $vqrange], _
	[24128, 8352, " ", $vqrange], _
	[24283, 8352, " ", $vqrange], _
	[24438, 8352, " ", $vqrange], _
	[24593, 8352, " ", $vqrange], _
	[24856, 8352, " ", $vqrange], _ ; auto
	[25119, 8352, " ", $vqrange], _
	[25236, 7536, " ", $vqrange], _
	[25354, 6720, " ", $vqrange], _
	[24995, 6613, " ", $vqrange], _
	[25766, 6432, " ", $vqrange], _
	[26036, 5525, " ", $vqrange], _
	[25877, 4775, " ", $vqrange], _
	[24993, 3895, " ", $vqrange], _
	[23905, 3561, " ", $vqrange], _
	[23360, 2441, " ", $vqrange], _
	[22323, 1712, " ", $vqrange], _
	[21286, 983, " ", $vqrange], _
	[20973, -111, " ", $vqrange], _
	[21099, -217, " ", $vqrange], _
	[21217, -317, " ", $vqrange], _
	[21336, -416, " ", $vqrange], _
	[21454, -516, " ", $vqrange], _
	[21603, -642, " ", $vqrange], _
	[21730, -748, " ", $vqrange], _
	[21982, -960, " ", $vqrange], _
	[21640, -1502, " ", $vqrange], _
	[21712, -354, " ", $vqrange], _
	[21561, -322, " ", $vqrange], _
	[21413, -291, " ", $vqrange], _
	[21266, -260, " ", $vqrange], _
	[21103, -226, " ", $vqrange], _ ; auto
	[20940, -192, " ", $vqrange], _
	[21397, 1081, " ", $vqrange], _
	[21614, 1213, " ", $vqrange], _
	[22564, 1898, " ", $vqrange], _
	[23514, 2582, " ", $vqrange], _
	[23736, 3181, " ", $vqrange], _
	[23897, 3479, " ", $vqrange], _
	[25076, 3922, " ", $vqrange], _
	[26018, 5078, " ", $vqrange], _
	[25944, 5952, " ", $vqrange], _
	[25521, 6910, " ", $vqrange], _
	[25098, 7869, " ", $vqrange], _
	[24676, 8827, " ", $vqrange], _
	[24284, 8839, " ", $vqrange], _
	[24438, 8383, " ", $vqrange], _
	[24278, 8383, " ", $vqrange], _
	[24058, 8383, " ", $vqrange], _
	[23678, 8383, " ", $vqrange], _
	[23298, 8383, " ", $vqrange], _
	[23144, 8383, " ", $vqrange], _
	[22918, 8383, " ", $vqrange], _
	[22741, 8461, " ", $vqrange], _
	[22564, 8539, " ", $vqrange], _
	[22402, 8575, " ", $vqrange], _
	[22133, 8634, " ", $vqrange], _
	[21702, 8730, " ", $vqrange], _
	[20840, 8920, " ", $vqrange], _
	[19978, 9110, " ", $vqrange], _
	[19116, 9301, " ", $vqrange], _
	[18320, 9513, " ", $vqrange], _
	[17523, 9725, " ", $vqrange], _
	[16523, 9764, " ", $vqrange], _
	[15524, 9804, " ", $vqrange], _
	[14524, 9843, " ", $vqrange], _
	[14959, 8569, " ", $vqrange], _
	[15394, 7295, " ", $vqrange], _
	[15828, 6021, " ", $vqrange], _
	[16263, 4747, " ", $vqrange], _
	[16698, 3473, " ", $vqrange], _
	[16509, 2696, " ", $vqrange], _
	[16320, 1920, " ", $vqrange], _
	[15808, 1024, " ", $vqrange], _
	[15296, 128, " ", $vqrange], _
	[14784, -768, " ", $vqrange], _
	[15028, -953, " ", $vqrange], _
	[15318, -2396, " ", $vqrange], _
	[15608, -3840, " ", $vqrange], _
	[14880, -5088, " ", $vqrange], _
	[15326, -5828, " ", $vqrange], _
	[15773, -6569, " ", $vqrange], _
	[15782, -7556, " ", $vqrange], _
	[15792, -8544, " ", $vqrange], _
	[15024, -9042, " ", $vqrange], _
	[14257, -9540, " ", $vqrange], _
	[13608, -8994, " ", $vqrange], _
	[13487, -8892, " ", $vqrange], _
	[13296, -8832, " ", $vqrange], _ ; auto
	[13344, -8811, " ", $vqrange], _
	[13152, -8629.5, " ", $vqrange], _ ; auto
	[12960, -8448, " ", $vqrange], _
	[12720, -8256, " ", $vqrange], _
	[11862, -7931, " ", $vqrange], _
	[10734, -7795, " ", $vqrange], _
	[9606, -7660, " ", $vqrange], _
	[8478, -7524, " ", $vqrange], _
	[7039, -7508, " ", $vqrange], _
	[7394, -6290, " ", $vqrange], _
	[7748, -5073, " ", $vqrange], _
	[6869, -4180, " ", $vqrange], _
	[5990, -3288, " ", $vqrange], _
	[5110, -2396, " ", $vqrange], _
	[4231, -1503, " ", $vqrange], _
	[3001, -1855, " ", $vqrange], _
	[1771, -2207, " ", $vqrange], _
	[540, -2560, " ", $vqrange], _
	[-690, -2912, " ", $vqrange], _
	[-1920, -3264, " ", $vqrange], _
	[-902, -3304, " ", $vqrange], _
	[117, -3343, " ", $vqrange], _
	[312, -4105, " ", $vqrange], _
	[507, -4867, " ", $vqrange], _
	[95, -6300, " ", $vqrange], _
	[-317, -7732, " ", $vqrange], _
	[-533, -7720, " ", $vqrange], _
	[-695, -7711, " ", $vqrange], _
	[-857, -7702, " ", $vqrange], _
	[-1019.5, -7693, " ", $vqrange], _ ; auto
	[-1182, -7684, " ", $vqrange], _
	[-2046, -7635, " ", $vqrange], _
	[-2262, -7623, " ", $vqrange], _
	[-2424, -7614, " ", $vqrange], _
	[-2586, -7605, " ", $vqrange], _
	[-2748, -7596, " ", $vqrange], _
	[-2910, -7586, " ", $vqrange], _
	[-3775, -7538, " ", $vqrange], _
	[-4159, -6149, " ", $vqrange], _
	[-4543, -4760, " ", $vqrange], _
	[-4892, -3586, " ", $vqrange], _
	[-5240, -2413, " ", $vqrange], _
	[-6342, -1604, " ", $vqrange], _
	[-7445, -795, " ", $vqrange], _
	[-8547, 14, " ", $vqrange], _
	[-9650, 823, " ", $vqrange], _
	[-10752, 1632, " ", $vqrange], _
	[-11180, 1656, " ", $vqrange], _
	[-12125, 942, " ", $vqrange], _
	[-13070, 227, " ", $vqrange], _
	[-13956, -342, " ", $vqrange], _
	[-14841, -910, " ", $vqrange], _
	[-13920, -642, " ", $vqrange], _
	[-13000, -373, " ", $vqrange], _
	[-12587, -1433, " ", $vqrange], _
	[-12173, -2492, " ", $vqrange], _
	[-11760, -3552, " ", $vqrange], _
	[-11325, -3876, " ", $vqrange], _
	[-10630, -4722, " ", $vqrange], _
	[-9936, -5568, " ", $vqrange], _
	[-9739, -6860, " ", $vqrange], _
	[-9541, -8152, " ", $vqrange], _
	[-9344, -9444, " ", $vqrange], _
	[-10120, -9570, " ", $vqrange], _
	[-10508, -9633, " ", $vqrange], _ ; auto
	[-10702, -9664.5, " ", $vqrange], _ ; auto
	[-10896, -9696, " ", $vqrange], _
	[-12310, -10122, " ", $vqrange], _
	[-13723, -10548, " ", $vqrange], _
	[-14470, -10362, " ", $vqrange], _
	[-15216, -10176, " ", $vqrange], _
	[-15744, -9408, " ", $vqrange], _
	[-16272, -8640, " ", $vqrange], _
	[-16656, -8544, " ", $vqrange], _ ; auto
	[-17088, -8474, " ", $vqrange], _
	[-17905, -8309, " ", $vqrange] _
]

