#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: vendor/vanquish-bot/Maps/Proph_SouthernShiverpeaks/SpearheadPeak.au3
; Map: SpearheadPeak (id 93), geometry from none
; Imported vendor vanquish coordinates; Spearhead Peak pmap may be missing.
; Spliced 30 off-path log point(s) from map_waypoints_93.csv / pathfinder_stuck_93.csv / combat_coords_93.
; Navmesh repair skipped: mapinfo has no pmap for map 93.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_SouthernShiverpeaks_SpearheadPeakRoute01[151][4] = [ _
	[7547, -25881, " ", $vqrange], _
	[7443, -25155, " ", $vqrange], _
	[6856, -24163, " ", $vqrange], _
	[6382, -23762, " ", $vqrange], _
	[6909, -22441, " ", $vqrange], _
	[5907, -22130, " ", $vqrange], _
	[5236, -21939, " ", $vqrange], _
	[4059, -21533, " ", $vqrange], _
	[1979, -21361, " ", $vqrange], _
	[3425, -22010, " ", $vqrange], _
	[3432, -22666, " ", $vqrange], _
	[2666, -23354, " ", $vqrange], _
	[1060, -24200, " ", $vqrange], _
	[-775, -24383, " ", $vqrange], _
	[-1163.59, -23699.01, " ", $vqrange], _
	[-1757, -24035, " ", $vqrange], _
	[-2301, -23203, " ", $vqrange], _
	[-1753, -22679.57, " ", $vqrange], _
	[-2413, -22464, " ", $vqrange], _
	[-2349, -20969, " ", $vqrange], _
	[-2327, -20610, " ", $vqrange], _
	[-2363, -20048, " ", $vqrange], _
	[-1595, -16834, " ", $vqrange], _
	[-149, -15189, " ", $vqrange], _
	[522, -14406, " ", $vqrange], _
	[2323, -12787, " ", $vqrange], _
	[3677, -11082, " ", $vqrange], _
	[4168, -10351, " ", $vqrange], _
	[3901.24, -9606.62, " ", $vqrange], _
	[6164, -9754, " ", $vqrange], _
	[7850, -8623, " ", $vqrange], _
	[8142, -8460, " ", $vqrange], _
	[9439, -8195, " ", $vqrange], _
	[9959, -8170, " ", $vqrange], _
	[10272, -8298, " ", $vqrange], _
	[11375, -8173, " ", $vqrange], _
	[11757, -8872, " ", $vqrange], _
	[11809, -10308, " ", $vqrange], _
	[11598, -10977, " ", $vqrange], _
	[11257, -12346, " ", $vqrange], _
	[11097, -13656, " ", $vqrange], _
	[10589, -14462, " ", $vqrange], _
	[9983, -14922, " ", $vqrange], _
	[8657.62, -14729.8, " ", $vqrange], _
	[10732, -13698, " ", $vqrange], _
	[9220.78, -11264.56, " ", $vqrange], _
	[10144.17, -9780.66, " ", $vqrange], _
	[10125.05, -9554.95, " ", $vqrange], _
	[11348, -8130, " ", $vqrange], _
	[10754, -7286, " ", $vqrange], _
	[10058, -4718, " ", $vqrange], _
	[8889, -3731, " ", $vqrange], _
	[7724, -3316, " ", $vqrange], _
	[7371, -3085, " ", $vqrange], _
	[6497, -1914, " ", $vqrange], _
	[4764, -916, " ", $vqrange], _
	[3749, -699, " ", $vqrange], _
	[2573, -1037, " ", $vqrange], _
	[1182, -979, " ", $vqrange], _
	[1454, -81, " ", $vqrange], _
	[2370, 761, " ", $vqrange], _
	[2942, 1875, " ", $vqrange], _
	[2509, 3170, " ", $vqrange], _
	[2459, 4362, " ", $vqrange], _
	[2774.55, 4957.18, " ", $vqrange], _
	[2504.66, 5700.32, " ", $vqrange], _
	[1881, 4283, " ", $vqrange], _
	[457, 3664, " ", $vqrange], _
	[-918, 3473, " ", $vqrange], _
	[-1596, 4270, " ", $vqrange], _
	[-2251, 5089, " ", $vqrange], _
	[-2572, 5430, " ", $vqrange], _
	[-2591.89, 6721.31, " ", $vqrange], _
	[-2828.01, 6635.39, " ", $vqrange], _
	[-2994, 5274, " ", $vqrange], _
	[-3955, 4793, " ", $vqrange], _
	[-5580, 5265, " ", $vqrange], _
	[-6093.25, 4327.62, " ", $vqrange], _
	[-6554, 5135, " ", $vqrange], _
	[-8236, 5414, " ", $vqrange], _
	[-9182, 5820, " ", $vqrange], _
	[-10246, 5487, " ", $vqrange], _
	[-10369, 5121, " ", $vqrange], _
	[-12060, 4780, " ", $vqrange], _
	[-12048.77, 596.11, " ", $vqrange], _
	[-14392, 666, " ", $vqrange], _
	[-12163, 5046, " ", $vqrange], _
	[-12523, 5770, " ", $vqrange], _
	[-13152, 8023, " ", $vqrange], _
	[-13081, 9078, " ", $vqrange], _
	[-13043, 9344, " ", $vqrange], _
	[-12897, 9674, " ", $vqrange], _
	[-12956, 10249, " ", $vqrange], _
	[-12329, 12101, " ", $vqrange], _
	[-12276.13, 9704.5, " ", $vqrange], _
	[-13011, 9048, " ", $vqrange], _
	[-13129, 7311, " ", $vqrange], _
	[-12841, 6340, " ", $vqrange], _
	[-11847, 5401, " ", $vqrange], _
	[-10541, 4848, " ", $vqrange], _
	[-10076, 3909, " ", $vqrange], _
	[-9465, 2654, " ", $vqrange], _
	[-9234, 1467, " ", $vqrange], _
	[-6897, 127, " ", $vqrange], _
	[-5231, -807, " ", $vqrange], _
	[-4769, -1285, " ", $vqrange], _
	[-5930.82, -2109.74, " ", $vqrange], _
	[-6422.35, -2641.9, " ", $vqrange], _
	[-10419.88, -990.99, " ", $vqrange], _
	[-10058.01, -1419.28, " ", $vqrange], _
	[-8659.19, -2703.83, " ", $vqrange], _
	[-8105.14, -3825.16, " ", $vqrange], _
	[-8008.02, -4657.22, " ", $vqrange], _
	[-6847.14, -3727.93, " ", $vqrange], _
	[-5451.66, -2609.82, " ", $vqrange], _
	[-5354.65, -3036.55, " ", $vqrange], _
	[-4473, -4281, " ", $vqrange], _
	[-5353, -4131, " ", $vqrange], _
	[-4974, -4449, " ", $vqrange], _
	[-4790, -4737, " ", $vqrange], _
	[-4634, -5829, " ", $vqrange], _
	[-4933, -6184, " ", $vqrange], _
	[-4238.3, -6889.44, " ", $vqrange], _
	[-5705, -8053, " ", $vqrange], _
	[-5754, -8838, " ", $vqrange], _
	[-5675.18, -9606.83, " ", $vqrange], _
	[-7465, -7977, " ", $vqrange], _
	[-9510, -8759, " ", $vqrange], _
	[-8799, -7647, " ", $vqrange], _
	[-10214, -8605, " ", $vqrange], _
	[-10634.14, -9178.88, " ", $vqrange], _
	[-10739, -7478, " ", $vqrange], _
	[-11056, -8069, " ", $vqrange], _
	[-12446, -8594, " ", $vqrange], _
	[-12714, -9526, " ", $vqrange], _
	[-12845, -10052, " ", $vqrange], _
	[-13110, -12824, " ", $vqrange], _
	[-12964, -14425, " ", $vqrange], _
	[-12686, -16653, " ", $vqrange], _
	[-11716, -17194, " ", $vqrange], _
	[-11098, -17593, " ", $vqrange], _
	[-10447, -18371, " ", $vqrange], _
	[-8631, -19331, " ", $vqrange], _
	[-10109, -19370, " ", $vqrange], _
	[-10262, -19966, " ", $vqrange], _
	[-10157, -20649, " ", $vqrange], _
	[-10589, -21278, " ", $vqrange], _
	[-11323.83, -21763.54, " ", $vqrange], _
	[-7936.64, -22774.04, " ", $vqrange], _
	[-7321.23, -23298.38, " ", $vqrange], _
	[-8791, -22860, " ", $vqrange] _
]

