#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: vendor/vanquish-bot/Maps/Proph_SouthernShiverpeaks/TascasDemise.au3
; Map: TascasDemise (id 92), geometry from MAP 0000046597.pmap
; Repaired 10 of 10 blocked segments by inserting 14 waypoints.
; Smoothed 39 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.

Global $aProph_SouthernShiverpeaks_TascasDemiseRoute01[76][2] = [ _
	[-7318, 20765], _
	[-8721.6855, 20928], _ ; auto
	[-7854.7695, 20928], _ ; auto
	[-6987.8535, 20928], _ ; auto
	[-6825.3068, 20928], _ ; auto
	[-6662.76, 20928], _ ; auto
	[-6500.2133, 20928], _ ; auto
	[-6337.6665, 20928], _ ; auto
	[-6175.1198, 20928], _ ; auto
	[-6012.573, 20928], _ ; auto
	[-5850.0262, 20928], _ ; auto
	[-5687.4795, 20928], _ ; auto
	[-5254.0215, 20928], _ ; auto
	[-4967, 20426], _
	[-4403.5, 19717], _ ; auto
	[-3840, 19008], _ ; auto
	[-2959.6667, 18359], _ ; auto
	[-2079.3333, 17710], _ ; auto
	[-1199, 17061], _
	[-332.5, 17215], _ ; auto
	[534, 17369], _
	[723, 18620.5], _ ; auto
	[912, 19872], _ ; auto
	[1271, 20404], _
	[1472, 20928], _ ; auto
	[2628, 21072], _ ; auto
	[3784, 21216], _ ; auto
	[4940, 21360], _ ; auto
	[6096, 21504], _ ; auto
	[6097, 21830], _
	[5784.5, 22963], _ ; auto
	[5472, 24096], _ ; auto
	[5013.5, 24863], _ ; auto
	[4555, 25630], _
	[4131, 27041], _
	[4882.5, 27786.5], _ ; auto
	[5634, 28532], _
	[6247, 27996], _
	[6634.5918, 27324], _ ; auto
	[7022.1836, 26652], _ ; auto
	[7535, 26067], _
	[8303.4642, 26327.5], _ ; auto
	[9071.9285, 26588], _ ; auto
	[9791.9642, 26611], _ ; auto
	[9949.4721, 26616.0312], _ ; auto
	[10101.3546, 26620.8828], _ ; auto
	[10512, 26634], _
	[11208, 26277], _ ; auto
	[11904, 25920], _ ; auto
	[12153.2642, 25164], _ ; auto
	[12902, 24369], _
	[12939.6667, 23349], _ ; auto
	[12977.3333, 22329], _ ; auto
	[13015, 21309], _
	[12324.6667, 20464.6667], _ ; auto
	[11634.3333, 19620.3333], _ ; auto
	[10944, 18776], _
	[10164.75, 17616], _ ; auto
	[9385.5, 16456], _ ; auto
	[9210, 15807], _
	[8611, 15439], _
	[7584, 16416], _ ; auto
	[7336, 17215], _
	[6205, 17276], _
	[7327.5, 17206], _ ; auto
	[7680, 16320], _ ; auto
	[8441, 15381], _
	[7604.5, 14938.5], _ ; auto
	[6768, 14496], _ ; auto
	[6021.5, 14398], _ ; auto
	[5275, 14300], _
	[4402, 14433.5], _ ; auto
	[3529, 14567], _
	[2744.6667, 15351.3333], _ ; auto
	[1960.3333, 16135.6667], _ ; auto
	[1176, 16920] _
]

