#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_SouthernShiverpeaks/TascasDemise.au3
; Map: TascasDemise (id 92), geometry from MAP 0000046597.pmap
; Repaired 0 of 0 blocked segments by inserting 0 waypoints.
; Smoothed 5 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_SouthernShiverpeaks_TascasDemiseRoute01[81][4] = [ _
	[-7318, 20765, " ", $vqrange], _
	[-8722, 20928, " ", $vqrange], _
	[-7855, 20928, " ", $vqrange], _
	[-6988, 20928, " ", $vqrange], _
	[-6825, 20928, " ", $vqrange], _
	[-6663, 20928, " ", $vqrange], _
	[-6500, 20928, " ", $vqrange], _
	[-6338, 20928, " ", $vqrange], _
	[-6175, 20928, " ", $vqrange], _
	[-6013, 20928, " ", $vqrange], _
	[-5850, 20928, " ", $vqrange], _
	[-5687, 20928, " ", $vqrange], _
	[-5254, 20928, " ", $vqrange], _
	[-4967, 20426, " ", $vqrange], _
	[-4404, 19717, " ", $vqrange], _
	[-3840, 19008, " ", $vqrange], _
	[-2960, 18359, " ", $vqrange], _
	[-2079, 17710, " ", $vqrange], _
	[-1199, 17061, " ", $vqrange], _
	[-332, 17215, " ", $vqrange], _
	[534, 17369, " ", $vqrange], _
	[723, 18620, " ", $vqrange], _
	[912, 19872, " ", $vqrange], _
	[1271, 20404, " ", $vqrange], _
	[1472, 20928, " ", $vqrange], _
	[2628, 21072, " ", $vqrange], _
	[3784, 21216, " ", $vqrange], _
	[4362, 21288, " ", $vqrange], _ ; auto
	[4651, 21324, " ", $vqrange], _ ; auto
	[4940, 21360, " ", $vqrange], _
	[6096, 21504, " ", $vqrange], _
	[6097, 21830, " ", $vqrange], _
	[5784, 22963, " ", $vqrange], _
	[5472, 24096, " ", $vqrange], _
	[5014, 24863, " ", $vqrange], _
	[4944, 25056, " ", $vqrange], _ ; auto
	[4752, 25152, " ", $vqrange], _ ; auto
	[4555, 25630, " ", $vqrange], _
	[4131, 27041, " ", $vqrange], _
	[4882, 27786, " ", $vqrange], _
	[5634, 28532, " ", $vqrange], _
	[6247, 27996, " ", $vqrange], _
	[6635, 27324, " ", $vqrange], _
	[7022, 26652, " ", $vqrange], _
	[7535, 26067, " ", $vqrange], _
	[8303, 26328, " ", $vqrange], _
	[9072, 26588, " ", $vqrange], _
	[9792, 26611, " ", $vqrange], _
	[9949, 26616, " ", $vqrange], _
	[10101, 26621, " ", $vqrange], _
	[10512, 26634, " ", $vqrange], _
	[11208, 26277, " ", $vqrange], _
	[11904, 25920, " ", $vqrange], _
	[12153, 25164, " ", $vqrange], _
	[12474.5, 24882, " ", $vqrange], _ ; auto
	[12902, 24369, " ", $vqrange], _
	[12940, 23349, " ", $vqrange], _
	[12977, 22329, " ", $vqrange], _
	[13015, 21309, " ", $vqrange], _
	[12325, 20465, " ", $vqrange], _
	[11634, 19620, " ", $vqrange], _
	[10944, 18776, " ", $vqrange], _
	[10165, 17616, " ", $vqrange], _
	[9386, 16456, " ", $vqrange], _
	[9210, 15807, " ", $vqrange], _
	[8611, 15439, " ", $vqrange], _
	[7584, 16416, " ", $vqrange], _
	[7336, 17215, " ", $vqrange], _
	[6205, 17276, " ", $vqrange], _
	[7328, 17206, " ", $vqrange], _
	[7680, 16320, " ", $vqrange], _
	[8441, 15381, " ", $vqrange], _
	[7604, 14938, " ", $vqrange], _
	[6768, 14496, " ", $vqrange], _
	[6022, 14398, " ", $vqrange], _
	[5275, 14300, " ", $vqrange], _
	[4402, 14434, " ", $vqrange], _
	[3529, 14567, " ", $vqrange], _
	[2745, 15351, " ", $vqrange], _
	[1960, 16136, " ", $vqrange], _
	[1176, 16920, " ", $vqrange] _
]

