#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_ShingJeaIsland/HaijuLagoon.au3
; Map: HaijuLagoon (id 237), geometry from MAP 0000157079.pmap
; Repaired 1 of 1 blocked segments by inserting 1 waypoints.
; Smoothed 14 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_ShingJeaIsland_HaijuLagoonRoute01[289][4] = [ _
	[14484, -18600, " ", $vqrange], _
	[14952, -17856, " ", $vqrange], _
	[15844, -16848, " ", $vqrange], _
	[16736, -15840, " ", $vqrange], _
	[16232, -14877, " ", $vqrange], _
	[16548, -14784, " ", $vqrange], _
	[15882, -14760, " ", $vqrange], _ ; auto
	[15731.1094, -14754.5625, " ", $vqrange], _ ; auto
	[15549, -14748, " ", $vqrange], _ ; auto
	[15216, -14736, " ", $vqrange], _
	[14550, -14712, " ", $vqrange], _
	[14217, -14700, " ", $vqrange], _
	[14061, -14694, " ", $vqrange], _
	[13884, -14688, " ", $vqrange], _
	[13778, -14547, " ", $vqrange], _
	[13673, -14406, " ", $vqrange], _
	[13462, -14123, " ", $vqrange], _
	[13040, -13558, " ", $vqrange], _
	[12196, -12428, " ", $vqrange], _
	[11396, -11394, " ", $vqrange], _
	[10597, -10359, " ", $vqrange], _
	[9797, -9325, " ", $vqrange], _
	[9006, -10088, " ", $vqrange], _
	[8216, -10852, " ", $vqrange], _
	[7157, -11875, " ", $vqrange], _
	[6099, -12897, " ", $vqrange], _
	[5040, -13920, " ", $vqrange], _
	[5635, -14835, " ", $vqrange], _
	[6230, -15751, " ", $vqrange], _
	[6826, -16666, " ", $vqrange], _
	[8225, -16686, " ", $vqrange], _
	[9624, -16705, " ", $vqrange], _
	[11023, -16725, " ", $vqrange], _
	[12136, -17578, " ", $vqrange], _
	[13248, -18432, " ", $vqrange], _
	[13585, -18592, " ", $vqrange], _
	[12360, -17744, " ", $vqrange], _
	[11136, -16896, " ", $vqrange], _
	[10327, -16720, " ", $vqrange], _
	[9518, -16544, " ", $vqrange], _
	[8719, -15856, " ", $vqrange], _
	[7920, -15168, " ", $vqrange], _
	[7691, -14408, " ", $vqrange], _
	[7972, -15512, " ", $vqrange], _
	[8254, -16617, " ", $vqrange], _
	[7134.5, -16582, " ", $vqrange], _ ; auto
	[6015, -16547, " ", $vqrange], _
	[4896, -16512, " ", $vqrange], _
	[5983, -16504, " ", $vqrange], _
	[7070, -16496, " ", $vqrange], _
	[5976, -16365, " ", $vqrange], _
	[4883, -16235, " ", $vqrange], _
	[3789, -16104, " ", $vqrange], _
	[3062, -16740, " ", $vqrange], _
	[2334, -17376, " ", $vqrange], _
	[1823, -17376, " ", $vqrange], _
	[1567, -17376, " ", $vqrange], _
	[1375, -17376, " ", $vqrange], _
	[1223, -17376, " ", $vqrange], _
	[1055, -17376, " ", $vqrange], _
	[800, -17376, " ", $vqrange], _
	[288, -17376, " ", $vqrange], _
	[220, -16995, " ", $vqrange], _
	[-889, -16585, " ", $vqrange], _
	[-1999, -16174, " ", $vqrange], _
	[-3108, -15764, " ", $vqrange], _
	[-3906, -15354, " ", $vqrange], _
	[-4705, -14943, " ", $vqrange], _
	[-3820, -14172, " ", $vqrange], _
	[-2934, -13400, " ", $vqrange], _
	[-2049, -12629, " ", $vqrange], _
	[-2893, -11944, " ", $vqrange], _
	[-3624, -11856, " ", $vqrange], _ ; auto
	[-3378, -11814, " ", $vqrange], _ ; auto
	[-3132, -11772, " ", $vqrange], _
	[-3315, -11601, " ", $vqrange], _
	[-3736, -11258, " ", $vqrange], _
	[-3855, -11162, " ", $vqrange], _
	[-3974, -11066, " ", $vqrange], _
	[-4092, -10969, " ", $vqrange], _
	[-4211, -10873, " ", $vqrange], _
	[-4369, -10745, " ", $vqrange], _
	[-4580, -10573, " ", $vqrange], _
	[-5424, -9888, " ", $vqrange], _
	[-4902, -10370, " ", $vqrange], _
	[-5328, -11328, " ", $vqrange], _
	[-5748, -11328, " ", $vqrange], _
	[-5899, -11328, " ", $vqrange], _
	[-6168, -11328, " ", $vqrange], _
	[-6303, -11190, " ", $vqrange], _
	[-6438, -11053, " ", $vqrange], _
	[-6288, -10944, " ", $vqrange], _
	[-6840, -9936, " ", $vqrange], _
	[-7392, -8928, " ", $vqrange], _
	[-6526, -8596, " ", $vqrange], _
	[-5661, -8264, " ", $vqrange], _
	[-4602, -8022, " ", $vqrange], _
	[-3543, -7779, " ", $vqrange], _
	[-2484, -7537, " ", $vqrange], _
	[-3298, -7584, " ", $vqrange], _
	[-3757, -7584, " ", $vqrange], _
	[-3930, -7584, " ", $vqrange], _
	[-4080, -7584, " ", $vqrange], _
	[-4231, -7584, " ", $vqrange], _
	[-4382, -7584, " ", $vqrange], _
	[-4561, -7584, " ", $vqrange], _
	[-5136, -7584, " ", $vqrange], _
	[-6288, -7056, " ", $vqrange], _
	[-7440, -6528, " ", $vqrange], _
	[-7200, -6323, " ", $vqrange], _
	[-6408, -5922, " ", $vqrange], _
	[-5616, -5520, " ", $vqrange], _
	[-6144, -4704, " ", $vqrange], _
	[-6885, -4272, " ", $vqrange], _
	[-7627, -3840, " ", $vqrange], _
	[-8089, -2895, " ", $vqrange], _
	[-7004, -2449, " ", $vqrange], _
	[-5920, -2003, " ", $vqrange], _
	[-4835, -1557, " ", $vqrange], _
	[-6240, -1536, " ", $vqrange], _ ; auto
	[-6128, -1402, " ", $vqrange], _
	[-6289.625, -1382.75, " ", $vqrange], _ ; auto
	[-6451.25, -1363.5, " ", $vqrange], _ ; auto
	[-6774.5, -1325, " ", $vqrange], _ ; auto
	[-7421, -1248, " ", $vqrange], _
	[-7729, -419, " ", $vqrange], _
	[-8037, 410, " ", $vqrange], _
	[-8050, 1501, " ", $vqrange], _
	[-8064, 2592, " ", $vqrange], _
	[-7032, 3158, " ", $vqrange], _
	[-6001, 3725, " ", $vqrange], _
	[-6960, 4694, " ", $vqrange], _
	[-7920, 5664, " ", $vqrange], _
	[-8814, 5841, " ", $vqrange], _
	[-9399, 5128, " ", $vqrange], _
	[-9984, 4416, " ", $vqrange], _
	[-9888, 4224, " ", $vqrange], _
	[-10627, 4224, " ", $vqrange], _
	[-10997, 4224, " ", $vqrange], _
	[-11147, 4224, " ", $vqrange], _
	[-11297, 4224, " ", $vqrange], _
	[-12071, 4224, " ", $vqrange], _ ; auto
	[-12845, 4224, " ", $vqrange], _
	[-12673, 4476, " ", $vqrange], _
	[-12783, 5480, " ", $vqrange], _
	[-12893, 6484, " ", $vqrange], _
	[-13004, 7488, " ", $vqrange], _
	[-12318, 8345, " ", $vqrange], _
	[-11633, 9202, " ", $vqrange], _
	[-12452, 7988, " ", $vqrange], _
	[-13270, 6773, " ", $vqrange], _
	[-14089, 5559, " ", $vqrange], _
	[-13410, 6756, " ", $vqrange], _
	[-12731, 7952, " ", $vqrange], _
	[-12052, 9149, " ", $vqrange], _
	[-11373, 10346, " ", $vqrange], _
	[-10694, 11542, " ", $vqrange], _
	[-10015, 12739, " ", $vqrange], _
	[-8885, 13274, " ", $vqrange], _
	[-7756, 13810, " ", $vqrange], _
	[-6626, 14345, " ", $vqrange], _
	[-6771, 14656, " ", $vqrange], _
	[-5403, 15030, " ", $vqrange], _
	[-4034, 15403, " ", $vqrange], _
	[-3680, 15999, " ", $vqrange], _
	[-2584, 16784, " ", $vqrange], _
	[-1488, 17568, " ", $vqrange], _
	[-2480, 17741, " ", $vqrange], _
	[-3471, 17914, " ", $vqrange], _
	[-2402, 18005, " ", $vqrange], _
	[-1332, 18097, " ", $vqrange], _
	[-263, 18188, " ", $vqrange], _
	[-646, 16982, " ", $vqrange], _
	[-1030, 15775, " ", $vqrange], _
	[-656, 15241, " ", $vqrange], _
	[455, 14669, " ", $vqrange], _
	[1566, 14096, " ", $vqrange], _
	[2677, 13524, " ", $vqrange], _
	[3479, 12983, " ", $vqrange], _
	[4281, 12442, " ", $vqrange], _
	[4572, 11334, " ", $vqrange], _
	[4862, 10225, " ", $vqrange], _
	[5152, 9116, " ", $vqrange], _
	[5443, 8008, " ", $vqrange], _
	[5855, 6578, " ", $vqrange], _
	[6663, 5655, " ", $vqrange], _
	[7043, 5650, " ", $vqrange], _
	[7296, 6054, " ", $vqrange], _
	[8434, 6128, " ", $vqrange], _
	[9572, 6201, " ", $vqrange], _
	[10710, 6275, " ", $vqrange], _
	[9733, 7192, " ", $vqrange], _
	[9056, 7931, " ", $vqrange], _
	[8379, 8670, " ", $vqrange], _
	[9228, 7512, " ", $vqrange], _
	[10020.8552, 6978, " ", $vqrange], _ ; auto
	[10813.7104, 6444, " ", $vqrange], _ ; auto
	[10077, 6354, " ", $vqrange], _
	[10926, 5196, " ", $vqrange], _
	[11775, 4038, " ", $vqrange], _
	[12624, 2880, " ", $vqrange], _
	[12676, 2298, " ", $vqrange], _
	[11619, 1468, " ", $vqrange], _
	[10561, 638, " ", $vqrange], _
	[9504, -192, " ", $vqrange], _
	[8652, -334, " ", $vqrange], _
	[9640, -583, " ", $vqrange], _
	[10629, -833, " ", $vqrange], _
	[11617, -1082, " ", $vqrange], _
	[12358, -1269, " ", $vqrange], _
	[13100, -1456, " ", $vqrange], _
	[13841, -1643, " ", $vqrange], _
	[14026, -1690, " ", $vqrange], _
	[14188, -1731, " ", $vqrange], _
	[14350, -1772, " ", $vqrange], _
	[14582, -1830, " ", $vqrange], _
	[14908, -1828, " ", $vqrange], _
	[15072, -1828, " ", $vqrange], _
	[15225, -1827, " ", $vqrange], _
	[15378, -1826, " ", $vqrange], _
	[15531, -1826, " ", $vqrange], _
	[15684, -1825, " ", $vqrange], _
	[15888, -1824, " ", $vqrange], _
	[16047, -1744, " ", $vqrange], _
	[16272, -1632, " ", $vqrange], _
	[16191, -1183, " ", $vqrange], _
	[16183, -1470, " ", $vqrange], _
	[16176, -1728, " ", $vqrange], _
	[15888, -1824, " ", $vqrange], _
	[15714, -1824, " ", $vqrange], _
	[15562, -1824, " ", $vqrange], _
	[15410, -1824, " ", $vqrange], _
	[15257, -1824, " ", $vqrange], _
	[15066.75, -1824, " ", $vqrange], _ ; auto
	[14876.5, -1824, " ", $vqrange], _ ; auto
	[14496, -1824, " ", $vqrange], _
	[14204, -1745, " ", $vqrange], _
	[13946, -1675, " ", $vqrange], _
	[13396, -1526, " ", $vqrange], _
	[12297, -1228, " ", $vqrange], _
	[11198, -930, " ", $vqrange], _
	[10098, -632, " ", $vqrange], _
	[8985, 11, " ", $vqrange], _
	[7873, 654, " ", $vqrange], _
	[6760, 1297, " ", $vqrange], _
	[5881, 517, " ", $vqrange], _
	[5002, -264, " ", $vqrange], _
	[4124, -1044, " ", $vqrange], _
	[3245, -1824, " ", $vqrange], _
	[4166, -2330, " ", $vqrange], _
	[5086, -2837, " ", $vqrange], _
	[6007, -3343, " ", $vqrange], _
	[5404, -4572, " ", $vqrange], _
	[4801, -5800, " ", $vqrange], _
	[4480, -4731, " ", $vqrange], _
	[4159, -3662, " ", $vqrange], _
	[3838, -2593, " ", $vqrange], _
	[3472, -1377, " ", $vqrange], _
	[3106, -162, " ", $vqrange], _
	[2740, 1054, " ", $vqrange], _
	[2374, 2270, " ", $vqrange], _
	[1633, 1720, " ", $vqrange], _
	[892, 1171, " ", $vqrange], _
	[-222, 1548, " ", $vqrange], _
	[-1336, 1925, " ", $vqrange], _
	[-2608, 2528, " ", $vqrange], _
	[-3879, 3130, " ", $vqrange], _
	[-3234, 4076, " ", $vqrange], _
	[-2589, 5021, " ", $vqrange], _
	[-1944, 5966, " ", $vqrange], _
	[-1299, 6912, " ", $vqrange], _
	[-2051, 7005, " ", $vqrange], _
	[-734, 7270, " ", $vqrange], _
	[582, 7534, " ", $vqrange], _
	[1899, 7799, " ", $vqrange], _
	[3216, 8064, " ", $vqrange], _
	[1881, 8544, " ", $vqrange], _
	[546, 9024, " ", $vqrange], _
	[-947, 9030, " ", $vqrange], _
	[-2441, 9036, " ", $vqrange], _
	[-3934, 9042, " ", $vqrange], _
	[-5427, 9048, " ", $vqrange], _
	[-4087, 9240, " ", $vqrange], _
	[-2748, 9433, " ", $vqrange], _
	[-1408, 9626, " ", $vqrange], _
	[-68, 9818, " ", $vqrange], _
	[1200, 9156, " ", $vqrange], _
	[2468, 8493, " ", $vqrange], _
	[3736, 7831, " ", $vqrange] _
]

