#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_ShingJeaIsland/SaoshangTrail.au3
; Map: SaoshangTrail (id 313), geometry from MAP 0000156969.pmap
; Repaired 0 of 0 blocked segments by inserting 0 waypoints.
; Smoothed 1 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_ShingJeaIsland_SaoshangTrailRoute01[27][4] = [ _
	[15519, 13409, " ", $vqrange], _
	[14502, 13165, " ", $vqrange], _
	[13632, 12799, " ", $vqrange], _
	[12763, 12433, " ", $vqrange], _
	[11590, 11736, " ", $vqrange], _
	[10416, 11040, " ", $vqrange], _
	[9805, 10947, " ", $vqrange], _
	[8860, 10272, " ", $vqrange], _
	[8553, 10272, " ", $vqrange], _
	[8399, 10272, " ", $vqrange], _
	[8246, 10272, " ", $vqrange], _
	[7632, 10272, " ", $vqrange], _
	[8162, 11075, " ", $vqrange], _
	[8691, 11878, " ", $vqrange], _
	[8329, 12867, " ", $vqrange], _
	[7704, 13824, " ", $vqrange], _
	[7460, 13833, " ", $vqrange], _
	[7215, 13842, " ", $vqrange], _
	[7059, 13840, " ", $vqrange], _
	[6834, 13837, " ", $vqrange], _ ; auto
	[6609, 13834, " ", $vqrange], _
	[6003, 13827, " ", $vqrange], _
	[5450, 13202, " ", $vqrange], _
	[4896, 12576, " ", $vqrange], _
	[4392, 11520, " ", $vqrange], _
	[3888, 10464, " ", $vqrange], _
	[3584, 10280, " ", $vqrange] _
]

