#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: vendor/vanquish-bot/Maps/Factions_ShingJeaIsland/SaoshangTrail.au3
; Map: SaoshangTrail (id 313), geometry from MAP 0000156969.pmap
; Repaired 3 of 3 blocked segments by inserting 5 waypoints.
; Smoothed 12 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.

Global $aFactions_ShingJeaIsland_SaoshangTrailRoute01[26][2] = [ _
	[15519, 13409], _
	[14502, 13165], _
	[13632.5, 12799], _ ; auto
	[12763, 12433], _
	[11589.5, 11736.5], _ ; auto
	[10416, 11040], _ ; auto
	[9805, 10947], _
	[8859.8467, 10272], _ ; auto
	[8552.885, 10272], _ ; auto
	[8399.4042, 10272], _ ; auto
	[8245.9233, 10272], _ ; auto
	[7632, 10272], _ ; auto
	[8161.5, 11075], _ ; auto
	[8691, 11878], _
	[8329, 12867], _
	[7704, 13824], _ ; auto
	[7459.5, 13833], _ ; auto
	[7215, 13842], _
	[7058.7656, 13840.0664], _ ; auto
	[6609, 13834.5], _ ; auto
	[6003, 13827], _
	[5449.5, 13201.5], _ ; auto
	[4896, 12576], _ ; auto
	[4392, 11520], _ ; auto
	[3888, 10464], _ ; auto
	[3584, 10280] _
]

