#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_ShingJeaIsland/SaoshangTrail.au3
; Map: SaoshangTrail (id 313), geometry from MAP 0000156969.pmap
; Repaired 0 of 0 blocked segments by inserting 0 waypoints.
; Smoothed 1 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.

Global $aFactions_ShingJeaIsland_SaoshangTrailRoute01[27][2] = [ _
	[15519, 13409], _
	[14502, 13165], _
	[13632, 12799], _
	[12763, 12433], _
	[11590, 11736], _
	[10416, 11040], _
	[9805, 10947], _
	[8860, 10272], _
	[8553, 10272], _
	[8399, 10272], _
	[8246, 10272], _
	[7632, 10272], _
	[8162, 11075], _
	[8691, 11878], _
	[8329, 12867], _
	[7704, 13824], _
	[7460, 13833], _
	[7215, 13842], _
	[7059, 13840], _
	[6834, 13837], _ ; auto
	[6609, 13834], _
	[6003, 13827], _
	[5450, 13202], _
	[4896, 12576], _
	[4392, 11520], _
	[3888, 10464], _
	[3584, 10280] _
]

