#!/usr/bin/env python3
"""Read vanquish-bot map files and emit repaired, tracked route arrays.

The vendored bot files under `vendor/vanquish-bot/Maps/<Campaign>/<Map>.au3`
mix coordinate arrays with bot logic, and the whole `vendor/` tree is
gitignored. So instead of editing them, this module reads the `Route<N>`
arrays, repairs them against the map's walkable geometry, and writes
array-only files under `lib/maps/Vanquish/<Campaign>/<Map>.au3` that keep the
original array names and are safe to include.

`OutpostPath`, `Path` and `2Path` arrays are deliberately skipped: they run in
the outpost, which is a different map with different geometry, so repairing
them against the explorable's mesh would corrupt them.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from .routes import AUTO_MARKER, RoutePoint, format_coord

ROOT = Path(__file__).resolve().parents[2]
VENDOR_MAPS = ROOT / "vendor/vanquish-bot/Maps"
OUTPUT_DIR = ROOT / "lib/maps/Vanquish"

_ARRAY_RE = re.compile(
    r"Global\s+\$(?P<name>\w+)\s*(?P<dims>(?:\[\d+\])*)\s*=\s*\[\s*_\r?\n"
    r"(?P<body>.*?)"
    r"\r?\n\]",
    re.DOTALL,
)
_COORD_RE = re.compile(r"\[\s*(-?\d+(?:\.\d+)?)\s*(?P<sep>,|\s)\s*(-?\d+(?:\.\d+)?)\s*\]")
_ROUTE_NAME_RE = re.compile(r"Route\d+$")


@dataclass(slots=True)
class RouteArray:
    name: str
    entries: list[RoutePoint] = field(default_factory=list)
    malformed: int = 0

    @property
    def points(self) -> list[tuple[float, float]]:
        return [e.point for e in self.entries]


@dataclass(slots=True)
class VanquishSource:
    path: Path
    campaign: str
    map_name: str
    arrays: list[RouteArray] = field(default_factory=list)

    @property
    def output_path(self) -> Path:
        return OUTPUT_DIR / self.campaign / f"{self.map_name}.au3"


def discover(vendor_dir: str | Path = VENDOR_MAPS) -> list[Path]:
    return sorted(Path(vendor_dir).glob("*/*.au3"))


def parse_source(path: str | Path) -> VanquishSource:
    path = Path(path)
    text = path.read_text(encoding="utf-8", errors="replace")
    source = VanquishSource(path=path, campaign=path.parent.name, map_name=path.stem)

    for match in _ARRAY_RE.finditer(text):
        name = match.group("name")
        if not _ROUTE_NAME_RE.search(name):
            continue
        array = RouteArray(name=name)
        for line in match.group("body").splitlines():
            coord = _COORD_RE.search(line)
            if coord is None:
                continue
            malformed = coord.group("sep") != ","
            if malformed:
                array.malformed += 1
            array.entries.append(
                RoutePoint(
                    x=float(coord.group(1)),
                    y=float(coord.group(3)),
                    generated=AUTO_MARKER in line,
                    raw=None if malformed else coord.group(0),
                    malformed=malformed,
                )
            )
        if array.entries:
            source.arrays.append(array)
    return source


def render(
    source: VanquishSource,
    arrays: list[RouteArray],
    map_id: int,
    pmap_name: str,
    notes: list[str],
) -> str:
    rel = source.path.relative_to(ROOT)
    lines = [
        "#include-once",
        "",
        "; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.",
        f"; Source: {rel}",
        f"; Map: {source.map_name} (id {map_id}), geometry from {pmap_name}",
    ]
    lines += [f"; {note}" for note in notes]
    lines += [
        f'; Waypoints tagged "{AUTO_MARKER.lstrip("; ")}" were generated to route around',
        "; unwalkable terrain; every other coordinate is unchanged from the source.",
        "",
    ]

    for array in arrays:
        lines.append(f"Global ${array.name}[{len(array.entries)}][2] = [ _")
        last = len(array.entries) - 1
        for i, entry in enumerate(array.entries):
            line = "\t" + format_coord(entry)
            line += " _" if i == last else ", _"
            if entry.generated:
                line += f" {AUTO_MARKER}"
            lines.append(line)
        lines.append("]")
        lines.append("")

    return "\n".join(lines) + "\n"
