; Generated by scripts/generate_map_route.py — do not edit by hand.
; Caravan routes: 16 | Vanquish arrays: 131 | Switch cases: 131
#include-once

#include "maps\Routes\CaravanAscalon_AnvilRock.au3"
#include "maps\Routes\CaravanAscalon_AscalonFoothills.au3"
#include "maps\Routes\CaravanAscalon_DeldrimorBowl.au3"
#include "maps\Routes\CaravanAscalon_DiessaLowlands.au3"
#include "maps\Routes\CaravanAscalon_DragonsGullet.au3"
#include "maps\Routes\CaravanAscalon_EasternFrontier.au3"
#include "maps\Routes\CaravanAscalon_FlameTempleCorridor.au3"
#include "maps\Routes\CaravanAscalon_GriffonsMouth.au3"
#include "maps\Routes\CaravanAscalon_IronHorseMine.au3"
#include "maps\Routes\CaravanAscalon_NorthKrytaProvince.au3"
#include "maps\Routes\CaravanAscalon_OldAscalon.au3"
#include "maps\Routes\CaravanAscalon_PockmarkFlats.au3"
#include "maps\Routes\CaravanAscalon_RegentValley.au3"
#include "maps\Routes\CaravanAscalon_ScoundrelsRise.au3"
#include "maps\Routes\CaravanAscalon_TheBreach.au3"
#include "maps\Routes\CaravanAscalon_TravelersVale.au3"
#include "maps\Vanquish\EOTN_CharrHomelands\DaladaUplands.au3"
#include "maps\Vanquish\EOTN_CharrHomelands\GrothmarWardowns.au3"
#include "maps\Vanquish\EOTN_CharrHomelands\SacnothValley.au3"
#include "maps\Vanquish\EOTN_FarShiverpeaks\BjoraMarches.au3"
#include "maps\Vanquish\EOTN_FarShiverpeaks\DrakkarLake.au3"
#include "maps\Vanquish\EOTN_FarShiverpeaks\JagaMoraine.au3"
#include "maps\Vanquish\EOTN_FarShiverpeaks\NorrhartDomains.au3"
#include "maps\Vanquish\EOTN_FarShiverpeaks\VarajarFells.au3"
#include "maps\Vanquish\EOTN_TarnishedCoast\AlcaziaTangle.au3"
#include "maps\Vanquish\EOTN_TarnishedCoast\ArborBay.au3"
#include "maps\Vanquish\EOTN_TarnishedCoast\MagusStones.au3"
#include "maps\Vanquish\EOTN_TarnishedCoast\RivenEarth.au3"
#include "maps\Vanquish\EOTN_TarnishedCoast\SparkflySwamp.au3"
#include "maps\Vanquish\EOTN_TarnishedCoast\VerdantCascades.au3"
#include "maps\Vanquish\Factions_EchovaldForest\Arborstone.au3"
#include "maps\Vanquish\Factions_EchovaldForest\DrazachThicket.au3"
#include "maps\Vanquish\Factions_EchovaldForest\Ferndale.au3"
#include "maps\Vanquish\Factions_EchovaldForest\MelandrusHope.au3"
#include "maps\Vanquish\Factions_EchovaldForest\MorostavTrail.au3"
#include "maps\Vanquish\Factions_EchovaldForest\MourningVeilFalls.au3"
#include "maps\Vanquish\Factions_EchovaldForest\TheEternalGrove.au3"
#include "maps\Vanquish\Factions_KainengCity\BukdekByway.au3"
#include "maps\Vanquish\Factions_KainengCity\NahpuiQuarter.au3"
#include "maps\Vanquish\Factions_KainengCity\PongmeiValley.au3"
#include "maps\Vanquish\Factions_KainengCity\RaisuPalace.au3"
#include "maps\Vanquish\Factions_KainengCity\ShadowsPassage.au3"
#include "maps\Vanquish\Factions_KainengCity\ShenzunTunnels.au3"
#include "maps\Vanquish\Factions_KainengCity\SunjiangDistrict.au3"
#include "maps\Vanquish\Factions_KainengCity\TahnnakiTemple.au3"
#include "maps\Vanquish\Factions_KainengCity\WajjunBazaar.au3"
#include "maps\Vanquish\Factions_KainengCity\XaquangSkyway.au3"
#include "maps\Vanquish\Factions_ShingJeaIsland\HaijuLagoon.au3"
#include "maps\Vanquish\Factions_ShingJeaIsland\JayaBluffs.au3"
#include "maps\Vanquish\Factions_ShingJeaIsland\KinyaProvince.au3"
#include "maps\Vanquish\Factions_ShingJeaIsland\MinisterChosEstate.au3"
#include "maps\Vanquish\Factions_ShingJeaIsland\PanjiangPeninsula.au3"
#include "maps\Vanquish\Factions_ShingJeaIsland\SaoshangTrail.au3"
#include "maps\Vanquish\Factions_ShingJeaIsland\SunquaVale.au3"
#include "maps\Vanquish\Factions_ShingJeaIsland\ZenDaijun.au3"
#include "maps\Vanquish\Factions_TheJadeSea\Archipelagos.au3"
#include "maps\Vanquish\Factions_TheJadeSea\BoreasSeabed.au3"
#include "maps\Vanquish\Factions_TheJadeSea\GyalaHatchery.au3"
#include "maps\Vanquish\Factions_TheJadeSea\MaishangHills.au3"
#include "maps\Vanquish\Factions_TheJadeSea\MountQinkai.au3"
#include "maps\Vanquish\Factions_TheJadeSea\RheasCrater.au3"
#include "maps\Vanquish\Factions_TheJadeSea\SilentSurf.au3"
#include "maps\Vanquish\Factions_TheJadeSea\UnwakingWaters.au3"
#include "maps\Vanquish\NF_Istan\IssnurIsles.au3"
#include "maps\Vanquish\NF_Istan\LahtendaBog.au3"
#include "maps\Vanquish\NF_Istan\MehtaniKeys.au3"
#include "maps\Vanquish\NF_Istan\PlainsofJarin.au3"
#include "maps\Vanquish\NF_Istan\ZehlonReach.au3"
#include "maps\Vanquish\NF_Kourna\ArkjokWard.au3"
#include "maps\Vanquish\NF_Kourna\BahdokCaverns.au3"
#include "maps\Vanquish\NF_Kourna\BarbarousShore.au3"
#include "maps\Vanquish\NF_Kourna\DejarinEstate.au3"
#include "maps\Vanquish\NF_Kourna\JahaiBluffs.au3"
#include "maps\Vanquish\NF_Kourna\MargaCoast.au3"
#include "maps\Vanquish\NF_Kourna\SunwardMarches.au3"
#include "maps\Vanquish\NF_Kourna\TheFloodplainOfMahnkelon.au3"
#include "maps\Vanquish\NF_Kourna\TuraisProcession.au3"
#include "maps\Vanquish\NF_TheDesolation\JokosDomain.au3"
#include "maps\Vanquish\NF_TheDesolation\PoisonedOutcrops.au3"
#include "maps\Vanquish\NF_TheDesolation\TheAlkaliPan.au3"
#include "maps\Vanquish\NF_TheDesolation\TheRupturedHeart.au3"
#include "maps\Vanquish\NF_TheDesolation\TheShatteredRavines.au3"
#include "maps\Vanquish\NF_TheDesolation\TheSulfurousWastes.au3"
#include "maps\Vanquish\NF_Vabbi\ForumHighlands.au3"
#include "maps\Vanquish\NF_Vabbi\GardenOfSeborhin.au3"
#include "maps\Vanquish\NF_Vabbi\HoldingsOfChokhin.au3"
#include "maps\Vanquish\NF_Vabbi\ResplendentMakuun.au3"
#include "maps\Vanquish\NF_Vabbi\TheHiddenCityOfAhdashim.au3"
#include "maps\Vanquish\NF_Vabbi\TheMirrorOfLyss.au3"
#include "maps\Vanquish\NF_Vabbi\VehjinMines.au3"
#include "maps\Vanquish\NF_Vabbi\VehtendiValley.au3"
#include "maps\Vanquish\NF_Vabbi\WildernessOfBahdza.au3"
#include "maps\Vanquish\NF_Vabbi\YatendiCanyons.au3"
#include "maps\Vanquish\Proph_Ascalon\AscalonFoothills.au3"
#include "maps\Vanquish\Proph_Ascalon\DiessaLowlands.au3"
#include "maps\Vanquish\Proph_Ascalon\DragonsGullet.au3"
#include "maps\Vanquish\Proph_Ascalon\EasternFrontier.au3"
#include "maps\Vanquish\Proph_Ascalon\FlameTempleCorridor.au3"
#include "maps\Vanquish\Proph_Ascalon\PockmarkFlats.au3"
#include "maps\Vanquish\Proph_Ascalon\RegentValley.au3"
#include "maps\Vanquish\Proph_Ascalon\TheBreach.au3"
#include "maps\Vanquish\Proph_CrystalDesert\DivinersAscent.au3"
#include "maps\Vanquish\Proph_CrystalDesert\ProphetsPath.au3"
#include "maps\Vanquish\Proph_CrystalDesert\SaltFlats.au3"
#include "maps\Vanquish\Proph_CrystalDesert\SkywardReach.au3"
#include "maps\Vanquish\Proph_CrystalDesert\TheAridSea.au3"
#include "maps\Vanquish\Proph_CrystalDesert\TheScar.au3"
#include "maps\Vanquish\Proph_CrystalDesert\VultureDrifts.au3"
#include "maps\Vanquish\Proph_Kryta\CursedLands.au3"
#include "maps\Vanquish\Proph_Kryta\KessexPeak.au3"
#include "maps\Vanquish\Proph_Kryta\MajestysRest.au3"
#include "maps\Vanquish\Proph_Kryta\NeboTerrace.au3"
#include "maps\Vanquish\Proph_Kryta\NorthKrytaProvince.au3"
#include "maps\Vanquish\Proph_Kryta\ScoundrelsRise.au3"
#include "maps\Vanquish\Proph_Kryta\StingrayStrand.au3"
#include "maps\Vanquish\Proph_Kryta\TalmarkWilderness.au3"
#include "maps\Vanquish\Proph_Kryta\TearsoftheFallen.au3"
#include "maps\Vanquish\Proph_Kryta\TheBlackCurtain.au3"
#include "maps\Vanquish\Proph_Kryta\TwinSerpentLakes.au3"
#include "maps\Vanquish\Proph_Kryta\WatchtowerCoast.au3"
#include "maps\Vanquish\Proph_Maguuma\DryTop.au3"
#include "maps\Vanquish\Proph_Maguuma\EttinsBack.au3"
#include "maps\Vanquish\Proph_Maguuma\MamnoonLagoon.au3"
#include "maps\Vanquish\Proph_Maguuma\ReedBog.au3"
#include "maps\Vanquish\Proph_Maguuma\SageLands.au3"
#include "maps\Vanquish\Proph_Maguuma\Silverwood.au3"
#include "maps\Vanquish\Proph_Maguuma\TangleRoot.au3"
#include "maps\Vanquish\Proph_Maguuma\TheFalls.au3"
#include "maps\Vanquish\Proph_NorthernShiverpeaks\AnvilRock.au3"
#include "maps\Vanquish\Proph_NorthernShiverpeaks\DeldrimorBowl.au3"
#include "maps\Vanquish\Proph_NorthernShiverpeaks\GriffonsMouth.au3"
#include "maps\Vanquish\Proph_NorthernShiverpeaks\IronHorseMine.au3"
#include "maps\Vanquish\Proph_NorthernShiverpeaks\TravelersVale.au3"
#include "maps\Vanquish\Proph_RingOfFireIsland\PerditionRock.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\DeldrimorBowl.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\DreadnoughtsDrift.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\FrozenForest.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\GrenthsFootprint.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\IceDome.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\IceFloe.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\LornarsPass.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\MineralSprings.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\SnakeDance.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\SpearheadPeak.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\TalusChute.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\TascasDemise.au3"
#include "maps\Vanquish\Proph_SouthernShiverpeaks\WitmansFolly.au3"

Func _MapRoute_Distance($a_f_X1, $a_f_Y1, $a_f_X2, $a_f_Y2)
	Return Sqrt(($a_f_X2 - $a_f_X1) ^ 2 + ($a_f_Y2 - $a_f_Y1) ^ 2)
EndFunc

Func MapRoute_DedupePath1D(ByRef $a_a_X, ByRef $a_a_Y, $a_i_Count, $a_f_MinSpacing = 150)
	If $a_i_Count < 2 Then Return $a_i_Count

	Local $l_a_TempX[$a_i_Count]
	Local $l_a_TempY[$a_i_Count]
	$l_a_TempX[0] = $a_a_X[0]
	$l_a_TempY[0] = $a_a_Y[0]
	Local $l_i_Out = 1

	For $i = 1 To $a_i_Count - 1
		Local $l_f_D = _MapRoute_Distance($l_a_TempX[$l_i_Out - 1], $l_a_TempY[$l_i_Out - 1], $a_a_X[$i], $a_a_Y[$i])
		If $l_f_D < $a_f_MinSpacing Then ContinueLoop
		$l_a_TempX[$l_i_Out] = $a_a_X[$i]
		$l_a_TempY[$l_i_Out] = $a_a_Y[$i]
		$l_i_Out += 1
	Next

	ReDim $a_a_X[$l_i_Out]
	ReDim $a_a_Y[$l_i_Out]
	For $i = 0 To $l_i_Out - 1
		$a_a_X[$i] = $l_a_TempX[$i]
		$a_a_Y[$i] = $l_a_TempY[$i]
	Next
	Return $l_i_Out
EndFunc

Func MapRoute_CopyPath1D(ByRef $a_a_Source, ByRef $a_a_X, ByRef $a_a_Y)
	If Not IsArray($a_a_Source) Then Return 0

	Local $l_i_Count = 0
	If UBound($a_a_Source, 0) = 2 Then
		$l_i_Count = UBound($a_a_Source, 1)
	Else
		$l_i_Count = UBound($a_a_Source)
	EndIf
	If $l_i_Count < 1 Then Return 0

	Local $l_a_X[$l_i_Count]
	Local $l_a_Y[$l_i_Count]
	For $i = 0 To $l_i_Count - 1
		$l_a_X[$i] = $a_a_Source[$i][0]
		$l_a_Y[$i] = $a_a_Source[$i][1]
	Next

	Local $l_i_Out = MapRoute_DedupePath1D($l_a_X, $l_a_Y, $l_i_Count)
	If $l_i_Out < 1 Then Return 0
	$a_a_X = $l_a_X
	$a_a_Y = $l_a_Y
	Return $l_i_Out
EndFunc

Func MapRoute_TryLoadForTitle($a_s_Title, ByRef $a_a_X, ByRef $a_a_Y)
	Switch $a_s_Title
		Case "AnvilRock"
			Return MapRoute_GetAnvilRock($a_a_X, $a_a_Y)
		Case "AscalonFoothills"
			Return MapRoute_GetAscalonFoothills($a_a_X, $a_a_Y)
		Case "DeldrimorBowl"
			Return MapRoute_GetDeldrimorBowl($a_a_X, $a_a_Y)
		Case "DiessaLowlands"
			Return MapRoute_GetDiessaLowlands($a_a_X, $a_a_Y)
		Case "DragonsGullet"
			Return MapRoute_GetDragonsGullet($a_a_X, $a_a_Y)
		Case "EasternFrontier"
			Return MapRoute_GetEasternFrontier($a_a_X, $a_a_Y)
		Case "FlameTempleCorridor"
			Return MapRoute_GetFlameTempleCorridor($a_a_X, $a_a_Y)
		Case "GriffonsMouth"
			Return MapRoute_GetGriffonsMouth($a_a_X, $a_a_Y)
		Case "IronHorseMine"
			Return MapRoute_GetIronHorseMine($a_a_X, $a_a_Y)
		Case "NorthKrytaProvince"
			Return MapRoute_GetNorthKrytaProvince($a_a_X, $a_a_Y)
		Case "OldAscalon"
			Return MapRoute_GetOldAscalon($a_a_X, $a_a_Y)
		Case "PockmarkFlats"
			Return MapRoute_GetPockmarkFlats($a_a_X, $a_a_Y)
		Case "RegentValley"
			Return MapRoute_GetRegentValley($a_a_X, $a_a_Y)
		Case "ScoundrelsRise"
			Return MapRoute_GetScoundrelsRise($a_a_X, $a_a_Y)
		Case "TheBreach"
			Return MapRoute_GetTheBreach($a_a_X, $a_a_Y)
		Case "TravelersVale"
			Return MapRoute_GetTravelersVale($a_a_X, $a_a_Y)
		Case "AlcaziaTangle"
			Return MapRoute_CopyPath1D($aEOTN_TarnishedCoast_AlcaziaTangleRoute01, $a_a_X, $a_a_Y)
		Case "ArborBay"
			Return MapRoute_CopyPath1D($aEOTN_TarnishedCoast_ArborBayRoute01, $a_a_X, $a_a_Y)
		Case "Arborstone"
			Return MapRoute_CopyPath1D($aFactions_EchovaldForest_ArborstoneRoute01, $a_a_X, $a_a_Y)
		Case "Archipelagos"
			Return MapRoute_CopyPath1D($aFactions_TheJadeSea_ArchipelagosRoute01, $a_a_X, $a_a_Y)
		Case "ArkjokWard"
			Return MapRoute_CopyPath1D($aNF_Kourna_ArkjokWardRoute01, $a_a_X, $a_a_Y)
		Case "BahdokCaverns"
			Return MapRoute_CopyPath1D($aNF_Kourna_BahdokCavernsRoute01, $a_a_X, $a_a_Y)
		Case "BarbarousShore"
			Return MapRoute_CopyPath1D($aNF_Kourna_BarbarousShoreRoute01, $a_a_X, $a_a_Y)
		Case "BjoraMarches"
			Return MapRoute_CopyPath1D($aEOTN_FarShiverpeaks_BjoraMarchesRoute01, $a_a_X, $a_a_Y)
		Case "BoreasSeabed"
			Return MapRoute_CopyPath1D($aFactions_TheJadeSea_BoreasSeabedRoute01, $a_a_X, $a_a_Y)
		Case "BukdekByway"
			Return MapRoute_CopyPath1D($aFactions_KainengCity_BukdekBywayRoute01, $a_a_X, $a_a_Y)
		Case "CursedLands"
			Return MapRoute_CopyPath1D($aProph_Kryta_CursedLandsRoute01, $a_a_X, $a_a_Y)
		Case "DaladaUplands"
			Return MapRoute_CopyPath1D($aEOTN_CharrHomelands_DaladaUplandsRoute01, $a_a_X, $a_a_Y)
		Case "DejarinEstate"
			Return MapRoute_CopyPath1D($aNF_Kourna_DejarinEstateRoute01, $a_a_X, $a_a_Y)
		Case "DivinersAscent"
			Return MapRoute_CopyPath1D($aProph_CrystalDesert_DivinersAscentRoute01, $a_a_X, $a_a_Y)
		Case "DrakkarLake"
			Return MapRoute_CopyPath1D($aEOTN_FarShiverpeaks_DrakkarLakeRoute01, $a_a_X, $a_a_Y)
		Case "DrazachThicket"
			Return MapRoute_CopyPath1D($aFactions_EchovaldForest_DrazachThicketRoute01, $a_a_X, $a_a_Y)
		Case "DreadnoughtsDrift"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_DreadnoughtsDriftRoute01, $a_a_X, $a_a_Y)
		Case "DryTop"
			Return MapRoute_CopyPath1D($aProph_Maguuma_DryTopRoute01, $a_a_X, $a_a_Y)
		Case "EttinsBack"
			Return MapRoute_CopyPath1D($aProph_Maguuma_EttinsBackRoute01, $a_a_X, $a_a_Y)
		Case "Ferndale"
			Return MapRoute_CopyPath1D($aFactions_EchovaldForest_FerndaleRoute01, $a_a_X, $a_a_Y)
		Case "ForumHighlands"
			Return MapRoute_CopyPath1D($aNF_Vabbi_ForumHighlandsRoute01, $a_a_X, $a_a_Y)
		Case "FrozenForest"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_FrozenForestRoute01, $a_a_X, $a_a_Y)
		Case "GardenOfSeborhin"
			Return MapRoute_CopyPath1D($aNF_Vabbi_GardenOfSeborhinRoute01, $a_a_X, $a_a_Y)
		Case "GrenthsFootprint"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_GrenthsFootprintRoute01, $a_a_X, $a_a_Y)
		Case "GrothmarWardowns"
			Return MapRoute_CopyPath1D($aEOTN_CharrHomelands_GrothmarWardownsRoute01, $a_a_X, $a_a_Y)
		Case "GyalaHatchery"
			Return MapRoute_CopyPath1D($aFactions_TheJadeSea_GyalaHatcheryRoute01, $a_a_X, $a_a_Y)
		Case "HaijuLagoon"
			Return MapRoute_CopyPath1D($aFactions_ShingJeaIsland_HaijuLagoonRoute01, $a_a_X, $a_a_Y)
		Case "HoldingsOfChokhin"
			Return MapRoute_CopyPath1D($aNF_Vabbi_HoldingsOfChokhinRoute01, $a_a_X, $a_a_Y)
		Case "IceDome"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_IceDomeRoute01, $a_a_X, $a_a_Y)
		Case "IceFloe"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_IceFloeRoute01, $a_a_X, $a_a_Y)
		Case "IssnurIsles"
			Return MapRoute_CopyPath1D($aNF_Istan_IssnurIslesRoute01, $a_a_X, $a_a_Y)
		Case "JagaMoraine"
			Return MapRoute_CopyPath1D($aEOTN_FarShiverpeaks_JagaMoraineRoute01, $a_a_X, $a_a_Y)
		Case "JahaiBluffs"
			Return MapRoute_CopyPath1D($aNF_Kourna_JahaiBluffsRoute01, $a_a_X, $a_a_Y)
		Case "JayaBluffs"
			Return MapRoute_CopyPath1D($aFactions_ShingJeaIsland_JayaBluffsRoute01, $a_a_X, $a_a_Y)
		Case "JokosDomain"
			Return MapRoute_CopyPath1D($aNF_TheDesolation_JokosDomainRoute01, $a_a_X, $a_a_Y)
		Case "KessexPeak"
			Return MapRoute_CopyPath1D($aProph_Kryta_KessexPeakRoute01, $a_a_X, $a_a_Y)
		Case "KinyaProvince"
			Return MapRoute_CopyPath1D($aFactions_ShingJeaIsland_KinyaProvinceRoute01, $a_a_X, $a_a_Y)
		Case "LahtendaBog"
			Return MapRoute_CopyPath1D($aNF_Istan_LahtendaBogRoute01, $a_a_X, $a_a_Y)
		Case "LornarsPass"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_LornarsPassRoute01, $a_a_X, $a_a_Y)
		Case "MagusStones"
			Return MapRoute_CopyPath1D($aEOTN_TarnishedCoast_MagusStonesRoute01, $a_a_X, $a_a_Y)
		Case "MaishangHills"
			Return MapRoute_CopyPath1D($aFactions_TheJadeSea_MaishangHillsRoute01, $a_a_X, $a_a_Y)
		Case "MajestysRest"
			Return MapRoute_CopyPath1D($aProph_Kryta_MajestysRestRoute01, $a_a_X, $a_a_Y)
		Case "MamnoonLagoon"
			Return MapRoute_CopyPath1D($aProph_Maguuma_MamnoonLagoonRoute01, $a_a_X, $a_a_Y)
		Case "MargaCoast"
			Return MapRoute_CopyPath1D($aNF_Kourna_MargaCoastRoute01, $a_a_X, $a_a_Y)
		Case "MehtaniKeys"
			Return MapRoute_CopyPath1D($aNF_Istan_MehtaniKeysRoute01, $a_a_X, $a_a_Y)
		Case "MelandrusHope"
			Return MapRoute_CopyPath1D($aFactions_EchovaldForest_MelandrusHopeRoute01, $a_a_X, $a_a_Y)
		Case "MineralSprings"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_MineralSpringsRoute01, $a_a_X, $a_a_Y)
		Case "MinisterChosEstate"
			Return MapRoute_CopyPath1D($aFactions_ShingJeaIsland_MinisterChosEstateRoute01, $a_a_X, $a_a_Y)
		Case "MorostavTrail"
			Return MapRoute_CopyPath1D($aFactions_EchovaldForest_MorostavTrailRoute01, $a_a_X, $a_a_Y)
		Case "MountQinkai"
			Return MapRoute_CopyPath1D($aFactions_TheJadeSea_MountQinkaiRoute01, $a_a_X, $a_a_Y)
		Case "MourningVeilFalls"
			Return MapRoute_CopyPath1D($aFactions_EchovaldForest_MourningVeilFallsRoute01, $a_a_X, $a_a_Y)
		Case "NahpuiQuarter"
			Return MapRoute_CopyPath1D($aFactions_KainengCity_NahpuiQuarterRoute01, $a_a_X, $a_a_Y)
		Case "NeboTerrace"
			Return MapRoute_CopyPath1D($aProph_Kryta_NeboTerraceRoute01, $a_a_X, $a_a_Y)
		Case "NorrhartDomains"
			Return MapRoute_CopyPath1D($aEOTN_FarShiverpeaks_NorrhartDomainsRoute02, $a_a_X, $a_a_Y)
		Case "PanjiangPeninsula"
			Return MapRoute_CopyPath1D($aFactions_ShingJeaIsland_PanjiangPeninsulaRoute01, $a_a_X, $a_a_Y)
		Case "PerditionRock"
			Return MapRoute_CopyPath1D($aProph_RingOfFireIsland_PerditionRockRoute01, $a_a_X, $a_a_Y)
		Case "PlainsofJarin"
			Return MapRoute_CopyPath1D($aNF_Istan_PlainsofJarinRoute01, $a_a_X, $a_a_Y)
		Case "PoisonedOutcrops"
			Return MapRoute_CopyPath1D($aNF_TheDesolation_PoisonedOutcropsRoute01, $a_a_X, $a_a_Y)
		Case "PongmeiValley"
			Return MapRoute_CopyPath1D($aFactions_KainengCity_PongmeiValleyRoute01, $a_a_X, $a_a_Y)
		Case "ProphetsPath"
			Return MapRoute_CopyPath1D($aProph_CrystalDesert_ProphetsPathRoute01, $a_a_X, $a_a_Y)
		Case "RaisuPalace"
			Return MapRoute_CopyPath1D($aFactions_KainengCity_RaisuPalaceRoute01, $a_a_X, $a_a_Y)
		Case "ReedBog"
			Return MapRoute_CopyPath1D($aProph_Maguuma_ReedBogRoute01, $a_a_X, $a_a_Y)
		Case "ResplendentMakuun"
			Return MapRoute_CopyPath1D($aNF_Vabbi_ResplendentMakuunRoute01, $a_a_X, $a_a_Y)
		Case "RheasCrater"
			Return MapRoute_CopyPath1D($aFactions_TheJadeSea_RheasCraterRoute01, $a_a_X, $a_a_Y)
		Case "RivenEarth"
			Return MapRoute_CopyPath1D($aEOTN_TarnishedCoast_RivenEarthRoute01, $a_a_X, $a_a_Y)
		Case "SacnothValley"
			Return MapRoute_CopyPath1D($aEOTN_CharrHomelands_SacnothValleyRoute01, $a_a_X, $a_a_Y)
		Case "SageLands"
			Return MapRoute_CopyPath1D($aProph_Maguuma_SageLandsRoute01, $a_a_X, $a_a_Y)
		Case "SaltFlats"
			Return MapRoute_CopyPath1D($aProph_CrystalDesert_SaltFlatsRoute01, $a_a_X, $a_a_Y)
		Case "SaoshangTrail"
			Return MapRoute_CopyPath1D($aFactions_ShingJeaIsland_SaoshangTrailRoute01, $a_a_X, $a_a_Y)
		Case "ShadowsPassage"
			Return MapRoute_CopyPath1D($aFactions_KainengCity_ShadowsPassageRoute01, $a_a_X, $a_a_Y)
		Case "ShenzunTunnels"
			Return MapRoute_CopyPath1D($aFactions_KainengCity_ShenzunTunnelsRoute01, $a_a_X, $a_a_Y)
		Case "SilentSurf"
			Return MapRoute_CopyPath1D($aFactions_TheJadeSea_SilentSurfRoute01, $a_a_X, $a_a_Y)
		Case "Silverwood"
			Return MapRoute_CopyPath1D($aProph_Maguuma_SilverwoodRoute01, $a_a_X, $a_a_Y)
		Case "SkywardReach"
			Return MapRoute_CopyPath1D($aProph_CrystalDesert_SkywardReachRoute01, $a_a_X, $a_a_Y)
		Case "SnakeDance"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_SnakeDanceRoute01, $a_a_X, $a_a_Y)
		Case "SparkflySwamp"
			Return MapRoute_CopyPath1D($aEOTN_TarnishedCoast_SparkflySwampRoute01, $a_a_X, $a_a_Y)
		Case "SpearheadPeak"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_SpearheadPeakRoute01, $a_a_X, $a_a_Y)
		Case "StingrayStrand"
			Return MapRoute_CopyPath1D($aProph_Kryta_StingrayStrandRoute01, $a_a_X, $a_a_Y)
		Case "SunjiangDistrict"
			Return MapRoute_CopyPath1D($aFactions_KainengCity_SunjiangDistrictRoute01, $a_a_X, $a_a_Y)
		Case "SunquaVale"
			Return MapRoute_CopyPath1D($aFactions_ShingJeaIsland_SunquaValeRoute01, $a_a_X, $a_a_Y)
		Case "SunwardMarches"
			Return MapRoute_CopyPath1D($aNF_Kourna_SunwardMarchesRoute01, $a_a_X, $a_a_Y)
		Case "TahnnakiTemple"
			Return MapRoute_CopyPath1D($aFactions_KainengCity_TahnnakiTempleRoute01, $a_a_X, $a_a_Y)
		Case "TalmarkWilderness"
			Return MapRoute_CopyPath1D($aProph_Kryta_TalmarkWildernessRoute01, $a_a_X, $a_a_Y)
		Case "TalusChute"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_TalusChuteRoute01, $a_a_X, $a_a_Y)
		Case "TangleRoot"
			Return MapRoute_CopyPath1D($aProph_Maguuma_TangleRootRoute01, $a_a_X, $a_a_Y)
		Case "TascasDemise"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_TascasDemiseRoute01, $a_a_X, $a_a_Y)
		Case "TearsoftheFallen"
			Return MapRoute_CopyPath1D($aProph_Kryta_TearsoftheFallenRoute01, $a_a_X, $a_a_Y)
		Case "TheAlkaliPan"
			Return MapRoute_CopyPath1D($aNF_TheDesolation_TheAlkaliPanRoute01, $a_a_X, $a_a_Y)
		Case "TheAridSea"
			Return MapRoute_CopyPath1D($aProph_CrystalDesert_TheAridSeaRoute01, $a_a_X, $a_a_Y)
		Case "TheBlackCurtain"
			Return MapRoute_CopyPath1D($aProph_Kryta_TheBlackCurtainRoute01, $a_a_X, $a_a_Y)
		Case "TheEternalGrove"
			Return MapRoute_CopyPath1D($aFactions_EchovaldForest_TheEternalGroveRoute01, $a_a_X, $a_a_Y)
		Case "TheFalls"
			Return MapRoute_CopyPath1D($aProph_Maguuma_TheFallsRoute01, $a_a_X, $a_a_Y)
		Case "TheFloodplainOfMahnkelon"
			Return MapRoute_CopyPath1D($aNF_Kourna_TheFloodplainOfMahnkelonRoute01, $a_a_X, $a_a_Y)
		Case "TheHiddenCityOfAhdashim"
			Return MapRoute_CopyPath1D($aNF_Vabbi_TheHiddenCityOfAhdashimRoute01, $a_a_X, $a_a_Y)
		Case "TheMirrorOfLyss"
			Return MapRoute_CopyPath1D($aNF_Vabbi_TheMirrorOfLyssRoute01, $a_a_X, $a_a_Y)
		Case "TheRupturedHeart"
			Return MapRoute_CopyPath1D($aNF_TheDesolation_TheRupturedHeartRoute01, $a_a_X, $a_a_Y)
		Case "TheScar"
			Return MapRoute_CopyPath1D($aProph_CrystalDesert_TheScarRoute01, $a_a_X, $a_a_Y)
		Case "TheShatteredRavines"
			Return MapRoute_CopyPath1D($aNF_TheDesolation_TheShatteredRavinesRoute01, $a_a_X, $a_a_Y)
		Case "TheSulfurousWastes"
			Return MapRoute_CopyPath1D($aNF_TheDesolation_TheSulfurousWastesRoute01, $a_a_X, $a_a_Y)
		Case "TuraisProcession"
			Return MapRoute_CopyPath1D($aNF_Kourna_TuraisProcessionRoute01, $a_a_X, $a_a_Y)
		Case "TwinSerpentLakes"
			Return MapRoute_CopyPath1D($aProph_Kryta_TwinSerpentLakesRoute01, $a_a_X, $a_a_Y)
		Case "UnwakingWaters"
			Return MapRoute_CopyPath1D($aFactions_TheJadeSea_UnwakingWatersRoute01, $a_a_X, $a_a_Y)
		Case "VarajarFells"
			Return MapRoute_CopyPath1D($aEOTN_FarShiverpeaks_VarajarFellsRoute01, $a_a_X, $a_a_Y)
		Case "VehjinMines"
			Return MapRoute_CopyPath1D($aNF_Vabbi_VehjinMinesRoute01, $a_a_X, $a_a_Y)
		Case "VehtendiValley"
			Return MapRoute_CopyPath1D($aNF_Vabbi_VehtendiValleyRoute01, $a_a_X, $a_a_Y)
		Case "VerdantCascades"
			Return MapRoute_CopyPath1D($aEOTN_TarnishedCoast_VerdantCascadesRoute01, $a_a_X, $a_a_Y)
		Case "VultureDrifts"
			Return MapRoute_CopyPath1D($aProph_CrystalDesert_VultureDriftsRoute01, $a_a_X, $a_a_Y)
		Case "WajjunBazaar"
			Return MapRoute_CopyPath1D($aFactions_KainengCity_WajjunBazaarRoute01, $a_a_X, $a_a_Y)
		Case "WatchtowerCoast"
			Return MapRoute_CopyPath1D($aProph_Kryta_WatchtowerCoastRoute01, $a_a_X, $a_a_Y)
		Case "WildernessOfBahdza"
			Return MapRoute_CopyPath1D($aNF_Vabbi_WildernessOfBahdzaRoute01, $a_a_X, $a_a_Y)
		Case "WitmansFolly"
			Return MapRoute_CopyPath1D($aProph_SouthernShiverpeaks_WitmansFollyRoute01, $a_a_X, $a_a_Y)
		Case "XaquangSkyway"
			Return MapRoute_CopyPath1D($aFactions_KainengCity_XaquangSkywayRoute01, $a_a_X, $a_a_Y)
		Case "YatendiCanyons"
			Return MapRoute_CopyPath1D($aNF_Vabbi_YatendiCanyonsRoute01, $a_a_X, $a_a_Y)
		Case "ZehlonReach"
			Return MapRoute_CopyPath1D($aNF_Istan_ZehlonReachRoute01, $a_a_X, $a_a_Y)
		Case "ZenDaijun"
			Return MapRoute_CopyPath1D($aFactions_ShingJeaIsland_ZenDaijunRoute01, $a_a_X, $a_a_Y)
	EndSwitch
	Return 0
EndFunc

Func MapRoute_HasRoute($a_s_Title)
	Local $l_a_X, $l_a_Y
	Return MapRoute_TryLoadForTitle($a_s_Title, $l_a_X, $l_a_Y) > 0
EndFunc

