#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_TheJadeSea/BoreasSeabed.au3
; Map: BoreasSeabed (id 247), geometry from MAP 0000155159.pmap
; Repaired 1 of 3 blocked segments by inserting 3 waypoints.
; Smoothed 9 additional anchor(s) for wall clearance and hop distance.
; Filled 2 long hop(s) by walking the current mesh component toward a disconnected goal.
; 2 segment(s) could not be routed and were left as-is.
; 2 hop(s) still exceed 1500 units (worst 2395 between index 179 and 180).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_TheJadeSea_BoreasSeabedRoute01[206][4] = [ _
	[15139, -7063, " ", $vqrange], _
	[16189, -7744, " ", $vqrange], _
	[17238, -8425, " ", $vqrange], _
	[18288, -9106, " ", $vqrange], _
	[18338, -9208, " ", $vqrange], _
	[18824, -9208, " ", $vqrange], _
	[18976, -9208, " ", $vqrange], _
	[19128, -9208, " ", $vqrange], _
	[19280, -9208, " ", $vqrange], _
	[19530.5, -9208, " ", $vqrange], _ ; auto
	[19781, -9208, " ", $vqrange], _ ; auto
	[20282, -9208, " ", $vqrange], _
	[19941, -7916, " ", $vqrange], _
	[19600, -6624, " ", $vqrange], _
	[19930, -6525, " ", $vqrange], _
	[19684, -7776, " ", $vqrange], _
	[20752, -7958, " ", $vqrange], _
	[21821, -8140, " ", $vqrange], _
	[20752, -7958, " ", $vqrange], _
	[19684, -7776, " ", $vqrange], _
	[19643, -6812, " ", $vqrange], _
	[19603, -5849, " ", $vqrange], _
	[19274, -4738, " ", $vqrange], _
	[18945, -3627, " ", $vqrange], _
	[18616, -2516, " ", $vqrange], _
	[17577, -2008, " ", $vqrange], _
	[16539, -1501, " ", $vqrange], _
	[15500, -993, " ", $vqrange], _
	[14511, -1327, " ", $vqrange], _
	[13521, -1661, " ", $vqrange], _
	[12532, -1995, " ", $vqrange], _
	[11482, -1843, " ", $vqrange], _
	[10433, -1691, " ", $vqrange], _
	[9383, -1539, " ", $vqrange], _
	[8534, -1713, " ", $vqrange], _
	[7684, -1887, " ", $vqrange], _
	[7822, -2968, " ", $vqrange], _
	[7961, -4050, " ", $vqrange], _
	[9004, -4779, " ", $vqrange], _
	[10048, -5508, " ", $vqrange], _
	[11091, -6237, " ", $vqrange], _
	[9912, -6691, " ", $vqrange], _
	[8733, -7146, " ", $vqrange], _
	[7554, -7600, " ", $vqrange], _
	[6397, -7332, " ", $vqrange], _
	[5240, -7064, " ", $vqrange], _
	[4082, -6795, " ", $vqrange], _
	[2925, -6527, " ", $vqrange], _
	[3875, -6143, " ", $vqrange], _
	[4824, -5760, " ", $vqrange], _
	[5774, -5376, " ", $vqrange], _
	[4740, -5376, " ", $vqrange], _
	[3705, -5376, " ", $vqrange], _
	[2671, -5376, " ", $vqrange], _
	[1895, -5376, " ", $vqrange], _
	[1119, -5376, " ", $vqrange], _
	[926, -5376, " ", $vqrange], _
	[756, -5376, " ", $vqrange], _
	[586, -5376, " ", $vqrange], _
	[416, -5376, " ", $vqrange], _
	[247, -5376, " ", $vqrange], _
	[77, -5376, " ", $vqrange], _
	[-177.5, -5376, " ", $vqrange], _ ; auto
	[-432, -5376, " ", $vqrange], _
	[-634, -5828, " ", $vqrange], _
	[-951, -6861, " ", $vqrange], _
	[-1267, -7895, " ", $vqrange], _
	[-1584, -8928, " ", $vqrange], _
	[-1275, -9005, " ", $vqrange], _
	[-2204, -8290, " ", $vqrange], _
	[-3134, -7574, " ", $vqrange], _
	[-4327.8926, -6912, " ", $vqrange], _ ; auto
	[-4063, -6859, " ", $vqrange], _
	[-4822.9727, -6625.35, " ", $vqrange], _ ; auto
	[-4992, -6144, " ", $vqrange], _
	[-5928, -5322, " ", $vqrange], _
	[-7096, -4770, " ", $vqrange], _
	[-8263, -4218, " ", $vqrange], _
	[-9430, -3666, " ", $vqrange], _
	[-10598, -3114, " ", $vqrange], _
	[-11184, -1920, " ", $vqrange], _
	[-10873, -816, " ", $vqrange], _
	[-10562, 288, " ", $vqrange], _
	[-9772, 1067, " ", $vqrange], _
	[-9465, 2148, " ", $vqrange], _
	[-9158, 3230, " ", $vqrange], _
	[-8819, 4111, " ", $vqrange], _
	[-8480, 4992, " ", $vqrange], _
	[-9360, 5050, " ", $vqrange], _
	[-10241, 5109, " ", $vqrange], _
	[-9040, 4980, " ", $vqrange], _
	[-7839, 4851, " ", $vqrange], _
	[-8752, 5538, " ", $vqrange], _
	[-9665, 6225, " ", $vqrange], _
	[-10579, 6912, " ", $vqrange], _
	[-10869, 7276, " ", $vqrange], _
	[-11626, 8526, " ", $vqrange], _
	[-11256, 9728, " ", $vqrange], _
	[-11028, 8832, " ", $vqrange], _
	[-10338, 8832, " ", $vqrange], _
	[-10187, 8832, " ", $vqrange], _
	[-10036, 8832, " ", $vqrange], _
	[-9821, 8832, " ", $vqrange], _
	[-9648, 8832, " ", $vqrange], _
	[-8924, 9406, " ", $vqrange], _
	[-8200, 9981, " ", $vqrange], _
	[-7584, 10464, " ", $vqrange], _
	[-7168, 10464, " ", $vqrange], _
	[-7012, 10464, " ", $vqrange], _
	[-6856, 10464, " ", $vqrange], _
	[-6700, 10464, " ", $vqrange], _
	[-6545, 10464, " ", $vqrange], _
	[-6337, 10464, " ", $vqrange], _
	[-5921, 10464, " ", $vqrange], _
	[-4776, 10080, " ", $vqrange], _
	[-3983, 9940, " ", $vqrange], _
	[-3190, 9801, " ", $vqrange], _
	[-3822, 9102, " ", $vqrange], _
	[-3560, 9079, " ", $vqrange], _
	[-3375, 9063, " ", $vqrange], _
	[-2928, 9024, " ", $vqrange], _
	[-2424, 8451, " ", $vqrange], _
	[-1840, 7586, " ", $vqrange], _
	[-1256, 6721, " ", $vqrange], _
	[-672, 5856, " ", $vqrange], _
	[-1218, 4743, " ", $vqrange], _
	[-1763, 3630, " ", $vqrange], _
	[-2522, 2770, " ", $vqrange], _
	[-3282, 1911, " ", $vqrange], _
	[-4041, 1052, " ", $vqrange], _
	[-4800, 192, " ", $vqrange], _
	[-4181, 113, " ", $vqrange], _
	[-4800, 192, " ", $vqrange], _
	[-4423, 192, " ", $vqrange], _
	[-4234, 192, " ", $vqrange], _
	[-4070, 192, " ", $vqrange], _
	[-3905, 192, " ", $vqrange], _
	[-3669, 192, " ", $vqrange], _
	[-3292, 192, " ", $vqrange], _
	[-2538, 192, " ", $vqrange], _
	[-1784, 192, " ", $vqrange], _
	[-778, 192, " ", $vqrange], _
	[227, 192, " ", $vqrange], _
	[1232, 192, " ", $vqrange], _
	[1951, -984, " ", $vqrange], _
	[2611, -14, " ", $vqrange], _
	[3271, 957, " ", $vqrange], _
	[2499, 1786, " ", $vqrange], _
	[1728, 2614, " ", $vqrange], _
	[956, 3443, " ", $vqrange], _
	[184, 4272, " ", $vqrange], _
	[1345, 4488, " ", $vqrange], _
	[2506, 4704, " ", $vqrange], _
	[3667, 4919, " ", $vqrange], _
	[4828, 5135, " ", $vqrange], _
	[5713, 5988, " ", $vqrange], _
	[6598, 6842, " ", $vqrange], _
	[7482, 7696, " ", $vqrange], _
	[8367, 8549, " ", $vqrange], _
	[9219, 7451, " ", $vqrange], _
	[10071, 6352, " ", $vqrange], _
	[10923, 5254, " ", $vqrange], _
	[11376, 4224, " ", $vqrange], _
	[11727, 4215, " ", $vqrange], _
	[11881, 4211, " ", $vqrange], _
	[12078, 4206, " ", $vqrange], _
	[12232, 4202, " ", $vqrange], _
	[12385, 4198, " ", $vqrange], _
	[12539, 4194, " ", $vqrange], _
	[12692, 4190, " ", $vqrange], _
	[14184, 4152, " ", $vqrange], _
	[15280, 3792, " ", $vqrange], _
	[16376, 3432, " ", $vqrange], _
	[17472, 3072, " ", $vqrange], _
	[17822, 2507, " ", $vqrange], _
	[17102, 3625, " ", $vqrange], _
	[16381, 4744, " ", $vqrange], _
	[15661, 5862, " ", $vqrange], _
	[14940, 6981, " ", $vqrange], _
	[14220, 8099, " ", $vqrange], _
	[15520, 10111, " ", $vqrange], _
	[16209.7139, 9171, " ", $vqrange], _ ; auto
	[17418, 8581, " ", $vqrange], _
	[18973, 8433, " ", $vqrange], _
	[19623, 8179, " ", $vqrange], _
	[19782, 8184, " ", $vqrange], _
	[19940, 8188, " ", $vqrange], _
	[20258, 8198, " ", $vqrange], _
	[20892, 8217, " ", $vqrange], _
	[21069, 8231, " ", $vqrange], _
	[21222, 8243, " ", $vqrange], _
	[21374, 8255, " ", $vqrange], _
	[21673, 8279, " ", $vqrange], _
	[21803, 8558, " ", $vqrange], _
	[22059, 8556, " ", $vqrange], _
	[22212, 8554, " ", $vqrange], _
	[22366, 8553, " ", $vqrange], _
	[22519, 8552, " ", $vqrange], _
	[22673, 8551, " ", $vqrange], _
	[22826, 8549, " ", $vqrange], _
	[23031, 8548, " ", $vqrange], _
	[23440, 8544, " ", $vqrange], _
	[22850, 8471, " ", $vqrange], _
	[24070, 8805, " ", $vqrange], _
	[25057, 8966, " ", $vqrange], _
	[25243, 10408, " ", $vqrange] _
]

