#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_TheJadeSea/MaishangHills.au3
; Map: MaishangHills (id 199), geometry from MAP 0000154893.pmap
; Repaired 1 of 4 blocked segments by inserting 25 waypoints.
; Smoothed 72 additional anchor(s) for wall clearance and hop distance.
; Filled 3 long hop(s) by walking the current mesh component toward a disconnected goal.
; 3 segment(s) could not be routed and were left as-is.
; 3 hop(s) still exceed 1500 units (worst 10409 between index 240 and 241).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_TheJadeSea_MaishangHillsRoute01[319][4] = [ _
	[16423, -10318, " ", $vqrange], _
	[17298, -11009, " ", $vqrange], _
	[18172, -11699, " ", $vqrange], _
	[19047, -12390, " ", $vqrange], _
	[20338, -12695, " ", $vqrange], _
	[21315, -12774, " ", $vqrange], _
	[20231, -12655, " ", $vqrange], _
	[19147, -12537, " ", $vqrange], _
	[18064, -12418, " ", $vqrange], _
	[18053, -11548, " ", $vqrange], _
	[18043, -10677, " ", $vqrange], _
	[17929, -9478, " ", $vqrange], _
	[17815, -8280, " ", $vqrange], _
	[17701, -7081, " ", $vqrange], _
	[18402, -5832, " ", $vqrange], _
	[19104, -4583, " ", $vqrange], _
	[19805, -3334, " ", $vqrange], _
	[19520, -2436, " ", $vqrange], _
	[19234, -1539, " ", $vqrange], _
	[18500, -1044, " ", $vqrange], _
	[17767, -548, " ", $vqrange], _
	[18325, 755, " ", $vqrange], _
	[18882, 2057, " ", $vqrange], _
	[19440, 3360, " ", $vqrange], _
	[19742, 3713, " ", $vqrange], _
	[19785, 4939, " ", $vqrange], _
	[19829, 6166, " ", $vqrange], _
	[19872, 7392, " ", $vqrange], _
	[19589, 7580, " ", $vqrange], _
	[19740, 8454, " ", $vqrange], _
	[19891, 9327, " ", $vqrange], _
	[18574, 9754, " ", $vqrange], _
	[17256, 10181, " ", $vqrange], _
	[18400, 9908, " ", $vqrange], _
	[19544, 9634, " ", $vqrange], _
	[18787, 9630, " ", $vqrange], _
	[18030, 9626, " ", $vqrange], _
	[17841, 9624, " ", $vqrange], _
	[17652, 9623, " ", $vqrange], _
	[17462, 9622, " ", $vqrange], _
	[17297, 9621, " ", $vqrange], _
	[17131, 9620, " ", $vqrange], _
	[16895, 9619, " ", $vqrange], _
	[16516, 9617, " ", $vqrange], _
	[15507, 9611, " ", $vqrange], _
	[14497, 9606, " ", $vqrange], _
	[13488, 9600, " ", $vqrange], _
	[14057, 9514, " ", $vqrange], _
	[13332, 9244, " ", $vqrange], _
	[12606, 8973, " ", $vqrange], _
	[11174, 8629, " ", $vqrange], _
	[9742, 8285, " ", $vqrange], _
	[8730, 8560, " ", $vqrange], _
	[7717, 8836, " ", $vqrange], _
	[6705, 9111, " ", $vqrange], _
	[5506, 9442, " ", $vqrange], _
	[4307, 9773, " ", $vqrange], _
	[3108, 10104, " ", $vqrange], _
	[2244, 10368, " ", $vqrange], _
	[871, 10550, " ", $vqrange], _
	[346, 9839, " ", $vqrange], _
	[-178, 9128, " ", $vqrange], _
	[-549, 8048, " ", $vqrange], _
	[-919, 6967, " ", $vqrange], _
	[-1290, 5887, " ", $vqrange], _
	[-1919, 5044, " ", $vqrange], _
	[-2549, 4201, " ", $vqrange], _
	[-3178, 3358, " ", $vqrange], _
	[-5161.2104, 237.5789, " ", $vqrange], _
	[-5388.9078, 237.5842, " ", $vqrange], _ ; auto
	[-5616.6052, 237.5894, " ", $vqrange], _ ; auto
	[-6072, 237.6, " ", $vqrange], _ ; auto
	[-7080.0334, 919.68, " ", $vqrange], _ ; auto
	[-8088.0668, 1601.76, " ", $vqrange], _ ; auto
	[-9096.1002, 2283.84, " ", $vqrange], _ ; auto
	[-10104.1336, 2965.92, " ", $vqrange], _ ; auto
	[-11112.167, 3648, " ", $vqrange], _ ; auto
	[-10159.6113, 4077.3333, " ", $vqrange], _ ; auto
	[-9207.0557, 4506.6667, " ", $vqrange], _ ; auto
	[-8254.5, 4936, " ", $vqrange], _ ; auto
	[-7856.5, 4936, " ", $vqrange], _ ; auto
	[-7701.0312, 4936, " ", $vqrange], _ ; auto
	[-7545.5625, 4936, " ", $vqrange], _ ; auto
	[-7390.0938, 4936, " ", $vqrange], _ ; auto
	[-7234.625, 4936, " ", $vqrange], _ ; auto
	[-7060.5, 4936, " ", $vqrange], _ ; auto
	[-6662.5, 4936, " ", $vqrange], _ ; auto
	[-5913, 4457, " ", $vqrange], _
	[-6904, 4874, " ", $vqrange], _
	[-7895, 5291, " ", $vqrange], _
	[-8957, 4676, " ", $vqrange], _
	[-10019, 4062, " ", $vqrange], _
	[-11081, 3447, " ", $vqrange], _
	[-10219, 2938, " ", $vqrange], _
	[-9358, 2429, " ", $vqrange], _
	[-8496, 1920, " ", $vqrange], _
	[-8502, 1646, " ", $vqrange], _
	[-7287, 942, " ", $vqrange], _
	[-6072, 238, " ", $vqrange], _
	[-5800, -364, " ", $vqrange], _
	[-6712, -1430, " ", $vqrange], _
	[-7624, -2495, " ", $vqrange], _
	[-8582, -2524, " ", $vqrange], _
	[-9540, -2552, " ", $vqrange], _
	[-9388, -1352, " ", $vqrange], _
	[-9235, -153, " ", $vqrange], _
	[-8968, 1100, " ", $vqrange], _
	[-8702, 2353, " ", $vqrange], _
	[-10042, 2771, " ", $vqrange], _
	[-11381, 3189, " ", $vqrange], _
	[-11951, 1810, " ", $vqrange], _
	[-12521, 432, " ", $vqrange], _
	[-13091, -947, " ", $vqrange], _
	[-12884, -2407, " ", $vqrange], _
	[-13613, -1509, " ", $vqrange], _
	[-14343, -610, " ", $vqrange], _
	[-15072, 288, " ", $vqrange], _
	[-16046, 382, " ", $vqrange], _
	[-17021, 476, " ", $vqrange], _
	[-17552, -578, " ", $vqrange], _
	[-18084, -1632, " ", $vqrange], _
	[-18874, -2605, " ", $vqrange], _
	[-19037, -3762, " ", $vqrange], _
	[-19199, -4918, " ", $vqrange], _
	[-19362, -6075, " ", $vqrange], _
	[-18237, -6719, " ", $vqrange], _
	[-17113, -7362, " ", $vqrange], _
	[-15988, -8006, " ", $vqrange], _
	[-17113, -7362, " ", $vqrange], _
	[-18237, -6719, " ", $vqrange], _
	[-19362, -6075, " ", $vqrange], _
	[-19541, -4766, " ", $vqrange], _
	[-19720, -3458, " ", $vqrange], _
	[-19900, -2149, " ", $vqrange], _
	[-20079, -840, " ", $vqrange], _
	[-19978, 324, " ", $vqrange], _
	[-19876, 1489, " ", $vqrange], _
	[-19775, 2653, " ", $vqrange], _
	[-18651, 3519, " ", $vqrange], _
	[-18433, 4838, " ", $vqrange], _
	[-19177, 5539, " ", $vqrange], _
	[-19194, 6629, " ", $vqrange], _
	[-19210, 7720, " ", $vqrange], _
	[-19227, 8810, " ", $vqrange], _
	[-18433, 9475, " ", $vqrange], _
	[-17639, 10139, " ", $vqrange], _
	[-16845, 10804, " ", $vqrange], _
	[-15565, 11177, " ", $vqrange], _
	[-14284, 11550, " ", $vqrange], _
	[-13004, 11923, " ", $vqrange], _
	[-12186, 11610, " ", $vqrange], _
	[-11368, 11297, " ", $vqrange], _
	[-10203, 11147, " ", $vqrange], _
	[-9037, 10998, " ", $vqrange], _
	[-7872, 10848, " ", $vqrange], _
	[-8531, 11174, " ", $vqrange], _
	[-8671, 10051, " ", $vqrange], _
	[-8959, 8901, " ", $vqrange], _
	[-9624, 8160, " ", $vqrange], _
	[-10512, 7701, " ", $vqrange], _
	[-11400, 7242, " ", $vqrange], _
	[-10116, 7989, " ", $vqrange], _
	[-8832, 8736, " ", $vqrange], _
	[-8959, 8901, " ", $vqrange], _
	[-8128, 9586, " ", $vqrange], _
	[-7296, 10272, " ", $vqrange], _
	[-6546, 10303, " ", $vqrange], _
	[-5337, 9808, " ", $vqrange], _
	[-4128, 9312, " ", $vqrange], _
	[-3964, 8953, " ", $vqrange], _
	[-3240, 7978, " ", $vqrange], _
	[-2516, 7003, " ", $vqrange], _
	[-2418, 5950, " ", $vqrange], _
	[-2320, 4896, " ", $vqrange], _
	[-1452, 4076, " ", $vqrange], _
	[-585, 3255, " ", $vqrange], _
	[-1153, 2419, " ", $vqrange], _
	[-1720, 1583, " ", $vqrange], _
	[-2288, 747, " ", $vqrange], _
	[-2316, -322, " ", $vqrange], _
	[-2345, -1390, " ", $vqrange], _
	[-1460, -1920, " ", $vqrange], _
	[-576, -2449, " ", $vqrange], _
	[309, -2979, " ", $vqrange], _
	[1285, -3351, " ", $vqrange], _
	[2261, -3723, " ", $vqrange], _
	[3237, -4095, " ", $vqrange], _
	[3698, -5388, " ", $vqrange], _
	[4159, -6681, " ", $vqrange], _
	[2764, -7036, " ", $vqrange], _
	[1368, -7392, " ", $vqrange], _
	[1187, -7498, " ", $vqrange], _
	[1159, -8593, " ", $vqrange], _
	[1994, -9167, " ", $vqrange], _
	[2828, -9741, " ", $vqrange], _
	[3964, -9910, " ", $vqrange], _
	[5100, -10080, " ", $vqrange], _
	[5172, -10477, " ", $vqrange], _
	[6177, -9533, " ", $vqrange], _
	[7183, -8589, " ", $vqrange], _
	[8188, -7645, " ", $vqrange], _
	[9391, -8117, " ", $vqrange], _
	[10595, -8588, " ", $vqrange], _
	[11798, -9060, " ", $vqrange], _
	[10595, -8588, " ", $vqrange], _
	[9391, -8117, " ", $vqrange], _
	[8188, -7645, " ", $vqrange], _
	[8363, -6316, " ", $vqrange], _
	[8538, -4986, " ", $vqrange], _
	[9568, -4594, " ", $vqrange], _
	[10597, -4203, " ", $vqrange], _
	[11475, -3911, " ", $vqrange], _
	[12353, -3619, " ", $vqrange], _
	[12339, -2605, " ", $vqrange], _
	[12326, -1590, " ", $vqrange], _
	[12312, -576, " ", $vqrange], _
	[12598, 233, " ", $vqrange], _
	[13007, 896, " ", $vqrange], _
	[13416, 1560, " ", $vqrange], _
	[12845, 507, " ", $vqrange], _
	[12273, -546, " ", $vqrange], _
	[11702, -1599, " ", $vqrange], _
	[11424, -1920, " ", $vqrange], _
	[11147, -1920, " ", $vqrange], _
	[10870, -1920, " ", $vqrange], _
	[10315, -1920, " ", $vqrange], _
	[10308, -1080, " ", $vqrange], _ ; auto
	[9452, -848, " ", $vqrange], _
	[8588, 224, " ", $vqrange], _
	[9238, 1072, " ", $vqrange], _
	[9888, 1920, " ", $vqrange], _
	[9850, 2893, " ", $vqrange], _
	[9694, 2070, " ", $vqrange], _
	[9538, 1248, " ", $vqrange], _
	[8588, 224, " ", $vqrange], _
	[7160, 458, " ", $vqrange], _
	[5731, 692, " ", $vqrange], _
	[5475, 1921, " ", $vqrange], _
	[5220, 3150, " ", $vqrange], _
	[4964, 4379, " ", $vqrange], _
	[-4821, 3259, " ", $vqrange], _
	[-14726, 6458, " ", $vqrange], _
	[-13450, 6884, " ", $vqrange], _
	[-12175, 7309, " ", $vqrange], _
	[-10900, 7734, " ", $vqrange], _
	[-9624, 8160, " ", $vqrange], _
	[-8862, 9072, " ", $vqrange], _
	[-8101, 9984, " ", $vqrange], _
	[-7527, 9984, " ", $vqrange], _
	[-7366, 9984, " ", $vqrange], _
	[-7214, 9984, " ", $vqrange], _
	[-7062, 9984, " ", $vqrange], _
	[-6910, 9984, " ", $vqrange], _
	[-6668, 9984, " ", $vqrange], _
	[-6381, 9984, " ", $vqrange], _
	[-5808, 9984, " ", $vqrange], _
	[-4968, 9648, " ", $vqrange], _
	[-4128, 9312, " ", $vqrange], _
	[-3536, 8416, " ", $vqrange], _
	[-2944, 7520, " ", $vqrange], _
	[-2352, 6624, " ", $vqrange], _
	[-2336, 5760, " ", $vqrange], _
	[-2320, 4896, " ", $vqrange], _
	[-1659, 4096, " ", $vqrange], _
	[-997, 3296, " ", $vqrange], _
	[-336, 2496, " ", $vqrange], _
	[-1072, 1760, " ", $vqrange], _
	[-1808, 1024, " ", $vqrange], _
	[-2544, 288, " ", $vqrange], _
	[-2549, -981, " ", $vqrange], _
	[-1683, -1786, " ", $vqrange], _
	[-816, -2592, " ", $vqrange], _
	[582, -2808, " ", $vqrange], _
	[1980, -3024, " ", $vqrange], _
	[3378, -3240, " ", $vqrange], _
	[4776, -3456, " ", $vqrange], _
	[6174, -3672, " ", $vqrange], _
	[7572, -3888, " ", $vqrange], _
	[8970, -4104, " ", $vqrange], _
	[10368, -4320, " ", $vqrange], _
	[9264, -4896, " ", $vqrange], _
	[8160, -5472, " ", $vqrange], _
	[9154, -6405, " ", $vqrange], _
	[10149, -7338, " ", $vqrange], _
	[11143, -8271, " ", $vqrange], _
	[12138, -9204, " ", $vqrange], _
	[13105, -9623, " ", $vqrange], _
	[12078, -8831, " ", $vqrange], _
	[11050, -8039, " ", $vqrange], _
	[10023, -7248, " ", $vqrange], _
	[8995, -6456, " ", $vqrange], _
	[7968, -5664, " ", $vqrange], _
	[9024, -4896, " ", $vqrange], _
	[10080, -4128, " ", $vqrange], _
	[11308, -4106, " ", $vqrange], _
	[12537, -4085, " ", $vqrange], _
	[12406, -3043, " ", $vqrange], _
	[12275, -2002, " ", $vqrange], _
	[12144, -960, " ", $vqrange], _
	[12739, 114, " ", $vqrange], _
	[13334, 1187, " ", $vqrange], _
	[13930, 2260, " ", $vqrange], _
	[14525, 3334, " ", $vqrange], _
	[13905, 2283, " ", $vqrange], _
	[13285, 1232, " ", $vqrange], _
	[12664, 182, " ", $vqrange], _
	[12044, -869, " ", $vqrange], _
	[11424, -1920, " ", $vqrange], _
	[10868, -2417, " ", $vqrange], _
	[10318, -1316, " ", $vqrange], _
	[9768, -216, " ", $vqrange], _
	[9743, 1264, " ", $vqrange], _
	[9718, 2744, " ", $vqrange], _
	[9692, 4224, " ", $vqrange], _
	[8722, 4848, " ", $vqrange], _
	[7752, 5472, " ", $vqrange], _
	[6731, 5623, " ", $vqrange], _
	[5711, 5775, " ", $vqrange], _
	[4691, 5926, " ", $vqrange] _
]

