#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: vendor/vanquish-bot/Maps/Factions_TheJadeSea/UnwakingWaters.au3
; Map: UnwakingWaters (id 227), geometry from MAP 0000155168.pmap
; Repaired 7 of 8 blocked segments by inserting 10 waypoints.
; Smoothed 38 additional anchor(s) for wall clearance and hop distance.
; 1 segment(s) could not be routed and were left as-is.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.

Global $aFactions_TheJadeSea_UnwakingWatersRoute01[71][2] = [ _
	[3464, 1917], _
	[4039.6266, 2405], _ ; auto
	[4615.2532, 2893], _ ; auto
	[4567.7782, 3659.5], _ ; auto
	[4520.3032, 4426], _ ; auto
	[3858.1555, 5248], _ ; auto
	[3079, 5448], _
	[798, 3819], _
	[912.5, 2584], _ ; auto
	[1027, 1349], _
	[1437.5, 674.5], _ ; auto
	[1848, 0], _ ; auto
	[2464.3485, -466], _ ; auto
	[3080.697, -932], _ ; auto
	[3400, -1051], _
	[4702.3333, -884], _ ; auto
	[6004.6667, -717], _ ; auto
	[7307, -550], _
	[8380.3333, -577], _ ; auto
	[9453.6667, -604], _ ; auto
	[10527, -631], _
	[11794, 18.3333], _ ; auto
	[13061, 667.6667], _ ; auto
	[14328, 1317], _
	[12976.5443, 1550], _ ; auto
	[11625.0885, 1783], _ ; auto
	[10273.6328, 2016], _ ; auto
	[10432.3164, 2808.5], _ ; auto
	[10591, 3601], _
	[10507.259, 2448.6667], _ ; auto
	[10423.5179, 1296.3333], _ ; auto
	[10339.7769, 144], _ ; auto
	[9321.1846, 123.6667], _ ; auto
	[8302.5923, 103.3333], _ ; auto
	[7284, 83], _
	[7086, 1018], _
	[7891.6667, 2269], _ ; auto
	[8697.3333, 3520], _ ; auto
	[9503, 4771], _
	[9642, 4987], _
	[10328.5, 6101], _ ; auto
	[11015, 7215], _
	[9757.25, 7286.5], _ ; auto
	[8499.5, 7358], _ ; auto
	[7241.75, 7429.5], _ ; auto
	[5984, 7501], _
	[4848.6824, 7816.6667], _ ; auto
	[3713.3647, 8132.3333], _ ; auto
	[2578.0471, 8448], _ ; auto
	[1519, 8470], _
	[542, 7778.6667], _ ; auto
	[-435, 7087.3333], _ ; auto
	[-1412, 6396], _
	[-2630, 5805.6667], _ ; auto
	[-3848, 5215.3333], _ ; auto
	[-5066, 4625], _
	[-6260, 3873], _ ; auto
	[-7454, 3121], _ ; auto
	[-8648, 2369], _
	[-7327.8082, 2158.5], _ ; auto
	[-6007.6165, 1948], _ ; auto
	[-5463.8082, 906], _ ; auto
	[-4920, -136], _
	[-4320, 894], _ ; auto
	[-3720, 1924], _
	[-3876, 674], _ ; auto
	[-4032, -576], _ ; auto
	[-2685, -954], _
	[-2396.6667, 308], _ ; auto
	[-2108.3333, 1570], _ ; auto
	[-1820, 2832] _
]

