#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_TheJadeSea/UnwakingWaters.au3
; Map: UnwakingWaters (id 227), geometry from MAP 0000155168.pmap
; Repaired 1 of 1 blocked segments by inserting 1 waypoints.
; Smoothed 7 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.

Global $aFactions_TheJadeSea_UnwakingWatersRoute01[79][2] = [ _
	[3464, 1917], _
	[4040, 2405], _
	[4615, 2893], _
	[4568, 3660], _
	[4520, 4426], _
	[3858, 5248], _
	[3079, 5448], _
	[2672.5, 5365], _ ; auto
	[2523.2383, 5334.5234], _ ; auto
	[2266, 5282], _ ; auto
	[2082.5, 5099.125], _ ; auto
	[1899, 4916.25], _ ; auto
	[1532, 4550.5], _ ; auto
	[798, 3819], _
	[912, 2584], _
	[1027, 1349], _
	[1080, 768], _ ; auto
	[1438, 674], _
	[1848, 0], _
	[2464, -466], _
	[3081, -932], _
	[3400, -1051], _
	[4702, -884], _
	[6005, -717], _
	[7307, -550], _
	[8380, -577], _
	[9454, -604], _
	[10527, -631], _
	[11794, 18], _
	[13061, 668], _
	[14328, 1317], _
	[12977, 1550], _
	[11625, 1783], _
	[10274, 2016], _
	[10432, 2808], _
	[10591, 3601], _
	[10507, 2449], _
	[10424, 1296], _
	[10340, 144], _
	[9321, 124], _
	[8303, 103], _
	[7284, 83], _
	[7086, 1018], _
	[7892, 2269], _
	[8304.3328, 3168], _ ; auto
	[8697, 3520], _
	[9503, 4771], _
	[9642, 4987], _
	[10328, 6101], _
	[11015, 7215], _
	[9757, 7286], _
	[8500, 7358], _
	[7242, 7430], _
	[5984, 7501], _
	[4849, 7817], _
	[3713, 8132], _
	[2578, 8448], _
	[1519, 8470], _
	[542, 7779], _
	[-435, 7087], _
	[-1412, 6396], _
	[-2630, 5806], _
	[-3848, 5215], _
	[-5066, 4625], _
	[-6260, 3873], _
	[-7454, 3121], _
	[-8648, 2369], _
	[-7328, 2158], _
	[-6008, 1948], _
	[-5464, 906], _
	[-4920, -136], _
	[-4320, 894], _
	[-3720, 1924], _
	[-3876, 674], _
	[-4032, -576], _
	[-2685, -954], _
	[-2397, 308], _
	[-2108, 1570], _
	[-1820, 2832] _
]

