#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_TheJadeSea/UnwakingWaters.au3
; Map: UnwakingWaters (id 227), geometry from MAP 0000155168.pmap
; Repaired 1 of 1 blocked segments by inserting 1 waypoints.
; Smoothed 7 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_TheJadeSea_UnwakingWatersRoute01[79][4] = [ _
	[3464, 1917, " ", $vqrange], _
	[4040, 2405, " ", $vqrange], _
	[4615, 2893, " ", $vqrange], _
	[4568, 3660, " ", $vqrange], _
	[4520, 4426, " ", $vqrange], _
	[3858, 5248, " ", $vqrange], _
	[3079, 5448, " ", $vqrange], _
	[2672.5, 5365, " ", $vqrange], _ ; auto
	[2523.2383, 5334.5234, " ", $vqrange], _ ; auto
	[2266, 5282, " ", $vqrange], _ ; auto
	[2082.5, 5099.125, " ", $vqrange], _ ; auto
	[1899, 4916.25, " ", $vqrange], _ ; auto
	[1532, 4550.5, " ", $vqrange], _ ; auto
	[798, 3819, " ", $vqrange], _
	[912, 2584, " ", $vqrange], _
	[1027, 1349, " ", $vqrange], _
	[1080, 768, " ", $vqrange], _ ; auto
	[1438, 674, " ", $vqrange], _
	[1848, 0, " ", $vqrange], _
	[2464, -466, " ", $vqrange], _
	[3081, -932, " ", $vqrange], _
	[3400, -1051, " ", $vqrange], _
	[4702, -884, " ", $vqrange], _
	[6005, -717, " ", $vqrange], _
	[7307, -550, " ", $vqrange], _
	[8380, -577, " ", $vqrange], _
	[9454, -604, " ", $vqrange], _
	[10527, -631, " ", $vqrange], _
	[11794, 18, " ", $vqrange], _
	[13061, 668, " ", $vqrange], _
	[14328, 1317, " ", $vqrange], _
	[12977, 1550, " ", $vqrange], _
	[11625, 1783, " ", $vqrange], _
	[10274, 2016, " ", $vqrange], _
	[10432, 2808, " ", $vqrange], _
	[10591, 3601, " ", $vqrange], _
	[10507, 2449, " ", $vqrange], _
	[10424, 1296, " ", $vqrange], _
	[10340, 144, " ", $vqrange], _
	[9321, 124, " ", $vqrange], _
	[8303, 103, " ", $vqrange], _
	[7284, 83, " ", $vqrange], _
	[7086, 1018, " ", $vqrange], _
	[7892, 2269, " ", $vqrange], _
	[8304.3328, 3168, " ", $vqrange], _ ; auto
	[8697, 3520, " ", $vqrange], _
	[9503, 4771, " ", $vqrange], _
	[9642, 4987, " ", $vqrange], _
	[10328, 6101, " ", $vqrange], _
	[11015, 7215, " ", $vqrange], _
	[9757, 7286, " ", $vqrange], _
	[8500, 7358, " ", $vqrange], _
	[7242, 7430, " ", $vqrange], _
	[5984, 7501, " ", $vqrange], _
	[4849, 7817, " ", $vqrange], _
	[3713, 8132, " ", $vqrange], _
	[2578, 8448, " ", $vqrange], _
	[1519, 8470, " ", $vqrange], _
	[542, 7779, " ", $vqrange], _
	[-435, 7087, " ", $vqrange], _
	[-1412, 6396, " ", $vqrange], _
	[-2630, 5806, " ", $vqrange], _
	[-3848, 5215, " ", $vqrange], _
	[-5066, 4625, " ", $vqrange], _
	[-6260, 3873, " ", $vqrange], _
	[-7454, 3121, " ", $vqrange], _
	[-8648, 2369, " ", $vqrange], _
	[-7328, 2158, " ", $vqrange], _
	[-6008, 1948, " ", $vqrange], _
	[-5464, 906, " ", $vqrange], _
	[-4920, -136, " ", $vqrange], _
	[-4320, 894, " ", $vqrange], _
	[-3720, 1924, " ", $vqrange], _
	[-3876, 674, " ", $vqrange], _
	[-4032, -576, " ", $vqrange], _
	[-2685, -954, " ", $vqrange], _
	[-2397, 308, " ", $vqrange], _
	[-2108, 1570, " ", $vqrange], _
	[-1820, 2832, " ", $vqrange] _
]

