#include-once

; Generated by scripts/import_goout_outpost.py — do not edit by hand.
; Outpost exit lookup for MapTravel_TryGetCaravanPortalPath.

Func MapTravel_TryGetOutpostPath($a_i_FromMap, $a_s_TargetTitle, ByRef $a_a_Path, ByRef $a_s_Label)
	Switch $a_s_TargetTitle
		Case "AnvilRock"
			If $a_i_FromMap = $AnvilRock_Outpost Then
				$a_a_Path = $aAnvilRockOutpostPath
				$a_s_Label = "Ice Tooth Cave->AnvilRock "
				Return True
			EndIf
		Case "CrystalOverlook"
			If $a_i_FromMap = $CrystalOverlook_Outpost Then
				$a_a_Path = $aCrystalOverlookOutpostPath
				$a_s_Label = "The Mouth of Torment->CrystalOverlook "
				Return True
			EndIf
		Case "CursedLands"
			If $a_i_FromMap = $CursedLands_Outpost Then
				$a_a_Path = $aCursedLandsOutpostPath
				$a_s_Label = "Temple of the Ages->CursedLands "
				Return True
			EndIf
		Case "DaladaUplands"
			If $a_i_FromMap = $DaladaUplands_Outpost Then
				$a_a_Path = $aDaladaUplandsOutpostPath
				$a_s_Label = "Doomlore Shrine->DaladaUplands "
				Return True
			EndIf
		Case "DeldrimorBowl"
			If $a_i_FromMap = $DeldrimorBowl_Outpost Then
				$a_a_Path = $aDeldrimorBowlOutpostPath
				$a_s_Label = "Beacons Perch->DeldrimorBowl "
				Return True
			EndIf
		Case "DivinersAscent"
			If $a_i_FromMap = $DivinersAscent_Outpost Then
				$a_a_Path = $aDivinersAscentOutpostPath
				$a_s_Label = "Elona Reach->DivinersAscent "
				Return True
			EndIf
		Case "DryTop"
			If $a_i_FromMap = $DryTop_Outpost Then
				$a_a_Path = $aDryTopOutpostPath
				$a_s_Label = "Aurora Glade->DryTop "
				Return True
			EndIf
		Case "EttinsBack"
			If $a_i_FromMap = $EttinsBack_Outpost Then
				$a_a_Path = $aEttinsBackOutpostPath
				$a_s_Label = "Quarrel Falls->EttinsBack "
				Return True
			EndIf
		Case "GrenthsFootprint"
			If $a_i_FromMap = $GrenthsFootprint_Outpost Then
				$a_a_Path = $aGrenthsFootprintOutpostPath
				$a_s_Label = "Deldrimor's Terrace->GrenthsFootprint "
				Return True
			EndIf
		Case "GriffonsMouth"
			If $a_i_FromMap = $GriffonsMouth_Outpost Then
				$a_a_Path = $aGriffonsMouthOutpostPath
				$a_s_Label = "Gates of Kryta->GriffonsMouth "
				Return True
			EndIf
		Case "IronHorseMine"
			If $a_i_FromMap = $IronHorseMine_Outpost Then
				$a_a_Path = $aIronHorseMineOutpostPath
				$a_s_Label = "Ice Tooth Cave->IronHorseMine "
				Return True
			EndIf
		Case "JokosDomain"
			If $a_i_FromMap = $JokosDomain_Outpost Then
				$a_a_Path = $aJokosDomainOutpostPath
				$a_s_Label = "Bone Palace->JokosDomain "
				Return True
			EndIf
		Case "KessexPeak"
			If $a_i_FromMap = $KessexPeak_Outpost Then
				$a_a_Path = $aKessexPeakOutpostPath
				$a_s_Label = "Temple of the Ages->KessexPeak "
				Return True
			EndIf
		Case "MajestysRest"
			If $a_i_FromMap = $MajestysRest_Outpost Then
				$a_a_Path = $aMajestysRestOutpostPath
				$a_s_Label = "Temple of the Ages->MajestysRest "
				Return True
			EndIf
		Case "MamnoonLagoon"
			If $a_i_FromMap = $MamnoonLagoon_Outpost Then
				$a_a_Path = $aMamnoonLagoonOutpostPath
				$a_s_Label = "Quarrel Falls->MamnoonLagoon "
				Return True
			EndIf
		Case "MineralSprings"
			If $a_i_FromMap = $MineralSprings_Outpost Then
				$a_a_Path = $aMineralSpringsOutpostPath
				$a_s_Label = "MineralSprings->MineralSprings "
				Return True
			EndIf
		Case "NeboTerrace"
			If $a_i_FromMap = $NeboTerrace_Outpost Then
				$a_a_Path = $aNeboTerraceOutpostPath
				$a_s_Label = "Temple of the Ages->NeboTerrace "
				Return True
			EndIf
		Case "NorthKrytaProvince"
			If $a_i_FromMap = $NorthKrytaProvince_Outpost Then
				$a_a_Path = $aNorthKrytaProvinceOutpostPath
				$a_s_Label = "Lion's Arch->NorthKrytaProvince "
				Return True
			EndIf
		Case "PerditionRock"
			If $a_i_FromMap = $PerditionRock_Outpost Then
				$a_a_Path = $aPerditionRockOutpostPath
				$a_s_Label = "PerditionRock->PerditionRock "
				Return True
			EndIf
		Case "PoisonedOutcrops"
			If $a_i_FromMap = $PoisonedOutcrops_Outpost Then
				$a_a_Path = $aPoisonedOutcropsOutpostPath
				$a_s_Label = "Lair of the Forgotten->PoisonedOutcrops "
				Return True
			EndIf
		Case "ProphetsPath"
			If $a_i_FromMap = $ProphetsPath_Outpost Then
				$a_a_Path = $aProphetsPathOutpostPath
				$a_s_Label = "ProphetsPath->ProphetsPath "
				Return True
			EndIf
		Case "ReedBog"
			If $a_i_FromMap = $ReedBog_Outpost Then
				$a_a_Path = $aReedBogOutpostPath
				$a_s_Label = "ReedBog->ReedBog "
				Return True
			EndIf
		Case "SacnothValley"
			If $a_i_FromMap = $SacnothValley_Outpost Then
				$a_a_Path = $aSacnothValleyOutpostPath
				$a_s_Label = "Doomlore Shrine->SacnothValley "
				Return True
			EndIf
		Case "SageLands"
			If $a_i_FromMap = $SageLands_Outpost Then
				$a_a_Path = $aSageLandsOutpostPath
				$a_s_Label = "Druid Overlook->SageLands "
				Return True
			EndIf
		Case "SaltFlats"
			If $a_i_FromMap = $SaltFlats_Outpost Then
				$a_a_Path = $aSaltFlatsOutpostPath
				$a_s_Label = "Seekers Passage->SaltFlats "
				Return True
			EndIf
		Case "ScoundrelsRise"
			If $a_i_FromMap = $ScoundrelsRise_Outpost Then
				$a_a_Path = $aScoundrelsRiseOutpostPath
				$a_s_Label = "Gates of Kryta->ScoundrelsRise "
				Return True
			EndIf
		Case "Silverwood"
			If $a_i_FromMap = $Silverwood_Outpost Then
				$a_a_Path = $aSilverwoodOutpostPath
				$a_s_Label = "Quarrel Falls->Silverwood "
				Return True
			EndIf
		Case "SkywardReach"
			If $a_i_FromMap = $SkywardReach_Outpost Then
				$a_a_Path = $aSkywardReachOutpostPath
				$a_s_Label = "Augury Rock->SkywardReach "
				Return True
			EndIf
		Case "SpearheadPeak"
			If $a_i_FromMap = $SpearheadPeak_Outpost Then
				$a_a_Path = $aSpearheadPeakOutpostPath
				$a_s_Label = "The Granite Citadel->SpearheadPeak "
				Return True
			EndIf
		Case "TangleRoot"
			If $a_i_FromMap = $TangleRoot_Outpost Then
				$a_a_Path = $aTangleRootOutpostPath
				$a_s_Label = "Henge of Denravi->TangleRoot "
				Return True
			EndIf
		Case "TascasDemise"
			If $a_i_FromMap = $TascasDemise_Outpost Then
				$a_a_Path = $aTascasDemiseOutpostPath
				$a_s_Label = "TascasDemise->TascasDemise "
				Return True
			EndIf
		Case "TheAlkaliPan"
			If $a_i_FromMap = $TheAlkaliPan_Outpost Then
				$a_a_Path = $aTheAlkaliPanOutpostPath
				$a_s_Label = "Ruins of Morah->TheAlkaliPan "
				Return True
			EndIf
		Case "TheAridSea"
			If $a_i_FromMap = $TheAridSea_Outpost Then
				$a_a_Path = $aTheAridSeaOutpostPath
				$a_s_Label = "Dunes of Despair->TheAridSea "
				Return True
			EndIf
		Case "TheBlackCurtain"
			If $a_i_FromMap = $TheBlackCurtain_Outpost Then
				$a_a_Path = $aTheBlackCurtainOutpostPath
				$a_s_Label = "Temple of the Ages->TheBlackCurtain "
				Return True
			EndIf
		Case "TheFalls"
			If $a_i_FromMap = $TheFalls_Outpost Then
				$a_a_Path = $aTheFallsOutpostPath
				$a_s_Label = "Ventari's Refuge->TheFalls "
				Return True
			EndIf
		Case "TheRupturedHeart"
			If $a_i_FromMap = $TheRupturedHeart_Outpost Then
				$a_a_Path = $aTheRupturedHeartOutpostPath
				$a_s_Label = "The Mouth of Torment->TheRupturedHeart "
				Return True
			EndIf
		Case "TheScar"
			If $a_i_FromMap = $TheScar_Outpost Then
				$a_a_Path = $aTheScarOutpostPath
				$a_s_Label = "Thirsty River->TheScar "
				Return True
			EndIf
		Case "TheShatteredRavines"
			If $a_i_FromMap = $TheShatteredRavines_Outpost Then
				$a_a_Path = $aTheShatteredRavinesOutpostPath
				$a_s_Label = "Lair of the Forgotten->TheShatteredRavines "
				Return True
			EndIf
		Case "TwinSerpentLakes"
			If $a_i_FromMap = $TwinSerpentLakes_Outpost Then
				$a_a_Path = $aTwinSerpentLakesOutpostPath
				$a_s_Label = "Riverside Province->TwinSerpentLakes "
				Return True
			EndIf
		Case "WatchtowerCoast"
			If $a_i_FromMap = $WatchtowerCoast_Outpost Then
				$a_a_Path = $aWatchtowerCoastOutpostPath
				$a_s_Label = "Beetletun->WatchtowerCoast "
				Return True
			EndIf
		Case "WitmansFolly"
			If $a_i_FromMap = $WitmansFolly_Outpost Then
				$a_a_Path = $aWitmansFollyOutpostPath
				$a_s_Label = "WitmansFolly->WitmansFolly "
				Return True
			EndIf
	EndSwitch
	Return False
EndFunc
