;Ascalon IDs Caravan Yack's to Traveler's Vale - Select Ascalon
Global $AscalonFoothills_Map = 103            ;Grendich Courthouse
Global $AscalonFoothills_Transit = 99         ;Traveler's Vale
Global $DiessaLowlands_Map = 13               ;Nolani Academy
Global $DiessaLowlands_Transit = 103          ;Ascalon Foothills
Global $DragonsGullet_Map = 105                 ;Grendich Courthouse
Global $DragonsGullet_Transit = 106           ;Flame Temple Corridor
Global $DragonsGullet_Transit2 = 13           ;Diessa Lowlands (Diessa -> FTC)
Global $EasternFrontier_Map = 107             ;Frontier Gate
Global $EasternFrontier_Transit = 104         ;Pockmark Flats
Global $FlameTempleCorridor_Map = 106         ;Grendich Courthouse
Global $FlameTempleCorridor_Transit = 13      ;Diessa Lowlands
Global $OldAscalon_Map = 33                  ;
Global $OldAscalon_Transit = 102              ;The Breach
Global $PockmarkFlats_Map = 104
Global $PockmarkFlats_Transit = 101           ;Regent Valley
Global $RegentValley_Map = 101
Global $RegentValley_Transit = 33             ;Old Ascalon
Global $TheBreach_Map = 102
Global $TheBreach_Transit = 13                ;Diessa Lowlands
Global $TheBreach_Transit2 = 106              ;Flame Temple Corridor (return from Dragon's Gullet)
Global $TheBreach_Transit3 = 105              ;Dragon's Gullet (return start)
;NorthernShiverpeaks IDs
Global $AnvilRock_Map = 89
Global $AnvilRock_Outpost = 132               ;Ice Tooth Cave
Global $AnvilRock_Transit = 100               ;Deldrimor Bowl
Global $DeldrimorBowl_Map = 100
Global $DeldrimorBowl_Outpost = 133           ;Beacons Perch
Global $GriffonsMouth_Map = 27
Global $GriffonsMouth_Outpost = 14            ;Gates of Kryta
Global $GriffonsMouth_Transit = 54           ;Scoundrels Rise
Global $IronHorseMine_Map = 88
Global $IronHorseMine_Outpost = 132           ;Ice Tooth Cave
Global $IronHorseMine_Transit = 89            ;Anvil Rock
Global $TravelersVale_Map = 99
Global $TravelersVale_Outpost = 134           ;Yak's Bend
;Maguuma IDs
Global $DryTop_Map = 47
Global $DryTop_Outpost = 141                  ;Aurora Glade
Global $DryTop_Transit = 48                   ;Tangle Root
Global $DryTop_Transit2 = 44                  ;Ettin's Back (southern Maguuma caravan split)
Global $EttinsBack_Map = 44
Global $EttinsBack_Outpost = 142              ;Quarrel Falls
Global $MamnoonLagoon_Map = 42
Global $MamnoonLagoon_Outpost = 142           ;Quarrel Falls
Global $MamnoonLagoon_Transit = 43            ;Silverwood
Global $MamnoonLagoon_Transit2 = 41           ;Sage Lands
Global $ReedBog_Map = 45
Global $ReedBog_Outpost = 139
Global $ReedBog_Transit = 44                  ;Ettin's Back
Global $SageLands_Map = 41
Global $SageLands_Outpost = 140               ;Druid Overlook
Global $SageLands_Transit = 60                ;Majesty's Rest (Kryta <-> Maguuma portal)
Global $Silverwood_Map = 43
Global $Silverwood_Outpost = 142              ;Quarrel Falls
Global $TangleRoot_Map = 48
Global $TangleRoot_Outpost = 49               ;Henge of Denravi
Global $TheFalls_Map = 46
Global $TheFalls_Outpost = 139                 ;Ventari's Refuge
Global $TheFalls_Transit = 44                  ;Ettin's Back
Global $TheFalls_Transit2 = 45                 ;Reed Bog
;CrystalDesert IDs
Global $DivinersAscent_Map = 110
Global $DivinersAscent_Outpost = 118          ;Elona Reach
Global $ProphetsPath_Map = 113
Global $ProphetsPath_Outpost = 152
Global $SaltFlats_Map = 114
Global $SaltFlats_Outpost = 153               ;Seekers Passage
Global $SkywardReach_Map = 115
Global $SkywardReach_Outpost = 38             ;Augury Rock
Global $TheAridSea_Map = 112
Global $TheAridSea_Outpost = 116              ;Dunes of Despair
Global $TheAridSea_Transit = 111              ;Vulture Drifts
Global $TheScar_Map = 108
Global $TheScar_Outpost = 117                  ;Thirsty River
Global $VultureDrifts_Map = 111
Global $VultureDrifts_Outpost = 116            ;Dunes of Despair
;Kryta IDs
Global $CursedLands_Map = 56
Global $CursedLands_Outpost = 138             ;Temple of the Ages
Global $CursedLands_Transit = 18              ;The Black Curtain
Global $KessexPeak_Map = 64
Global $KessexPeak_Outpost = 138              ;Temple of the Ages
Global $KessexPeak_Transit = 18               ;The Black Curtain
Global $MajestysRest_Map = 60
Global $MajestysRest_Outpost = 138            ;Temple of the Ages
Global $MajestysRest_Transit = 18             ;The Black Curtain
Global $MajestysRest_Transit2 = 17            ;Talmark Wilderness
Global $NeboTerrace_Map = 59
Global $NeboTerrace_Outpost = 138              ;Temple of the Ages
Global $NeboTerrace_Transit = 18               ;The Black Curtain
Global $NeboTerrace_Transit2 = 56              ;Cursed Lands
Global $NorthKrytaProvince_Map = 58
Global $NorthKrytaProvince_Outpost = 55        ;Lion's Arch
Global $ScoundrelsRise_Map = 54
Global $ScoundrelsRise_Outpost = 14            ;Gates of Kryta
Global $StingrayStrand_Map = 63
Global $StingrayStrand_Outpost = $GC_I_MAP_ID_RIVERSIDE_PROVINCE_OUTPOST ; 73 — Riverside Province
Global $TalmarkWilderness_Map = 17
Global $TalmarkWilderness_Outpost = 138       ;Temple of the Ages
Global $TalmarkWilderness_Transit = 18        ;The Black Curtain
Global $TearsoftheFallen_Map = 53
Global $TearsoftheFallen_Outpost = $GC_I_MAP_ID_FISHERMENS_HAVEN ; 137 — Fisherman's Haven
Global $TearsoftheFallen_Transit = 63 	      ; Stingray Strand (first portal from haven)
Global $TheBlackCurtain_Map = 18
Global $TheBlackCurtain_Outpost = 138
Global $TwinSerpentLakes_Map = 61
Global $TwinSerpentLakes_Outpost = 73         ;Riverside Province
Global $WatchtowerCoast_Map = 62
Global $WatchtowerCoast_Outpost = 136          ;Beetletun
;SouthernShiverpeaks IDs
Global $DreadnoughtsDrift_Map = 97
Global $DreadnoughtsDrift_Outpost = 155           ;Camp Rankor
Global $DreadnoughtsDrift_Transit = 91            ;Snake Dance
Global $FrozenForest_Map = 98
Global $FrozenForest_Outpost = 24              ;Copperhammer Mines
Global $GrenthsFootprint_Map = 191
Global $GrenthsFootprint_Outpost = 206         ;Deldrimor's Terrace
Global $IceFloe_Map = 94
Global $IceFloe_Outpost = 23                  ;Ice Caves of Sorrow
Global $Icedome_Map = 87
Global $Icedome_Outpost = 22                  ;Marhan's Grotto
Global $Icedome_Transit = 26                  ;Talus Chute
Global $LornarsPass_Map = 90
Global $LornarsPass_Outpost = 133              ;Beacon's Perch
Global $LornarsPass_Transit = 88               ;Iron Horse Mine
Global $LornarsPass_Transit2 = 91              ;Snake Dance
Global $MineralSprings_Map = 96
Global $MineralSprings_Outpost = 156
Global $MineralSprings_Transit = 92           ;Tasca's Demise
Global $SnakeDance_Map = 91
Global $SnakeDance_Outpost = 155               ;Camp Rankor
Global $SpearheadPeak_Map = 93
Global $SpearheadPeak_Outpost = 159            ;The Granite Citadel
Global $TalusChute_Map = 26
Global $TalusChute_Outpost = 20
Global $TascasDemise_Map = 92			; Granite Citadel
Global $TascasDemise_Outpost =156
Global $WitmansFolly_Map = 95
Global $WitmansFolly_Outpost = 20
;RingOfFireIsland IDs
Global $PerditionRock_Outpost = 35
Global $PerditionRock_Map = 121
;ShingJeaIsland IDs
Global $HaijuLagoon_Map = 237
Global $HaijuLagoon_Outpost = 213		;Zen DaiJun
Global $JayaBluffs_Map = 196
Global $JayaBluffs_Outpost = 250                ;Seitung Harbor
Global $KinyaProvince_Map = 236
Global $KinyaProvince_Outpost = 251		;Ran Musu Garden
Global $MinisterChosEstate_Map = 245
Global $MinisterChosEstate_Outpost = 251
Global $RanMusuGardens_OutPost =251
Global $PanjiangPeninsula_Map = 235
Global $PanjiangPeninsula_Outpost = 249         ;Tsumei Village
Global $SaoshangTrail_Map = 313
Global $SaoshangTrail_Outpost = 250             ;Seitung Harbor
Global $SunquaVale_Map = 238
Global $SunquaVale_Outpost = 242                ;Shing Jea Monastery
Global $ZenDaijun_Map = 246			
Global $ZenDaijun_Outpost = 250			;Seitung Harbor
;KainengCity IDs
Global $BukdekByway_Map = 240
Global $BukdekByway_Outpost = 303
Global $NahpuiQuarter_Map = 265
Global $NahpuiQuarter_Outpost = 51
Global $PongmeiValley_Map = 211
Global $PongmeiValley_Outpost = 283
Global $RaisuPalace_Map = 233
Global $RaisuPalace_Outpost = 226
Global $ShadowsPassage_Map = 232
Global $ShadowsPassage_Outpost = 274
Global $ShenzunTunnels_Map = 197
Global $ShenzunTunnels_Outpost = 283
Global $SunjiangDistrict_Map = 256
Global $SunjiangDistrict_Outpost = 284
Global $TahnnakiTemple_Map = 269
Global $TahnnakiTemple_Outpost = 284
Global $WajjunBazaar_Map = 239
Global $WajjunBazaar_Outpost = 303
Global $XaquangSkyway_Map = 31
Global $XaquangSkyway_Outpost = 51              ;Senji's Corner
;Echovald Forest IDs
Global $Arborstone_Map = 244
Global $Arborstone_Outpost = 272
Global $DrazachThicket_Map = 195
Global $DrazachThicket_Outpost = 222
Global $Ferndale_Map = 210
Global $Ferndale_Outpost = 77
Global $MelandrusHope_Map = 201
Global $MelandrusHope_Outpost = 390
Global $MorostavTrail_Map = 205
Global $MorostavTrail_Outpost = 298
Global $MourningVeilFalls_Map = 209
Global $MourningVeilFalls_Outpost = 230
Global $TheEternalGrove_Map = 128
Global $TheEternalGrove_Outpost = 130
;TheJadeSea IDs
Global $Archipelagos_Map = 198
Global $Archipelagos_Outpost = 193
Global $BoreasSeabed_Map = 247
Global $BoreasSeabed_Outpost = 273
Global $GyalaHatchery_Map = 144
Global $GyalaHatchery_Outpost = 279
Global $MaishangHills_Map = 199
Global $MaishangHills_Outpost = 224
Global $MountQinkai_Map = 200
Global $MountQinkai_Outpost = 389
Global $RheasCrater_Map = 202
Global $RheasCrater_Outpost = 234
Global $SilentSurf_Map = 203
Global $SilentSurf_Outpost = 279
Global $UnwakingWaters_Map = 227
Global $UnwakingWaters_Outpost = 277
;Istan IDs
Global $CliffsOfDohjok_Map = 432
Global $CliffsOfDohjok_Outpost = 492		;Blacktide Den
Global $FahranurTheFirstCity_Map = 481
Global $FahranurTheFirstCity_Outpost = 492	;Blacktide Den
Global $IssnurIsles_Map = 486
Global $IssnurIsles_Outpost = 487		;Beknur Harbor
Global $LahtendaBog_Map = 484
Global $LahtendaBog_Outpost = 492		;Blacktide Den
Global $MehtaniKeys_Map = 488
Global $MehtaniKeys_Outpost = 489		;Kodlonu Hamlet
Global $PlainsofJarin_Map = 430
Global $PlainsofJarin_Outpost = 449             ;Kamadan
Global $ZehlonReach_Map = 483
Global $ZehlonReach_Outpost = 491               ;Jokanur Diggins
;Kourna IDs
Global $ArkjokWard_Map = 380
Global $ArkjokWard_Outpost = 381                ;Yohlon Haven
Global $BahdokCaverns_Map = 377
Global $BahdokCaverns_Outpost = 427	        ;Moddok Crevice
Global $BarbarousShore_Map = 375	     
Global $BarbarousShore_Outpost = 376 	        ;Camp Hojanu
Global $DejarinEstate_Map = 379
Global $DejarinEstate_Outpost = 426 						;Pogahn Passage
Global $GandaraTheMoonFortress_Map = 382
Global $GandaraTheMoonFortress_Outpost = 426    ;Pogahn Passage
Global $JahaiBluffs_Map = 369		      
Global $JahaiBluffs_Outpost = 424 	        ;Kodonur Crossroads
Global $MargaCoast_Map = 371
Global $MargaCoast_Outpost = 381                ;Yohlon Haven
Global $SunwardMarches_Map = 373
Global $SunwardMarches_Outpost = 421	        ;Venta Cemetery
Global $TheFloodplainOfMahnkelon_Map = 384
Global $TheFloodplainOfMahnkelon_Outpost = 424 	;Kodonur Crossroads
Global $TuraisProcession_Map = 386
Global $TuraisProcession_Outpost = 421		;Venta Cemetery
;Vabbi IDs
Global $ForumHighlands_Map = 399
Global $ForumHighlands_Outpost = 476		;Jennur's Horde
Global $GardenOfSeborhin_Map = 399
Global $GardenOfSeborhin_Outpost = 428		;Tihark Orchard
Global $HoldingsOfChokhin_Map = 395
Global $HoldingsOfChokhin_Outpost = 396		;Mihanu Township
Global $ResplendentMakuun_Map = 402
Global $ResplendentMakuun_Outpost = 403 	;Honur Hill
Global $TheHiddenCityOfAhdashim_Map = 413
Global $TheHiddenCityOfAhdashim_Outpost = 434	;Dasha Vestibule
Global $TheMirrorOfLyss_Map = 419
Global $TheMirrorOfLyss_Outpost = 414		;The Kodash Bazaar
Global $VehjinMines_Map = 397
Global $VehjinMines_Outpost = 476		;Jennur's Horde
Global $VehtendiValley_Map = 406
Global $VehtendiValley_Outpost = 414		;The Kodash Bazaar
Global $WildernessOfBahdza_Map = 404
Global $WildernessOfBahdza_Outpost = 433	;Dzagonur Bastion
Global $YatendiCanyons_Map = 392
Global $YatendiCanyons_Outpost = 378 		;Wehhan Terraces
;TheDesolation IDs
Global $CrystalOverlook_Map = 448
Global $CrystalOverlook_Outpost = 440            ;The Mouth of Torment
Global $CrystalOverlook_Transit = 439            ;The Ruptured Heart
Global $JokosDomain_Map =437
Global $JokosDomain_Outpost = 438               ;Bone Palace
Global $PoisonedOutcrops_Map = 443
Global $PoisonedOutcrops_Outpost = 442          ;Lair of the Forgotten
Global $TheAlkaliPan_Map = 446
Global $TheAlkaliPan_Outpost = 480              ;Ruins of Morah
Global $TheRupturedHeart_Map = 439
Global $TheRupturedHeart_Outpost = 440          ;The Mouth of Torment
Global $TheShatteredRavines_Map = 441
Global $TheShatteredRavines_Outpost = 442       ;Lair of the Forgotten
Global $TheSulfurousWastes_Map = 444
Global $TheSulfurousWastes_Outpost = 478 	;Gate of Desolation
;CharrHomelands IDs
Global $DaladaUplands_Map = 647
Global $DaladaUplands_Outpost = 648             ;Doomlore Shrine
Global $GrothmarWardowns_Map = 649
Global $GrothmarWardowns_Outpost = 650          ;Longeye's Ledge
Global $SacnothValley_Map = 651
Global $SacnothValley_Outpost = 648             ;Doomlore Shrine
Global $SacnothValley_Transit = 647             ;Dalada Uplands
;FarShiverpeaks IDs
Global $BjoraMarches_Map = 482
Global $BjoraMarches_Outpost = 650
Global $DrakkarLake_Map = 513
Global $DrakkarLake_Outpost = 644               ;Gunnar's Hold
Global $IceCliffChasms_Map = $GC_I_MAP_ID_ICE_CLIFF_CHASMS   ; 499
Global $IceCliffChasms_Outpost = $GC_I_MAP_ID_GUNNARS_HOLD   ; 644 — Gunnar's Hold
Global $JagaMoraine_Map = 546
Global $JagaMoraine_Outpost = 643              ;Sifhalla
Global $NorrhartDomains_Map = 548
Global $NorrhartDomains_Outpost = 644
Global $VarajarFells_Map = 553
Global $VarajarFells_Outpost = 650             ;Longeye's Ledge
;TarnishedCoast IDs
Global $ArborBay_Map = 485
Global $ArborBay_Outpost = 624
Global $AlcaziaTangle_Map = 572
Global $AlcaziaTangle_Outpost = 641
Global $MagusStones_Map = 569
Global $MagusStones_Outpost = 640
Global $RivenEarth_Map = 501
Global $RivenEarth_Outpost = 640
Global $SparkflySwamp_Map = 558
Global $SparkflySwamp_Outpost = 638            ;Gadd's Encampment
Global $VerdantCascades_Map = 566
Global $VerdantCascades_Outpost = 642          ;Eye of the North
