#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Proph_CrystalDesert/DivinersAscent.au3
; Map: DivinersAscent (id 110), geometry from MAP 0000052821.pmap
; Repaired 0 of 0 blocked segments by inserting 0 waypoints.
; Smoothed 25 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aProph_CrystalDesert_DivinersAscentRoute01[311][4] = [ _
	[-5681, 3541, " ", $vqrange], _
	[-5101, 4506, " ", $vqrange], _
	[-4522, 5472, " ", $vqrange], _
	[-3577, 5936, " ", $vqrange], _
	[-2632, 6401, " ", $vqrange], _
	[-1982, 7452, " ", $vqrange], _
	[-1332, 8504, " ", $vqrange], _
	[-562, 9590, " ", $vqrange], _
	[208, 10675, " ", $vqrange], _
	[979, 11761, " ", $vqrange], _
	[1749, 12846, " ", $vqrange], _
	[2519, 13932, " ", $vqrange], _
	[1269, 14567, " ", $vqrange], _
	[19, 15201, " ", $vqrange], _
	[-1231, 15836, " ", $vqrange], _
	[-1814, 16908, " ", $vqrange], _
	[-2398, 17979, " ", $vqrange], _
	[-2981, 19051, " ", $vqrange], _
	[-4096, 19174, " ", $vqrange], _
	[-5212, 19298, " ", $vqrange], _
	[-4224, 19072, " ", $vqrange], _
	[-3237, 18846, " ", $vqrange], _
	[-2249, 18620, " ", $vqrange], _
	[-2037, 18179, " ", $vqrange], _
	[-3117, 18174, " ", $vqrange], _
	[-3657, 18171, " ", $vqrange], _
	[-3826, 18170, " ", $vqrange], _
	[-3995, 18169, " ", $vqrange], _
	[-4197, 18168, " ", $vqrange], _
	[-5278, 18163, " ", $vqrange], _
	[-5818, 18161, " ", $vqrange], _
	[-5970, 18160, " ", $vqrange], _
	[-6164, 18159, " ", $vqrange], _ ; auto
	[-6358, 18158, " ", $vqrange], _
	[-6751, 17911, " ", $vqrange], _
	[-6928, 16972, " ", $vqrange], _
	[-7104, 16032, " ", $vqrange], _
	[-7880, 14906, " ", $vqrange], _
	[-8056, 13858, " ", $vqrange], _
	[-8231, 12809, " ", $vqrange], _
	[-8076, 12804, " ", $vqrange], _
	[-7921, 12799, " ", $vqrange], _
	[-7612, 12788, " ", $vqrange], _
	[-6992, 12768, " ", $vqrange], _
	[-7855, 12140, " ", $vqrange], _
	[-8717, 11511, " ", $vqrange], _
	[-9580, 10883, " ", $vqrange], _
	[-10791, 10365, " ", $vqrange], _
	[-12003, 9847, " ", $vqrange], _
	[-13214, 9329, " ", $vqrange], _
	[-14054, 8726, " ", $vqrange], _
	[-14894, 8123, " ", $vqrange], _
	[-14852, 9127, " ", $vqrange], _
	[-14810, 10132, " ", $vqrange], _
	[-14768, 11136, " ", $vqrange], _
	[-15369, 12149, " ", $vqrange], _
	[-16164, 13252, " ", $vqrange], _
	[-16959, 14354, " ", $vqrange], _
	[-16176, 14496, " ", $vqrange], _
	[-16771.25, 15483, " ", $vqrange], _ ; auto
	[-16824, 15660, " ", $vqrange], _
	[-16905, 15805, " ", $vqrange], _
	[-16981, 15941, " ", $vqrange], _
	[-17057, 16078, " ", $vqrange], _
	[-17133, 16214, " ", $vqrange], _
	[-17210, 16350, " ", $vqrange], _
	[-17310, 16532, " ", $vqrange], _
	[-17472, 16823, " ", $vqrange], _
	[-17310, 16532, " ", $vqrange], _
	[-17229, 16387, " ", $vqrange], _
	[-17153, 16250, " ", $vqrange], _
	[-17077, 16114, " ", $vqrange], _
	[-17001, 15978, " ", $vqrange], _
	[-16925, 15841, " ", $vqrange], _
	[-16824, 15660, " ", $vqrange], _
	[-16646.8335, 15215, " ", $vqrange], _ ; auto
	[-16272, 14688, " ", $vqrange], _ ; auto
	[-16176, 14496, " ", $vqrange], _
	[-16061, 13696, " ", $vqrange], _
	[-15823, 12864, " ", $vqrange], _
	[-15157, 11593, " ", $vqrange], _
	[-14491, 10323, " ", $vqrange], _
	[-13825, 9052, " ", $vqrange], _
	[-12619, 9765, " ", $vqrange], _
	[-11413, 10478, " ", $vqrange], _
	[-10208, 11190, " ", $vqrange], _
	[-9002, 11903, " ", $vqrange], _
	[-7796, 12616, " ", $vqrange], _
	[-6590, 13329, " ", $vqrange], _
	[-5837, 14239, " ", $vqrange], _
	[-5085, 15148, " ", $vqrange], _
	[-4332, 16058, " ", $vqrange], _
	[-3086, 16184, " ", $vqrange], _
	[-1841, 16311, " ", $vqrange], _
	[-595, 16437, " ", $vqrange], _
	[650, 16564, " ", $vqrange], _
	[1896, 16690, " ", $vqrange], _
	[3272, 16135, " ", $vqrange], _
	[4647, 15579, " ", $vqrange], _
	[6023, 15024, " ", $vqrange], _
	[6586, 14190, " ", $vqrange], _
	[7148, 13356, " ", $vqrange], _
	[8127, 13951, " ", $vqrange], _
	[9106, 14546, " ", $vqrange], _
	[10085, 15140, " ", $vqrange], _
	[11064, 15735, " ", $vqrange], _
	[12126, 16099, " ", $vqrange], _
	[13187, 16463, " ", $vqrange], _
	[13138, 15365, " ", $vqrange], _
	[13089, 14267, " ", $vqrange], _
	[13040, 13169, " ", $vqrange], _
	[11805, 12780, " ", $vqrange], _
	[10570, 12390, " ", $vqrange], _
	[9335, 12001, " ", $vqrange], _
	[8100, 11612, " ", $vqrange], _
	[6999, 10666, " ", $vqrange], _
	[5898, 9721, " ", $vqrange], _
	[4796, 8776, " ", $vqrange], _
	[3695, 7830, " ", $vqrange], _
	[3540, 6562, " ", $vqrange], _
	[3384, 5293, " ", $vqrange], _
	[4540, 4910, " ", $vqrange], _
	[5697, 4528, " ", $vqrange], _
	[6600, 5523, " ", $vqrange], _
	[7504, 6519, " ", $vqrange], _
	[8407, 7514, " ", $vqrange], _
	[9311, 8510, " ", $vqrange], _
	[10214, 9505, " ", $vqrange], _
	[10605, 9298, " ", $vqrange], _
	[11286.5, 9289, " ", $vqrange], _ ; auto
	[11627.25, 9284.5, " ", $vqrange], _ ; auto
	[11797.625, 9282.25, " ", $vqrange], _ ; auto
	[11968, 9280, " ", $vqrange], _
	[12138.5, 9277.625, " ", $vqrange], _ ; auto
	[12309, 9275.25, " ", $vqrange], _ ; auto
	[12479.5, 9272.875, " ", $vqrange], _ ; auto
	[12650, 9270.5, " ", $vqrange], _ ; auto
	[13332, 9261, " ", $vqrange], _
	[14695, 9242, " ", $vqrange], _
	[16058, 9224, " ", $vqrange], _
	[15034, 9095, " ", $vqrange], _
	[14009, 8967, " ", $vqrange], _
	[12984, 8838, " ", $vqrange], _
	[14150, 8452, " ", $vqrange], _
	[15315, 8067, " ", $vqrange], _
	[16481, 7681, " ", $vqrange], _
	[16801, 6680, " ", $vqrange], _
	[17121, 5679, " ", $vqrange], _
	[16139, 5679, " ", $vqrange], _
	[15157, 5679, " ", $vqrange], _
	[14175, 5679, " ", $vqrange], _
	[13930, 5679, " ", $vqrange], _
	[13746, 5679, " ", $vqrange], _
	[13470, 5679, " ", $vqrange], _ ; auto
	[13194, 5679, " ", $vqrange], _
	[13010, 5679, " ", $vqrange], _
	[12825, 5679, " ", $vqrange], _
	[12212, 5679, " ", $vqrange], _
	[11230, 5679, " ", $vqrange], _
	[10248, 5679, " ", $vqrange], _
	[9266, 5679, " ", $vqrange], _
	[7957, 5679, " ", $vqrange], _
	[6648, 5679, " ", $vqrange], _
	[5339, 5679, " ", $vqrange], _
	[4030, 5679, " ", $vqrange], _
	[2721, 5679, " ", $vqrange], _
	[1412, 5679, " ", $vqrange], _
	[2824, 5689, " ", $vqrange], _
	[4236, 5699, " ", $vqrange], _
	[5648, 5709, " ", $vqrange], _
	[7060, 5720, " ", $vqrange], _
	[8472, 5730, " ", $vqrange], _
	[9884, 5740, " ", $vqrange], _
	[11296, 5750, " ", $vqrange], _
	[12708, 5760, " ", $vqrange], _
	[11564, 5890, " ", $vqrange], _
	[10220, 5820, " ", $vqrange], _
	[8876, 5749, " ", $vqrange], _
	[7531, 5679, " ", $vqrange], _
	[8860, 5676, " ", $vqrange], _
	[10189, 5674, " ", $vqrange], _
	[11518, 5672, " ", $vqrange], _
	[12514, 5670, " ", $vqrange], _
	[12763, 5669, " ", $vqrange], _
	[12919, 5669, " ", $vqrange], _
	[13075, 5669, " ", $vqrange], _
	[13262, 5668, " ", $vqrange], _
	[13511, 5668, " ", $vqrange], _
	[13698, 5667, " ", $vqrange], _
	[13853, 5667, " ", $vqrange], _
	[14009, 5667, " ", $vqrange], _
	[14507, 5666, " ", $vqrange], _
	[15504, 5664, " ", $vqrange], _
	[15262, 4732, " ", $vqrange], _
	[15019, 3801, " ", $vqrange], _
	[13981, 3782, " ", $vqrange], _
	[12942, 3763, " ", $vqrange], _
	[12682.5, 3758.25, " ", $vqrange], _ ; auto
	[12423, 3753.5, " ", $vqrange], _ ; auto
	[11904, 3744, " ", $vqrange], _
	[12492, 2982, " ", $vqrange], _
	[11491, 2521, " ", $vqrange], _
	[10491, 2059, " ", $vqrange], _
	[9490, 1598, " ", $vqrange], _
	[8533, 1205, " ", $vqrange], _
	[7577, 812, " ", $vqrange], _
	[6620, 419, " ", $vqrange], _
	[6598, -426, " ", $vqrange], _
	[6576, -1272, " ", $vqrange], _
	[7872, -1252, " ", $vqrange], _
	[9167, -1233, " ", $vqrange], _
	[8416, -2039, " ", $vqrange], _
	[7664, -2845, " ", $vqrange], _
	[8352, -3917, " ", $vqrange], _
	[9040, -4989, " ", $vqrange], _
	[10093, -5387, " ", $vqrange], _
	[11145, -5784, " ", $vqrange], _
	[12198, -6182, " ", $vqrange], _
	[13329, -5700, " ", $vqrange], _
	[14460, -5217, " ", $vqrange], _
	[15591, -4735, " ", $vqrange], _
	[14362, -5190, " ", $vqrange], _
	[13132, -5644, " ", $vqrange], _
	[11903, -6099, " ", $vqrange], _
	[10673, -6553, " ", $vqrange], _
	[9444, -7008, " ", $vqrange], _
	[10676, -7039, " ", $vqrange], _
	[11909, -7070, " ", $vqrange], _
	[13141, -7100, " ", $vqrange], _
	[14374, -7131, " ", $vqrange], _
	[15606, -7162, " ", $vqrange], _
	[14198.1956, -7248.3333, " ", $vqrange], _ ; auto
	[12790.3913, -7334.6667, " ", $vqrange], _ ; auto
	[11382.5869, -7421, " ", $vqrange], _ ; auto
	[9974.7826, -7507.3333, " ", $vqrange], _ ; auto
	[8566.9782, -7593.6667, " ", $vqrange], _ ; auto
	[7159.1738, -7680, " ", $vqrange], _ ; auto
	[8587.1391, -7689.2, " ", $vqrange], _ ; auto
	[10015.1043, -7698.4, " ", $vqrange], _ ; auto
	[11443.0695, -7707.6, " ", $vqrange], _ ; auto
	[12871.0348, -7716.8, " ", $vqrange], _ ; auto
	[14299, -7726, " ", $vqrange], _
	[12992, -8291, " ", $vqrange], _
	[11686, -8855, " ", $vqrange], _
	[10379, -9420, " ", $vqrange], _
	[9072, -9984, " ", $vqrange], _
	[10551, -10006, " ", $vqrange], _
	[12031, -10029, " ", $vqrange], _
	[13510, -10051, " ", $vqrange], _
	[14619, -10068, " ", $vqrange], _
	[15729, -10084, " ", $vqrange], _
	[16838, -10101, " ", $vqrange], _
	[17012, -10104, " ", $vqrange], _
	[17393, -10110, " ", $vqrange], _
	[17948, -10118, " ", $vqrange], _
	[17114, -10290, " ", $vqrange], _
	[17816, -10472, " ", $vqrange], _
	[17091, -10774, " ", $vqrange], _
	[16367, -11077, " ", $vqrange], _
	[15259, -11046, " ", $vqrange], _
	[14151, -11014, " ", $vqrange], _
	[13043, -10983, " ", $vqrange], _
	[11719, -10650, " ", $vqrange], _
	[10396, -10317, " ", $vqrange], _
	[9072, -9984, " ", $vqrange], _
	[10499, -9886, " ", $vqrange], _
	[11926, -9787, " ", $vqrange], _
	[10887, -10330, " ", $vqrange], _
	[9849, -10874, " ", $vqrange], _
	[8810, -11417, " ", $vqrange], _
	[9761, -11771, " ", $vqrange], _
	[10713, -12126, " ", $vqrange], _
	[11664, -12480, " ", $vqrange], _
	[10584, -12480, " ", $vqrange], _
	[9504, -12480, " ", $vqrange], _
	[8424, -12480, " ", $vqrange], _
	[7884, -12480, " ", $vqrange], _
	[7682, -12480, " ", $vqrange], _
	[7479, -12480, " ", $vqrange], _
	[6691.5, -12480, " ", $vqrange], _ ; auto
	[5904, -12480, " ", $vqrange], _
	[4464, -12480, " ", $vqrange], _
	[3024, -12480, " ", $vqrange], _
	[4297, -12222, " ", $vqrange], _
	[5569, -11965, " ", $vqrange], _
	[6842, -11707, " ", $vqrange], _
	[6070, -10476, " ", $vqrange], _
	[5298, -9244, " ", $vqrange], _
	[4526, -8013, " ", $vqrange], _
	[3754, -6782, " ", $vqrange], _
	[3265, -7957, " ", $vqrange], _
	[2776, -9131, " ", $vqrange], _
	[2287, -10306, " ", $vqrange], _
	[1325, -11344, " ", $vqrange], _
	[364, -12383, " ", $vqrange], _
	[-598, -13421, " ", $vqrange], _
	[-295, -14610, " ", $vqrange], _
	[8, -15799, " ", $vqrange], _
	[-612, -15552, " ", $vqrange], _
	[-1898, -15491, " ", $vqrange], _
	[-3183, -15429, " ", $vqrange], _
	[-4469, -15368, " ", $vqrange], _
	[-5755, -15307, " ", $vqrange], _
	[-7041, -15246, " ", $vqrange], _
	[-8326, -15184, " ", $vqrange], _
	[-9612, -15123, " ", $vqrange], _
	[-9730, -14060, " ", $vqrange], _
	[-9848, -12998, " ", $vqrange], _
	[-11047, -13268, " ", $vqrange], _
	[-12245, -13538, " ", $vqrange], _
	[-13444, -13808, " ", $vqrange] _
]

