#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_EchovaldForest/Arborstone.au3
; Map: Arborstone (id 244), geometry from MAP 0000155158.pmap
; Repaired 4 of 25 blocked segments by inserting 40 waypoints.
; Smoothed 70 additional anchor(s) for wall clearance and hop distance.
; Filled 25 long hop(s) by walking the current mesh component toward a disconnected goal.
; 21 segment(s) could not be routed and were left as-is.
; 21 hop(s) still exceed 1500 units (worst 6199 between index 30 and 31).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_EchovaldForest_ArborstoneRoute01[356][4] = [ _
	[12238, -15807, " ", $vqrange], _
	[12326, -14790, " ", $vqrange], _
	[13243, -13824, " ", $vqrange], _
	[13173, -12716, " ", $vqrange], _
	[13103, -11609, " ", $vqrange], _
	[12944, -13063, " ", $vqrange], _
	[11762, -13728, " ", $vqrange], _
	[10581, -14393, " ", $vqrange], _
	[10470.127, -14248.25, " ", $vqrange], _ ; auto
	[10378.3102, -14128.3789, " ", $vqrange], _ ; auto
	[10248.3809, -13958.75, " ", $vqrange], _ ; auto
	[10137.5078, -13814, " ", $vqrange], _ ; auto
	[8979.6162, -13186, " ", $vqrange], _ ; auto
	[8391.5649, -12417, " ", $vqrange], _ ; auto
	[7869, -12246, " ", $vqrange], _ ; auto
	[7230, -12890, " ", $vqrange], _
	[8682, -16138, " ", $vqrange], _
	[8168, -17209, " ", $vqrange], _
	[7654, -18280, " ", $vqrange], _
	[7987, -18515, " ", $vqrange], _
	[6710, -18571, " ", $vqrange], _
	[5433, -18627, " ", $vqrange], _
	[4156, -18683, " ", $vqrange], _
	[2039, -17168, " ", $vqrange], _
	[1156, -16049, " ", $vqrange], _
	[388, -16384, " ", $vqrange], _
	[-380, -16720, " ", $vqrange], _
	[315, -16374, " ", $vqrange], _
	[1010, -16029, " ", $vqrange], _
	[1826, -16792, " ", $vqrange], _
	[2641, -17554, " ", $vqrange], _
	[-3508, -18341, " ", $vqrange], _
	[-3593, -17344, " ", $vqrange], _
	[-3678, -16346, " ", $vqrange], _
	[-3764, -15349, " ", $vqrange], _
	[-4847, -14842, " ", $vqrange], _
	[-5931, -14336, " ", $vqrange], _
	[-5942, -13902, " ", $vqrange], _
	[-7407, -13847, " ", $vqrange], _
	[-8872, -13792, " ", $vqrange], _
	[-11966, -17936, " ", $vqrange], _
	[-11129, -17806, " ", $vqrange], _ ; auto
	[-10292, -17676, " ", $vqrange], _ ; auto
	[-9987, -17673, " ", $vqrange], _ ; auto
	[-9834.5, -17671.5, " ", $vqrange], _ ; auto
	[-9682, -17670, " ", $vqrange], _ ; auto
	[-9529.5, -17668.5, " ", $vqrange], _ ; auto
	[-9377, -17667, " ", $vqrange], _ ; auto
	[-9224.5, -17665.5, " ", $vqrange], _ ; auto
	[-9072, -17664, " ", $vqrange], _ ; auto
	[-9005.3333, -16618, " ", $vqrange], _ ; auto
	[-8938.6667, -15572, " ", $vqrange], _ ; auto
	[-8872, -14526, " ", $vqrange], _ ; auto
	[-8872, -13792, " ", $vqrange], _
	[-7361, -9263, " ", $vqrange], _
	[-6430, -8474, " ", $vqrange], _
	[-5498, -7684, " ", $vqrange], _
	[-3803, -11097, " ", $vqrange], _
	[-5498, -7684, " ", $vqrange], _
	[-4981.25, -6548, " ", $vqrange], _ ; auto
	[-4464.5, -5412, " ", $vqrange], _ ; auto
	[-4580, -4978, " ", $vqrange], _ ; auto
	[-4580, -4030, " ", $vqrange], _
	[-4799, -874, " ", $vqrange], _
	[-1467, -1012, " ", $vqrange], _
	[35, -5683, " ", $vqrange], _
	[880, -5324, " ", $vqrange], _
	[1726, -4965, " ", $vqrange], _
	[2475, -4478, " ", $vqrange], _
	[3224, -3991, " ", $vqrange], _
	[4093, -4741, " ", $vqrange], _
	[4962, -5491, " ", $vqrange], _
	[6118, -5653, " ", $vqrange], _
	[6448, -6919, " ", $vqrange], _
	[7312, -8127, " ", $vqrange], _
	[8177, -9335, " ", $vqrange], _
	[7529, -9880, " ", $vqrange], _
	[7776, -9164, " ", $vqrange], _
	[8023, -8448, " ", $vqrange], _
	[6993, -7400, " ", $vqrange], _
	[5964, -6351, " ", $vqrange], _
	[6118, -5653, " ", $vqrange], _
	[4684, -5429, " ", $vqrange], _
	[3954, -4710, " ", $vqrange], _
	[3224, -3991, " ", $vqrange], _
	[2243, -4598, " ", $vqrange], _
	[1262, -5205, " ", $vqrange], _
	[281, -5812, " ", $vqrange], _
	[-318, -6670, " ", $vqrange], _
	[-917, -7527, " ", $vqrange], _
	[-1516, -8385, " ", $vqrange], _
	[-785, -9272, " ", $vqrange], _
	[-54, -10159, " ", $vqrange], _
	[678, -11046, " ", $vqrange], _
	[-78, -11248, " ", $vqrange], _
	[2307, -9887, " ", $vqrange], _
	[3027, -9142, " ", $vqrange], _
	[3747, -8398, " ", $vqrange], _
	[4467, -7653, " ", $vqrange], _
	[4486, -8890, " ", $vqrange], _
	[4506, -10127, " ", $vqrange], _
	[5543, -11174, " ", $vqrange], _
	[6580, -12220, " ", $vqrange], _
	[7617, -13267, " ", $vqrange], _
	[8654, -14314, " ", $vqrange], _
	[12983, -13356, " ", $vqrange], _
	[12989, -11930, " ", $vqrange], _
	[12996, -10504, " ", $vqrange], _
	[13002, -9078, " ", $vqrange], _
	[13008, -7652, " ", $vqrange], _
	[13143, -6510, " ", $vqrange], _
	[13278, -5369, " ", $vqrange], _
	[13413, -4227, " ", $vqrange], _
	[13052, -3168, " ", $vqrange], _
	[12680, -3168, " ", $vqrange], _
	[12529, -3168, " ", $vqrange], _
	[12378, -3168, " ", $vqrange], _
	[12227, -3168, " ", $vqrange], _
	[12076, -3168, " ", $vqrange], _
	[11925, -3168, " ", $vqrange], _
	[11750, -3168, " ", $vqrange], _
	[11564, -3168, " ", $vqrange], _
	[10077, -3168, " ", $vqrange], _
	[9208, -3312, " ", $vqrange], _
	[8339, -3457, " ", $vqrange], _
	[9092, -4636, " ", $vqrange], _
	[9671, -4612, " ", $vqrange], _
	[9960, -4600, " ", $vqrange], _
	[10250, -4588, " ", $vqrange], _
	[11408, -4539, " ", $vqrange], _
	[11016, -3950, " ", $vqrange], _
	[10311.0559, -3840, " ", $vqrange], _ ; auto
	[9677, -3779, " ", $vqrange], _
	[8338, -3608, " ", $vqrange], _
	[8339, -3457, " ", $vqrange], _
	[9519, -3166, " ", $vqrange], _
	[10698, -2874, " ", $vqrange], _
	[11878, -2583, " ", $vqrange], _
	[13057, -2292, " ", $vqrange], _
	[13761.084, -2208, " ", $vqrange], _ ; auto
	[12771.0418, -2180, " ", $vqrange], _ ; auto
	[12523.5313, -2173, " ", $vqrange], _ ; auto
	[12368.8372, -2168.625, " ", $vqrange], _ ; auto
	[12214.1431, -2164.25, " ", $vqrange], _ ; auto
	[12059.449, -2159.875, " ", $vqrange], _ ; auto
	[11904.7549, -2155.5, " ", $vqrange], _ ; auto
	[11750.0608, -2151.125, " ", $vqrange], _ ; auto
	[11533.4891, -2145, " ", $vqrange], _ ; auto
	[11285.9785, -2138, " ", $vqrange], _ ; auto
	[10790.9574, -2124, " ", $vqrange], _ ; auto
	[9800.9153, -2096, " ", $vqrange], _ ; auto
	[9361, -2096, " ", $vqrange], _
	[8084, -2095, " ", $vqrange], _
	[6808, -2094, " ", $vqrange], _
	[5531, -2094, " ", $vqrange], _
	[4254, -2093, " ", $vqrange], _
	[3518, -1357, " ", $vqrange], _
	[2782, -620, " ", $vqrange], _
	[2046, 116, " ", $vqrange], _
	[5154, 1232, " ", $vqrange], _
	[6622, 1301, " ", $vqrange], _
	[7606, 1310, " ", $vqrange], _
	[7760, 1311, " ", $vqrange], _
	[7914, 1312, " ", $vqrange], _
	[8098, 1314, " ", $vqrange], _
	[8590, 1318, " ", $vqrange], _
	[8258, 1395, " ", $vqrange], _
	[8271, 334, " ", $vqrange], _
	[8274, 69, " ", $vqrange], _
	[8277, -129, " ", $vqrange], _
	[8279, -287, " ", $vqrange], _
	[8281, -461, " ", $vqrange], _
	[8284, -726, " ", $vqrange], _
	[8281, -496, " ", $vqrange], _
	[8279, -324, " ", $vqrange], _
	[8277, -166, " ", $vqrange], _
	[8272, 194, " ", $vqrange], _
	[8261, 1114, " ", $vqrange], _
	[8250, 2033, " ", $vqrange], _
	[8238, 2953, " ", $vqrange], _
	[9435, 6494, " ", $vqrange], _
	[9925.5, 6415, " ", $vqrange], _ ; auto
	[10074.9492, 6390.9297, " ", $vqrange], _ ; auto
	[10416, 6336, " ", $vqrange], _
	[10656, 5952, " ", $vqrange], _
	[11554, 5643, " ", $vqrange], _
	[12451, 5334, " ", $vqrange], _
	[12488, 3984, " ", $vqrange], _
	[12525, 2635, " ", $vqrange], _
	[12561, 1285, " ", $vqrange], _
	[12832, 845, " ", $vqrange], _
	[13572, 768, " ", $vqrange], _
	[12863, 728, " ", $vqrange], _
	[12508, 709, " ", $vqrange], _
	[12331, 699, " ", $vqrange], _
	[12176, 690, " ", $vqrange], _
	[12021, 682, " ", $vqrange], _
	[11866, 673, " ", $vqrange], _
	[11711, 664, " ", $vqrange], _
	[11445, 650, " ", $vqrange], _
	[10736, 610, " ", $vqrange], _
	[10624, 2081, " ", $vqrange], _
	[10512, 3552, " ", $vqrange], _
	[9503, 3847, " ", $vqrange], _
	[8494, 4141, " ", $vqrange], _
	[7485, 4436, " ", $vqrange], _
	[6309, 5082, " ", $vqrange], _
	[5680, 5711, " ", $vqrange], _
	[5052, 6340, " ", $vqrange], _
	[6002, 7253, " ", $vqrange], _
	[6952, 8165, " ", $vqrange], _
	[7902, 9078, " ", $vqrange], _
	[7064, 9935, " ", $vqrange], _
	[6227, 10792, " ", $vqrange], _
	[7064, 9935, " ", $vqrange], _
	[7902, 9078, " ", $vqrange], _
	[8756, 9604, " ", $vqrange], _
	[9610, 10130, " ", $vqrange], _
	[10464, 10656, " ", $vqrange], _
	[11118, 11594, " ", $vqrange], _
	[11773, 12531, " ", $vqrange], _
	[10685, 13533, " ", $vqrange], _
	[10368, 13533, " ", $vqrange], _
	[10215, 13533, " ", $vqrange], _
	[10062, 13533, " ", $vqrange], _
	[9894, 13533, " ", $vqrange], _
	[9736, 13533, " ", $vqrange], _
	[9419, 13533, " ", $vqrange], _
	[8454, 13150, " ", $vqrange], _
	[7488, 12768, " ", $vqrange], _
	[6766, 12751, " ", $vqrange], _
	[6119, 13144, " ", $vqrange], _
	[5472, 13536, " ", $vqrange], _
	[5187, 13536, " ", $vqrange], _
	[5009, 13536, " ", $vqrange], _
	[4857, 13536, " ", $vqrange], _
	[4706, 13536, " ", $vqrange], _
	[4555, 13536, " ", $vqrange], _
	[4403, 13536, " ", $vqrange], _
	[4252, 13536, " ", $vqrange], _
	[4100, 13536, " ", $vqrange], _
	[3931, 13536, " ", $vqrange], _ ; auto
	[3762, 13536, " ", $vqrange], _
	[3477, 13536, " ", $vqrange], _ ; auto
	[3192, 13536, " ", $vqrange], _
	[1994, 12974, " ", $vqrange], _
	[797, 12411, " ", $vqrange], _
	[-175, 11278, " ", $vqrange], _
	[-872, 11278, " ", $vqrange], _
	[-1220, 11278, " ", $vqrange], _
	[-1394, 11278, " ", $vqrange], _
	[-1546, 11278, " ", $vqrange], _
	[-1699, 11278, " ", $vqrange], _
	[-1916, 11278, " ", $vqrange], _
	[-2264, 11278, " ", $vqrange], _
	[-2960, 11278, " ", $vqrange], _
	[-4353, 11278, " ", $vqrange], _
	[-5746, 11278, " ", $vqrange], _
	[-4570, 11364, " ", $vqrange], _
	[-3394, 11450, " ", $vqrange], _
	[-3745, 11635, " ", $vqrange], _
	[-3813, 12531, " ", $vqrange], _
	[-3881, 13427, " ", $vqrange], _
	[-4608, 14304, " ", $vqrange], _
	[-5903, 14538, " ", $vqrange], _
	[-7198, 14773, " ", $vqrange], _
	[-8412, 14626, " ", $vqrange], _
	[-9627, 14478, " ", $vqrange], _
	[-10841, 14331, " ", $vqrange], _
	[-11485, 14318, " ", $vqrange], _
	[-11636, 14314, " ", $vqrange], _
	[-11786, 14311, " ", $vqrange], _
	[-11967, 14307, " ", $vqrange], _
	[-12128, 14304, " ", $vqrange], _
	[-12770, 13453, " ", $vqrange], _
	[-12128, 14304, " ", $vqrange], _
	[-11916, 14304, " ", $vqrange], _
	[-11764, 14304, " ", $vqrange], _
	[-11612, 14304, " ", $vqrange], _
	[-11282, 14304, " ", $vqrange], _
	[-10436, 14304, " ", $vqrange], _
	[-9750, 13392, " ", $vqrange], _
	[-9063, 12480, " ", $vqrange], _
	[-8991, 11416, " ", $vqrange], _
	[-8138, 11348, " ", $vqrange], _
	[-7113, 11348, " ", $vqrange], _
	[-6601, 11348, " ", $vqrange], _
	[-6440, 11348, " ", $vqrange], _
	[-6280, 11348, " ", $vqrange], _
	[-6120, 11348, " ", $vqrange], _
	[-5960, 11348, " ", $vqrange], _
	[-5575, 11348, " ", $vqrange], _
	[-5063, 11348, " ", $vqrange], _
	[-4037, 11348, " ", $vqrange], _
	[-3901, 11511, " ", $vqrange], _
	[-2490, 11226, " ", $vqrange], _
	[-1079, 10941, " ", $vqrange], _
	[332, 10656, " ", $vqrange], _
	[1010, 9408, " ", $vqrange], _
	[975, 8737, " ", $vqrange], _
	[1009, 7344, " ", $vqrange], _
	[1042, 5952, " ", $vqrange], _
	[1076, 4559, " ", $vqrange], _
	[1042, 5952, " ", $vqrange], _
	[1009, 7344, " ", $vqrange], _
	[975, 8737, " ", $vqrange], _
	[-1838, 5310, " ", $vqrange], _
	[-3742, 5810, " ", $vqrange], _
	[-7920, 5230, " ", $vqrange], _
	[-8997, 5218, " ", $vqrange], _
	[-9148, 5217, " ", $vqrange], _
	[-9300, 5215, " ", $vqrange], _
	[-9451, 5214, " ", $vqrange], _
	[-9603, 5212, " ", $vqrange], _
	[-9805, 5210, " ", $vqrange], _
	[-10074, 5207, " ", $vqrange], _
	[-11151, 5196, " ", $vqrange], _
	[-12228, 5184, " ", $vqrange], _
	[-11328, 5136, " ", $vqrange], _
	[-10878, 5112, " ", $vqrange], _
	[-10653, 5100, " ", $vqrange], _
	[-10428, 5088, " ", $vqrange], _
	[-10610, 5040, " ", $vqrange], _
	[-10791, 4992, " ", $vqrange], _
	[-11154, 4896, " ", $vqrange], _
	[-11880, 4704, " ", $vqrange], _
	[-11806, 3397, " ", $vqrange], _
	[-11733, 2091, " ", $vqrange], _
	[-11659, 784, " ", $vqrange], _
	[-10382, -1151, " ", $vqrange], _
	[-7386, 2025, " ", $vqrange], _
	[-10382, -1151, " ", $vqrange], _
	[-12734, -5800, " ", $vqrange], _
	[-12912, -7008, " ", $vqrange], _
	[-12816, -7200, " ", $vqrange], _
	[-12040, -7727, " ", $vqrange], _
	[-12816, -7200, " ", $vqrange], _
	[-12922, -6336, " ", $vqrange], _
	[-12734, -5800, " ", $vqrange], _
	[-12624, -5760, " ", $vqrange], _
	[-12264, -5760, " ", $vqrange], _
	[-12112, -5760, " ", $vqrange], _
	[-11960, -5760, " ", $vqrange], _
	[-11808, -5760, " ", $vqrange], _
	[-11544, -5760, " ", $vqrange], _
	[-11184, -5760, " ", $vqrange], _
	[-10556, -6190, " ", $vqrange], _
	[-9928, -6620, " ", $vqrange], _
	[-10198, -7370, " ", $vqrange], _
	[-10468, -8121, " ", $vqrange], _
	[-11099, -9004, " ", $vqrange], _
	[-11730, -9888, " ", $vqrange], _
	[-11906, -9984, " ", $vqrange], _
	[-12124, -10030, " ", $vqrange], _
	[-12308, -10068, " ", $vqrange], _
	[-12979, -10208, " ", $vqrange] _
]

