#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_EchovaldForest/DrazachThicket.au3
; Map: DrazachThicket (id 195), geometry from MAP 0000154527.pmap
; Repaired 0 of 2 blocked segments by inserting 9 waypoints.
; Smoothed 52 additional anchor(s) for wall clearance and hop distance.
; Filled 2 long hop(s) by walking the current mesh component toward a disconnected goal.
; 2 segment(s) could not be routed and were left as-is.
; 2 hop(s) still exceed 1500 units (worst 2206 between index 228 and 229).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_EchovaldForest_DrazachThicketRoute01[279][4] = [ _
	[-6506, -16099, " ", $vqrange], _
	[-7544, -15726, " ", $vqrange], _
	[-8581, -15354, " ", $vqrange], _
	[-8592.5, -14803, " ", $vqrange], _ ; auto
	[-8598.25, -14527.5, " ", $vqrange], _ ; auto
	[-8604, -14252, " ", $vqrange], _
	[-8627, -13151, " ", $vqrange], _
	[-7315, -12672, " ", $vqrange], _
	[-6683, -12115, " ", $vqrange], _
	[-6534, -11098, " ", $vqrange], _
	[-6384, -10080, " ", $vqrange], _
	[-7474, -10044, " ", $vqrange], _
	[-6748, -9201, " ", $vqrange], _
	[-6021, -8358, " ", $vqrange], _
	[-6278, -7441, " ", $vqrange], _
	[-6536, -6524, " ", $vqrange], _
	[-5184, -6307, " ", $vqrange], _
	[-4643, -5336, " ", $vqrange], _
	[-6006, -5690, " ", $vqrange], _
	[-7368, -6043, " ", $vqrange], _
	[-7776, -6432, " ", $vqrange], _
	[-8645, -6486, " ", $vqrange], _
	[-9514, -6539, " ", $vqrange], _
	[-10251, -7358, " ", $vqrange], _
	[-10988, -8177, " ", $vqrange], _
	[-11388, -7827, " ", $vqrange], _
	[-10738, -7054, " ", $vqrange], _
	[-10087, -6281, " ", $vqrange], _
	[-11291, -5987, " ", $vqrange], _
	[-11336, -4887, " ", $vqrange], _
	[-11380, -3787, " ", $vqrange], _
	[-11010, -2750, " ", $vqrange], _
	[-10641, -1714, " ", $vqrange], _
	[-9434, -1468, " ", $vqrange], _
	[-8227, -1222, " ", $vqrange], _
	[-7020, -976, " ", $vqrange], _
	[-6750, 146, " ", $vqrange], _
	[-5607, 464, " ", $vqrange], _
	[-4465, 781, " ", $vqrange], _
	[-5825, 201, " ", $vqrange], _
	[-7184, -380, " ", $vqrange], _
	[-8544, -960, " ", $vqrange], _
	[-7782, -968, " ", $vqrange], _
	[-7020, -976, " ", $vqrange], _
	[-8205, -488, " ", $vqrange], _
	[-9390, 1, " ", $vqrange], _
	[-10575, 489, " ", $vqrange], _
	[-10920, 1535, " ", $vqrange], _
	[-11266, 2581, " ", $vqrange], _
	[-10855, 3408, " ", $vqrange], _
	[-10444, 4234, " ", $vqrange], _
	[-10770, 4032, " ", $vqrange], _
	[-11682, 4032, " ", $vqrange], _
	[-11839, 4032, " ", $vqrange], _
	[-11996, 4032, " ", $vqrange], _
	[-12153, 4032, " ", $vqrange], _
	[-12366, 4032, " ", $vqrange], _
	[-12594, 4032, " ", $vqrange], _
	[-12820, 4153, " ", $vqrange], _
	[-12812, 5255, " ", $vqrange], _
	[-12804, 6357, " ", $vqrange], _
	[-12439, 7402, " ", $vqrange], _
	[-12074, 8448, " ", $vqrange], _
	[-11536, 9390, " ", $vqrange], _
	[-10999, 10333, " ", $vqrange], _
	[-10215, 10333, " ", $vqrange], _
	[-10020, 10333, " ", $vqrange], _
	[-9861, 10333, " ", $vqrange], _
	[-9702, 10333, " ", $vqrange], _
	[-9530, 10333, " ", $vqrange], _
	[-8649, 10333, " ", $vqrange], _
	[-7866, 10333, " ", $vqrange], _
	[-7702, 10258, " ", $vqrange], _
	[-6531, 10258, " ", $vqrange], _
	[-5945, 10258, " ", $vqrange], _
	[-5652, 10258, " ", $vqrange], _
	[-5359, 10258, " ", $vqrange], _
	[-4188, 10258, " ", $vqrange], _
	[-3016, 10258, " ", $vqrange], _
	[-3750, 10568, " ", $vqrange], _
	[-3016, 10258, " ", $vqrange], _
	[-4188, 10258, " ", $vqrange], _
	[-5359, 10258, " ", $vqrange], _
	[-5652, 10258, " ", $vqrange], _
	[-5817, 10258, " ", $vqrange], _
	[-5995.5, 10258, " ", $vqrange], _ ; auto
	[-6174, 10258, " ", $vqrange], _ ; auto
	[-6531, 10258, " ", $vqrange], _
	[-7702, 10258, " ", $vqrange], _
	[-7758, 10565, " ", $vqrange], _
	[-7702, 10258, " ", $vqrange], _
	[-6531, 10258, " ", $vqrange], _
	[-5945, 10258, " ", $vqrange], _
	[-5652, 10258, " ", $vqrange], _
	[-5359, 10258, " ", $vqrange], _
	[-4188, 10258, " ", $vqrange], _
	[-3016, 10258, " ", $vqrange], _
	[-1622, 10505, " ", $vqrange], _
	[-228, 10752, " ", $vqrange], _
	[638, 11363, " ", $vqrange], _
	[2038, 11690, " ", $vqrange], _
	[3024, 11712, " ", $vqrange], _ ; auto
	[3439, 12018, " ", $vqrange], _
	[4840, 12345, " ", $vqrange], _
	[6240, 12672, " ", $vqrange], _
	[5171, 12722, " ", $vqrange], _
	[4102, 12772, " ", $vqrange], _
	[3055, 12098, " ", $vqrange], _
	[2008, 11424, " ", $vqrange], _
	[638, 11363, " ", $vqrange], _
	[-336, 10750, " ", $vqrange], _
	[-1676, 10504, " ", $vqrange], _
	[-3016, 10258, " ", $vqrange], _
	[-4188, 10258, " ", $vqrange], _
	[-5359, 10258, " ", $vqrange], _
	[-5652, 10258, " ", $vqrange], _
	[-5817, 10258, " ", $vqrange], _
	[-5995.5, 10258, " ", $vqrange], _ ; auto
	[-6174, 10258, " ", $vqrange], _ ; auto
	[-6531, 10258, " ", $vqrange], _
	[-7702, 10258, " ", $vqrange], _
	[-7758, 10565, " ", $vqrange], _
	[-6860, 9451, " ", $vqrange], _
	[-5963, 8337, " ", $vqrange], _
	[-5524, 7142, " ", $vqrange], _
	[-5085, 5948, " ", $vqrange], _
	[-5780, 7044, " ", $vqrange], _
	[-6476, 8140, " ", $vqrange], _
	[-7171, 9237, " ", $vqrange], _
	[-7866, 10333, " ", $vqrange], _
	[-9007, 10390, " ", $vqrange], _
	[-10148, 10448, " ", $vqrange], _
	[-11289, 10505, " ", $vqrange], _
	[-10241, 10840, " ", $vqrange], _
	[-9193, 11175, " ", $vqrange], _
	[-8252, 10598, " ", $vqrange], _
	[-7310, 10021, " ", $vqrange], _
	[-5864, 10169, " ", $vqrange], _
	[-4418, 10316, " ", $vqrange], _
	[-2973, 10464, " ", $vqrange], _
	[-4084, 10551, " ", $vqrange], _
	[-5196, 10638, " ", $vqrange], _
	[-4263.4574, 11019, " ", $vqrange], _ ; auto
	[-3330.9149, 11400, " ", $vqrange], _ ; auto
	[-4622, 11433, " ", $vqrange], _
	[-4049, 12228, " ", $vqrange], _
	[-4567, 12753, " ", $vqrange], _
	[-4900, 13768, " ", $vqrange], _
	[-5154, 14878, " ", $vqrange], _
	[-4418, 15442, " ", $vqrange], _
	[-3682, 16006, " ", $vqrange], _
	[-3280, 16044, " ", $vqrange], _
	[-2258, 15798, " ", $vqrange], _
	[-1236, 15552, " ", $vqrange], _
	[-1272, 15113, " ", $vqrange], _
	[-1080, 14976, " ", $vqrange], _
	[-678, 14976, " ", $vqrange], _
	[-527, 14976, " ", $vqrange], _
	[-376, 14976, " ", $vqrange], _
	[-176, 14976, " ", $vqrange], _
	[-25, 14976, " ", $vqrange], _
	[126, 14976, " ", $vqrange], _
	[327, 14976, " ", $vqrange], _
	[528, 14976, " ", $vqrange], _
	[930, 15165, " ", $vqrange], _
	[1056, 15264, " ", $vqrange], _
	[1363, 15264, " ", $vqrange], _
	[1516, 15264, " ", $vqrange], _
	[1670, 15264, " ", $vqrange], _
	[1823, 15264, " ", $vqrange], _
	[1977, 15264, " ", $vqrange], _
	[2284, 15264, " ", $vqrange], _
	[3106, 14786, " ", $vqrange], _
	[3953, 14545, " ", $vqrange], _
	[4800, 14304, " ", $vqrange], _
	[5094, 13825, " ", $vqrange], _
	[6201, 13802, " ", $vqrange], _
	[7308, 13779, " ", $vqrange], _
	[7981, 12908, " ", $vqrange], _
	[8654, 12037, " ", $vqrange], _
	[8444, 10956, " ", $vqrange], _
	[8235, 9874, " ", $vqrange], _
	[7917, 8531, " ", $vqrange], _
	[7513, 7790, " ", $vqrange], _
	[7644, 6696, " ", $vqrange], _
	[7774, 5603, " ", $vqrange], _
	[8846, 5306, " ", $vqrange], _
	[9917, 5008, " ", $vqrange], _
	[8794, 5062, " ", $vqrange], _
	[9869, 5075, " ", $vqrange], _
	[10138, 5078, " ", $vqrange], _
	[10289, 5080, " ", $vqrange], _
	[10440, 5082, " ", $vqrange], _
	[10591, 5084, " ", $vqrange], _
	[10767.5, 5086, " ", $vqrange], _ ; auto
	[10944, 5088, " ", $vqrange], _
	[11983, 5810, " ", $vqrange], _
	[10944, 5088, " ", $vqrange], _
	[9813, 4866, " ", $vqrange], _
	[8682, 4645, " ", $vqrange], _
	[9438, 4586, " ", $vqrange], _
	[10193, 4527, " ", $vqrange], _
	[9232, 3552, " ", $vqrange], _
	[9738, 2938, " ", $vqrange], _
	[10244, 2324, " ", $vqrange], _
	[10858, 1258, " ", $vqrange], _
	[11472, 192, " ", $vqrange], _
	[10734, 174, " ", $vqrange], _
	[12065, 135, " ", $vqrange], _
	[13396, 96, " ", $vqrange], _
	[12245, 96, " ", $vqrange], _
	[11094, 96, " ", $vqrange], _
	[10806, 96, " ", $vqrange], _
	[10626, 96, " ", $vqrange], _
	[10447, 96, " ", $vqrange], _
	[10231, 96, " ", $vqrange], _
	[9943, 96, " ", $vqrange], _
	[8792, 96, " ", $vqrange], _
	[7641, 96, " ", $vqrange], _
	[6490, 96, " ", $vqrange], _
	[5339, 96, " ", $vqrange], _
	[4188, 96, " ", $vqrange], _
	[5636, 152, " ", $vqrange], _
	[7083, 207, " ", $vqrange], _
	[8531, 263, " ", $vqrange], _
	[7428, 198, " ", $vqrange], _
	[6324, 132, " ", $vqrange], _
	[5876, -879, " ", $vqrange], _
	[5427, -1890, " ", $vqrange], _
	[4553, -3915, " ", $vqrange], _
	[3930, -6028, " ", $vqrange], _
	[3262, -7002, " ", $vqrange], _
	[2593, -7976, " ", $vqrange], _
	[3094, -8066, " ", $vqrange], _
	[2187, -7466, " ", $vqrange], _
	[1280, -6866, " ", $vqrange], _
	[1736, -6672, " ", $vqrange], _
	[642, -5979, " ", $vqrange], _
	[446, -5656, " ", $vqrange], _
	[-16, -5437, " ", $vqrange], _
	[235, -5024, " ", $vqrange], _
	[40, -5534, " ", $vqrange], _
	[446, -5656, " ", $vqrange], _
	[905, -6342, " ", $vqrange], _
	[1365, -7028, " ", $vqrange], _
	[846, -7592, " ", $vqrange], _
	[539, -8352, " ", $vqrange], _
	[985, -8475, " ", $vqrange], _
	[778, -7735, " ", $vqrange], _
	[855, -7584, " ", $vqrange], _
	[1055, -7340, " ", $vqrange], _
	[2038, -7104, " ", $vqrange], _
	[3022, -6869, " ", $vqrange], _
	[4005, -6633, " ", $vqrange], _
	[3633, -5568, " ", $vqrange], _
	[2415, -4840, " ", $vqrange], _
	[1197, -4112, " ", $vqrange], _
	[-21, -3384, " ", $vqrange], _
	[-1076, -3378, " ", $vqrange], _
	[-2131, -3371, " ", $vqrange], _
	[-2563, -2168, " ", $vqrange], _
	[-2995, -966, " ", $vqrange], _
	[-3427, 237, " ", $vqrange], _
	[-3859, 1440, " ", $vqrange], _
	[-3055, 1867, " ", $vqrange], _
	[-2335, 2685, " ", $vqrange], _
	[-1615, 3502, " ", $vqrange], _
	[-895, 4320, " ", $vqrange], _
	[-1661, 4856, " ", $vqrange], _
	[-2427, 5392, " ", $vqrange], _
	[-1920, 6470, " ", $vqrange], _
	[-1412, 7547, " ", $vqrange], _
	[-905, 8625, " ", $vqrange], _
	[115, 9177, " ", $vqrange], _
	[1134, 9730, " ", $vqrange], _
	[2154, 10282, " ", $vqrange], _
	[3174, 10834, " ", $vqrange], _
	[3640, 10065, " ", $vqrange], _
	[4105, 9296, " ", $vqrange] _
]

