#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_EchovaldForest/MorostavTrail.au3
; Map: MorostavTrail (id 205), geometry from MAP 0000154638.pmap
; Repaired 1 of 3 blocked segments by inserting 3 waypoints.
; Smoothed 44 additional anchor(s) for wall clearance and hop distance.
; Filled 1 long hop(s) by walking the current mesh component toward a disconnected goal.
; 2 segment(s) could not be routed and were left as-is.
; 1 hop(s) still exceed 1500 units (worst 2533 between index 59 and 60).
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_EchovaldForest_MorostavTrailRoute01[352][4] = [ _
	[20315, 12173, " ", $vqrange], _
	[20167, 10944, " ", $vqrange], _
	[20506, 9857, " ", $vqrange], _
	[20845, 8770, " ", $vqrange], _
	[20544, 8256, " ", $vqrange], _
	[20208, 8256, " ", $vqrange], _
	[20040, 8256, " ", $vqrange], _
	[19872, 8256, " ", $vqrange], _
	[19704, 8256, " ", $vqrange], _
	[19536, 8256, " ", $vqrange], _
	[19368, 8256, " ", $vqrange], _
	[19200, 8256, " ", $vqrange], _
	[17856, 8256, " ", $vqrange], _
	[16512, 8256, " ", $vqrange], _
	[15168, 8256, " ", $vqrange], _
	[16594, 8355, " ", $vqrange], _
	[18020, 8454, " ", $vqrange], _
	[16765, 8132, " ", $vqrange], _
	[15511, 7810, " ", $vqrange], _
	[14256, 7488, " ", $vqrange], _
	[15214, 7360, " ", $vqrange], _
	[16171, 7232, " ", $vqrange], _
	[15213.5, 7360, " ", $vqrange], _ ; auto
	[14256, 7488, " ", $vqrange], _ ; auto
	[15062, 7504, " ", $vqrange], _
	[13952, 7776, " ", $vqrange], _
	[14917, 8128, " ", $vqrange], _
	[15883, 8480, " ", $vqrange], _
	[16848, 8832, " ", $vqrange], _
	[16657, 10270, " ", $vqrange], _
	[15744.5, 11030, " ", $vqrange], _ ; auto
	[15656, 11250, " ", $vqrange], _
	[15600, 11424, " ", $vqrange], _
	[15125, 11424, " ", $vqrange], _
	[14973, 11424, " ", $vqrange], _
	[14811.5, 11424, " ", $vqrange], _ ; auto
	[14650, 11424, " ", $vqrange], _
	[14393, 11062, " ", $vqrange], _
	[13743, 10193, " ", $vqrange], _
	[13093, 9324, " ", $vqrange], _
	[11884, 8702, " ", $vqrange], _
	[10674, 8080, " ", $vqrange], _
	[9976, 7574, " ", $vqrange], _
	[9279, 7069, " ", $vqrange], _
	[9872, 7998, " ", $vqrange], _
	[10464, 8928, " ", $vqrange], _
	[10246, 9098, " ", $vqrange], _
	[9768, 9888, " ", $vqrange], _ ; auto
	[9635, 10021, " ", $vqrange], _
	[9024, 10944, " ", $vqrange], _
	[8478, 11608, " ", $vqrange], _
	[7199, 11483, " ", $vqrange], _
	[5919, 11357, " ", $vqrange], _
	[4640, 11232, " ", $vqrange], _
	[5118, 10962, " ", $vqrange], _
	[5064, 9888, " ", $vqrange], _
	[4721, 8571, " ", $vqrange], _
	[4274, 7638, " ", $vqrange], _
	[3828, 6704, " ", $vqrange], _
	[2871, 7379, " ", $vqrange], _
	[2796, 9911, " ", $vqrange], _
	[1890, 9276, " ", $vqrange], _
	[984, 8640, " ", $vqrange], _
	[324, 7944, " ", $vqrange], _
	[-335, 7249, " ", $vqrange], _
	[-1594, 6454, " ", $vqrange], _
	[-2853, 5660, " ", $vqrange], _
	[-2930, 4894, " ", $vqrange], _
	[-3008, 4128, " ", $vqrange], _
	[-4111, 3580, " ", $vqrange], _
	[-5214, 3032, " ", $vqrange], _
	[-6321, 2590, " ", $vqrange], _
	[-7427, 2149, " ", $vqrange], _
	[-8534, 1707, " ", $vqrange], _
	[-9350, 2367, " ", $vqrange], _
	[-10165, 3027, " ", $vqrange], _
	[-10914, 2666, " ", $vqrange], _
	[-11664, 2304, " ", $vqrange], _
	[-12120, 2304, " ", $vqrange], _
	[-12348, 2304, " ", $vqrange], _
	[-12505, 2304, " ", $vqrange], _
	[-12662, 2304, " ", $vqrange], _
	[-12847, 2304, " ", $vqrange], _ ; auto
	[-13032, 2304, " ", $vqrange], _
	[-13488, 2304, " ", $vqrange], _
	[-13202, 2487, " ", $vqrange], _
	[-13751, 3386, " ", $vqrange], _
	[-14299, 4285, " ", $vqrange], _
	[-14848, 5184, " ", $vqrange], _
	[-14079, 5232, " ", $vqrange], _
	[-14938, 5936, " ", $vqrange], _
	[-15797, 6641, " ", $vqrange], _
	[-16558, 7412, " ", $vqrange], _
	[-17320, 8183, " ", $vqrange], _
	[-17984, 9062, " ", $vqrange], _
	[-18647, 9941, " ", $vqrange], _
	[-19702, 9482, " ", $vqrange], _
	[-20757, 9024, " ", $vqrange], _
	[-20777, 8615, " ", $vqrange], _
	[-20529, 7608, " ", $vqrange], _
	[-20281, 6601, " ", $vqrange], _
	[-20033, 5594, " ", $vqrange], _
	[-19937, 5234, " ", $vqrange], _
	[-19098, 4320, " ", $vqrange], _
	[-18735, 4310, " ", $vqrange], _
	[-18585, 4305, " ", $vqrange], _
	[-18373, 4299, " ", $vqrange], _
	[-17715, 4292, " ", $vqrange], _
	[-17312, 4608, " ", $vqrange], _
	[-16977, 4613, " ", $vqrange], _
	[-16809, 4616, " ", $vqrange], _
	[-16652, 4618, " ", $vqrange], _
	[-16495, 4620, " ", $vqrange], _
	[-16338, 4623, " ", $vqrange], _
	[-16154.5, 4625.5, " ", $vqrange], _ ; auto
	[-15971, 4628, " ", $vqrange], _
	[-15803, 4630, " ", $vqrange], _
	[-15646, 4633, " ", $vqrange], _
	[-15489, 4635, " ", $vqrange], _
	[-15332, 4638, " ", $vqrange], _
	[-15175, 4640, " ", $vqrange], _
	[-15018, 4642, " ", $vqrange], _
	[-14860, 4645, " ", $vqrange], _
	[-14630, 4648, " ", $vqrange], _
	[-14059, 3476, " ", $vqrange], _
	[-13488, 2304, " ", $vqrange], _
	[-13717, 1908, " ", $vqrange], _
	[-14274, 1290, " ", $vqrange], _
	[-14832, 672, " ", $vqrange], _
	[-14975, 571, " ", $vqrange], _
	[-14304, 1045, " ", $vqrange], _
	[-13633, 1519, " ", $vqrange], _
	[-12194, 1661, " ", $vqrange], _
	[-11795, 1681, " ", $vqrange], _
	[-11596, 1691, " ", $vqrange], _
	[-11396, 1701, " ", $vqrange], _
	[-11472, 384, " ", $vqrange], _
	[-10756, -118, " ", $vqrange], _
	[-9872, -203, " ", $vqrange], _
	[-8988, -288, " ", $vqrange], _
	[-9015, -780, " ", $vqrange], _
	[-8976, -2102, " ", $vqrange], _
	[-8938, -3425, " ", $vqrange], _
	[-9190, -4537, " ", $vqrange], _
	[-9442, -5649, " ", $vqrange], _
	[-10802, -5993, " ", $vqrange], _
	[-12163, -6337, " ", $vqrange], _
	[-13346, -6336, " ", $vqrange], _
	[-12085, -6336, " ", $vqrange], _
	[-11927, -6336, " ", $vqrange], _
	[-11770, -6336, " ", $vqrange], _
	[-11612, -6336, " ", $vqrange], _
	[-11454, -6336, " ", $vqrange], _
	[-11297, -6336, " ", $vqrange], _
	[-11139, -6336, " ", $vqrange], _
	[-10824, -6336, " ", $vqrange], _
	[-9563, -6336, " ", $vqrange], _
	[-8932, -6336, " ", $vqrange], _
	[-8617, -6336, " ", $vqrange], _
	[-8459, -6336, " ", $vqrange], _
	[-8301, -6336, " ", $vqrange], _
	[-8597, -6378, " ", $vqrange], _
	[-8893, -6419, " ", $vqrange], _
	[-8960, -5039, " ", $vqrange], _
	[-9026, -3659, " ", $vqrange], _
	[-9093, -2280, " ", $vqrange], _
	[-9159, -900, " ", $vqrange], _
	[-9226, 480, " ", $vqrange], _
	[-9043, 576, " ", $vqrange], _
	[-8164, 1392, " ", $vqrange], _
	[-7284, 2207, " ", $vqrange], _
	[-6183, 2202, " ", $vqrange], _
	[-5082, 2197, " ", $vqrange], _
	[-6568, 2200.3333, " ", $vqrange], _ ; auto
	[-8054, 2203.6667, " ", $vqrange], _ ; auto
	[-9540, 2207, " ", $vqrange], _ ; auto
	[-8095.0544, 2207, " ", $vqrange], _ ; auto
	[-6650.1088, 2207, " ", $vqrange], _ ; auto
	[-5205.1632, 2207, " ", $vqrange], _ ; auto
	[-5001.9677, 2207, " ", $vqrange], _ ; auto
	[-4798.7723, 2207, " ", $vqrange], _ ; auto
	[-4121.454, 2207, " ", $vqrange], _ ; auto
	[-3037.7448, 2207, " ", $vqrange], _ ; auto
	[-1954.0356, 2207, " ", $vqrange], _ ; auto
	[-870.3264, 2207, " ", $vqrange], _ ; auto
	[574.6192, 2207, " ", $vqrange], _ ; auto
	[2019.5648, 2207, " ", $vqrange], _ ; auto
	[3464.5104, 2207, " ", $vqrange], _ ; auto
	[4548.2196, 2207, " ", $vqrange], _ ; auto
	[5631.9288, 2207, " ", $vqrange], _ ; auto
	[6173.7834, 2207, " ", $vqrange], _ ; auto
	[6376.9788, 2207, " ", $vqrange], _ ; auto
	[6715.638, 2207, " ", $vqrange], _ ; auto
	[7799.3472, 2207, " ", $vqrange], _ ; auto
	[7011.513, 2206.3125, " ", $vqrange], _ ; auto
	[6617.5959, 2205.9688, " ", $vqrange], _ ; auto
	[6420.6373, 2205.7969, " ", $vqrange], _ ; auto
	[6223.6788, 2205.625, " ", $vqrange], _ ; auto
	[5435.8446, 2204.9375, " ", $vqrange], _ ; auto
	[4648.0104, 2204.25, " ", $vqrange], _ ; auto
	[3597.5648, 2203.3333, " ", $vqrange], _ ; auto
	[2547.1192, 2202.4167, " ", $vqrange], _ ; auto
	[1496.6736, 2201.5, " ", $vqrange], _ ; auto
	[236.1389, 2200.4, " ", $vqrange], _ ; auto
	[-1024.3958, 2199.3, " ", $vqrange], _ ; auto
	[-2284.9306, 2198.2, " ", $vqrange], _ ; auto
	[-3545.4653, 2197.1, " ", $vqrange], _ ; auto
	[-4806, 2196, " ", $vqrange], _
	[-4531, 2194, " ", $vqrange], _
	[-3981, 2192, " ", $vqrange], _
	[-2879, 2187, " ", $vqrange], _
	[-1411, 2180, " ", $vqrange], _
	[57, 2174, " ", $vqrange], _
	[1525, 2167, " ", $vqrange], _
	[332, 2156, " ", $vqrange], _
	[-861, 2145, " ", $vqrange], _
	[-1458, 2140, " ", $vqrange], _
	[-1626, 2138, " ", $vqrange], _
	[-1793, 2136, " ", $vqrange], _
	[-2055, 2134, " ", $vqrange], _
	[-3248, 2123, " ", $vqrange], _
	[-3443, 1348, " ", $vqrange], _
	[-3638, 572, " ", $vqrange], _
	[-3528, -380, " ", $vqrange], _
	[-3418, -1333, " ", $vqrange], _
	[-3763, -1536, " ", $vqrange], _
	[-4254, -2685, " ", $vqrange], _
	[-4746, -3834, " ", $vqrange], _
	[-5237, -4982, " ", $vqrange], _
	[-5728, -6131, " ", $vqrange], _
	[-6219, -7280, " ", $vqrange], _
	[-5650, -6080, " ", $vqrange], _
	[-5081, -4879, " ", $vqrange], _
	[-4707, -3923, " ", $vqrange], _
	[-4334, -2968, " ", $vqrange], _
	[-3960, -2012, " ", $vqrange], _
	[-3947, -3118, " ", $vqrange], _
	[-3934, -4224, " ", $vqrange], _
	[-2620, -4307, " ", $vqrange], _
	[-1305, -4390, " ", $vqrange], _
	[-2155, -4401, " ", $vqrange], _
	[-3004, -4411, " ", $vqrange], _
	[-2185, -4755, " ", $vqrange], _
	[-1366, -5099, " ", $vqrange], _
	[-657, -4844, " ", $vqrange], _
	[52, -4588, " ", $vqrange], _
	[324, -5322, " ", $vqrange], _
	[595, -6057, " ", $vqrange], _
	[1886, -5578, " ", $vqrange], _
	[3177, -5099, " ", $vqrange], _
	[4360, -4534, " ", $vqrange], _
	[5544, -3970, " ", $vqrange], _
	[6484, -3921, " ", $vqrange], _
	[5546, -4024, " ", $vqrange], _
	[4608, -4128, " ", $vqrange], _
	[4859, -5518, " ", $vqrange], _
	[5582, -5927, " ", $vqrange], _
	[6304, -6336, " ", $vqrange], _
	[6522, -6806, " ", $vqrange], _
	[7803, -6640, " ", $vqrange], _
	[9084, -6473, " ", $vqrange], _
	[10368, -6048, " ", $vqrange], _ ; auto
	[10432, -5856, " ", $vqrange], _
	[10804, -5131, " ", $vqrange], _
	[11177, -4406, " ", $vqrange], _
	[11157, -3374, " ", $vqrange], _
	[11137, -2343, " ", $vqrange], _
	[11564, -1508, " ", $vqrange], _
	[11992, -672, " ", $vqrange], _
	[12304, -384, " ", $vqrange], _
	[12388, -220, " ", $vqrange], _
	[12426, -62, " ", $vqrange], _
	[12463, 96, " ", $vqrange], _
	[12732, 111, " ", $vqrange], _
	[12899, 120, " ", $vqrange], _
	[13050, 128, " ", $vqrange], _
	[13202, 136, " ", $vqrange], _
	[13353, 144, " ", $vqrange], _
	[13504, 153, " ", $vqrange], _
	[13671, 162, " ", $vqrange], _
	[14074, 184, " ", $vqrange], _
	[14611, 213, " ", $vqrange], _
	[15058, -468, " ", $vqrange], _
	[16270, -622, " ", $vqrange], _
	[15983, -1703, " ", $vqrange], _
	[15696, -2784, " ", $vqrange], _
	[15411, -2703, " ", $vqrange], _
	[16068, -2688, " ", $vqrange], _
	[15423, -2688, " ", $vqrange], _
	[15262, -2688, " ", $vqrange], _
	[15100, -2688, " ", $vqrange], _
	[14939, -2688, " ", $vqrange], _
	[14778, -2688, " ", $vqrange], _
	[14617, -2688, " ", $vqrange], _
	[14456, -2688, " ", $vqrange], _
	[14133, -2688, " ", $vqrange], _
	[13488, -2688, " ", $vqrange], _
	[12198, -2688, " ", $vqrange], _
	[10908, -2688, " ", $vqrange], _
	[12301, -2724, " ", $vqrange], _
	[13694, -2761, " ", $vqrange], _
	[12211, -2783, " ", $vqrange], _
	[12864, -2688, " ", $vqrange], _
	[11964, -2688, " ", $vqrange], _
	[11064, -2688, " ", $vqrange], _
	[10895, -2688, " ", $vqrange], _
	[10741, -2688, " ", $vqrange], _
	[10586, -2688, " ", $vqrange], _
	[10389, -2688, " ", $vqrange], _
	[10164, -2688, " ", $vqrange], _
	[9264, -2688, " ", $vqrange], _
	[8271, -2762, " ", $vqrange], _
	[9440, -2533, " ", $vqrange], _
	[10608, -2304, " ", $vqrange], _
	[10020.5, -2243, " ", $vqrange], _ ; auto
	[9864.4453, -2226.7969, " ", $vqrange], _ ; auto
	[9433, -2182, " ", $vqrange], _
	[9120, -960, " ", $vqrange], _ ; auto
	[8809, -864, " ", $vqrange], _
	[9537, -847, " ", $vqrange], _
	[8706, -712, " ", $vqrange], _
	[7875, -576, " ", $vqrange], _
	[6843, -45, " ", $vqrange], _
	[5811, 487, " ", $vqrange], _
	[4779, 1018, " ", $vqrange], _
	[6003, 1633, " ", $vqrange], _
	[7228, 2247, " ", $vqrange], _
	[8453, 2862, " ", $vqrange], _
	[7464, 2964, " ", $vqrange], _
	[6476, 3066, " ", $vqrange], _
	[7174, 3357, " ", $vqrange], _
	[7860, 3744, " ", $vqrange], _
	[7460, 3768, " ", $vqrange], _
	[7259, 3780, " ", $vqrange], _
	[7109, 3789, " ", $vqrange], _
	[6959, 3798, " ", $vqrange], _
	[6658, 3816, " ", $vqrange], _
	[6508, 3825, " ", $vqrange], _
	[6358, 3834, " ", $vqrange], _
	[5457, 3888, " ", $vqrange], _
	[4656, 3936, " ", $vqrange], _
	[3942, 4122, " ", $vqrange], _
	[3182, 3228, " ", $vqrange], _
	[2423, 2335, " ", $vqrange], _
	[1578, 2128, " ", $vqrange], _
	[732, 1920, " ", $vqrange], _
	[1005, 1426, " ", $vqrange], _
	[1422, 674, " ", $vqrange], _
	[1838, -78, " ", $vqrange], _
	[3175, 9, " ", $vqrange], _
	[4512, 96, " ", $vqrange], _
	[4075, 601, " ", $vqrange] _
]

