#include-once

; Generated by scripts/navmesh/repair_vanquish.py -- do not edit by hand.
; Source: lib/maps/Vanquish/Factions_EchovaldForest/MourningVeilFalls.au3
; Map: MourningVeilFalls (id 209), geometry from MAP 0000157242.pmap
; Repaired 1 of 1 blocked segments by inserting 2 waypoints.
; Smoothed 34 additional anchor(s) for wall clearance and hop distance.
; Waypoints tagged "auto" were generated to route around
; unwalkable terrain; every other coordinate is unchanged from the source.
; Layout matches MVR: [x, y, label, $vqrange].

Global $vqrange = 1450

Global $aFactions_EchovaldForest_MourningVeilFallsRoute01[275][4] = [ _
	[-20007, -6088, " ", $vqrange], _
	[-20281, -5234, " ", $vqrange], _
	[-21394, -4831, " ", $vqrange], _
	[-22507, -4428, " ", $vqrange], _
	[-23620, -4025, " ", $vqrange], _
	[-23978, -4329, " ", $vqrange], _
	[-25083, -4324, " ", $vqrange], _
	[-25238, -4324, " ", $vqrange], _
	[-23920, -4326.5, " ", $vqrange], _ ; auto
	[-23261, -4327.75, " ", $vqrange], _ ; auto
	[-22931.5, -4328.375, " ", $vqrange], _ ; auto
	[-22766.75, -4328.6875, " ", $vqrange], _ ; auto
	[-22602, -4329, " ", $vqrange], _ ; auto
	[-22850.4062, -4329, " ", $vqrange], _ ; auto
	[-23098.8125, -4329, " ", $vqrange], _ ; auto
	[-23595.625, -4329, " ", $vqrange], _ ; auto
	[-24589.25, -4329, " ", $vqrange], _ ; auto
	[-25086.0625, -4329, " ", $vqrange], _ ; auto
	[-25241.3164, -4329, " ", $vqrange], _ ; auto
	[-25396.5703, -4329, " ", $vqrange], _ ; auto
	[-25551.8242, -4329, " ", $vqrange], _ ; auto
	[-25707.0781, -4329, " ", $vqrange], _ ; auto
	[-26079.6875, -4329, " ", $vqrange], _ ; auto
	[-26328.0938, -4329, " ", $vqrange], _ ; auto
	[-26576.5, -4329, " ", $vqrange], _ ; auto
	[-26288.125, -4326.75, " ", $vqrange], _ ; auto
	[-25999.75, -4324.5, " ", $vqrange], _ ; auto
	[-25783.4688, -4322.8125, " ", $vqrange], _ ; auto
	[-25630.2695, -4321.6172, " ", $vqrange], _ ; auto
	[-25423, -4320, " ", $vqrange], _
	[-25574, -4322, " ", $vqrange], _
	[-25730, -4322, " ", $vqrange], _
	[-25911, -4321, " ", $vqrange], _
	[-26187, -4320, " ", $vqrange], _
	[-26706, -3994, " ", $vqrange], _
	[-27413, -3284, " ", $vqrange], _
	[-27040, -1920, " ", $vqrange], _
	[-26562, -736, " ", $vqrange], _
	[-26084, 449, " ", $vqrange], _
	[-25466, 1352, " ", $vqrange], _
	[-24848, 2255, " ", $vqrange], _
	[-24230, 3158, " ", $vqrange], _
	[-23294, 3976, " ", $vqrange], _ ; auto
	[-23714, 4336, " ", $vqrange], _
	[-23198, 5515, " ", $vqrange], _
	[-22682, 6693, " ", $vqrange], _
	[-21773, 7403, " ", $vqrange], _
	[-20864, 8112, " ", $vqrange], _
	[-19955, 8822, " ", $vqrange], _
	[-19709, 8299.5, " ", $vqrange], _ ; auto
	[-19586, 8038.25, " ", $vqrange], _ ; auto
	[-19463, 7777, " ", $vqrange], _
	[-18971, 6732, " ", $vqrange], _
	[-18479, 5688, " ", $vqrange], _
	[-17987, 4643, " ", $vqrange], _
	[-18036, 3377, " ", $vqrange], _
	[-18084, 2111, " ", $vqrange], _
	[-18132, 845, " ", $vqrange], _
	[-19436, 827, " ", $vqrange], _
	[-18439, 742, " ", $vqrange], _
	[-17443, 657, " ", $vqrange], _
	[-16446, 572, " ", $vqrange], _
	[-16754, -803, " ", $vqrange], _
	[-17062, -2178, " ", $vqrange], _
	[-16754, -803, " ", $vqrange], _
	[-16446, 572, " ", $vqrange], _
	[-16681, 1370, " ", $vqrange], _
	[-16915, 2167, " ", $vqrange], _
	[-16254, 1036, " ", $vqrange], _
	[-15592, -96, " ", $vqrange], _
	[-15020, -144, " ", $vqrange], _
	[-14868, -157, " ", $vqrange], _
	[-14710.5, -170.125, " ", $vqrange], _ ; auto
	[-14448, -192, " ", $vqrange], _
	[-13370, -1202, " ", $vqrange], _
	[-12954, -1202, " ", $vqrange], _
	[-12798, -1202, " ", $vqrange], _
	[-12641, -1202, " ", $vqrange], _
	[-12406.75, -1202, " ", $vqrange], _ ; auto
	[-12172.5, -1202, " ", $vqrange], _ ; auto
	[-11704, -1202, " ", $vqrange], _
	[-11499, 63, " ", $vqrange], _
	[-11294, 1327, " ", $vqrange], _
	[-11088, 2592, " ", $vqrange], _
	[-11946, 2597, " ", $vqrange], _
	[-12100, 2598, " ", $vqrange], _
	[-12254, 2599, " ", $vqrange], _
	[-12529, 2600.5, " ", $vqrange], _ ; auto
	[-12804, 2602, " ", $vqrange], _
	[-13505, 3293, " ", $vqrange], _
	[-14206, 3984, " ", $vqrange], _
	[-14063, 5216, " ", $vqrange], _
	[-13919, 6448, " ", $vqrange], _
	[-13776, 7680, " ", $vqrange], _
	[-13038, 7850, " ", $vqrange], _
	[-12092, 7765, " ", $vqrange], _
	[-11147, 7680, " ", $vqrange], _
	[-10480, 6628, " ", $vqrange], _
	[-9813, 5576, " ", $vqrange], _
	[-10263, 4524, " ", $vqrange], _
	[-10713, 3473, " ", $vqrange], _
	[-11164, 2421, " ", $vqrange], _
	[-11179, 1668, " ", $vqrange], _
	[-11140, 226, " ", $vqrange], _
	[-11101, -1215, " ", $vqrange], _
	[-11143, -2255, " ", $vqrange], _
	[-11088, -3360, " ", $vqrange], _
	[-10478, -3360, " ", $vqrange], _
	[-10326, -3360, " ", $vqrange], _
	[-10174, -3360, " ", $vqrange], _
	[-10021, -3360, " ", $vqrange], _
	[-9869, -3360, " ", $vqrange], _
	[-9716, -3360, " ", $vqrange], _
	[-9564, -3360, " ", $vqrange], _
	[-9259, -3360, " ", $vqrange], _
	[-8650, -3360, " ", $vqrange], _
	[-7430, -3360, " ", $vqrange], _
	[-6211, -3360, " ", $vqrange], _
	[-7074, -3358, " ", $vqrange], _
	[-7937, -3357, " ", $vqrange], _
	[-6826, -2839, " ", $vqrange], _
	[-5715, -2321, " ", $vqrange], _
	[-4604, -1803, " ", $vqrange], _
	[-4080, -2693, " ", $vqrange], _
	[-3556, -3583, " ", $vqrange], _
	[-3032, -4473, " ", $vqrange], _
	[-2510, -4459, " ", $vqrange], _
	[-2249, -4452, " ", $vqrange], _
	[-2094, -4447, " ", $vqrange], _
	[-1939, -4443, " ", $vqrange], _
	[-1727, -4437, " ", $vqrange], _
	[-1466, -4430, " ", $vqrange], _
	[-944, -4416, " ", $vqrange], _
	[-333, -3710, " ", $vqrange], _
	[734, -3128, " ", $vqrange], _
	[1802, -2546, " ", $vqrange], _
	[2869, -1965, " ", $vqrange], _
	[3936, -1383, " ", $vqrange], _
	[2869, -1965, " ", $vqrange], _
	[1802, -2546, " ", $vqrange], _
	[734, -3128, " ", $vqrange], _
	[-333, -3710, " ", $vqrange], _
	[-874, -3098, " ", $vqrange], _
	[-1415, -2485, " ", $vqrange], _
	[-1475, -1470, " ", $vqrange], _
	[-1536, -455, " ", $vqrange], _
	[-1508, 606, " ", $vqrange], _
	[-1481, 1666, " ", $vqrange], _
	[-1454, 2726, " ", $vqrange], _
	[-1447, 2992, " ", $vqrange], _
	[-1441, 3190, " ", $vqrange], _
	[-1437, 3356, " ", $vqrange], _
	[-1433, 3522, " ", $vqrange], _
	[-1426, 3787, " ", $vqrange], _
	[-1421, 4087, " ", $vqrange], _
	[-1416, 4387, " ", $vqrange], _
	[-1406, 4988, " ", $vqrange], _
	[-1386, 6188, " ", $vqrange], _
	[-678, 6812, " ", $vqrange], _
	[31, 7437, " ", $vqrange], _
	[1214, 7579, " ", $vqrange], _
	[2398, 7721, " ", $vqrange], _
	[3426, 6776, " ", $vqrange], _
	[4454, 5830, " ", $vqrange], _
	[4106, 5517, " ", $vqrange], _
	[4741, 4198, " ", $vqrange], _
	[5376, 2880, " ", $vqrange], _
	[4853, 2574, " ", $vqrange], _
	[4754, 1527, " ", $vqrange], _
	[4656, 480, " ", $vqrange], _
	[5263, -495, " ", $vqrange], _
	[4987, 526, " ", $vqrange], _
	[4710, 1546, " ", $vqrange], _
	[4853, 2574, " ", $vqrange], _
	[5464, 3834, " ", $vqrange], _
	[4848, 4224, " ", $vqrange], _
	[5838, 4224, " ", $vqrange], _
	[6023, 4224, " ", $vqrange], _
	[6178, 4224, " ", $vqrange], _
	[6332, 4224, " ", $vqrange], _
	[6827, 4224, " ", $vqrange], _
	[7559, 3972, " ", $vqrange], _
	[7742, 3909.25, " ", $vqrange], _ ; auto
	[7925, 3846.5, " ", $vqrange], _ ; auto
	[8291, 3721, " ", $vqrange], _
	[8865, 2896, " ", $vqrange], _
	[9439, 2070, " ", $vqrange], _
	[10515, 1725, " ", $vqrange], _
	[10554, 446, " ", $vqrange], _
	[10594, -833, " ", $vqrange], _
	[10633, -2112, " ", $vqrange], _
	[11687, -2189, " ", $vqrange], _
	[12742, -2266, " ", $vqrange], _
	[13796, -2343, " ", $vqrange], _
	[13730, -3284, " ", $vqrange], _
	[13664, -4224, " ", $vqrange], _
	[12723, -4405, " ", $vqrange], _
	[13664, -4224, " ", $vqrange], _
	[13728, -3744, " ", $vqrange], _
	[13926, -3744, " ", $vqrange], _
	[14098, -3744, " ", $vqrange], _
	[14321, -3744, " ", $vqrange], _
	[14518, -3744, " ", $vqrange], _
	[15457, -4829, " ", $vqrange], _
	[15733, -5760, " ", $vqrange], _
	[15079, -5760, " ", $vqrange], _
	[14925, -5760, " ", $vqrange], _
	[14751, -5760, " ", $vqrange], _
	[14424, -5760, " ", $vqrange], _
	[14333, -5665, " ", $vqrange], _
	[14672, -6528, " ", $vqrange], _
	[15892, -6586, " ", $vqrange], _
	[17111, -6643, " ", $vqrange], _
	[16595, -6043, " ", $vqrange], _
	[16080, -5443, " ", $vqrange], _
	[16201, -5164, " ", $vqrange], _
	[16449, -5124, " ", $vqrange], _
	[16603, -5100, " ", $vqrange], _
	[17191, -5006, " ", $vqrange], _
	[17346, -4981, " ", $vqrange], _
	[17501, -4956, " ", $vqrange], _
	[17686, -4926, " ", $vqrange], _
	[18182, -4847, " ", $vqrange], _
	[18752, -4814, " ", $vqrange], _
	[18930, -4804, " ", $vqrange], _
	[19081, -4795, " ", $vqrange], _
	[19322, -4781, " ", $vqrange], _
	[19038, -5280, " ", $vqrange], _
	[19560, -5287, " ", $vqrange], _
	[19821, -5291, " ", $vqrange], _
	[19976, -5293, " ", $vqrange], _
	[20263.25, -5297, " ", $vqrange], _ ; auto
	[20550.5, -5301, " ", $vqrange], _ ; auto
	[21125, -5309, " ", $vqrange], _
	[21385, -5321, " ", $vqrange], _
	[21557, -5329, " ", $vqrange], _
	[21989, -5349, " ", $vqrange], _
	[23275, -4910, " ", $vqrange], _
	[24560, -4472, " ", $vqrange], _
	[24773, -3859, " ", $vqrange], _
	[26022, -3641, " ", $vqrange], _
	[27271, -3423, " ", $vqrange], _
	[26706, -2426, " ", $vqrange], _
	[26141, -1430, " ", $vqrange], _
	[26929, -253, " ", $vqrange], _
	[25994, 354, " ", $vqrange], _
	[25059, 960, " ", $vqrange], _
	[25878, 1973, " ", $vqrange], _
	[24926, 3061, " ", $vqrange], _
	[25316, 3126, " ", $vqrange], _
	[24923, 3295, " ", $vqrange], _
	[25306, 4538, " ", $vqrange], _
	[25689, 5781, " ", $vqrange], _
	[24470, 6082, " ", $vqrange], _
	[23252, 6383, " ", $vqrange], _
	[23986.8262, 5879.5, " ", $vqrange], _ ; auto
	[24721.6523, 5376, " ", $vqrange], _ ; auto
	[23539, 5352, " ", $vqrange], _
	[23826, 4320, " ", $vqrange], _
	[23678.75, 4289.5, " ", $vqrange], _ ; auto
	[23531.5, 4259, " ", $vqrange], _ ; auto
	[23237, 4198, " ", $vqrange], _
	[22943, 3500, " ", $vqrange], _
	[21997, 2516, " ", $vqrange], _
	[21051, 1531, " ", $vqrange], _
	[20791, 349, " ", $vqrange], _
	[20531, -834, " ", $vqrange], _
	[20271, -2016, " ", $vqrange], _
	[21363, -2082, " ", $vqrange], _
	[20265, -1718, " ", $vqrange], _
	[19166, -1353, " ", $vqrange], _
	[18881, -933, " ", $vqrange], _
	[18129, -43, " ", $vqrange], _
	[17376, 847, " ", $vqrange], _
	[16624, 1737, " ", $vqrange] _
]

